# file name meaning

eg. 100_cairo_WCNN_2000_64_1000_1_8_1_1.ipynb

`[tag]_[dataset_name]_[method_name]_[data_length]_[batch_size]_[epochs]_[kernel_wide_base]_[kernel_number_base]_[net_deep_base]_[calculate_unit]`

In [1]:
from tools import general
import os
from tools.configure.constants import DATASETS_CONSTANT, METHOD_PARAMETER_TEMPLATE, JUPYTER_TOKEN
from tools.integration import train_val


nb_name_file = general.ipy_nb_name(JUPYTER_TOKEN["token_lists"])

Using TensorFlow backend.
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/musk/anaconda3/en

In [2]:
theNotebook = nb_name_file.split('_')
assert len(theNotebook) == 9 or len(theNotebook) == 10, 'The number of parameters should be 9 / 10'

global title_param
title_param = {
    'num': theNotebook[0],
    'dataset_name': theNotebook[1],
    'method_name': theNotebook[2],
    'data_lenght': int(theNotebook[3]),
    'batch_size': int(theNotebook[4]),
    'nb_epochs': int(theNotebook[5]),
    'kernel_wide_base': int(theNotebook[6]),
    'kernel_number_base': int(theNotebook[7]),
    'net_deep_base': int(theNotebook[8]),
    'calculation_unit': theNotebook[9] if len(theNotebook)==10 else '0',  # If not specified, the CPU is used to train the model
}

# assert title_param['dataset'] in ['cairo', 'milan', 'kyoto7', 'kyoto8', 'kyoto11'], 'Please correct the dataset name！'
# assert title_param['model_name'] in ['WCNN','LSTM'], 'The method is wrong. Please correct it！'
# assert title_param['optimizer'] in ['rms', 'adagrad'], 'The optimizer is wrong. Please correct it！'
# assert title_param['calculation_unit'] in ['0', '1', '2'], 'Error in calculation unit selection, please correct！'

display(title_param)

{'num': '653',
 'dataset_name': 'cairo',
 'method_name': 'WCNNR',
 'data_lenght': 2000,
 'batch_size': 64,
 'nb_epochs': 1000,
 'kernel_wide_base': 1,
 'kernel_number_base': 3,
 'net_deep_base': 1,
 'calculation_unit': '1'}

In [3]:
dict_config_cus = {

        "datasets_dir": DATASETS_CONSTANT["base_dir"],  # 这是公共数据集常量
        "archive_name": DATASETS_CONSTANT["archive_name"],
        "ksplit": DATASETS_CONSTANT["ksplit"],

        'distance_int': None,
    }

dict_config_cus = general.Merge(title_param, dict_config_cus)

from tools.configure.constants import WCNNR_CONSTANT as MODEL_DEFAULT_CONF

dict_config_cus = general.Merge(MODEL_DEFAULT_CONF, dict_config_cus)

In [4]:
import tensorflow as tf

calculation_unit = general.getAvailableId()
os.environ["CUDA_VISIBLE_DEVICES"] = calculation_unit

if calculation_unit != "-1":
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.Session(config=config)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

[origin](#origin)

[C](#constrain)

[CS_1](#constrain_1)

[CS_2](#constrain_2)

[CS_3](#constrain_3)

[CS_4](#constrain_4)

[CS_5](#constrain_5)


# <a id='origin'>origin</a>


In [16]:
%%time
dict_config_cus['distance_int'] = '9999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_100 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_100 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_100 (Conv1D)          (None, 2000, 12)          780       
_________________________________________________________________
activation_298 (Activation)  (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_100 (Gl (None, 12)                0         
_________________________________________________________________
dense_298 (Dense)            (None, 18)                234       
_____________________________________

12/12 [==============================] - 0s 11ms/step - loss: 0.7091 - acc: 0.7565 - val_loss: 0.7166 - val_acc: 0.7240
Epoch 104/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7406 - acc: 0.7500 - val_loss: 0.7279 - val_acc: 0.7161
Epoch 105/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6940 - acc: 0.7578 - val_loss: 0.7311 - val_acc: 0.7161
Epoch 106/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7314 - acc: 0.7448 - val_loss: 0.7258 - val_acc: 0.7135
Epoch 107/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7257 - acc: 0.7487 - val_loss: 0.7193 - val_acc: 0.7188
Epoch 108/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7867 - acc: 0.7461 - val_loss: 0.7159 - val_acc: 0.7214
Epoch 109/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7247 - acc: 0.7565 - val_loss: 0.7191 - val_acc: 0.7188
Epoch 110/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.7043 - acc: 0.7565 - val_loss: 0.7097 - val_acc: 0.7240
Epoch 163/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6972 - acc: 0.7656 - val_loss: 0.7181 - val_acc: 0.7240
Epoch 164/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6923 - acc: 0.7630 - val_loss: 0.7072 - val_acc: 0.7292
Epoch 165/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7004 - acc: 0.7734 - val_loss: 0.7113 - val_acc: 0.7240

Epoch 00165: loss improved from inf to 0.70040, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_3/weights/Pbest-0-000165-0.700402-0.723958.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7202 - acc: 0.7500 - val_loss: 0.7071 - val_acc: 0.7292
Epoch 167/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7332 - acc: 0.7513 - val_loss: 0.7159 - val_acc: 0.7214
Epoch 168/1000
12/12 [========

12/12 [==============================] - 0s 11ms/step - loss: 0.7011 - acc: 0.7487 - val_loss: 0.7207 - val_acc: 0.7188
Epoch 278/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6847 - acc: 0.7617 - val_loss: 0.7208 - val_acc: 0.7188
Epoch 279/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7234 - acc: 0.7513 - val_loss: 0.7216 - val_acc: 0.7188
Epoch 280/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7241 - acc: 0.7630 - val_loss: 0.7207 - val_acc: 0.7188
Epoch 281/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7200 - acc: 0.7643 - val_loss: 0.7168 - val_acc: 0.7214
Epoch 282/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7333 - acc: 0.7461 - val_loss: 0.7054 - val_acc: 0.7266
Epoch 283/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6973 - acc: 0.7487 - val_loss: 0.7240 - val_acc: 0.7161
Epoch 284/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 392/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6800 - acc: 0.7682 - val_loss: 0.7125 - val_acc: 0.7240
Epoch 393/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7104 - acc: 0.7591 - val_loss: 0.7174 - val_acc: 0.7214
Epoch 394/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7257 - acc: 0.7604 - val_loss: 0.7055 - val_acc: 0.7214
Epoch 395/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6946 - acc: 0.7682 - val_loss: 0.7117 - val_acc: 0.7240
Epoch 396/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7003 - acc: 0.7591 - val_loss: 0.7203 - val_acc: 0.7188
Epoch 397/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7036 - acc: 0.7357 - val_loss: 0.7163 - val_acc: 0.7214
Epoch 398/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7304 - acc: 0.7591 - val_loss: 0.6986 - val_acc: 0.7266
Epoch 399/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 4s 11ms/step
0-cairo:	acc: 72.19%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 5s 425ms/step - loss: 1.4735 - acc: 0.6185 - val_loss: 1.2425 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.2724 - acc: 0.6315 - val_loss: 1.1670 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.2198 - acc: 0.6341 - val_loss: 1.1408 - val_acc: 0.6354
Epoch 4/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1828 - acc: 0.6354 - val_loss: 1.0955 - val_acc: 0.6406
Epoch 5/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1448 - acc: 0.6354 - val_loss: 1.0835 - val_acc: 0.6380
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1368 - acc: 0.6380 - val_loss: 1.0624 - val_acc: 0.6380
Epoch 7/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0974 - acc: 0.6354 - val_loss: 1.0413 - val_acc: 0.6354
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.7260 - acc: 0.7135 - val_loss: 0.6626 - val_acc: 0.7656
Epoch 116/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7527 - acc: 0.7096 - val_loss: 0.6593 - val_acc: 0.7656
Epoch 117/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7182 - acc: 0.7253 - val_loss: 0.6631 - val_acc: 0.7682
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7309 - acc: 0.7201 - val_loss: 0.6598 - val_acc: 0.7682
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7442 - acc: 0.7109 - val_loss: 0.6539 - val_acc: 0.7708
Epoch 120/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7124 - acc: 0.7201 - val_loss: 0.6539 - val_acc: 0.7708
Epoch 121/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7267 - acc: 0.7188 - val_loss: 0.6448 - val_acc: 0.7656
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step -


Epoch 00173: loss improved from 0.70933 to 0.67314, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_3/weights/Pbest-1-000173-0.673137-0.781250.hdf5
Epoch 174/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7184 - acc: 0.7188 - val_loss: 0.6366 - val_acc: 0.7760
Epoch 175/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6845 - acc: 0.7435 - val_loss: 0.6327 - val_acc: 0.7760
Epoch 176/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6705 - acc: 0.7422 - val_loss: 0.6312 - val_acc: 0.7786
Epoch 177/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7155 - acc: 0.7148 - val_loss: 0.6352 - val_acc: 0.7760
Epoch 178/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6827 - acc: 0.7240 - val_loss: 0.6412 - val_acc: 0.7734
Epoch 179/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6827 - acc: 0.7461 - val_loss: 0.6373 - val_acc: 0.7734
Epoch 180/1

Epoch 232/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7053 - acc: 0.7344 - val_loss: 0.6337 - val_acc: 0.7786
Epoch 233/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6993 - acc: 0.7227 - val_loss: 0.6299 - val_acc: 0.7786
Epoch 234/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6974 - acc: 0.7214 - val_loss: 0.6349 - val_acc: 0.7734
Epoch 235/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6965 - acc: 0.7344 - val_loss: 0.6272 - val_acc: 0.7786
Epoch 236/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6911 - acc: 0.7253 - val_loss: 0.6258 - val_acc: 0.7786

Epoch 00236: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 237/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6911 - acc: 0.7370 - val_loss: 0.6238 - val_acc: 0.7812
Epoch 238/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6938 - acc: 0.7279 - val_loss: 0.6337 - val_a

Epoch 348/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6876 - acc: 0.7396 - val_loss: 0.6308 - val_acc: 0.7786
Epoch 349/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7069 - acc: 0.7253 - val_loss: 0.6265 - val_acc: 0.7812
Epoch 350/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7016 - acc: 0.7292 - val_loss: 0.6270 - val_acc: 0.7786
Epoch 351/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6891 - acc: 0.7201 - val_loss: 0.6354 - val_acc: 0.7734
Epoch 352/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7192 - acc: 0.7240 - val_loss: 0.6336 - val_acc: 0.7734
Epoch 353/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7020 - acc: 0.7292 - val_loss: 0.6318 - val_acc: 0.7786
Epoch 354/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6720 - acc: 0.7422 - val_loss: 0.6338 - val_acc: 0.7760
Epoch 355/1000
12/12 [==============================] -

Epoch 404/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6850 - acc: 0.7422 - val_loss: 0.6312 - val_acc: 0.7760
Epoch 405/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6670 - acc: 0.7422 - val_loss: 0.6370 - val_acc: 0.7734
Epoch 406/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6732 - acc: 0.7396 - val_loss: 0.6344 - val_acc: 0.7734
Epoch 407/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6843 - acc: 0.7305 - val_loss: 0.6266 - val_acc: 0.7812
Epoch 408/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6903 - acc: 0.7331 - val_loss: 0.6331 - val_acc: 0.7760
Epoch 409/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7175 - acc: 0.7214 - val_loss: 0.6313 - val_acc: 0.7760
Epoch 410/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6654 - acc: 0.7396 - val_loss: 0.6242 - val_acc: 0.7812
Epoch 411/1000
12/12 [==============================] -

Epoch 465/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6822 - acc: 0.7513 - val_loss: 0.6289 - val_acc: 0.7786

Epoch 00465: loss improved from inf to 0.68217, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_3/weights/Pbest-1-000465-0.682171-0.778646.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6866 - acc: 0.7487 - val_loss: 0.6315 - val_acc: 0.7760
Epoch 467/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7031 - acc: 0.7305 - val_loss: 0.6296 - val_acc: 0.7786
Epoch 468/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7217 - acc: 0.7344 - val_loss: 0.6314 - val_acc: 0.7760
Epoch 469/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6938 - acc: 0.7370 - val_loss: 0.6159 - val_acc: 0.7812
Epoch 470/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7062 - acc: 0.7279 - val_loss: 0.6313 - val_acc: 0.7760
Epoch 471/1000


Epoch 521/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6886 - acc: 0.7383 - val_loss: 0.6295 - val_acc: 0.7760
Epoch 522/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6964 - acc: 0.7409 - val_loss: 0.6334 - val_acc: 0.7760
Epoch 523/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6908 - acc: 0.7253 - val_loss: 0.6365 - val_acc: 0.7734
Epoch 524/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6879 - acc: 0.7279 - val_loss: 0.6362 - val_acc: 0.7734
Epoch 525/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6656 - acc: 0.7565 - val_loss: 0.6277 - val_acc: 0.7760
Epoch 526/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7014 - acc: 0.7383 - val_loss: 0.6347 - val_acc: 0.7760
Epoch 527/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7099 - acc: 0.7161 - val_loss: 0.6351 - val_acc: 0.7734
Epoch 528/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 4s 11ms/step
1-cairo:	acc: 77.75%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 5s 441ms/step - loss: 1.4519 - acc: 0.6120 - val_loss: 1.1741 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.1578 - acc: 0.6380 - val_loss: 1.0817 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0995 - acc: 0.6432 - val_loss: 1.0189 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0648 - acc: 0.6406 - val_loss: 0.9909 - val_acc: 0.6224
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0355 - acc: 0.6393 - val_loss: 0.9661 - val_acc: 0.6745
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.0326 - acc: 0.6341 - val_loss: 0.9425 - val_acc: 0.6875
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.9850 - acc: 0.6576 - val_loss: 0.9219 - val_acc: 0.6953
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.6677 - acc: 0.7565 - val_loss: 0.6753 - val_acc: 0.7969
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6665 - acc: 0.7604 - val_loss: 0.6419 - val_acc: 0.8047
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6651 - acc: 0.7604 - val_loss: 0.6629 - val_acc: 0.7995
Epoch 121/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6642 - acc: 0.7539 - val_loss: 0.6551 - val_acc: 0.7969
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6608 - acc: 0.7786 - val_loss: 0.6563 - val_acc: 0.8073
Epoch 123/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7145 - acc: 0.7448 - val_loss: 0.6680 - val_acc: 0.7969
Epoch 124/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6551 - acc: 0.7565 - val_loss: 0.6612 - val_acc: 0.8021
Epoch 125/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 175/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6650 - acc: 0.7669 - val_loss: 0.6573 - val_acc: 0.7943
Epoch 176/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6601 - acc: 0.7565 - val_loss: 0.6496 - val_acc: 0.7969
Epoch 177/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6699 - acc: 0.7539 - val_loss: 0.6615 - val_acc: 0.7943

Epoch 00177: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 178/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6784 - acc: 0.7604 - val_loss: 0.6642 - val_acc: 0.7917
Epoch 179/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6574 - acc: 0.7578 - val_loss: 0.6607 - val_acc: 0.7943
Epoch 180/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6776 - acc: 0.7591 - val_loss: 0.6616 - val_acc: 0.7969
Epoch 181/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6966 - acc: 0.7344 - val_loss: 0.6664 - val_a

Epoch 233/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6534 - acc: 0.7682 - val_loss: 0.6385 - val_acc: 0.7995
Epoch 234/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6631 - acc: 0.7630 - val_loss: 0.6643 - val_acc: 0.7917
Epoch 235/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6780 - acc: 0.7487 - val_loss: 0.6577 - val_acc: 0.7943
Epoch 236/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6555 - acc: 0.7695 - val_loss: 0.6461 - val_acc: 0.7969
Epoch 237/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6632 - acc: 0.7617 - val_loss: 0.6514 - val_acc: 0.7995
Epoch 238/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6322 - acc: 0.7565 - val_loss: 0.6446 - val_acc: 0.7995
Epoch 239/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6766 - acc: 0.7487 - val_loss: 0.6549 - val_acc: 0.7969
Epoch 240/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.6509 - acc: 0.7812 - val_loss: 0.6542 - val_acc: 0.7969
Epoch 292/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6475 - acc: 0.7591 - val_loss: 0.6580 - val_acc: 0.7943
Epoch 293/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6568 - acc: 0.7513 - val_loss: 0.6624 - val_acc: 0.7943
Epoch 294/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6754 - acc: 0.7500 - val_loss: 0.6538 - val_acc: 0.7995
Epoch 295/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6349 - acc: 0.7682 - val_loss: 0.6574 - val_acc: 0.7969
Epoch 296/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6583 - acc: 0.7617 - val_loss: 0.6527 - val_acc: 0.7943
Epoch 297/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6508 - acc: 0.7669 - val_loss: 0.6600 - val_acc: 0.7969
Epoch 298/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 351/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6929 - acc: 0.7500 - val_loss: 0.6645 - val_acc: 0.7917
Epoch 352/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6539 - acc: 0.7578 - val_loss: 0.6613 - val_acc: 0.7969
Epoch 353/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6589 - acc: 0.7578 - val_loss: 0.6618 - val_acc: 0.7969
Epoch 354/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6566 - acc: 0.7539 - val_loss: 0.6474 - val_acc: 0.7995
Epoch 355/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6450 - acc: 0.7656 - val_loss: 0.6526 - val_acc: 0.7995
Epoch 356/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6543 - acc: 0.7578 - val_loss: 0.6424 - val_acc: 0.7995
Epoch 357/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6666 - acc: 0.7656 - val_loss: 0.6555 - val_acc: 0.7969
Epoch 358/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 4s 11ms/step
2-cairo:	acc: 79.54%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 77.77% (+/- 2.23%)
final: current database: cairo 	 77.69% (+/- 2.35%)
CPU times: user 5min 5s, sys: 20.6 s, total: 5min 26s
Wall time: 5min 7s

best: current database: cairo 	 77.26% (+/- 2.14%)
final: current database: cairo 	 77.35% (+/- 2.20%)
CPU times: user 6min 43s, sys: 24.4 s, total: 7min 8s
Wall time: 5min 50s

best: current database: cairo 	 76.49% (+/- 3.13%)
final: current database: cairo 	 76.49% (+/- 3.13%)
CPU times: user 6min 8s, sys: 21.2 s, total: 6min 29s
Wall time: 4min 55s
```

# <a id='constrain'>C</a>

In [17]:
%%time
dict_config_cus['distance_int'] = '999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_109 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_109 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_109 (Conv1D)          (None, 2000, 12)          780       
_________________________________________________________________
activation_325 (Activation)  (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_109 (Gl (None, 12)                0         
_________________________________________________________________
dense_325 (Dense)            (None, 18)                234       
______________________________________

12/12 [==============================] - 0s 11ms/step - loss: 0.6900 - acc: 0.7552 - val_loss: 0.6856 - val_acc: 0.7083
Epoch 102/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6913 - acc: 0.7422 - val_loss: 0.6839 - val_acc: 0.7109
Epoch 103/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6632 - acc: 0.7565 - val_loss: 0.6693 - val_acc: 0.7240
Epoch 104/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6966 - acc: 0.7461 - val_loss: 0.6807 - val_acc: 0.7266

Epoch 00104: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 105/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6903 - acc: 0.7396 - val_loss: 0.6881 - val_acc: 0.7188
Epoch 106/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6893 - acc: 0.7565 - val_loss: 0.6845 - val_acc: 0.7214
Epoch 107/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6901 - acc: 0.7357 - val_loss: 0.6849 - val_a

12/12 [==============================] - 0s 11ms/step - loss: 0.7087 - acc: 0.7383 - val_loss: 0.6718 - val_acc: 0.7188
Epoch 218/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6615 - acc: 0.7526 - val_loss: 0.6698 - val_acc: 0.7214
Epoch 219/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6939 - acc: 0.7565 - val_loss: 0.6675 - val_acc: 0.7240
Epoch 220/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6835 - acc: 0.7500 - val_loss: 0.6750 - val_acc: 0.7161
Epoch 221/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6696 - acc: 0.7552 - val_loss: 0.6763 - val_acc: 0.7188
Epoch 222/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6498 - acc: 0.7643 - val_loss: 0.6667 - val_acc: 0.7214
Epoch 223/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6904 - acc: 0.7461 - val_loss: 0.6468 - val_acc: 0.7318
Epoch 224/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 335/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6565 - acc: 0.7656 - val_loss: 0.6657 - val_acc: 0.7214
Epoch 336/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6687 - acc: 0.7539 - val_loss: 0.6483 - val_acc: 0.7292
Epoch 337/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6582 - acc: 0.7682 - val_loss: 0.6766 - val_acc: 0.7188
Epoch 338/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6673 - acc: 0.7539 - val_loss: 0.6724 - val_acc: 0.7188
Epoch 339/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6652 - acc: 0.7591 - val_loss: 0.6721 - val_acc: 0.7161
Epoch 340/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6555 - acc: 0.7734 - val_loss: 0.6643 - val_acc: 0.7240
Epoch 341/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6627 - acc: 0.7565 - val_loss: 0.6655 - val_acc: 0.7214
Epoch 342/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 5s 12ms/step
0-cairo:	acc: 72.19%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 6s 476ms/step - loss: 1.6347 - acc: 0.4219 - val_loss: 1.2790 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.2925 - acc: 0.6302 - val_loss: 1.1093 - val_acc: 0.6432
Epoch 3/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.2405 - acc: 0.6315 - val_loss: 1.0844 - val_acc: 0.6328
Epoch 4/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1597 - acc: 0.6328 - val_loss: 1.0522 - val_acc: 0.6536
Epoch 5/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1128 - acc: 0.6523 - val_loss: 1.0134 - val_acc: 0.6667
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1028 - acc: 0.6562 - val_loss: 1.0250 - val_acc: 0.6797
Epoch 7/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0917 - acc: 0.6706 - val_loss: 0.9914 - val_acc: 0.6875
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5901 - acc: 0.7578 - val_loss: 0.5427 - val_acc: 0.7865
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6204 - acc: 0.7630 - val_loss: 0.5484 - val_acc: 0.7786
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6028 - acc: 0.7786 - val_loss: 0.5395 - val_acc: 0.7865
Epoch 120/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6247 - acc: 0.7474 - val_loss: 0.5409 - val_acc: 0.7760
Epoch 121/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5944 - acc: 0.7747 - val_loss: 0.5471 - val_acc: 0.7734
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6307 - acc: 0.7591 - val_loss: 0.5301 - val_acc: 0.7734
Epoch 123/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6258 - acc: 0.7695 - val_loss: 0.5347 - val_acc: 0.7891
Epoch 124/1000
12/12 [==============================] -

Epoch 176/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5862 - acc: 0.7786 - val_loss: 0.5402 - val_acc: 0.7734
Epoch 177/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6044 - acc: 0.7669 - val_loss: 0.5369 - val_acc: 0.7786
Epoch 178/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5711 - acc: 0.7865 - val_loss: 0.5377 - val_acc: 0.7786
Epoch 179/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5892 - acc: 0.7826 - val_loss: 0.5407 - val_acc: 0.7760
Epoch 180/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5883 - acc: 0.7734 - val_loss: 0.5333 - val_acc: 0.7786
Epoch 181/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6140 - acc: 0.7617 - val_loss: 0.5390 - val_acc: 0.7760
Epoch 182/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5834 - acc: 0.7773 - val_loss: 0.5296 - val_acc: 0.7760
Epoch 183/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.6031 - acc: 0.7734 - val_loss: 0.5421 - val_acc: 0.7734
Epoch 294/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5769 - acc: 0.7708 - val_loss: 0.5390 - val_acc: 0.7760
Epoch 295/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5733 - acc: 0.7917 - val_loss: 0.5386 - val_acc: 0.7734
Epoch 296/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5732 - acc: 0.7786 - val_loss: 0.5356 - val_acc: 0.7786
Epoch 297/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5968 - acc: 0.7682 - val_loss: 0.5315 - val_acc: 0.7812
Epoch 298/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5765 - acc: 0.7812 - val_loss: 0.5402 - val_acc: 0.7760
Epoch 299/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5952 - acc: 0.7656 - val_loss: 0.5369 - val_acc: 0.7786
Epoch 300/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 353/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6034 - acc: 0.7604 - val_loss: 0.5385 - val_acc: 0.7760
Epoch 354/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5974 - acc: 0.7565 - val_loss: 0.5348 - val_acc: 0.7812
Epoch 355/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6174 - acc: 0.7643 - val_loss: 0.5310 - val_acc: 0.7760
Epoch 356/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5967 - acc: 0.7643 - val_loss: 0.5299 - val_acc: 0.7786
Epoch 357/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5801 - acc: 0.7812 - val_loss: 0.5342 - val_acc: 0.7786
Epoch 358/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5903 - acc: 0.7721 - val_loss: 0.5354 - val_acc: 0.7760
Epoch 359/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5681 - acc: 0.7786 - val_loss: 0.5402 - val_acc: 0.7734
Epoch 360/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 5s 12ms/step
1-cairo:	acc: 77.75%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 6s 481ms/step - loss: 1.5341 - acc: 0.5911 - val_loss: 1.2325 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.2527 - acc: 0.6380 - val_loss: 1.1469 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.1793 - acc: 0.6380 - val_loss: 1.0988 - val_acc: 0.6354
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.1315 - acc: 0.6484 - val_loss: 1.0743 - val_acc: 0.6328
Epoch 5/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1214 - acc: 0.6615 - val_loss: 1.0328 - val_acc: 0.6589
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0807 - acc: 0.6602 - val_loss: 0.9983 - val_acc: 0.6641
Epoch 7/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0745 - acc: 0.6654 - val_loss: 0.9941 - val_acc: 0.6615
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6244 - acc: 0.7656 - val_loss: 0.5884 - val_acc: 0.7943
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6136 - acc: 0.7852 - val_loss: 0.5989 - val_acc: 0.7969
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6354 - acc: 0.7604 - val_loss: 0.5922 - val_acc: 0.7969
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6116 - acc: 0.7773 - val_loss: 0.6010 - val_acc: 0.7943
Epoch 121/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5837 - acc: 0.7930 - val_loss: 0.5978 - val_acc: 0.7969
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6198 - acc: 0.7891 - val_loss: 0.5974 - val_acc: 0.7969
Epoch 123/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6673 - acc: 0.7513 - val_loss: 0.5842 - val_acc: 0.7969
Epoch 124/1000
12/12 [==============================] -

Epoch 232/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6009 - acc: 0.7904 - val_loss: 0.5957 - val_acc: 0.7995
Epoch 233/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6116 - acc: 0.7695 - val_loss: 0.5804 - val_acc: 0.8073
Epoch 234/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6040 - acc: 0.7799 - val_loss: 0.5811 - val_acc: 0.8073
Epoch 235/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5954 - acc: 0.7891 - val_loss: 0.5884 - val_acc: 0.8047
Epoch 236/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5938 - acc: 0.7747 - val_loss: 0.5848 - val_acc: 0.8047
Epoch 237/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6080 - acc: 0.7839 - val_loss: 0.5942 - val_acc: 0.7995
Epoch 238/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6021 - acc: 0.7917 - val_loss: 0.5905 - val_acc: 0.8021
Epoch 239/1000
12/12 [==============================] -

12/12 [==============================] - 0s 12ms/step - loss: 0.6175 - acc: 0.7839 - val_loss: 0.5826 - val_acc: 0.8047
Epoch 291/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6054 - acc: 0.7878 - val_loss: 0.5734 - val_acc: 0.8073
Epoch 292/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6133 - acc: 0.7734 - val_loss: 0.5813 - val_acc: 0.8073
Epoch 293/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6255 - acc: 0.7643 - val_loss: 0.5930 - val_acc: 0.8021
Epoch 294/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5629 - acc: 0.8060 - val_loss: 0.5775 - val_acc: 0.8073
Epoch 295/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6265 - acc: 0.7799 - val_loss: 0.5844 - val_acc: 0.8047
Epoch 296/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5816 - acc: 0.7865 - val_loss: 0.5936 - val_acc: 0.7995
Epoch 297/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.6158 - acc: 0.7630 - val_loss: 0.5806 - val_acc: 0.8047
Epoch 406/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6167 - acc: 0.7630 - val_loss: 0.5935 - val_acc: 0.8021
Epoch 407/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5962 - acc: 0.7760 - val_loss: 0.5828 - val_acc: 0.8073
Epoch 408/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6378 - acc: 0.7708 - val_loss: 0.5921 - val_acc: 0.7995
Epoch 409/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6055 - acc: 0.7878 - val_loss: 0.5825 - val_acc: 0.8073
Epoch 410/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5853 - acc: 0.7773 - val_loss: 0.5968 - val_acc: 0.7995
Epoch 411/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6091 - acc: 0.7734 - val_loss: 0.5895 - val_acc: 0.8021
Epoch 412/1000
12/12 [==============================] - 0s 11ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 5s 13ms/step
2-cairo:	acc: 80.31%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 75.04% (+/- 1.91%)
final: current database: cairo 	 75.13% (+/- 1.85%)
CPU times: user 6min 30s, sys: 20.8 s, total: 6min 50s
Wall time: 7min 5s

best: current database: cairo 	 76.75% (+/- 3.39%)
final: current database: cairo 	 76.75% (+/- 3.39%)
CPU times: user 5min 47s, sys: 18 s, total: 6min 5s
Wall time: 4min 45s
```

# <a id='constrain_1'>CS_1</a>

In [7]:
%%time
dict_config_cus['distance_int'] = '1'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_19 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_19 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_19 (Conv1D)           (None, 2000, 12)          780       
_________________________________________________________________
activation_55 (Activation)   (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_19 (Glo (None, 12)                0         
_________________________________________________________________
dense_55 (Dense)             (None, 18)                234       
________________________________________

12/12 [==============================] - 0s 32ms/step - loss: 0.3199 - acc: 0.8828 - val_loss: 0.3740 - val_acc: 0.9010
Epoch 105/1000
12/12 [==============================] - 0s 31ms/step - loss: 0.3200 - acc: 0.8854 - val_loss: 0.3722 - val_acc: 0.9010
Epoch 106/1000
12/12 [==============================] - 0s 33ms/step - loss: 0.3351 - acc: 0.8854 - val_loss: 0.3617 - val_acc: 0.9089
Epoch 107/1000
12/12 [==============================] - 0s 32ms/step - loss: 0.3058 - acc: 0.8880 - val_loss: 0.3394 - val_acc: 0.9089
Epoch 108/1000
12/12 [==============================] - 0s 30ms/step - loss: 0.3269 - acc: 0.8828 - val_loss: 0.3752 - val_acc: 0.9062
Epoch 109/1000
12/12 [==============================] - 0s 33ms/step - loss: 0.3093 - acc: 0.8932 - val_loss: 0.3785 - val_acc: 0.9036
Epoch 110/1000
12/12 [==============================] - 0s 33ms/step - loss: 0.2959 - acc: 0.8945 - val_loss: 0.3728 - val_acc: 0.9036
Epoch 111/1000
12/12 [==============================] - 0s 36ms/step -

12/12 [==============================] - 0s 28ms/step - loss: 0.2789 - acc: 0.8919 - val_loss: 0.3815 - val_acc: 0.9089
Epoch 218/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.3044 - acc: 0.8958 - val_loss: 0.3819 - val_acc: 0.9089
Epoch 219/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.2954 - acc: 0.8854 - val_loss: 0.3852 - val_acc: 0.9062
Epoch 220/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.2931 - acc: 0.8945 - val_loss: 0.3693 - val_acc: 0.9089
Epoch 221/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.2922 - acc: 0.8997 - val_loss: 0.3863 - val_acc: 0.9062
Epoch 222/1000
12/12 [==============================] - 0s 28ms/step - loss: 0.3036 - acc: 0.8893 - val_loss: 0.3823 - val_acc: 0.9089
Epoch 223/1000
12/12 [==============================] - 0s 36ms/step - loss: 0.2880 - acc: 0.8919 - val_loss: 0.3856 - val_acc: 0.9062
Epoch 224/1000
12/12 [==============================] - 0s 25ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 2ms/step
0-cairo:	acc: 90.82%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 1s 112ms/step - loss: 1.4884 - acc: 0.5833 - val_loss: 1.0721 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 26ms/step - loss: 1.0706 - acc: 0.6341 - val_loss: 0.9128 - val_acc: 0.6406
Epoch 3/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.9586 - acc: 0.6484 - val_loss: 0.8690 - val_acc: 0.6797
Epoch 4/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.9352 - acc: 0.6549 - val_loss: 0.8336 - val_acc: 0.6927
Epoch 5/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.8722 - acc: 0.6758 - val_loss: 0.7918 - val_acc: 0.7344
Epoch 6/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.8391 - acc: 0.6862 - val_loss: 0.7380 - val_acc: 0.7422
Epoch 7/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.8055 - acc: 0.6914 - val_loss: 0.7129 - val_acc: 0.7344
Epoch 8/1000
12/12 [==============================] - 0s 33ms/step -

12/12 [==============================] - 0s 31ms/step - loss: 0.3614 - acc: 0.8659 - val_loss: 0.3216 - val_acc: 0.8828
Epoch 115/1000
12/12 [==============================] - 0s 33ms/step - loss: 0.3582 - acc: 0.8516 - val_loss: 0.3190 - val_acc: 0.8828
Epoch 116/1000
12/12 [==============================] - 0s 35ms/step - loss: 0.3879 - acc: 0.8542 - val_loss: 0.3196 - val_acc: 0.8932
Epoch 117/1000
12/12 [==============================] - 0s 31ms/step - loss: 0.3573 - acc: 0.8672 - val_loss: 0.3166 - val_acc: 0.8932
Epoch 118/1000
12/12 [==============================] - 0s 32ms/step - loss: 0.3698 - acc: 0.8607 - val_loss: 0.3234 - val_acc: 0.8906
Epoch 119/1000
12/12 [==============================] - 0s 32ms/step - loss: 0.3422 - acc: 0.8607 - val_loss: 0.3240 - val_acc: 0.8802
Epoch 120/1000
12/12 [==============================] - 0s 37ms/step - loss: 0.3560 - acc: 0.8490 - val_loss: 0.3179 - val_acc: 0.8958
Epoch 121/1000
12/12 [==============================] - 0s 34ms/step -

12/12 [==============================] - 0s 27ms/step - loss: 0.3113 - acc: 0.8893 - val_loss: 0.3032 - val_acc: 0.9036
Epoch 231/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.2999 - acc: 0.8880 - val_loss: 0.3160 - val_acc: 0.9010
Epoch 232/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.2865 - acc: 0.8997 - val_loss: 0.3153 - val_acc: 0.9010
Epoch 233/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.3007 - acc: 0.8815 - val_loss: 0.3176 - val_acc: 0.9010

Epoch 00233: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 234/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.2842 - acc: 0.9049 - val_loss: 0.3119 - val_acc: 0.9036
Epoch 235/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.2899 - acc: 0.8958 - val_loss: 0.3141 - val_acc: 0.9010
Epoch 236/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.3137 - acc: 0.8945 - val_loss: 0.3104 - val_a

12/12 [==============================] - 0s 25ms/step - loss: 0.3025 - acc: 0.8919 - val_loss: 0.3077 - val_acc: 0.9141
Epoch 344/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.3019 - acc: 0.8880 - val_loss: 0.3148 - val_acc: 0.9089
Epoch 345/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.3047 - acc: 0.8841 - val_loss: 0.3137 - val_acc: 0.9089
Epoch 346/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.3002 - acc: 0.8906 - val_loss: 0.3132 - val_acc: 0.9115
Epoch 347/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.2913 - acc: 0.8997 - val_loss: 0.3009 - val_acc: 0.9167
Epoch 348/1000
12/12 [==============================] - 0s 29ms/step - loss: 0.2731 - acc: 0.9010 - val_loss: 0.3134 - val_acc: 0.9115
Epoch 349/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.2750 - acc: 0.9023 - val_loss: 0.3068 - val_acc: 0.9115
Epoch 350/1000
12/12 [==============================] - 0s 27ms/step -

Epoch 458/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3081 - acc: 0.8880 - val_loss: 0.3004 - val_acc: 0.9141
Epoch 459/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3086 - acc: 0.8919 - val_loss: 0.3115 - val_acc: 0.9115
Epoch 460/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3068 - acc: 0.8945 - val_loss: 0.2948 - val_acc: 0.9167
Epoch 461/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3081 - acc: 0.8828 - val_loss: 0.2897 - val_acc: 0.9115
Epoch 462/1000
12/12 [==============================] - 0s 21ms/step - loss: 0.2878 - acc: 0.8958 - val_loss: 0.3141 - val_acc: 0.9115
Epoch 463/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3033 - acc: 0.8828 - val_loss: 0.3134 - val_acc: 0.9089
Epoch 464/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3172 - acc: 0.8893 - val_loss: 0.3168 - val_acc: 0.9089
Epoch 465/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
1-cairo:	acc: 91.05%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 1s 111ms/step - loss: 1.7246 - acc: 0.2721 - val_loss: 1.3401 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 25ms/step - loss: 1.1890 - acc: 0.6016 - val_loss: 1.0030 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 26ms/step - loss: 1.0224 - acc: 0.6419 - val_loss: 0.9277 - val_acc: 0.6328
Epoch 4/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.9487 - acc: 0.6510 - val_loss: 0.9015 - val_acc: 0.6510
Epoch 5/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.8947 - acc: 0.6680 - val_loss: 0.8578 - val_acc: 0.6667
Epoch 6/1000
12/12 [==============================] - 0s 30ms/step - loss: 0.8798 - acc: 0.6771 - val_loss: 0.8283 - val_acc: 0.6719
Epoch 7/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.8583 - acc: 0.6732 - val_loss: 0.8175 - val_acc: 0.6667
Epoch 8/1000
12/12 [==============================] - 0s 26ms/step -

12/12 [==============================] - 0s 27ms/step - loss: 0.3093 - acc: 0.9023 - val_loss: 0.3770 - val_acc: 0.9010
Epoch 116/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.3022 - acc: 0.9102 - val_loss: 0.3760 - val_acc: 0.9010
Epoch 117/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.3074 - acc: 0.9062 - val_loss: 0.3693 - val_acc: 0.9010
Epoch 118/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.3068 - acc: 0.9049 - val_loss: 0.3755 - val_acc: 0.8984
Epoch 119/1000
12/12 [==============================] - 0s 26ms/step - loss: 0.3021 - acc: 0.9128 - val_loss: 0.3711 - val_acc: 0.9010
Epoch 120/1000
12/12 [==============================] - 0s 27ms/step - loss: 0.3034 - acc: 0.9102 - val_loss: 0.3724 - val_acc: 0.9036
Epoch 121/1000
12/12 [==============================] - 0s 25ms/step - loss: 0.2981 - acc: 0.9089 - val_loss: 0.3278 - val_acc: 0.9089
Epoch 122/1000
12/12 [==============================] - 0s 24ms/step -

12/12 [==============================] - 0s 20ms/step - loss: 0.2765 - acc: 0.9141 - val_loss: 0.3329 - val_acc: 0.9062
Epoch 173/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3135 - acc: 0.9010 - val_loss: 0.3706 - val_acc: 0.9062
Epoch 174/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.2875 - acc: 0.9115 - val_loss: 0.3744 - val_acc: 0.9036
Epoch 175/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.2822 - acc: 0.9167 - val_loss: 0.3730 - val_acc: 0.9062
Epoch 176/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3248 - acc: 0.8971 - val_loss: 0.3700 - val_acc: 0.9062
Epoch 177/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.2571 - acc: 0.9128 - val_loss: 0.3707 - val_acc: 0.9062

Epoch 00177: loss improved from 0.30024 to 0.25714, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_3/weights/Pbest-2-000177-0.257138-0.906250.hdf5
Epoch 178/1000
12/12 [=======

12/12 [==============================] - 0s 20ms/step - loss: 0.2919 - acc: 0.9141 - val_loss: 0.3675 - val_acc: 0.9089
Epoch 231/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3105 - acc: 0.9076 - val_loss: 0.3589 - val_acc: 0.9062
Epoch 232/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3000 - acc: 0.9102 - val_loss: 0.3680 - val_acc: 0.9062
Epoch 233/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3132 - acc: 0.9128 - val_loss: 0.3700 - val_acc: 0.9062
Epoch 234/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3077 - acc: 0.8984 - val_loss: 0.3751 - val_acc: 0.9036
Epoch 235/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3228 - acc: 0.8958 - val_loss: 0.3697 - val_acc: 0.9062
Epoch 236/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.2960 - acc: 0.9036 - val_loss: 0.3596 - val_acc: 0.9062
Epoch 237/1000
12/12 [==============================] - 0s 19ms/step -

Epoch 349/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3209 - acc: 0.9010 - val_loss: 0.3750 - val_acc: 0.9036
Epoch 350/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.2934 - acc: 0.9089 - val_loss: 0.3596 - val_acc: 0.9062
Epoch 351/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3030 - acc: 0.9036 - val_loss: 0.3746 - val_acc: 0.9036
Epoch 352/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.2737 - acc: 0.9036 - val_loss: 0.3586 - val_acc: 0.9089
Epoch 353/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.2852 - acc: 0.9036 - val_loss: 0.3747 - val_acc: 0.9036
Epoch 354/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3125 - acc: 0.9049 - val_loss: 0.3740 - val_acc: 0.9036
Epoch 355/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.2895 - acc: 0.9036 - val_loss: 0.3702 - val_acc: 0.9062
Epoch 356/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
2-cairo:	acc: 90.54%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 90.80% (+/- 0.21%)
final: current database: cairo 	 90.80% (+/- 0.21%)
CPU times: user 6min 24s, sys: 19.4 s, total: 6min 43s
Wall time: 7min

```

# <a id='constrain_2'>CS_2</a>

In [8]:
%%time
dict_config_cus['distance_int'] = '2'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_28 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_28 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_28 (Conv1D)           (None, 2000, 12)          780       
_________________________________________________________________
activation_82 (Activation)   (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_28 (Glo (None, 12)                0         
_________________________________________________________________
dense_82 (Dense)             (None, 18)                234       
________________________________________

12/12 [==============================] - 0s 20ms/step - loss: 0.6318 - acc: 0.7695 - val_loss: 0.6357 - val_acc: 0.7448

Epoch 00100: saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/0-000100-0.631849-0.744792.hdf5
Epoch 101/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6035 - acc: 0.7682 - val_loss: 0.6514 - val_acc: 0.7318
Epoch 102/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6188 - acc: 0.7656 - val_loss: 0.6562 - val_acc: 0.7266
Epoch 103/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6361 - acc: 0.7487 - val_loss: 0.6264 - val_acc: 0.7370
Epoch 104/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.6168 - acc: 0.7669 - val_loss: 0.6540 - val_acc: 0.7266
Epoch 105/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.6173 - acc: 0.7682 - val_loss: 0.6441 - val_acc: 0.7318
Epoch 106/1000
12/12 [==============================] - 0s 21ms/step - los

12/12 [==============================] - 0s 19ms/step - loss: 0.5899 - acc: 0.7747 - val_loss: 0.6567 - val_acc: 0.7240
Epoch 214/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5605 - acc: 0.7865 - val_loss: 0.6582 - val_acc: 0.7266
Epoch 215/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5736 - acc: 0.7878 - val_loss: 0.6428 - val_acc: 0.7292
Epoch 216/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5794 - acc: 0.7760 - val_loss: 0.6486 - val_acc: 0.7292
Epoch 217/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5939 - acc: 0.7812 - val_loss: 0.6434 - val_acc: 0.7292
Epoch 218/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5957 - acc: 0.7773 - val_loss: 0.6446 - val_acc: 0.7344
Epoch 219/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5631 - acc: 0.7917 - val_loss: 0.6533 - val_acc: 0.7318
Epoch 220/1000
12/12 [==============================] - 0s 20ms/step -

Epoch 271/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5673 - acc: 0.7969 - val_loss: 0.6456 - val_acc: 0.7292
Epoch 272/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5819 - acc: 0.7865 - val_loss: 0.6491 - val_acc: 0.7266
Epoch 273/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5863 - acc: 0.7865 - val_loss: 0.6574 - val_acc: 0.7292

Epoch 00273: loss improved from 0.59570 to 0.58635, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/Pbest-0-000273-0.586347-0.729167.hdf5
Epoch 274/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.6021 - acc: 0.7760 - val_loss: 0.6455 - val_acc: 0.7318
Epoch 275/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5842 - acc: 0.7904 - val_loss: 0.6361 - val_acc: 0.7318
Epoch 276/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5630 - acc: 0.7878 - val_loss: 0.6562 - val_acc: 0.7292
Epoch 277/1000

12/12 [==============================] - 0s 20ms/step - loss: 0.5856 - acc: 0.7826 - val_loss: 0.6506 - val_acc: 0.7240
Epoch 329/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5680 - acc: 0.7826 - val_loss: 0.6372 - val_acc: 0.7292
Epoch 330/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6022 - acc: 0.7747 - val_loss: 0.6389 - val_acc: 0.7318
Epoch 331/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5847 - acc: 0.7839 - val_loss: 0.6496 - val_acc: 0.7292
Epoch 332/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5589 - acc: 0.7839 - val_loss: 0.6525 - val_acc: 0.7318
Epoch 333/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5757 - acc: 0.7839 - val_loss: 0.6499 - val_acc: 0.7292
Epoch 334/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5808 - acc: 0.7669 - val_loss: 0.6621 - val_acc: 0.7214
Epoch 335/1000
12/12 [==============================] - 0s 19ms/step -

12/12 [==============================] - 0s 19ms/step - loss: 0.5877 - acc: 0.7865 - val_loss: 0.6622 - val_acc: 0.7214
Epoch 387/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5866 - acc: 0.7591 - val_loss: 0.6585 - val_acc: 0.7240
Epoch 00387: early stopping
ModelCheckpoint 已经保存到 ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/0-final.hdf5
Create subdir directory: ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/log...
save in: ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/log/20220201_2000_64_1_3.csv
time: 0:01:38 s
time: 98.0 s
average 0.098000 s
0 epoch finished
--------------------   best   --------------------
no_activities: 7

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 2ms/step
0-cairo:	acc: 74.23%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 2ms/step
0-cairo:	acc: 72.70%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 119ms/step - loss: 1.8934 - acc: 0.3438 - val_loss: 1.7931 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.6516 - acc: 0.5977 - val_loss: 1.3821 - val_acc: 0.6406
Epoch 3/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.3465 - acc: 0.6380 - val_loss: 1.1644 - val_acc: 0.6406
Epoch 4/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.2261 - acc: 0.6419 - val_loss: 1.0767 - val_acc: 0.6354
Epoch 5/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.1430 - acc: 0.6549 - val_loss: 1.0229 - val_acc: 0.6667
Epoch 6/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.1189 - acc: 0.6523 - val_loss: 0.9904 - val_acc: 0.6771
Epoch 7/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.0677 - acc: 0.6641 - val_loss: 0.9455 - val_acc: 0.6797
Epoch 8/1000
12/12 [=============================

12/12 [==============================] - 0s 19ms/step - loss: 0.7126 - acc: 0.7318 - val_loss: 0.5888 - val_acc: 0.7500
Epoch 63/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.7086 - acc: 0.7461 - val_loss: 0.5847 - val_acc: 0.7526
Epoch 64/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7161 - acc: 0.7422 - val_loss: 0.5823 - val_acc: 0.7500
Epoch 65/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6831 - acc: 0.7344 - val_loss: 0.5859 - val_acc: 0.7448

Epoch 00065: loss improved from inf to 0.68315, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/Pbest-1-000065-0.683146-0.744792.hdf5
Epoch 66/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6929 - acc: 0.7357 - val_loss: 0.5830 - val_acc: 0.7474
Epoch 67/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6914 - acc: 0.7552 - val_loss: 0.5753 - val_acc: 0.7604
Epoch 68/1000
12/12 [=================

Epoch 173/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5989 - acc: 0.7852 - val_loss: 0.4786 - val_acc: 0.8307
Epoch 174/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5941 - acc: 0.7734 - val_loss: 0.4886 - val_acc: 0.8281
Epoch 175/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5822 - acc: 0.7839 - val_loss: 0.4923 - val_acc: 0.8177
Epoch 176/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5754 - acc: 0.7969 - val_loss: 0.4967 - val_acc: 0.8151
Epoch 177/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5837 - acc: 0.7878 - val_loss: 0.4893 - val_acc: 0.8203
Epoch 178/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5951 - acc: 0.7786 - val_loss: 0.4933 - val_acc: 0.8255
Epoch 179/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5982 - acc: 0.7747 - val_loss: 0.4924 - val_acc: 0.8177
Epoch 180/1000
12/12 [==============================] -

Epoch 287/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5764 - acc: 0.7956 - val_loss: 0.4828 - val_acc: 0.8177
Epoch 288/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5813 - acc: 0.7904 - val_loss: 0.4899 - val_acc: 0.8151
Epoch 289/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5818 - acc: 0.7656 - val_loss: 0.4936 - val_acc: 0.8151
Epoch 290/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5983 - acc: 0.7839 - val_loss: 0.4935 - val_acc: 0.8151
Epoch 291/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5524 - acc: 0.7969 - val_loss: 0.4856 - val_acc: 0.8177
Epoch 292/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5853 - acc: 0.7878 - val_loss: 0.4904 - val_acc: 0.8203
Epoch 293/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5759 - acc: 0.7839 - val_loss: 0.4919 - val_acc: 0.8151
Epoch 294/1000
12/12 [==============================] -

Epoch 347/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5881 - acc: 0.7773 - val_loss: 0.4927 - val_acc: 0.8177
Epoch 348/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5826 - acc: 0.7786 - val_loss: 0.4809 - val_acc: 0.8229
Epoch 349/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5531 - acc: 0.7917 - val_loss: 0.4863 - val_acc: 0.8203
Epoch 350/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5919 - acc: 0.7839 - val_loss: 0.4764 - val_acc: 0.8229
Epoch 351/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5926 - acc: 0.7734 - val_loss: 0.4959 - val_acc: 0.8151
Epoch 352/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5799 - acc: 0.7878 - val_loss: 0.4933 - val_acc: 0.8151
Epoch 353/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5780 - acc: 0.7721 - val_loss: 0.4837 - val_acc: 0.8203
Epoch 354/1000
12/12 [==============================] -

Epoch 403/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5907 - acc: 0.7747 - val_loss: 0.4931 - val_acc: 0.8151
Epoch 404/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.6058 - acc: 0.7812 - val_loss: 0.4803 - val_acc: 0.8203
Epoch 405/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.5614 - acc: 0.7995 - val_loss: 0.4905 - val_acc: 0.8177
Epoch 406/1000
12/12 [==============================] - 0s 23ms/step - loss: 0.5817 - acc: 0.7721 - val_loss: 0.4917 - val_acc: 0.8203
Epoch 407/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.6036 - acc: 0.7708 - val_loss: 0.4900 - val_acc: 0.8203
Epoch 408/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5849 - acc: 0.7812 - val_loss: 0.4839 - val_acc: 0.8229
Epoch 409/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5559 - acc: 0.7865 - val_loss: 0.4845 - val_acc: 0.8229
Epoch 410/1000
12/12 [==============================] -

Epoch 464/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5759 - acc: 0.7760 - val_loss: 0.4885 - val_acc: 0.8203
Epoch 465/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5579 - acc: 0.7930 - val_loss: 0.4797 - val_acc: 0.8229

Epoch 00465: loss improved from inf to 0.55790, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/Pbest-1-000465-0.557895-0.822917.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5917 - acc: 0.7878 - val_loss: 0.4889 - val_acc: 0.8203
Epoch 467/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5618 - acc: 0.7799 - val_loss: 0.4950 - val_acc: 0.8177
Epoch 468/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5672 - acc: 0.7852 - val_loss: 0.4937 - val_acc: 0.8177
Epoch 469/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5766 - acc: 0.7943 - val_loss: 0.4930 - val_acc: 0.8177
Epoch 470/1000
12/

12/12 [==============================] - 0s 19ms/step - loss: 0.5901 - acc: 0.7799 - val_loss: 0.4906 - val_acc: 0.8203
Epoch 581/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5769 - acc: 0.7826 - val_loss: 0.4911 - val_acc: 0.8203
Epoch 582/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5665 - acc: 0.7604 - val_loss: 0.4918 - val_acc: 0.8177
Epoch 583/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5807 - acc: 0.7695 - val_loss: 0.4913 - val_acc: 0.8203
Epoch 584/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5925 - acc: 0.7852 - val_loss: 0.4865 - val_acc: 0.8203
Epoch 585/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5856 - acc: 0.7669 - val_loss: 0.4920 - val_acc: 0.8177
Epoch 586/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5878 - acc: 0.7773 - val_loss: 0.4934 - val_acc: 0.8177
Epoch 587/1000
12/12 [==============================] - 0s 19ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
1-cairo:	acc: 82.10%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 2s 131ms/step - loss: 1.6315 - acc: 0.5560 - val_loss: 1.2785 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 15ms/step - loss: 1.2626 - acc: 0.6341 - val_loss: 1.1364 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 22ms/step - loss: 1.2169 - acc: 0.6341 - val_loss: 1.0919 - val_acc: 0.6302
Epoch 4/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.1206 - acc: 0.6458 - val_loss: 1.0393 - val_acc: 0.6328
Epoch 5/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.0836 - acc: 0.6484 - val_loss: 0.9822 - val_acc: 0.6771
Epoch 6/1000
12/12 [==============================] - 0s 20ms/step - loss: 1.0649 - acc: 0.6562 - val_loss: 0.9562 - val_acc: 0.6693
Epoch 7/1000
12/12 [==============================] - 0s 20ms/step - loss: 1.0302 - acc: 0.6602 - val_loss: 0.9304 - val_acc: 0.6693
Epoch 8/1000
12/12 [==============================] - 0s 19ms/step -

12/12 [==============================] - 0s 19ms/step - loss: 0.6640 - acc: 0.7474 - val_loss: 0.5903 - val_acc: 0.8177
Epoch 120/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6345 - acc: 0.7591 - val_loss: 0.5886 - val_acc: 0.8047
Epoch 121/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6554 - acc: 0.7604 - val_loss: 0.5825 - val_acc: 0.8125
Epoch 122/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6185 - acc: 0.7474 - val_loss: 0.5795 - val_acc: 0.8151
Epoch 123/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6064 - acc: 0.7617 - val_loss: 0.5691 - val_acc: 0.8125
Epoch 124/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.6493 - acc: 0.7448 - val_loss: 0.5767 - val_acc: 0.8177
Epoch 125/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.6251 - acc: 0.7370 - val_loss: 0.5790 - val_acc: 0.7995
Epoch 126/1000
12/12 [==============================] - 0s 19ms/step -

Epoch 233/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5540 - acc: 0.7878 - val_loss: 0.5215 - val_acc: 0.8229
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5486 - acc: 0.7904 - val_loss: 0.5208 - val_acc: 0.8125
Epoch 235/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5690 - acc: 0.7734 - val_loss: 0.5116 - val_acc: 0.8151
Epoch 236/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5700 - acc: 0.7682 - val_loss: 0.5253 - val_acc: 0.8099
Epoch 237/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5583 - acc: 0.7786 - val_loss: 0.5331 - val_acc: 0.8177
Epoch 238/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5580 - acc: 0.8021 - val_loss: 0.5300 - val_acc: 0.8229
Epoch 239/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5807 - acc: 0.7878 - val_loss: 0.5200 - val_acc: 0.8203
Epoch 240/1000
12/12 [==============================] -

12/12 [==============================] - 0s 19ms/step - loss: 0.5609 - acc: 0.7799 - val_loss: 0.5261 - val_acc: 0.8229
Epoch 351/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5777 - acc: 0.7799 - val_loss: 0.5279 - val_acc: 0.8203
Epoch 352/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5353 - acc: 0.7956 - val_loss: 0.5038 - val_acc: 0.8229
Epoch 353/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5740 - acc: 0.7630 - val_loss: 0.5281 - val_acc: 0.8177
Epoch 354/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5508 - acc: 0.7826 - val_loss: 0.5142 - val_acc: 0.8229
Epoch 355/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5310 - acc: 0.7917 - val_loss: 0.5186 - val_acc: 0.8203
Epoch 356/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.5498 - acc: 0.7852 - val_loss: 0.5306 - val_acc: 0.8177
Epoch 357/1000
12/12 [==============================] - 0s 19ms/step -

Epoch 465/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5408 - acc: 0.7891 - val_loss: 0.5180 - val_acc: 0.8229

Epoch 00465: loss improved from inf to 0.54081, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/Pbest-2-000465-0.540815-0.822917.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5591 - acc: 0.7799 - val_loss: 0.5239 - val_acc: 0.8281
Epoch 467/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5628 - acc: 0.7708 - val_loss: 0.5132 - val_acc: 0.8255
Epoch 468/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5511 - acc: 0.8047 - val_loss: 0.5240 - val_acc: 0.8203
Epoch 469/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5381 - acc: 0.7904 - val_loss: 0.5227 - val_acc: 0.8229

Epoch 00469: loss improved from 0.54081 to 0.53808, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_3/weights/Pbest-2-000469-

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
2-cairo:	acc: 82.10%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 78.88% (+/- 3.36%)
final: current database: cairo 	 78.97% (+/- 4.43%)
CPU times: user 6min 22s, sys: 23.9 s, total: 6min 46s
Wall time: 6min 21s

```

# <a id='constrain_3'>CS_3</a>

In [22]:
%%time
dict_config_cus['distance_int'] = '3'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_154 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_154 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_154 (Conv1D)          (None, 2000, 12)          780       
_________________________________________________________________
activation_460 (Activation)  (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_154 (Gl (None, 12)                0         
_________________________________________________________________
dense_460 (Dense)            (None, 18)                234       
________________________________________

12/12 [==============================] - 0s 12ms/step - loss: 0.5627 - acc: 0.8021 - val_loss: 0.6028 - val_acc: 0.7760
Epoch 103/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5664 - acc: 0.8047 - val_loss: 0.6057 - val_acc: 0.7708
Epoch 104/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5655 - acc: 0.8216 - val_loss: 0.6057 - val_acc: 0.7760
Epoch 105/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6012 - acc: 0.7969 - val_loss: 0.6075 - val_acc: 0.7734
Epoch 106/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5713 - acc: 0.8151 - val_loss: 0.5964 - val_acc: 0.7734
Epoch 107/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5797 - acc: 0.8047 - val_loss: 0.5836 - val_acc: 0.7839
Epoch 108/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5601 - acc: 0.8034 - val_loss: 0.6002 - val_acc: 0.7734
Epoch 109/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5685 - acc: 0.8073 - val_loss: 0.5874 - val_acc: 0.7760
Epoch 219/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5595 - acc: 0.8203 - val_loss: 0.5959 - val_acc: 0.7682
Epoch 220/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5567 - acc: 0.8125 - val_loss: 0.5950 - val_acc: 0.7682
Epoch 221/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5501 - acc: 0.8060 - val_loss: 0.5874 - val_acc: 0.7760
Epoch 222/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5567 - acc: 0.8151 - val_loss: 0.5855 - val_acc: 0.7734
Epoch 223/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.5789 - acc: 0.7982 - val_loss: 0.5978 - val_acc: 0.7708
Epoch 224/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5405 - acc: 0.8190 - val_loss: 0.5934 - val_acc: 0.7708
Epoch 225/1000
12/12 [==============================] -

12/12 [==============================] - 0s 12ms/step - loss: 0.5643 - acc: 0.8177 - val_loss: 0.5887 - val_acc: 0.7760
Epoch 277/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5436 - acc: 0.8294 - val_loss: 0.5908 - val_acc: 0.7734
Epoch 278/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5551 - acc: 0.8086 - val_loss: 0.5835 - val_acc: 0.7708
Epoch 279/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.5402 - acc: 0.8216 - val_loss: 0.5917 - val_acc: 0.7734
Epoch 280/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5670 - acc: 0.8073 - val_loss: 0.5910 - val_acc: 0.7708
Epoch 281/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5534 - acc: 0.8177 - val_loss: 0.5929 - val_acc: 0.7734
Epoch 282/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5447 - acc: 0.8255 - val_loss: 0.5995 - val_acc: 0.7682
Epoch 283/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 336/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5526 - acc: 0.8164 - val_loss: 0.5795 - val_acc: 0.7760
Epoch 337/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5564 - acc: 0.8242 - val_loss: 0.5939 - val_acc: 0.7734
Epoch 338/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5455 - acc: 0.8229 - val_loss: 0.5917 - val_acc: 0.7734
Epoch 339/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5474 - acc: 0.8190 - val_loss: 0.5950 - val_acc: 0.7708
Epoch 340/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5270 - acc: 0.8320 - val_loss: 0.5879 - val_acc: 0.7760
Epoch 341/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5605 - acc: 0.8021 - val_loss: 0.5824 - val_acc: 0.7760
Epoch 342/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5843 - acc: 0.8034 - val_loss: 0.5901 - val_acc: 0.7760
Epoch 343/1000
12/12 [==============================] -

Epoch 451/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5184 - acc: 0.8255 - val_loss: 0.5870 - val_acc: 0.7734
Epoch 452/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5222 - acc: 0.8307 - val_loss: 0.5958 - val_acc: 0.7682
Epoch 453/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5608 - acc: 0.8099 - val_loss: 0.5946 - val_acc: 0.7734
Epoch 454/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5416 - acc: 0.8177 - val_loss: 0.5854 - val_acc: 0.7734
Epoch 455/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5432 - acc: 0.8151 - val_loss: 0.5858 - val_acc: 0.7708
Epoch 456/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5417 - acc: 0.8164 - val_loss: 0.5893 - val_acc: 0.7734
Epoch 457/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5693 - acc: 0.8047 - val_loss: 0.5975 - val_acc: 0.7682
Epoch 458/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.5318 - acc: 0.8203 - val_loss: 0.5959 - val_acc: 0.7708
Epoch 568/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5390 - acc: 0.8125 - val_loss: 0.5972 - val_acc: 0.7682
Epoch 569/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5430 - acc: 0.8177 - val_loss: 0.5873 - val_acc: 0.7760

Epoch 00569: loss improved from 0.54706 to 0.54297, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-0-000569-0.542968-0.776042.hdf5
Epoch 570/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.5516 - acc: 0.8216 - val_loss: 0.5945 - val_acc: 0.7734
Epoch 571/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5456 - acc: 0.8125 - val_loss: 0.5904 - val_acc: 0.7734
Epoch 572/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5678 - acc: 0.8073 - val_loss: 0.6001 - val_acc: 0.7682
Epoch 573/1000
12/12 [=======

Epoch 623/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5547 - acc: 0.8151 - val_loss: 0.5965 - val_acc: 0.7708
Epoch 624/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5468 - acc: 0.8164 - val_loss: 0.5958 - val_acc: 0.7682
Epoch 625/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5410 - acc: 0.8060 - val_loss: 0.5971 - val_acc: 0.7682
Epoch 626/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5365 - acc: 0.8216 - val_loss: 0.5918 - val_acc: 0.7734
Epoch 627/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5392 - acc: 0.8203 - val_loss: 0.5947 - val_acc: 0.7708
Epoch 628/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5365 - acc: 0.8177 - val_loss: 0.5853 - val_acc: 0.7734
Epoch 629/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5388 - acc: 0.8086 - val_loss: 0.5870 - val_acc: 0.7708
Epoch 630/1000
12/12 [==============================] -

Epoch 742/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5493 - acc: 0.8047 - val_loss: 0.5893 - val_acc: 0.7760
Epoch 743/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5501 - acc: 0.8086 - val_loss: 0.5970 - val_acc: 0.7682
Epoch 744/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5404 - acc: 0.7995 - val_loss: 0.5910 - val_acc: 0.7760
Epoch 745/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5514 - acc: 0.8060 - val_loss: 0.5841 - val_acc: 0.7760
Epoch 746/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5606 - acc: 0.8073 - val_loss: 0.5984 - val_acc: 0.7682
Epoch 747/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5629 - acc: 0.8112 - val_loss: 0.5969 - val_acc: 0.7708
Epoch 748/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5072 - acc: 0.8320 - val_loss: 0.5899 - val_acc: 0.7708
Epoch 749/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.5610 - acc: 0.8047 - val_loss: 0.5890 - val_acc: 0.7734

Epoch 00800: saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/0-000800-0.561006-0.773438.hdf5
Epoch 801/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.5697 - acc: 0.8086 - val_loss: 0.5972 - val_acc: 0.7708
Epoch 802/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5485 - acc: 0.8021 - val_loss: 0.5933 - val_acc: 0.7734
Epoch 803/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5320 - acc: 0.8216 - val_loss: 0.5914 - val_acc: 0.7734
Epoch 804/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5477 - acc: 0.8255 - val_loss: 0.5773 - val_acc: 0.7760
Epoch 805/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5438 - acc: 0.8164 - val_loss: 0.5927 - val_acc: 0.7708
Epoch 806/1000
12/12 [==============================] - 0s 12ms/step - los

Epoch 860/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5675 - acc: 0.8060 - val_loss: 0.5905 - val_acc: 0.7708
Epoch 861/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5778 - acc: 0.8086 - val_loss: 0.5947 - val_acc: 0.7708
Epoch 862/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5510 - acc: 0.8073 - val_loss: 0.5953 - val_acc: 0.7682
Epoch 863/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5548 - acc: 0.8177 - val_loss: 0.5832 - val_acc: 0.7734
Epoch 864/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5602 - acc: 0.8255 - val_loss: 0.5844 - val_acc: 0.7786
Epoch 865/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5300 - acc: 0.8398 - val_loss: 0.5677 - val_acc: 0.7786

Epoch 00865: loss improved from inf to 0.53003, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-0-000865-0.530032-0.778646.hdf5
Epoch 866/1000
12/

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 7s 19ms/step
0-cairo:	acc: 77.30%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 8s 701ms/step - loss: 1.4927 - acc: 0.6107 - val_loss: 1.2485 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.2482 - acc: 0.6341 - val_loss: 1.1577 - val_acc: 0.6406
Epoch 3/1000
12/12 [==============================] - 0s 19ms/step - loss: 1.1755 - acc: 0.6328 - val_loss: 1.1253 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.1581 - acc: 0.6354 - val_loss: 1.0967 - val_acc: 0.6380
Epoch 5/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.1062 - acc: 0.6380 - val_loss: 1.0601 - val_acc: 0.6380
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.0941 - acc: 0.6419 - val_loss: 1.0427 - val_acc: 0.6354
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0753 - acc: 0.6406 - val_loss: 1.0171 - val_acc: 0.6380
Epoch 8/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.7255 - acc: 0.7253 - val_loss: 0.6799 - val_acc: 0.7344
Epoch 115/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6937 - acc: 0.7396 - val_loss: 0.6815 - val_acc: 0.7370
Epoch 116/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7192 - acc: 0.7435 - val_loss: 0.6753 - val_acc: 0.7448
Epoch 117/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6895 - acc: 0.7383 - val_loss: 0.6723 - val_acc: 0.7370
Epoch 118/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7115 - acc: 0.7396 - val_loss: 0.6633 - val_acc: 0.7448
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7324 - acc: 0.7253 - val_loss: 0.6597 - val_acc: 0.7500
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7016 - acc: 0.7279 - val_loss: 0.6626 - val_acc: 0.7422
Epoch 121/1000
12/12 [==============================] - 0s 13ms/step -

Epoch 228/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6303 - acc: 0.7682 - val_loss: 0.6289 - val_acc: 0.7578
Epoch 229/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6581 - acc: 0.7604 - val_loss: 0.6247 - val_acc: 0.7578
Epoch 230/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6608 - acc: 0.7409 - val_loss: 0.6193 - val_acc: 0.7630
Epoch 231/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6277 - acc: 0.7565 - val_loss: 0.6253 - val_acc: 0.7578
Epoch 232/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6469 - acc: 0.7656 - val_loss: 0.6194 - val_acc: 0.7630
Epoch 233/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6416 - acc: 0.7630 - val_loss: 0.6317 - val_acc: 0.7578
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6630 - acc: 0.7513 - val_loss: 0.6269 - val_acc: 0.7578
Epoch 235/1000
12/12 [==============================] -

Epoch 287/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6844 - acc: 0.7513 - val_loss: 0.6263 - val_acc: 0.7604
Epoch 288/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6288 - acc: 0.7591 - val_loss: 0.6243 - val_acc: 0.7630
Epoch 289/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6791 - acc: 0.7422 - val_loss: 0.6242 - val_acc: 0.7578
Epoch 290/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6797 - acc: 0.7383 - val_loss: 0.6189 - val_acc: 0.7630
Epoch 291/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.6771 - acc: 0.7526 - val_loss: 0.6093 - val_acc: 0.7682
Epoch 292/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6298 - acc: 0.7500 - val_loss: 0.6312 - val_acc: 0.7552
Epoch 293/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6629 - acc: 0.7422 - val_loss: 0.6162 - val_acc: 0.7630
Epoch 294/1000
12/12 [==============================] -

Epoch 347/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6452 - acc: 0.7565 - val_loss: 0.6322 - val_acc: 0.7552
Epoch 348/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6723 - acc: 0.7422 - val_loss: 0.6302 - val_acc: 0.7578
Epoch 349/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6382 - acc: 0.7539 - val_loss: 0.6222 - val_acc: 0.7604
Epoch 350/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6528 - acc: 0.7500 - val_loss: 0.6252 - val_acc: 0.7578
Epoch 351/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6483 - acc: 0.7630 - val_loss: 0.6236 - val_acc: 0.7630
Epoch 352/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6557 - acc: 0.7578 - val_loss: 0.6269 - val_acc: 0.7578
Epoch 353/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6431 - acc: 0.7565 - val_loss: 0.6206 - val_acc: 0.7604
Epoch 354/1000
12/12 [==============================] -

Epoch 465/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6377 - acc: 0.7604 - val_loss: 0.6248 - val_acc: 0.7578

Epoch 00465: loss improved from inf to 0.63771, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-1-000465-0.637707-0.757812.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.6346 - acc: 0.7591 - val_loss: 0.6142 - val_acc: 0.7682
Epoch 467/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6767 - acc: 0.7617 - val_loss: 0.6317 - val_acc: 0.7552
Epoch 468/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6645 - acc: 0.7487 - val_loss: 0.6292 - val_acc: 0.7578
Epoch 469/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6501 - acc: 0.7552 - val_loss: 0.6275 - val_acc: 0.7578
Epoch 470/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6613 - acc: 0.7461 - val_loss: 0.6231 - val_acc: 0.7604
Epoch 471/1000
12/

12/12 [==============================] - 0s 12ms/step - loss: 0.6689 - acc: 0.7539 - val_loss: 0.6216 - val_acc: 0.7630
Epoch 582/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6392 - acc: 0.7695 - val_loss: 0.6190 - val_acc: 0.7604
Epoch 583/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6778 - acc: 0.7383 - val_loss: 0.6201 - val_acc: 0.7630
Epoch 584/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6464 - acc: 0.7448 - val_loss: 0.6196 - val_acc: 0.7630
Epoch 585/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6683 - acc: 0.7331 - val_loss: 0.6296 - val_acc: 0.7604
Epoch 586/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6600 - acc: 0.7448 - val_loss: 0.6232 - val_acc: 0.7604
Epoch 587/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6481 - acc: 0.7461 - val_loss: 0.6340 - val_acc: 0.7552
Epoch 588/1000
12/12 [==============================] - 0s 13ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 8s 19ms/step
1-cairo:	acc: 75.96%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 9s 740ms/step - loss: 1.5258 - acc: 0.5898 - val_loss: 1.1728 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.1843 - acc: 0.6354 - val_loss: 1.0719 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.1370 - acc: 0.6380 - val_loss: 1.0147 - val_acc: 0.6328
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0931 - acc: 0.6367 - val_loss: 0.9886 - val_acc: 0.6406
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0839 - acc: 0.6523 - val_loss: 0.9410 - val_acc: 0.6458
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.0359 - acc: 0.6484 - val_loss: 0.9162 - val_acc: 0.7031
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0255 - acc: 0.6576 - val_loss: 0.9002 - val_acc: 0.6979
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 17ms/step - loss: 0.6507 - acc: 0.7656 - val_loss: 0.5936 - val_acc: 0.7917
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6822 - acc: 0.7435 - val_loss: 0.5879 - val_acc: 0.7943
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6836 - acc: 0.7409 - val_loss: 0.5943 - val_acc: 0.7943
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6661 - acc: 0.7409 - val_loss: 0.5936 - val_acc: 0.7891
Epoch 122/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6745 - acc: 0.7565 - val_loss: 0.5981 - val_acc: 0.7891
Epoch 123/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6662 - acc: 0.7513 - val_loss: 0.5914 - val_acc: 0.7969
Epoch 124/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6473 - acc: 0.7578 - val_loss: 0.5943 - val_acc: 0.7891
Epoch 125/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 175/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6112 - acc: 0.7604 - val_loss: 0.5601 - val_acc: 0.8099
Epoch 176/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6300 - acc: 0.7396 - val_loss: 0.5650 - val_acc: 0.8047
Epoch 177/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5958 - acc: 0.7734 - val_loss: 0.5577 - val_acc: 0.8073

Epoch 00177: loss improved from 0.60864 to 0.59582, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-2-000177-0.595817-0.807292.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.6452 - acc: 0.7500 - val_loss: 0.5661 - val_acc: 0.8073
Epoch 179/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6404 - acc: 0.7422 - val_loss: 0.5692 - val_acc: 0.7995
Epoch 180/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6366 - acc: 0.7695 - val_loss: 0.5743 - val_acc: 0.8047
Epoch 181/1000

Epoch 289/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5900 - acc: 0.7656 - val_loss: 0.5512 - val_acc: 0.8229
Epoch 290/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5516 - acc: 0.7826 - val_loss: 0.5562 - val_acc: 0.8203
Epoch 291/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5830 - acc: 0.7852 - val_loss: 0.5490 - val_acc: 0.8229
Epoch 292/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.5949 - acc: 0.7786 - val_loss: 0.5526 - val_acc: 0.8229
Epoch 293/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5410 - acc: 0.7891 - val_loss: 0.5532 - val_acc: 0.8229

Epoch 00293: loss improved from 0.56726 to 0.54102, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-2-000293-0.541021-0.822917.hdf5
Epoch 294/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.5658 - acc: 0.7812 - val_loss: 0.5538 - val_acc: 0.8229
Epoch 295/1000

Epoch 347/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5895 - acc: 0.7656 - val_loss: 0.5503 - val_acc: 0.8229
Epoch 348/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5681 - acc: 0.7799 - val_loss: 0.5508 - val_acc: 0.8229
Epoch 349/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5861 - acc: 0.7812 - val_loss: 0.5537 - val_acc: 0.8203
Epoch 350/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5939 - acc: 0.7773 - val_loss: 0.5462 - val_acc: 0.8229
Epoch 351/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5576 - acc: 0.7995 - val_loss: 0.5314 - val_acc: 0.8281
Epoch 352/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5725 - acc: 0.7695 - val_loss: 0.5498 - val_acc: 0.8229
Epoch 353/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5959 - acc: 0.7682 - val_loss: 0.5503 - val_acc: 0.8229
Epoch 354/1000
12/12 [==============================] -


Epoch 00465: loss improved from inf to 0.58052, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-2-000465-0.580521-0.822917.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.5804 - acc: 0.7734 - val_loss: 0.5421 - val_acc: 0.8307
Epoch 467/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5896 - acc: 0.7695 - val_loss: 0.5463 - val_acc: 0.8229
Epoch 468/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5948 - acc: 0.7695 - val_loss: 0.5535 - val_acc: 0.8203
Epoch 469/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5658 - acc: 0.7852 - val_loss: 0.5547 - val_acc: 0.8203

Epoch 00469: loss improved from 0.58052 to 0.56583, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_3/weights/Pbest-2-000469-0.565827-0.820312.hdf5
Epoch 470/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.5949 - acc: 0.7669 - val_loss: 0.

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 8s 20ms/step
2-cairo:	acc: 82.35%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 78.79% (+/- 1.89%)
final: current database: cairo 	 78.79% (+/- 1.89%)
CPU times: user 5min 19s, sys: 18.6 s, total: 5min 37s
Wall time: 5min 14s

best: current database: cairo 	 80.41% (+/- 3.53%)
final: current database: cairo 	 80.41% (+/- 3.53%)
CPU times: user 8min 5s, sys: 29.3 s, total: 8min 35s
Wall time: 6min 41s

best: current database: cairo 	 77.60% (+/- 1.54%)
final: current database: cairo 	 77.60% (+/- 1.54%)
CPU times: user 9min 11s, sys: 29.5 s, total: 9min 41s
Wall time: 8min 33s

best: current database: cairo 	 78.54% (+/- 2.75%)
final: current database: cairo 	 78.54% (+/- 2.75%)
CPU times: user 10min 26s, sys: 34.1 s, total: 11min
Wall time: 10min 3s
```

# <a id='constrain_4'>CS_4</a>

In [19]:
%%time
dict_config_cus['distance_int'] = '4'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_127 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_127 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_127 (Conv1D)          (None, 2000, 12)          780       
_________________________________________________________________
activation_379 (Activation)  (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_127 (Gl (None, 12)                0         
_________________________________________________________________
dense_379 (Dense)            (None, 18)                234       
________________________________________

12/12 [==============================] - 0s 18ms/step - loss: 0.6786 - acc: 0.7630 - val_loss: 0.6756 - val_acc: 0.7578
Epoch 100/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6721 - acc: 0.7565 - val_loss: 0.6728 - val_acc: 0.7552

Epoch 00100: saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3/weights/0-000100-0.672124-0.755208.hdf5
Epoch 101/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.6876 - acc: 0.7435 - val_loss: 0.6760 - val_acc: 0.7578
Epoch 102/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6887 - acc: 0.7591 - val_loss: 0.6759 - val_acc: 0.7578
Epoch 103/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6678 - acc: 0.7656 - val_loss: 0.6734 - val_acc: 0.7552
Epoch 104/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6557 - acc: 0.7656 - val_loss: 0.6722 - val_acc: 0.7578
Epoch 105/1000
12/12 [==============================] - 0s 12ms/step - los

12/12 [==============================] - 0s 12ms/step - loss: 0.6112 - acc: 0.7669 - val_loss: 0.6469 - val_acc: 0.7734
Epoch 213/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5992 - acc: 0.7786 - val_loss: 0.6594 - val_acc: 0.7656
Epoch 214/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6273 - acc: 0.7643 - val_loss: 0.6501 - val_acc: 0.7708
Epoch 215/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6359 - acc: 0.7734 - val_loss: 0.6548 - val_acc: 0.7708
Epoch 216/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6198 - acc: 0.7643 - val_loss: 0.6486 - val_acc: 0.7708
Epoch 217/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6291 - acc: 0.7578 - val_loss: 0.6487 - val_acc: 0.7708
Epoch 218/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6072 - acc: 0.7669 - val_loss: 0.6509 - val_acc: 0.7734
Epoch 219/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 12ms/step - loss: 0.6368 - acc: 0.7578 - val_loss: 0.6496 - val_acc: 0.7734
Epoch 272/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6166 - acc: 0.7773 - val_loss: 0.6505 - val_acc: 0.7734
Epoch 273/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6098 - acc: 0.7760 - val_loss: 0.6435 - val_acc: 0.7708

Epoch 00273: loss improved from 0.61901 to 0.60980, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3/weights/Pbest-0-000273-0.609799-0.770833.hdf5
Epoch 274/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.6081 - acc: 0.7695 - val_loss: 0.6557 - val_acc: 0.7708
Epoch 275/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6174 - acc: 0.7734 - val_loss: 0.6435 - val_acc: 0.7708
Epoch 276/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6242 - acc: 0.7760 - val_loss: 0.6558 - val_acc: 0.7708
Epoch 277/1000
12/12 [=======

12/12 [==============================] - 0s 12ms/step - loss: 0.6275 - acc: 0.7630 - val_loss: 0.6520 - val_acc: 0.7734
Epoch 389/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6208 - acc: 0.7669 - val_loss: 0.6550 - val_acc: 0.7734
Epoch 390/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6023 - acc: 0.7747 - val_loss: 0.6592 - val_acc: 0.7682
Epoch 391/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6135 - acc: 0.7682 - val_loss: 0.6476 - val_acc: 0.7734
Epoch 392/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6069 - acc: 0.7734 - val_loss: 0.6593 - val_acc: 0.7682
Epoch 393/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6145 - acc: 0.7682 - val_loss: 0.6428 - val_acc: 0.7760

Epoch 00393: loss improved from 0.61949 to 0.61453, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3/weights/Pbest-0-000393-0.614533-0.776042.hdf5
Epoch 394/1000
12/12 [=======

Epoch 502/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6203 - acc: 0.7786 - val_loss: 0.6357 - val_acc: 0.7786
Epoch 503/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6072 - acc: 0.7747 - val_loss: 0.6485 - val_acc: 0.7760
Epoch 504/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6317 - acc: 0.7604 - val_loss: 0.6497 - val_acc: 0.7734
Epoch 505/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6370 - acc: 0.7565 - val_loss: 0.6399 - val_acc: 0.7760
Epoch 506/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6190 - acc: 0.7799 - val_loss: 0.6549 - val_acc: 0.7708
Epoch 507/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6115 - acc: 0.7839 - val_loss: 0.6466 - val_acc: 0.7734
Epoch 508/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6352 - acc: 0.7643 - val_loss: 0.6504 - val_acc: 0.7708
Epoch 509/1000
12/12 [==============================] -

Epoch 563/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6163 - acc: 0.7747 - val_loss: 0.6500 - val_acc: 0.7734
Epoch 564/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5964 - acc: 0.7734 - val_loss: 0.6446 - val_acc: 0.7760
Epoch 565/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6286 - acc: 0.7799 - val_loss: 0.6452 - val_acc: 0.7734

Epoch 00565: loss improved from inf to 0.62861, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3/weights/Pbest-0-000565-0.628615-0.773438.hdf5
Epoch 566/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6381 - acc: 0.7578 - val_loss: 0.6517 - val_acc: 0.7734
Epoch 567/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6219 - acc: 0.7760 - val_loss: 0.6504 - val_acc: 0.7734
Epoch 568/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6201 - acc: 0.7656 - val_loss: 0.6563 - val_acc: 0.7708
Epoch 569/1000
12/

12/12 [==============================] - 0s 17ms/step - loss: 0.6399 - acc: 0.7513 - val_loss: 0.6368 - val_acc: 0.7760
Epoch 677/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6138 - acc: 0.7734 - val_loss: 0.6415 - val_acc: 0.7734

Epoch 00677: loss improved from 0.62336 to 0.61382, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3/weights/Pbest-0-000677-0.613817-0.773438.hdf5
Epoch 678/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5894 - acc: 0.7852 - val_loss: 0.6510 - val_acc: 0.7708
Epoch 679/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6309 - acc: 0.7617 - val_loss: 0.6507 - val_acc: 0.7708
Epoch 680/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6250 - acc: 0.7773 - val_loss: 0.6555 - val_acc: 0.7708
Epoch 681/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6228 - acc: 0.7734 - val_loss: 0.6527 - val_acc: 0.7708
Epoch 682/1000
12/12 [=======

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 6s 14ms/step
0-cairo:	acc: 77.30%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 7s 567ms/step - loss: 1.5665 - acc: 0.5898 - val_loss: 1.2352 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 13ms/step - loss: 1.2272 - acc: 0.6367 - val_loss: 1.1094 - val_acc: 0.6380
Epoch 3/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.1684 - acc: 0.6354 - val_loss: 1.0649 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.1548 - acc: 0.6367 - val_loss: 1.0299 - val_acc: 0.6380
Epoch 5/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.1288 - acc: 0.6302 - val_loss: 1.0092 - val_acc: 0.6354
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0930 - acc: 0.6367 - val_loss: 0.9922 - val_acc: 0.6380
Epoch 7/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0596 - acc: 0.6341 - val_loss: 0.9679 - val_acc: 0.6380
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.6743 - acc: 0.7539 - val_loss: 0.6144 - val_acc: 0.7839
Epoch 115/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6998 - acc: 0.7448 - val_loss: 0.6129 - val_acc: 0.7865
Epoch 116/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.7133 - acc: 0.7409 - val_loss: 0.6045 - val_acc: 0.7865
Epoch 117/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6992 - acc: 0.7422 - val_loss: 0.6143 - val_acc: 0.7812
Epoch 118/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6937 - acc: 0.7487 - val_loss: 0.6097 - val_acc: 0.7839
Epoch 119/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6911 - acc: 0.7539 - val_loss: 0.5969 - val_acc: 0.7839
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6934 - acc: 0.7578 - val_loss: 0.5951 - val_acc: 0.7865
Epoch 121/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 12ms/step - loss: 0.6496 - acc: 0.7513 - val_loss: 0.5839 - val_acc: 0.7839
Epoch 233/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6742 - acc: 0.7513 - val_loss: 0.5788 - val_acc: 0.7891
Epoch 234/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6547 - acc: 0.7513 - val_loss: 0.5848 - val_acc: 0.7839
Epoch 235/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6414 - acc: 0.7669 - val_loss: 0.5834 - val_acc: 0.7865
Epoch 236/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6375 - acc: 0.7669 - val_loss: 0.5785 - val_acc: 0.7891
Epoch 237/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6424 - acc: 0.7591 - val_loss: 0.5812 - val_acc: 0.7865
Epoch 238/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6110 - acc: 0.7734 - val_loss: 0.5843 - val_acc: 0.7839
Epoch 239/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 286/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6413 - acc: 0.7630 - val_loss: 0.5915 - val_acc: 0.7812
Epoch 287/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6433 - acc: 0.7409 - val_loss: 0.5900 - val_acc: 0.7812
Epoch 288/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6571 - acc: 0.7552 - val_loss: 0.5820 - val_acc: 0.7891
Epoch 289/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6563 - acc: 0.7591 - val_loss: 0.5904 - val_acc: 0.7812
Epoch 290/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6529 - acc: 0.7682 - val_loss: 0.5823 - val_acc: 0.7865
Epoch 291/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6038 - acc: 0.7643 - val_loss: 0.5818 - val_acc: 0.7865
Epoch 292/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6629 - acc: 0.7669 - val_loss: 0.5888 - val_acc: 0.7812
Epoch 293/1000
12/12 [==============================] -

Epoch 346/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6424 - acc: 0.7604 - val_loss: 0.5887 - val_acc: 0.7839
Epoch 347/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6402 - acc: 0.7487 - val_loss: 0.5716 - val_acc: 0.7865
Epoch 348/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6438 - acc: 0.7409 - val_loss: 0.5864 - val_acc: 0.7839
Epoch 349/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6638 - acc: 0.7513 - val_loss: 0.5802 - val_acc: 0.7891
Epoch 350/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6654 - acc: 0.7630 - val_loss: 0.5916 - val_acc: 0.7812
Epoch 351/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6486 - acc: 0.7487 - val_loss: 0.5638 - val_acc: 0.7917
Epoch 352/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6528 - acc: 0.7617 - val_loss: 0.5810 - val_acc: 0.7865
Epoch 353/1000
12/12 [==============================] -

Epoch 402/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6500 - acc: 0.7500 - val_loss: 0.5853 - val_acc: 0.7812
Epoch 403/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6484 - acc: 0.7448 - val_loss: 0.5856 - val_acc: 0.7839
Epoch 404/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6379 - acc: 0.7526 - val_loss: 0.5851 - val_acc: 0.7839
Epoch 405/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6784 - acc: 0.7539 - val_loss: 0.5873 - val_acc: 0.7839
Epoch 406/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6370 - acc: 0.7604 - val_loss: 0.5881 - val_acc: 0.7839
Epoch 407/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6476 - acc: 0.7578 - val_loss: 0.5871 - val_acc: 0.7812
Epoch 408/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6458 - acc: 0.7630 - val_loss: 0.5863 - val_acc: 0.7839
Epoch 409/1000
12/12 [==============================] -

Epoch 463/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6253 - acc: 0.7617 - val_loss: 0.5748 - val_acc: 0.7891
Epoch 464/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.6206 - acc: 0.7552 - val_loss: 0.5870 - val_acc: 0.7865
Epoch 465/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6650 - acc: 0.7487 - val_loss: 0.5891 - val_acc: 0.7812

Epoch 00465: loss improved from inf to 0.66496, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_3/weights/Pbest-1-000465-0.664961-0.781250.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6589 - acc: 0.7357 - val_loss: 0.5846 - val_acc: 0.7839
Epoch 467/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6173 - acc: 0.7708 - val_loss: 0.5872 - val_acc: 0.7839
Epoch 468/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6436 - acc: 0.7604 - val_loss: 0.5830 - val_acc: 0.7839
Epoch 469/1000
12/

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 6s 15ms/step
1-cairo:	acc: 78.52%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 7s 577ms/step - loss: 1.5414 - acc: 0.5547 - val_loss: 1.2351 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.2236 - acc: 0.6341 - val_loss: 1.1560 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.1778 - acc: 0.6341 - val_loss: 1.0993 - val_acc: 0.6354
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.1141 - acc: 0.6523 - val_loss: 1.0626 - val_acc: 0.6328
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0974 - acc: 0.6576 - val_loss: 0.9949 - val_acc: 0.7083
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0566 - acc: 0.6602 - val_loss: 0.9637 - val_acc: 0.7214
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.9967 - acc: 0.6732 - val_loss: 0.9330 - val_acc: 0.7214
Epoch 8/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 12ms/step - loss: 0.6345 - acc: 0.7604 - val_loss: 0.6136 - val_acc: 0.7786
Epoch 116/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6227 - acc: 0.7604 - val_loss: 0.6159 - val_acc: 0.7786
Epoch 117/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5941 - acc: 0.7682 - val_loss: 0.6179 - val_acc: 0.7734
Epoch 118/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6464 - acc: 0.7539 - val_loss: 0.6165 - val_acc: 0.7760
Epoch 119/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5885 - acc: 0.7826 - val_loss: 0.6132 - val_acc: 0.7786
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6104 - acc: 0.7852 - val_loss: 0.6128 - val_acc: 0.7812
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6028 - acc: 0.7891 - val_loss: 0.6161 - val_acc: 0.7786
Epoch 122/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 230/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5961 - acc: 0.7695 - val_loss: 0.5810 - val_acc: 0.7760
Epoch 231/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5731 - acc: 0.7734 - val_loss: 0.5871 - val_acc: 0.7760
Epoch 232/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5707 - acc: 0.7734 - val_loss: 0.5806 - val_acc: 0.7786
Epoch 233/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5772 - acc: 0.7669 - val_loss: 0.5906 - val_acc: 0.7812
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5958 - acc: 0.7760 - val_loss: 0.5918 - val_acc: 0.7812
Epoch 235/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5762 - acc: 0.7682 - val_loss: 0.5873 - val_acc: 0.7839
Epoch 236/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5893 - acc: 0.7812 - val_loss: 0.5806 - val_acc: 0.7865
Epoch 237/1000
12/12 [==============================] -

Epoch 287/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5756 - acc: 0.7669 - val_loss: 0.5750 - val_acc: 0.7812
Epoch 288/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6041 - acc: 0.7630 - val_loss: 0.5869 - val_acc: 0.7839
Epoch 289/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6045 - acc: 0.7708 - val_loss: 0.5842 - val_acc: 0.7865
Epoch 290/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5816 - acc: 0.7812 - val_loss: 0.5726 - val_acc: 0.7839
Epoch 291/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5707 - acc: 0.7799 - val_loss: 0.5853 - val_acc: 0.7865
Epoch 292/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5994 - acc: 0.7656 - val_loss: 0.5942 - val_acc: 0.7786
Epoch 293/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5743 - acc: 0.7852 - val_loss: 0.5908 - val_acc: 0.7812
Epoch 294/1000
12/12 [==============================] -

Epoch 347/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5982 - acc: 0.7643 - val_loss: 0.5944 - val_acc: 0.7839
Epoch 348/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5771 - acc: 0.7695 - val_loss: 0.5920 - val_acc: 0.7839
Epoch 349/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5490 - acc: 0.7812 - val_loss: 0.5945 - val_acc: 0.7812
Epoch 350/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5985 - acc: 0.7656 - val_loss: 0.5660 - val_acc: 0.7917
Epoch 351/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5813 - acc: 0.7773 - val_loss: 0.5830 - val_acc: 0.7891
Epoch 352/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5659 - acc: 0.7721 - val_loss: 0.5939 - val_acc: 0.7812
Epoch 353/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5758 - acc: 0.7826 - val_loss: 0.5911 - val_acc: 0.7839
Epoch 354/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 6s 15ms/step
2-cairo:	acc: 78.52%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 78.02% (+/- 1.57%)
final: current database: cairo 	 78.02% (+/- 1.67%)
CPU times: user 7min 26s, sys: 26.7 s, total: 7min 53s
Wall time: 7min 26s

best: current database: cairo 	 77.68% (+/- 0.59%)
final: current database: cairo 	 78.11% (+/- 0.58%)
CPU times: user 7min 59s, sys: 26.4 s, total: 8min 25s
Wall time: 7min

```

# <a id='constrain_5'>CS_5</a>

In [23]:
%%time
dict_config_cus['distance_int'] = '5'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_3
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_163 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_163 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_163 (Conv1D)          (None, 2000, 12)          780       
_________________________________________________________________
activation_487 (Activation)  (None, 2000, 12)          0         
_________________________________________________________________
global_max_pooling1d_163 (Gl (None, 12)                0         
_________________________________________________________________
dense_487 (Dense)            (None, 18)                234       
________________________________________

Epoch 101/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6779 - acc: 0.7552 - val_loss: 0.7147 - val_acc: 0.7344
Epoch 102/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6593 - acc: 0.7487 - val_loss: 0.7226 - val_acc: 0.7292
Epoch 103/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6747 - acc: 0.7474 - val_loss: 0.7241 - val_acc: 0.7292
Epoch 104/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6762 - acc: 0.7409 - val_loss: 0.7240 - val_acc: 0.7292
Epoch 105/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6804 - acc: 0.7422 - val_loss: 0.7250 - val_acc: 0.7318
Epoch 106/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6786 - acc: 0.7565 - val_loss: 0.7227 - val_acc: 0.7344
Epoch 107/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6905 - acc: 0.7500 - val_loss: 0.7265 - val_acc: 0.7266
Epoch 108/1000
12/12 [==============================] -

Epoch 162/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6231 - acc: 0.7695 - val_loss: 0.6842 - val_acc: 0.7604
Epoch 163/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6153 - acc: 0.7695 - val_loss: 0.6536 - val_acc: 0.7656
Epoch 164/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5902 - acc: 0.7852 - val_loss: 0.6815 - val_acc: 0.7578
Epoch 165/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6143 - acc: 0.7721 - val_loss: 0.6835 - val_acc: 0.7578

Epoch 00165: loss improved from inf to 0.61434, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_3/weights/Pbest-0-000165-0.614335-0.757812.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.6113 - acc: 0.7799 - val_loss: 0.6917 - val_acc: 0.7526
Epoch 167/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6006 - acc: 0.7721 - val_loss: 0.6868 - val_acc: 0.7552
Epoch 168/1000
12/

Epoch 216/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6154 - acc: 0.7773 - val_loss: 0.6740 - val_acc: 0.7604
Epoch 217/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5910 - acc: 0.7852 - val_loss: 0.6689 - val_acc: 0.7630
Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6121 - acc: 0.7643 - val_loss: 0.6791 - val_acc: 0.7604
Epoch 219/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6058 - acc: 0.7865 - val_loss: 0.6667 - val_acc: 0.7682
Epoch 220/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5989 - acc: 0.7695 - val_loss: 0.6778 - val_acc: 0.7630

Epoch 00220: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 221/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5983 - acc: 0.7852 - val_loss: 0.6614 - val_acc: 0.7708
Epoch 222/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5931 - acc: 0.7799 - val_loss:

12/12 [==============================] - 0s 12ms/step - loss: 0.5958 - acc: 0.7826 - val_loss: 0.6531 - val_acc: 0.7656
Epoch 274/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6137 - acc: 0.7591 - val_loss: 0.6767 - val_acc: 0.7630
Epoch 275/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6010 - acc: 0.7630 - val_loss: 0.6761 - val_acc: 0.7630
Epoch 276/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5996 - acc: 0.7799 - val_loss: 0.6631 - val_acc: 0.7708
Epoch 277/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6175 - acc: 0.7630 - val_loss: 0.6780 - val_acc: 0.7630
Epoch 278/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6241 - acc: 0.7604 - val_loss: 0.6624 - val_acc: 0.7708
Epoch 279/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.5999 - acc: 0.7826 - val_loss: 0.6793 - val_acc: 0.7604
Epoch 280/1000
12/12 [==============================] - 0s 17ms/step -

Epoch 333/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6264 - acc: 0.7578 - val_loss: 0.6795 - val_acc: 0.7604
Epoch 334/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5673 - acc: 0.7826 - val_loss: 0.6612 - val_acc: 0.7734
Epoch 335/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6082 - acc: 0.7669 - val_loss: 0.6737 - val_acc: 0.7656
Epoch 336/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5787 - acc: 0.7917 - val_loss: 0.6766 - val_acc: 0.7630
Epoch 337/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5944 - acc: 0.7799 - val_loss: 0.6731 - val_acc: 0.7604
Epoch 338/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5682 - acc: 0.7734 - val_loss: 0.6474 - val_acc: 0.7656
Epoch 339/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5933 - acc: 0.7799 - val_loss: 0.6711 - val_acc: 0.7656
Epoch 340/1000
12/12 [==============================] -

Epoch 390/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6076 - acc: 0.7721 - val_loss: 0.6671 - val_acc: 0.7682
Epoch 391/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5774 - acc: 0.7812 - val_loss: 0.6720 - val_acc: 0.7656
Epoch 392/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6110 - acc: 0.7773 - val_loss: 0.6716 - val_acc: 0.7656
Epoch 393/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5968 - acc: 0.7695 - val_loss: 0.6708 - val_acc: 0.7656
Epoch 394/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5819 - acc: 0.7773 - val_loss: 0.6777 - val_acc: 0.7604
Epoch 395/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6097 - acc: 0.7799 - val_loss: 0.6792 - val_acc: 0.7604
Epoch 396/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5848 - acc: 0.7839 - val_loss: 0.6616 - val_acc: 0.7682
Epoch 397/1000
12/12 [==============================] -

Epoch 450/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5772 - acc: 0.7708 - val_loss: 0.6719 - val_acc: 0.7630
Epoch 451/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5988 - acc: 0.7852 - val_loss: 0.6708 - val_acc: 0.7630
Epoch 452/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6288 - acc: 0.7708 - val_loss: 0.6717 - val_acc: 0.7656
Epoch 453/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5897 - acc: 0.7826 - val_loss: 0.6675 - val_acc: 0.7656
Epoch 454/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.5787 - acc: 0.7812 - val_loss: 0.6761 - val_acc: 0.7630
Epoch 455/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5974 - acc: 0.7812 - val_loss: 0.6653 - val_acc: 0.7682
Epoch 456/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5978 - acc: 0.7747 - val_loss: 0.6711 - val_acc: 0.7682
Epoch 457/1000
12/12 [==============================] -

Epoch 506/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5971 - acc: 0.7695 - val_loss: 0.6702 - val_acc: 0.7630
Epoch 507/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5603 - acc: 0.7878 - val_loss: 0.6726 - val_acc: 0.7630
Epoch 508/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6033 - acc: 0.7721 - val_loss: 0.6762 - val_acc: 0.7630
Epoch 509/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5908 - acc: 0.7812 - val_loss: 0.6766 - val_acc: 0.7630
Epoch 510/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5931 - acc: 0.7799 - val_loss: 0.6634 - val_acc: 0.7682
Epoch 511/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6016 - acc: 0.7760 - val_loss: 0.6762 - val_acc: 0.7604
Epoch 512/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.5977 - acc: 0.7747 - val_loss: 0.6475 - val_acc: 0.7708
Epoch 513/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 8s 20ms/step
0-cairo:	acc: 76.53%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 9s 757ms/step - loss: 1.6001 - acc: 0.5625 - val_loss: 1.3210 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.3305 - acc: 0.6354 - val_loss: 1.2341 - val_acc: 0.6380
Epoch 3/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.2623 - acc: 0.6354 - val_loss: 1.1949 - val_acc: 0.6354
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.2495 - acc: 0.6315 - val_loss: 1.1686 - val_acc: 0.6328
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.1857 - acc: 0.6328 - val_loss: 1.1225 - val_acc: 0.6354
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.1840 - acc: 0.6341 - val_loss: 1.1031 - val_acc: 0.6406
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.1601 - acc: 0.6289 - val_loss: 1.0852 - val_acc: 0.6510
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7225 - acc: 0.7552 - val_loss: 0.6630 - val_acc: 0.7734
Epoch 118/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7107 - acc: 0.7578 - val_loss: 0.6588 - val_acc: 0.7812
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7067 - acc: 0.7396 - val_loss: 0.6532 - val_acc: 0.7734
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7188 - acc: 0.7474 - val_loss: 0.6546 - val_acc: 0.7786
Epoch 121/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7248 - acc: 0.7396 - val_loss: 0.6616 - val_acc: 0.7708
Epoch 122/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.7039 - acc: 0.7500 - val_loss: 0.6516 - val_acc: 0.7839
Epoch 123/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6930 - acc: 0.7513 - val_loss: 0.6565 - val_acc: 0.7839
Epoch 124/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.6985 - acc: 0.7552 - val_loss: 0.6337 - val_acc: 0.7865
Epoch 176/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6571 - acc: 0.7539 - val_loss: 0.6181 - val_acc: 0.7891
Epoch 177/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6639 - acc: 0.7773 - val_loss: 0.6281 - val_acc: 0.7865
Epoch 178/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6893 - acc: 0.7552 - val_loss: 0.6199 - val_acc: 0.7969
Epoch 179/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6577 - acc: 0.7578 - val_loss: 0.6245 - val_acc: 0.7943
Epoch 180/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6460 - acc: 0.7695 - val_loss: 0.6283 - val_acc: 0.7917
Epoch 181/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6834 - acc: 0.7591 - val_loss: 0.6260 - val_acc: 0.7865
Epoch 182/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 17ms/step - loss: 0.6795 - acc: 0.7474 - val_loss: 0.6231 - val_acc: 0.7734
Epoch 289/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6494 - acc: 0.7617 - val_loss: 0.6206 - val_acc: 0.7760
Epoch 290/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6477 - acc: 0.7578 - val_loss: 0.6223 - val_acc: 0.7734
Epoch 291/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6194 - acc: 0.7773 - val_loss: 0.6148 - val_acc: 0.7760
Epoch 292/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6610 - acc: 0.7617 - val_loss: 0.6181 - val_acc: 0.7734
Epoch 293/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7010 - acc: 0.7344 - val_loss: 0.6173 - val_acc: 0.7734
Epoch 294/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6509 - acc: 0.7708 - val_loss: 0.6230 - val_acc: 0.7734
Epoch 295/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 348/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6630 - acc: 0.7565 - val_loss: 0.6158 - val_acc: 0.7760
Epoch 349/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6568 - acc: 0.7682 - val_loss: 0.6223 - val_acc: 0.7734
Epoch 350/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6728 - acc: 0.7682 - val_loss: 0.6221 - val_acc: 0.7708
Epoch 351/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6532 - acc: 0.7604 - val_loss: 0.6211 - val_acc: 0.7734
Epoch 352/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6552 - acc: 0.7604 - val_loss: 0.6148 - val_acc: 0.7786
Epoch 353/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6471 - acc: 0.7552 - val_loss: 0.6183 - val_acc: 0.7760
Epoch 354/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.6377 - acc: 0.7760 - val_loss: 0.6171 - val_acc: 0.7734
Epoch 355/1000
12/12 [==============================] -


Epoch 00465: loss improved from inf to 0.67440, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_3/weights/Pbest-1-000465-0.674401-0.776042.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.6424 - acc: 0.7578 - val_loss: 0.6200 - val_acc: 0.7708
Epoch 467/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6681 - acc: 0.7708 - val_loss: 0.5952 - val_acc: 0.7839
Epoch 468/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6684 - acc: 0.7617 - val_loss: 0.6166 - val_acc: 0.7786
Epoch 469/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6584 - acc: 0.7656 - val_loss: 0.6129 - val_acc: 0.7786

Epoch 00469: loss improved from 0.67440 to 0.65836, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_3/weights/Pbest-1-000469-0.658364-0.778646.hdf5
Epoch 470/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.6367 - acc: 0.7617 - val_loss: 0.

Epoch 522/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6633 - acc: 0.7487 - val_loss: 0.6262 - val_acc: 0.7708
Epoch 523/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6570 - acc: 0.7630 - val_loss: 0.6165 - val_acc: 0.7786
Epoch 524/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6792 - acc: 0.7513 - val_loss: 0.6183 - val_acc: 0.7760
Epoch 525/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6778 - acc: 0.7461 - val_loss: 0.6154 - val_acc: 0.7786
Epoch 526/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6325 - acc: 0.7682 - val_loss: 0.6219 - val_acc: 0.7734
Epoch 527/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6693 - acc: 0.7487 - val_loss: 0.6213 - val_acc: 0.7734
Epoch 528/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6509 - acc: 0.7721 - val_loss: 0.6222 - val_acc: 0.7734
Epoch 529/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 8s 20ms/step
1-cairo:	acc: 77.49%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 9s 771ms/step - loss: 1.7459 - acc: 0.4206 - val_loss: 1.4021 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.2988 - acc: 0.6328 - val_loss: 1.1420 - val_acc: 0.6276
Epoch 3/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.1731 - acc: 0.6328 - val_loss: 1.0536 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.1325 - acc: 0.6432 - val_loss: 1.0221 - val_acc: 0.6380
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0986 - acc: 0.6393 - val_loss: 0.9911 - val_acc: 0.6380
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 1.0542 - acc: 0.6602 - val_loss: 0.9754 - val_acc: 0.6615
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.0319 - acc: 0.6523 - val_loss: 0.9457 - val_acc: 0.6875
Epoch 8/1000
12/12 [==============================] - 0s 13ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.7117 - acc: 0.7448 - val_loss: 0.6505 - val_acc: 0.7656
Epoch 118/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7146 - acc: 0.7279 - val_loss: 0.6437 - val_acc: 0.7682

Epoch 00118: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 119/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.6983 - acc: 0.7565 - val_loss: 0.6390 - val_acc: 0.7682
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7299 - acc: 0.7292 - val_loss: 0.6513 - val_acc: 0.7656
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7067 - acc: 0.7474 - val_loss: 0.6370 - val_acc: 0.7708
Epoch 122/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6967 - acc: 0.7435 - val_loss: 0.6496 - val_acc: 0.7682
Epoch 123/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7226 - acc: 0.7227 - val_loss: 0.6547 - val_a

12/12 [==============================] - 0s 17ms/step - loss: 0.7292 - acc: 0.7253 - val_loss: 0.6531 - val_acc: 0.7656
Epoch 233/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7078 - acc: 0.7552 - val_loss: 0.6515 - val_acc: 0.7656
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7108 - acc: 0.7448 - val_loss: 0.6482 - val_acc: 0.7656
Epoch 235/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7022 - acc: 0.7344 - val_loss: 0.6486 - val_acc: 0.7682
Epoch 236/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7306 - acc: 0.7305 - val_loss: 0.6451 - val_acc: 0.7682
Epoch 237/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6839 - acc: 0.7448 - val_loss: 0.6335 - val_acc: 0.7734
Epoch 238/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7345 - acc: 0.7240 - val_loss: 0.6348 - val_acc: 0.7708
Epoch 239/1000
12/12 [==============================] - 0s 17ms/step -

Epoch 289/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6908 - acc: 0.7448 - val_loss: 0.6486 - val_acc: 0.7708

Epoch 00289: loss improved from 0.69435 to 0.69080, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_3/weights/Pbest-2-000289-0.690804-0.770833.hdf5
Epoch 290/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.7189 - acc: 0.7370 - val_loss: 0.6447 - val_acc: 0.7708
Epoch 291/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6913 - acc: 0.7448 - val_loss: 0.6467 - val_acc: 0.7656
Epoch 292/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7106 - acc: 0.7461 - val_loss: 0.6509 - val_acc: 0.7656
Epoch 293/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6753 - acc: 0.7669 - val_loss: 0.6489 - val_acc: 0.7656

Epoch 00293: loss improved from 0.69080 to 0.67534, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_3/weights/Pbest-2-000

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 8s 21ms/step
2-cairo:	acc: 76.73%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 78.54% (+/- 0.75%)
final: current database: cairo 	 78.45% (+/- 0.78%)
CPU times: user 8min 15s, sys: 25.5 s, total: 8min 40s
Wall time: 8min 38s

best: current database: cairo 	 78.79% (+/- 2.18%)
final: current database: cairo 	 78.79% (+/- 2.18%)
CPU times: user 8min 18s, sys: 26.8 s, total: 8min 45s
Wall time: 7min 25s

best: current database: cairo 	 77.26% (+/- 0.89%)
final: current database: cairo 	 76.92% (+/- 0.42%)
CPU times: user 8min 5s, sys: 22.9 s, total: 8min 27s
Wall time: 7min 56s
```