# file name meaning

eg. 100_cairo_WCNN_2000_64_1000_1_8_1_1.ipynb

`[tag]_[dataset_name]_[method_name]_[data_length]_[batch_size]_[epochs]_[kernel_wide_base]_[kernel_number_base]_[net_deep_base]_[calculate_unit]`

In [1]:
from tools import general
import os
from tools.configure.constants import DATASETS_CONSTANT, METHOD_PARAMETER_TEMPLATE, JUPYTER_TOKEN
from tools.integration import train_val


nb_name_file = general.ipy_nb_name(JUPYTER_TOKEN["token_lists"])

Using TensorFlow backend.
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/musk/anaconda3/en

In [2]:
theNotebook = nb_name_file.split('_')
assert len(theNotebook) == 9 or len(theNotebook) == 10, 'The number of parameters should be 9 / 10'

global title_param
title_param = {
    'num': theNotebook[0],
    'dataset_name': theNotebook[1],
    'method_name': theNotebook[2],
    'data_lenght': int(theNotebook[3]),
    'batch_size': int(theNotebook[4]),
    'nb_epochs': int(theNotebook[5]),
    'kernel_wide_base': int(theNotebook[6]),
    'kernel_number_base': int(theNotebook[7]),
    'net_deep_base': int(theNotebook[8]),
    'calculation_unit': theNotebook[9] if len(theNotebook)==10 else '0',  # If not specified, the CPU is used to train the model
}

# assert title_param['dataset'] in ['cairo', 'milan', 'kyoto7', 'kyoto8', 'kyoto11'], 'Please correct the dataset name！'
# assert title_param['model_name'] in ['WCNN','LSTM'], 'The method is wrong. Please correct it！'
# assert title_param['optimizer'] in ['rms', 'adagrad'], 'The optimizer is wrong. Please correct it！'
# assert title_param['calculation_unit'] in ['0', '1', '2'], 'Error in calculation unit selection, please correct！'

display(title_param)

{'num': '655',
 'dataset_name': 'cairo',
 'method_name': 'WCNNR',
 'data_lenght': 2000,
 'batch_size': 64,
 'nb_epochs': 1000,
 'kernel_wide_base': 1,
 'kernel_number_base': 5,
 'net_deep_base': 1,
 'calculation_unit': '1'}

In [3]:
dict_config_cus = {

        "datasets_dir": DATASETS_CONSTANT["base_dir"],  # 这是公共数据集常量
        "archive_name": DATASETS_CONSTANT["archive_name"],
        "ksplit": DATASETS_CONSTANT["ksplit"],

        'distance_int': None,
    }

dict_config_cus = general.Merge(title_param, dict_config_cus)

from tools.configure.constants import WCNNR_CONSTANT as MODEL_DEFAULT_CONF

dict_config_cus = general.Merge(MODEL_DEFAULT_CONF, dict_config_cus)

In [4]:
import tensorflow as tf

calculation_unit = general.getAvailableId()
os.environ["CUDA_VISIBLE_DEVICES"] = calculation_unit

if calculation_unit != "-1":
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.Session(config=config)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

[origin](#origin)

[C](#constrain)

[CS_1](#constrain_1)

[CS_2](#constrain_2)

[CS_3](#constrain_3)

[CS_4](#constrain_4)

[CS_5](#constrain_5)


# <a id='origin'>origin</a>


In [5]:
%%time
dict_config_cus['distance_int'] = '9999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2000)              0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 2000, 20)          1300      
_________________________________________________________________
activation_1 (Activation)    (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 20)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 30)                630       
_____________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.5367 - acc: 0.8151 - val_loss: 0.5859 - val_acc: 0.7604
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5573 - acc: 0.8164 - val_loss: 0.5736 - val_acc: 0.7682
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5024 - acc: 0.8281 - val_loss: 0.5832 - val_acc: 0.7604
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5053 - acc: 0.8216 - val_loss: 0.5863 - val_acc: 0.7630
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5245 - acc: 0.8190 - val_loss: 0.5699 - val_acc: 0.7708
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5154 - acc: 0.8333 - val_loss: 0.5830 - val_acc: 0.7630
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5213 - acc: 0.8281 - val_loss: 0.5907 - val_acc: 0.7630
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4859 - acc: 0.8320 - val_loss: 0.5696 - val_acc: 0.7656
Epoch 163/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5225 - acc: 0.8216 - val_loss: 0.5770 - val_acc: 0.7656
Epoch 164/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4972 - acc: 0.8359 - val_loss: 0.5851 - val_acc: 0.7604

Epoch 00164: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 165/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5268 - acc: 0.8177 - val_loss: 0.5669 - val_acc: 0.7656

Epoch 00165: loss improved from inf to 0.52678, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_5/weights/Pbest-0-000165-0.526775-0.765625.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4864 - acc: 0.8346 - val_loss: 0.5773 - val_acc: 0.7656
Epoch 167/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5054 - acc: 0.8177 - val_l

Epoch 214/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4951 - acc: 0.8229 - val_loss: 0.5811 - val_acc: 0.7630
Epoch 215/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4855 - acc: 0.8216 - val_loss: 0.5711 - val_acc: 0.7682
Epoch 216/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5013 - acc: 0.8281 - val_loss: 0.5615 - val_acc: 0.7708
Epoch 217/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4947 - acc: 0.8255 - val_loss: 0.5756 - val_acc: 0.7630
Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4986 - acc: 0.8320 - val_loss: 0.5761 - val_acc: 0.7630
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5032 - acc: 0.8242 - val_loss: 0.5749 - val_acc: 0.7656
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5023 - acc: 0.8216 - val_loss: 0.5656 - val_acc: 0.7708
Epoch 221/1000
12/12 [==============================] - 0s 9ms

Epoch 274/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4989 - acc: 0.8268 - val_loss: 0.5758 - val_acc: 0.7656
Epoch 275/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4936 - acc: 0.8307 - val_loss: 0.5766 - val_acc: 0.7656
Epoch 276/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4918 - acc: 0.8307 - val_loss: 0.5610 - val_acc: 0.7708
Epoch 277/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4937 - acc: 0.8346 - val_loss: 0.5653 - val_acc: 0.7682
Epoch 278/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5149 - acc: 0.8229 - val_loss: 0.5684 - val_acc: 0.7656
Epoch 279/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4759 - acc: 0.8503 - val_loss: 0.5781 - val_acc: 0.7630
Epoch 280/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5295 - acc: 0.8138 - val_loss: 0.5678 - val_acc: 0.7682
Epoch 281/1000
12/12 [==============================] - 0s 9ms

Epoch 394/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5062 - acc: 0.8307 - val_loss: 0.5720 - val_acc: 0.7682
Epoch 395/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5042 - acc: 0.8333 - val_loss: 0.5801 - val_acc: 0.7604
Epoch 396/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5297 - acc: 0.8255 - val_loss: 0.5773 - val_acc: 0.7656
Epoch 397/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4941 - acc: 0.8320 - val_loss: 0.5731 - val_acc: 0.7656
Epoch 398/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4804 - acc: 0.8229 - val_loss: 0.5672 - val_acc: 0.7656
Epoch 399/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5084 - acc: 0.8294 - val_loss: 0.5779 - val_acc: 0.7630
Epoch 400/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5061 - acc: 0.8190 - val_loss: 0.5795 - val_acc: 0.7630

Epoch 00400: saving model to ../datasets/casas/results/WCNNR/

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 0s 182us/step
0-cairo:	acc: 76.53%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 0s 27ms/step - loss: 1.4524 - acc: 0.5729 - val_loss: 1.1253 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.1116 - acc: 0.6380 - val_loss: 0.9866 - val_acc: 0.6380
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0414 - acc: 0.6497 - val_loss: 0.8779 - val_acc: 0.6745
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9569 - acc: 0.6706 - val_loss: 0.8459 - val_acc: 0.7109
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9119 - acc: 0.6823 - val_loss: 0.7990 - val_acc: 0.7214
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8688 - acc: 0.7005 - val_loss: 0.7681 - val_acc: 0.7188
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8751 - acc: 0.7018 - val_loss: 0.7293 - val_acc: 0.7292
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.4790 - acc: 0.8164 - val_loss: 0.5289 - val_acc: 0.7917
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4975 - acc: 0.8021 - val_loss: 0.5209 - val_acc: 0.7917
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5039 - acc: 0.7956 - val_loss: 0.5222 - val_acc: 0.7943
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4897 - acc: 0.7956 - val_loss: 0.5170 - val_acc: 0.7943
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4986 - acc: 0.7943 - val_loss: 0.5209 - val_acc: 0.7995
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5145 - acc: 0.8021 - val_loss: 0.5136 - val_acc: 0.7943
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4892 - acc: 0.8151 - val_loss: 0.5184 - val_acc: 0.7917
Epoch 125/1000
12/12 [==============================] - 0s 8ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4698 - acc: 0.8138 - val_loss: 0.5225 - val_acc: 0.7995
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4664 - acc: 0.8242 - val_loss: 0.4983 - val_acc: 0.8073
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4389 - acc: 0.8242 - val_loss: 0.5153 - val_acc: 0.8047
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4704 - acc: 0.8060 - val_loss: 0.5202 - val_acc: 0.7995
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4750 - acc: 0.8060 - val_loss: 0.5079 - val_acc: 0.8073
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4712 - acc: 0.7956 - val_loss: 0.5185 - val_acc: 0.8047
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4667 - acc: 0.7995 - val_loss: 0.5087 - val_acc: 0.8047
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4500 - acc: 0.8294 - val_loss: 0.5173 - val_acc: 0.8047
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4630 - acc: 0.8151 - val_loss: 0.5187 - val_acc: 0.8047
Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4793 - acc: 0.8099 - val_loss: 0.5205 - val_acc: 0.8047
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4821 - acc: 0.8164 - val_loss: 0.5203 - val_acc: 0.8021
Epoch 297/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4700 - acc: 0.8008 - val_loss: 0.5091 - val_acc: 0.8073
Epoch 298/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4564 - acc: 0.8255 - val_loss: 0.5192 - val_acc: 0.8047
Epoch 299/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4716 - acc: 0.8177 - val_loss: 0.5087 - val_acc: 0.8073
Epoch 300/1000
12/12 [==============================] - 0s 9ms

Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4465 - acc: 0.8294 - val_loss: 0.5180 - val_acc: 0.8047
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4726 - acc: 0.8242 - val_loss: 0.5083 - val_acc: 0.8099
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4461 - acc: 0.8177 - val_loss: 0.5188 - val_acc: 0.8021
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4609 - acc: 0.8190 - val_loss: 0.5094 - val_acc: 0.8073
Epoch 412/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4654 - acc: 0.8086 - val_loss: 0.5148 - val_acc: 0.8047
Epoch 413/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4530 - acc: 0.8203 - val_loss: 0.5133 - val_acc: 0.8047
Epoch 414/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4471 - acc: 0.8177 - val_loss: 0.5098 - val_acc: 0.8099
Epoch 415/1000
12/12 [==============================] - 0s 8m

Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4520 - acc: 0.8177 - val_loss: 0.5128 - val_acc: 0.8047
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4610 - acc: 0.8229 - val_loss: 0.5094 - val_acc: 0.8047

Epoch 00469: loss improved from 0.47699 to 0.46104, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_5/weights/Pbest-1-000469-0.461039-0.804688.hdf5
Epoch 470/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4485 - acc: 0.8190 - val_loss: 0.5160 - val_acc: 0.8047
Epoch 471/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4701 - acc: 0.7943 - val_loss: 0.5105 - val_acc: 0.8073
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4755 - acc: 0.8138 - val_loss: 0.5104 - val_acc: 0.8073
Epoch 473/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4756 - acc: 0.8034 - val_loss: 0.5115 - val_acc: 0.8073
Epoch 474/1000
12

Epoch 585/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4605 - acc: 0.8216 - val_loss: 0.5146 - val_acc: 0.8047
Epoch 586/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4577 - acc: 0.8138 - val_loss: 0.5119 - val_acc: 0.7995
Epoch 587/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4452 - acc: 0.8294 - val_loss: 0.5076 - val_acc: 0.7995
Epoch 588/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4509 - acc: 0.8177 - val_loss: 0.5172 - val_acc: 0.8021
Epoch 589/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4631 - acc: 0.8190 - val_loss: 0.5193 - val_acc: 0.7995
Epoch 590/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4618 - acc: 0.8255 - val_loss: 0.5182 - val_acc: 0.7995
Epoch 591/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4511 - acc: 0.8346 - val_loss: 0.5205 - val_acc: 0.7969
Epoch 592/1000
12/12 [==============================] - 0s 9ms

Epoch 704/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4442 - acc: 0.8242 - val_loss: 0.5175 - val_acc: 0.8021
Epoch 705/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4637 - acc: 0.8086 - val_loss: 0.5175 - val_acc: 0.8021
Epoch 706/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4395 - acc: 0.8255 - val_loss: 0.5082 - val_acc: 0.8047
Epoch 707/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4636 - acc: 0.8229 - val_loss: 0.5159 - val_acc: 0.8047
Epoch 708/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4421 - acc: 0.8320 - val_loss: 0.5213 - val_acc: 0.7995
Epoch 709/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4601 - acc: 0.8216 - val_loss: 0.5122 - val_acc: 0.8047
Epoch 710/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4563 - acc: 0.8125 - val_loss: 0.5187 - val_acc: 0.8047
Epoch 711/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 268us/step
1-cairo:	acc: 80.31%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 0s 31ms/step - loss: 1.5047 - acc: 0.5651 - val_loss: 1.0983 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.1280 - acc: 0.6393 - val_loss: 1.0196 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0694 - acc: 0.6367 - val_loss: 0.9738 - val_acc: 0.6328
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0335 - acc: 0.6562 - val_loss: 0.9263 - val_acc: 0.6615
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9747 - acc: 0.6745 - val_loss: 0.8830 - val_acc: 0.6849
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9373 - acc: 0.6875 - val_loss: 0.8414 - val_acc: 0.7005
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8877 - acc: 0.6810 - val_loss: 0.8062 - val_acc: 0.7292
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4805 - acc: 0.8060 - val_loss: 0.5274 - val_acc: 0.8021
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4716 - acc: 0.8268 - val_loss: 0.5208 - val_acc: 0.8099

Epoch 00117: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 118/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4642 - acc: 0.8255 - val_loss: 0.5177 - val_acc: 0.8099
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4705 - acc: 0.8138 - val_loss: 0.5157 - val_acc: 0.8151
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4582 - acc: 0.8281 - val_loss: 0.5252 - val_acc: 0.8099
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4718 - acc: 0.8099 - val_loss: 0.5258 - val_acc: 0.8099
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4519 - acc: 0.8177 - val_loss: 0.518

Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4585 - acc: 0.8138 - val_loss: 0.5232 - val_acc: 0.8099
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4703 - acc: 0.8242 - val_loss: 0.5168 - val_acc: 0.8099
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4477 - acc: 0.8359 - val_loss: 0.5247 - val_acc: 0.8099
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4639 - acc: 0.8164 - val_loss: 0.5202 - val_acc: 0.8125
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4484 - acc: 0.8229 - val_loss: 0.5263 - val_acc: 0.8073
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4773 - acc: 0.8164 - val_loss: 0.5201 - val_acc: 0.8125
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4501 - acc: 0.8281 - val_loss: 0.5240 - val_acc: 0.8073
Epoch 241/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.4425 - acc: 0.8438 - val_loss: 0.5194 - val_acc: 0.8099
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4734 - acc: 0.8229 - val_loss: 0.5097 - val_acc: 0.8125
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4655 - acc: 0.8151 - val_loss: 0.5200 - val_acc: 0.8099
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4619 - acc: 0.8177 - val_loss: 0.5086 - val_acc: 0.8151
Epoch 355/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4603 - acc: 0.8346 - val_loss: 0.5206 - val_acc: 0.8125
Epoch 356/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4650 - acc: 0.8164 - val_loss: 0.5217 - val_acc: 0.8099
Epoch 357/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4584 - acc: 0.8281 - val_loss: 0.5263 - val_acc: 0.8073
Epoch 358/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 406/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4469 - acc: 0.8151 - val_loss: 0.5204 - val_acc: 0.8125
Epoch 407/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4462 - acc: 0.8424 - val_loss: 0.5206 - val_acc: 0.8125
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4665 - acc: 0.8151 - val_loss: 0.5203 - val_acc: 0.8151
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4717 - acc: 0.8177 - val_loss: 0.5233 - val_acc: 0.8099
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4562 - acc: 0.8112 - val_loss: 0.5285 - val_acc: 0.8073
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4462 - acc: 0.8229 - val_loss: 0.5206 - val_acc: 0.8099
Epoch 412/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4679 - acc: 0.8164 - val_loss: 0.4899 - val_acc: 0.8177
Epoch 413/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 8ms/step - loss: 0.4495 - acc: 0.8255 - val_loss: 0.5247 - val_acc: 0.8099
Epoch 467/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4665 - acc: 0.8125 - val_loss: 0.5140 - val_acc: 0.8125
Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4641 - acc: 0.8164 - val_loss: 0.5166 - val_acc: 0.8125
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4560 - acc: 0.8320 - val_loss: 0.5223 - val_acc: 0.8099
Epoch 470/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4394 - acc: 0.8320 - val_loss: 0.5263 - val_acc: 0.8099
Epoch 471/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4524 - acc: 0.8216 - val_loss: 0.5155 - val_acc: 0.8125
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4644 - acc: 0.8281 - val_loss: 0.5149 - val_acc: 0.8099
Epoch 473/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 377us/step
2-cairo:	acc: 81.07%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 79.30% (+/- 1.96%)
final: current database: cairo 	 79.30% (+/- 1.99%)
CPU times: user 5min 30s, sys: 35.7 s, total: 6min 6s
Wall time: 3min 31s

```

# <a id='constrain'>C</a>

In [6]:
%%time
dict_config_cus['distance_int'] = '999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_10 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_10 (Conv1D)           (None, 2000, 20)          1300      
_________________________________________________________________
activation_28 (Activation)   (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_10 (Glo (None, 20)                0         
_________________________________________________________________
dense_28 (Dense)             (None, 30)                630       
______________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.5358 - acc: 0.8073 - val_loss: 0.6063 - val_acc: 0.7682
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5577 - acc: 0.8099 - val_loss: 0.6194 - val_acc: 0.7786
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5443 - acc: 0.7982 - val_loss: 0.6172 - val_acc: 0.7812
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5649 - acc: 0.8008 - val_loss: 0.6228 - val_acc: 0.7734
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5052 - acc: 0.8216 - val_loss: 0.6180 - val_acc: 0.7760
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5268 - acc: 0.8255 - val_loss: 0.6165 - val_acc: 0.7734
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5261 - acc: 0.8151 - val_loss: 0.5929 - val_acc: 0.7760
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4649 - acc: 0.8281 - val_loss: 0.5960 - val_acc: 0.7812
Epoch 217/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4604 - acc: 0.8333 - val_loss: 0.5971 - val_acc: 0.7760

Epoch 00217: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4446 - acc: 0.8333 - val_loss: 0.5929 - val_acc: 0.7760
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4640 - acc: 0.8346 - val_loss: 0.5974 - val_acc: 0.7708
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4725 - acc: 0.8294 - val_loss: 0.5857 - val_acc: 0.7786
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4423 - acc: 0.8411 - val_loss: 0.6032 - val_acc: 0.7682
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4590 - acc: 0.8438 - val_loss: 0.5922 - val_acc: 0.7

Epoch 275/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4641 - acc: 0.8411 - val_loss: 0.5996 - val_acc: 0.7734
Epoch 276/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4625 - acc: 0.8333 - val_loss: 0.5852 - val_acc: 0.7812
Epoch 277/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4698 - acc: 0.8359 - val_loss: 0.5977 - val_acc: 0.7734
Epoch 278/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4653 - acc: 0.8438 - val_loss: 0.5904 - val_acc: 0.7760
Epoch 279/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4545 - acc: 0.8268 - val_loss: 0.5821 - val_acc: 0.7786
Epoch 280/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4434 - acc: 0.8451 - val_loss: 0.5807 - val_acc: 0.7760
Epoch 281/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4527 - acc: 0.8333 - val_loss: 0.5989 - val_acc: 0.7734
Epoch 282/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.4532 - acc: 0.8346 - val_loss: 0.6035 - val_acc: 0.7708
Epoch 394/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4602 - acc: 0.8359 - val_loss: 0.5918 - val_acc: 0.7812
Epoch 395/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4584 - acc: 0.8216 - val_loss: 0.5973 - val_acc: 0.7734
Epoch 396/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4734 - acc: 0.8216 - val_loss: 0.5990 - val_acc: 0.7734
Epoch 397/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4584 - acc: 0.8320 - val_loss: 0.5826 - val_acc: 0.7786
Epoch 398/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4775 - acc: 0.8451 - val_loss: 0.5995 - val_acc: 0.7734
Epoch 399/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4718 - acc: 0.8346 - val_loss: 0.5855 - val_acc: 0.7786
Epoch 400/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 0s 477us/step
0-cairo:	acc: 77.30%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 0s 39ms/step - loss: 1.5210 - acc: 0.5547 - val_loss: 1.1847 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.1767 - acc: 0.6393 - val_loss: 1.0647 - val_acc: 0.6406
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0911 - acc: 0.6406 - val_loss: 1.0034 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0447 - acc: 0.6654 - val_loss: 0.9675 - val_acc: 0.6354
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0085 - acc: 0.6458 - val_loss: 0.9416 - val_acc: 0.6641
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9619 - acc: 0.6562 - val_loss: 0.9040 - val_acc: 0.6823
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9619 - acc: 0.6562 - val_loss: 0.8827 - val_acc: 0.6823
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 

Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4813 - acc: 0.8138 - val_loss: 0.5257 - val_acc: 0.7891
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4861 - acc: 0.8164 - val_loss: 0.5232 - val_acc: 0.7969
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4610 - acc: 0.8216 - val_loss: 0.5248 - val_acc: 0.7969
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4750 - acc: 0.8255 - val_loss: 0.5240 - val_acc: 0.7969
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4920 - acc: 0.8151 - val_loss: 0.5154 - val_acc: 0.7917
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4754 - acc: 0.8229 - val_loss: 0.5127 - val_acc: 0.7995
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4928 - acc: 0.8125 - val_loss: 0.5076 - val_acc: 0.7995
Epoch 123/1000
12/12 [==============================] - 0s 10m

Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4776 - acc: 0.8138 - val_loss: 0.5085 - val_acc: 0.8021
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4570 - acc: 0.8138 - val_loss: 0.4961 - val_acc: 0.8047
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4721 - acc: 0.8242 - val_loss: 0.5018 - val_acc: 0.8021
Epoch 179/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4407 - acc: 0.8346 - val_loss: 0.5055 - val_acc: 0.8021

Epoch 00179: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 180/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4555 - acc: 0.8320 - val_loss: 0.4944 - val_acc: 0.8021
Epoch 181/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4497 - acc: 0.8177 - val_loss: 0.4713 - val_acc: 0.8073
Epoch 182/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4670 - acc: 0.8320 - val_loss: 0.497

12/12 [==============================] - 0s 9ms/step - loss: 0.4491 - acc: 0.8333 - val_loss: 0.5039 - val_acc: 0.8073
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4389 - acc: 0.8346 - val_loss: 0.5069 - val_acc: 0.8047
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4367 - acc: 0.8372 - val_loss: 0.4970 - val_acc: 0.8073
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4241 - acc: 0.8281 - val_loss: 0.5066 - val_acc: 0.8047
Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4353 - acc: 0.8359 - val_loss: 0.5101 - val_acc: 0.8021
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4261 - acc: 0.8424 - val_loss: 0.5043 - val_acc: 0.8047
Epoch 297/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4338 - acc: 0.8203 - val_loss: 0.5105 - val_acc: 0.8021
Epoch 298/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4358 - acc: 0.8307 - val_loss: 0.5059 - val_acc: 0.8047
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4201 - acc: 0.8281 - val_loss: 0.5044 - val_acc: 0.8073
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4242 - acc: 0.8294 - val_loss: 0.5070 - val_acc: 0.8047
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4583 - acc: 0.8203 - val_loss: 0.4965 - val_acc: 0.8073
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4336 - acc: 0.8477 - val_loss: 0.5013 - val_acc: 0.8073
Epoch 412/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4183 - acc: 0.8333 - val_loss: 0.5087 - val_acc: 0.8047
Epoch 413/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4588 - acc: 0.8190 - val_loss: 0.5099 - val_acc: 0.8021
Epoch 414/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 467/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4272 - acc: 0.8529 - val_loss: 0.5049 - val_acc: 0.8099
Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4379 - acc: 0.8268 - val_loss: 0.4931 - val_acc: 0.8125
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4364 - acc: 0.8372 - val_loss: 0.5034 - val_acc: 0.8047

Epoch 00469: loss improved from 0.44520 to 0.43641, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_5/weights/Pbest-1-000469-0.436413-0.804688.hdf5
Epoch 470/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4345 - acc: 0.8216 - val_loss: 0.5031 - val_acc: 0.8047
Epoch 471/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4213 - acc: 0.8503 - val_loss: 0.5045 - val_acc: 0.8073
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4455 - acc: 0.8307 - val_loss: 0.5086 - val_acc: 0.8021
Epoch 473/1000
12/

Epoch 526/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4287 - acc: 0.8268 - val_loss: 0.5006 - val_acc: 0.8073
Epoch 527/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4398 - acc: 0.8398 - val_loss: 0.5055 - val_acc: 0.8073
Epoch 528/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4419 - acc: 0.8320 - val_loss: 0.5099 - val_acc: 0.8047
Epoch 529/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4531 - acc: 0.8333 - val_loss: 0.5095 - val_acc: 0.8047
Epoch 530/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4214 - acc: 0.8385 - val_loss: 0.4952 - val_acc: 0.8151
Epoch 531/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4404 - acc: 0.8333 - val_loss: 0.5080 - val_acc: 0.8073
Epoch 532/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4452 - acc: 0.8333 - val_loss: 0.4805 - val_acc: 0.8177
Epoch 533/1000
12/12 [==============================] - 0s 9m

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 592us/step
1-cairo:	acc: 80.82%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 44ms/step - loss: 1.4464 - acc: 0.5729 - val_loss: 1.1446 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.1287 - acc: 0.6367 - val_loss: 1.0403 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0310 - acc: 0.6419 - val_loss: 0.9568 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9782 - acc: 0.6536 - val_loss: 0.8806 - val_acc: 0.6849
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9437 - acc: 0.6628 - val_loss: 0.8738 - val_acc: 0.7161
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9107 - acc: 0.6953 - val_loss: 0.8423 - val_acc: 0.7318
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8929 - acc: 0.6914 - val_loss: 0.8109 - val_acc: 0.7526
Epoch 8/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4744 - acc: 0.8294 - val_loss: 0.5338 - val_acc: 0.8151
Epoch 115/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4844 - acc: 0.8164 - val_loss: 0.5451 - val_acc: 0.8125
Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4713 - acc: 0.8320 - val_loss: 0.5450 - val_acc: 0.8125
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4651 - acc: 0.8255 - val_loss: 0.5402 - val_acc: 0.8125
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4850 - acc: 0.8138 - val_loss: 0.5451 - val_acc: 0.8151
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4781 - acc: 0.8190 - val_loss: 0.5456 - val_acc: 0.8125
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4833 - acc: 0.8138 - val_loss: 0.5446 - val_acc: 0.8177
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4670 - acc: 0.8125 - val_loss: 0.5332 - val_acc: 0.8255
Epoch 173/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4497 - acc: 0.8255 - val_loss: 0.5368 - val_acc: 0.8229

Epoch 00173: loss improved from 0.46047 to 0.44965, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_5/weights/Pbest-2-000173-0.449650-0.822917.hdf5
Epoch 174/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4348 - acc: 0.8372 - val_loss: 0.5445 - val_acc: 0.8177
Epoch 175/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4550 - acc: 0.8281 - val_loss: 0.5255 - val_acc: 0.8255
Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4542 - acc: 0.8073 - val_loss: 0.5429 - val_acc: 0.8203
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4462 - acc: 0.8203 - val_loss: 0.5391 - val_acc: 0.8203

Epoch 00177: loss improved from

Epoch 228/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4779 - acc: 0.8203 - val_loss: 0.5329 - val_acc: 0.8229
Epoch 229/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4749 - acc: 0.8125 - val_loss: 0.5424 - val_acc: 0.8203
Epoch 230/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4484 - acc: 0.8216 - val_loss: 0.5381 - val_acc: 0.8203
Epoch 231/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4457 - acc: 0.8255 - val_loss: 0.5335 - val_acc: 0.8203
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4551 - acc: 0.8307 - val_loss: 0.5225 - val_acc: 0.8229
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4483 - acc: 0.8229 - val_loss: 0.5399 - val_acc: 0.8203
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4783 - acc: 0.8164 - val_loss: 0.5448 - val_acc: 0.8177
Epoch 235/1000
12/12 [==============================] - 0s 9ms

Epoch 284/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4629 - acc: 0.8255 - val_loss: 0.5246 - val_acc: 0.8229
Epoch 285/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4605 - acc: 0.8268 - val_loss: 0.5423 - val_acc: 0.8177
Epoch 286/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4575 - acc: 0.8216 - val_loss: 0.5419 - val_acc: 0.8177
Epoch 287/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4654 - acc: 0.8203 - val_loss: 0.5381 - val_acc: 0.8203
Epoch 288/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4567 - acc: 0.8320 - val_loss: 0.5352 - val_acc: 0.8229
Epoch 289/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4609 - acc: 0.8307 - val_loss: 0.5311 - val_acc: 0.8229
Epoch 290/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4753 - acc: 0.8203 - val_loss: 0.5447 - val_acc: 0.8177
Epoch 291/1000
12/12 [==============================] - 0s 10m

Epoch 403/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4648 - acc: 0.8229 - val_loss: 0.5365 - val_acc: 0.8229
Epoch 404/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4633 - acc: 0.8138 - val_loss: 0.5400 - val_acc: 0.8177
Epoch 405/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4454 - acc: 0.8242 - val_loss: 0.5341 - val_acc: 0.8229
Epoch 406/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4485 - acc: 0.8151 - val_loss: 0.5447 - val_acc: 0.8177
Epoch 407/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4588 - acc: 0.8151 - val_loss: 0.5432 - val_acc: 0.8203
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4498 - acc: 0.8216 - val_loss: 0.5378 - val_acc: 0.8203
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4521 - acc: 0.8177 - val_loss: 0.5312 - val_acc: 0.8255
Epoch 410/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 738us/step
2-cairo:	acc: 82.10%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 80.16% (+/- 1.91%)
final: current database: cairo 	 80.07% (+/- 2.03%)
CPU times: user 4min 40s, sys: 29.6 s, total: 5min 10s
Wall time: 3min
```

# <a id='constrain_1'>CS_1</a>

In [7]:
%%time
dict_config_cus['distance_int'] = '1'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_19 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_19 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_19 (Conv1D)           (None, 2000, 20)          1300      
_________________________________________________________________
activation_55 (Activation)   (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_19 (Glo (None, 20)                0         
_________________________________________________________________
dense_55 (Dense)             (None, 30)                630       
________________________________________


Epoch 00100: saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_5/weights/0-000100-0.247714-0.914062.hdf5
Epoch 101/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.2496 - acc: 0.9102 - val_loss: 0.3265 - val_acc: 0.9141
Epoch 102/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2397 - acc: 0.9089 - val_loss: 0.3409 - val_acc: 0.9062
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2553 - acc: 0.9115 - val_loss: 0.3420 - val_acc: 0.9089
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2414 - acc: 0.9128 - val_loss: 0.3396 - val_acc: 0.9089
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2521 - acc: 0.8997 - val_loss: 0.3371 - val_acc: 0.9141
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2292 - acc: 0.9180 - val_loss: 0.3344 - val_acc: 0.9141
Epoch 107/1000
12/12 [==============================] - 0s 9ms/st

12/12 [==============================] - 0s 9ms/step - loss: 0.1978 - acc: 0.9258 - val_loss: 0.3685 - val_acc: 0.9167
Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2094 - acc: 0.9245 - val_loss: 0.3719 - val_acc: 0.9141
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2161 - acc: 0.9219 - val_loss: 0.3489 - val_acc: 0.9167
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1945 - acc: 0.9193 - val_loss: 0.3704 - val_acc: 0.9141
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2072 - acc: 0.9245 - val_loss: 0.3717 - val_acc: 0.9141
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2207 - acc: 0.9206 - val_loss: 0.3715 - val_acc: 0.9141
Epoch 223/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2108 - acc: 0.9219 - val_loss: 0.3414 - val_acc: 0.9193
Epoch 224/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 334/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2087 - acc: 0.9206 - val_loss: 0.3732 - val_acc: 0.9141
Epoch 335/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2062 - acc: 0.9245 - val_loss: 0.3705 - val_acc: 0.9141
Epoch 336/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1952 - acc: 0.9323 - val_loss: 0.3705 - val_acc: 0.9141
Epoch 337/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2124 - acc: 0.9167 - val_loss: 0.3725 - val_acc: 0.9141
Epoch 338/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2184 - acc: 0.9245 - val_loss: 0.3127 - val_acc: 0.9193
Epoch 339/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2096 - acc: 0.9284 - val_loss: 0.3672 - val_acc: 0.9167
Epoch 340/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1951 - acc: 0.9219 - val_loss: 0.3726 - val_acc: 0.9141
Epoch 341/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 0s 878us/step
0-cairo:	acc: 91.58%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 58ms/step - loss: 1.3712 - acc: 0.5794 - val_loss: 0.9594 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9381 - acc: 0.6367 - val_loss: 0.8255 - val_acc: 0.6432
Epoch 3/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8173 - acc: 0.6523 - val_loss: 0.7545 - val_acc: 0.6849
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7362 - acc: 0.7227 - val_loss: 0.6716 - val_acc: 0.8698
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6825 - acc: 0.7839 - val_loss: 0.5835 - val_acc: 0.8750
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6285 - acc: 0.8203 - val_loss: 0.5167 - val_acc: 0.8750
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5468 - acc: 0.8451 - val_loss: 0.4701 - val_acc: 0.8724
Epoch 8/1000
12/12 [==============================] - 0s

Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2021 - acc: 0.9245 - val_loss: 0.2349 - val_acc: 0.9193
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2185 - acc: 0.9141 - val_loss: 0.2481 - val_acc: 0.9036
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2171 - acc: 0.9154 - val_loss: 0.2343 - val_acc: 0.9089
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2073 - acc: 0.9232 - val_loss: 0.2401 - val_acc: 0.9167
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2083 - acc: 0.9232 - val_loss: 0.2436 - val_acc: 0.9141
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2217 - acc: 0.9154 - val_loss: 0.2453 - val_acc: 0.8984
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2212 - acc: 0.9102 - val_loss: 0.2351 - val_acc: 0.9036
Epoch 123/1000
12/12 [==============================] - 0s 9ms

Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1875 - acc: 0.9349 - val_loss: 0.2361 - val_acc: 0.9036
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2155 - acc: 0.9167 - val_loss: 0.2373 - val_acc: 0.9010
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2048 - acc: 0.9141 - val_loss: 0.2287 - val_acc: 0.9062
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2033 - acc: 0.9245 - val_loss: 0.2415 - val_acc: 0.8984
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1878 - acc: 0.9232 - val_loss: 0.2435 - val_acc: 0.8984
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1977 - acc: 0.9271 - val_loss: 0.2355 - val_acc: 0.9036
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2034 - acc: 0.9284 - val_loss: 0.2425 - val_acc: 0.8984
Epoch 240/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.1883 - acc: 0.9284 - val_loss: 0.2327 - val_acc: 0.9036
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1983 - acc: 0.9232 - val_loss: 0.2406 - val_acc: 0.9010
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1978 - acc: 0.9245 - val_loss: 0.2443 - val_acc: 0.8984
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2001 - acc: 0.9154 - val_loss: 0.2437 - val_acc: 0.8984
Epoch 355/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1909 - acc: 0.9167 - val_loss: 0.2441 - val_acc: 0.8984
Epoch 356/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2054 - acc: 0.9193 - val_loss: 0.2445 - val_acc: 0.8984
Epoch 357/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1920 - acc: 0.9284 - val_loss: 0.2407 - val_acc: 0.9010
Epoch 358/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 405/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2029 - acc: 0.9258 - val_loss: 0.2427 - val_acc: 0.8984
Epoch 406/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2003 - acc: 0.9219 - val_loss: 0.2365 - val_acc: 0.9010
Epoch 407/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2110 - acc: 0.9167 - val_loss: 0.2396 - val_acc: 0.9010
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2032 - acc: 0.9310 - val_loss: 0.2428 - val_acc: 0.8984
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2015 - acc: 0.9193 - val_loss: 0.2426 - val_acc: 0.8984
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2012 - acc: 0.9284 - val_loss: 0.2399 - val_acc: 0.9010
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1886 - acc: 0.9401 - val_loss: 0.2444 - val_acc: 0.8984
Epoch 412/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 8ms/step - loss: 0.1978 - acc: 0.9297 - val_loss: 0.2428 - val_acc: 0.8984
Epoch 467/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1971 - acc: 0.9297 - val_loss: 0.2437 - val_acc: 0.8984
Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1991 - acc: 0.9180 - val_loss: 0.2413 - val_acc: 0.9010
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1852 - acc: 0.9180 - val_loss: 0.2378 - val_acc: 0.9036

Epoch 00469: loss improved from 0.19521 to 0.18524, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_5/weights/Pbest-1-000469-0.185243-0.903646.hdf5
Epoch 470/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.2018 - acc: 0.9284 - val_loss: 0.2325 - val_acc: 0.9036
Epoch 471/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2093 - acc: 0.9206 - val_loss: 0.2391 - val_acc: 0.9010
Epoch 472/1000
12/12 [============

Epoch 525/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1862 - acc: 0.9297 - val_loss: 0.2438 - val_acc: 0.8984
Epoch 526/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1944 - acc: 0.9245 - val_loss: 0.2424 - val_acc: 0.8984
Epoch 527/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2118 - acc: 0.9245 - val_loss: 0.2428 - val_acc: 0.8984
Epoch 528/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2166 - acc: 0.9154 - val_loss: 0.2419 - val_acc: 0.8984
Epoch 529/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2009 - acc: 0.9336 - val_loss: 0.2406 - val_acc: 0.9010
Epoch 530/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2041 - acc: 0.9180 - val_loss: 0.2380 - val_acc: 0.9010
Epoch 531/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2090 - acc: 0.9089 - val_loss: 0.2432 - val_acc: 0.8984
Epoch 532/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.2064 - acc: 0.9258 - val_loss: 0.2348 - val_acc: 0.9036
Epoch 640/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2035 - acc: 0.9232 - val_loss: 0.2419 - val_acc: 0.8984
Epoch 641/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2069 - acc: 0.9193 - val_loss: 0.2408 - val_acc: 0.9010
Epoch 642/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1937 - acc: 0.9297 - val_loss: 0.2325 - val_acc: 0.9062
Epoch 643/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1950 - acc: 0.9310 - val_loss: 0.2443 - val_acc: 0.8984
Epoch 644/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2176 - acc: 0.9167 - val_loss: 0.2431 - val_acc: 0.8984
Epoch 645/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1921 - acc: 0.9284 - val_loss: 0.2424 - val_acc: 0.9010
Epoch 646/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 699/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2101 - acc: 0.9232 - val_loss: 0.2406 - val_acc: 0.9010
Epoch 700/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1969 - acc: 0.9206 - val_loss: 0.2439 - val_acc: 0.8984

Epoch 00700: saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_5/weights/1-000700-0.196912-0.898438.hdf5
Epoch 701/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.2142 - acc: 0.9167 - val_loss: 0.2346 - val_acc: 0.9010
Epoch 702/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2059 - acc: 0.9323 - val_loss: 0.2437 - val_acc: 0.8984
Epoch 703/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2096 - acc: 0.9232 - val_loss: 0.2434 - val_acc: 0.8984
Epoch 704/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1944 - acc: 0.9232 - val_loss: 0.2428 - val_acc: 0.8984
Epoch 705/1000
12/12 [==============================] - 0s 9ms/s

[[  0   0   0   0  10   0   0]
 [  0  40   0   0   0   0   2]
 [  0   0  19   0   0   0   0]
 [  0   0   0  23   0   0   0]
 [  0   2   1   0 238   8   0]
 [  0   0   0   0   7  27   0]
 [  0   2   0   0   0   0  12]]
--------------------   final   --------------------
no_activities: 7



/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 1ms/step
1-cairo:	acc: 90.03%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 1s 62ms/step - loss: 1.3245 - acc: 0.5885 - val_loss: 0.9122 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8828 - acc: 0.6510 - val_loss: 0.7989 - val_acc: 0.6458
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7763 - acc: 0.7201 - val_loss: 0.6919 - val_acc: 0.7839
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6862 - acc: 0.7682 - val_loss: 0.6279 - val_acc: 0.7734
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6323 - acc: 0.7812 - val_loss: 0.5597 - val_acc: 0.7760
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5867 - acc: 0.7891 - val_loss: 0.5180 - val_acc: 0.7865
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5332 - acc: 0.8125 - val_loss: 0.4645 - val_acc: 0.8203
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 

Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2377 - acc: 0.9115 - val_loss: 0.2978 - val_acc: 0.8958
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2327 - acc: 0.9193 - val_loss: 0.2962 - val_acc: 0.8958
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2188 - acc: 0.9323 - val_loss: 0.2907 - val_acc: 0.8984
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2335 - acc: 0.9219 - val_loss: 0.2973 - val_acc: 0.8958
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2269 - acc: 0.9154 - val_loss: 0.2935 - val_acc: 0.8984
Epoch 125/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2161 - acc: 0.9219 - val_loss: 0.2965 - val_acc: 0.8958
Epoch 126/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2176 - acc: 0.9258 - val_loss: 0.2931 - val_acc: 0.8932
Epoch 127/1000
12/12 [==============================] - 0s 9ms


Epoch 00177: loss improved from 0.20610 to 0.20043, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_5/weights/Pbest-2-000177-0.200431-0.901042.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2080 - acc: 0.9232 - val_loss: 0.2925 - val_acc: 0.9010
Epoch 179/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2130 - acc: 0.9219 - val_loss: 0.2598 - val_acc: 0.9089
Epoch 180/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2122 - acc: 0.9206 - val_loss: 0.2901 - val_acc: 0.9036
Epoch 181/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2122 - acc: 0.9180 - val_loss: 0.2865 - val_acc: 0.9062
Epoch 182/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2117 - acc: 0.9284 - val_loss: 0.2919 - val_acc: 0.9010
Epoch 183/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2049 - acc: 0.9323 - val_loss: 0.2923 - val_acc: 0.9010
Epoch 184/1000
12/12

Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1979 - acc: 0.9323 - val_loss: 0.2955 - val_acc: 0.9010
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2120 - acc: 0.9310 - val_loss: 0.2929 - val_acc: 0.9010
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2146 - acc: 0.9206 - val_loss: 0.2876 - val_acc: 0.9036
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2041 - acc: 0.9323 - val_loss: 0.2942 - val_acc: 0.9010
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2102 - acc: 0.9232 - val_loss: 0.2931 - val_acc: 0.9036
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2047 - acc: 0.9258 - val_loss: 0.2910 - val_acc: 0.9036
Epoch 241/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2112 - acc: 0.9323 - val_loss: 0.2908 - val_acc: 0.9036
Epoch 242/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.2171 - acc: 0.9219 - val_loss: 0.2862 - val_acc: 0.9036
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2015 - acc: 0.9232 - val_loss: 0.2959 - val_acc: 0.9010
Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2039 - acc: 0.9310 - val_loss: 0.2813 - val_acc: 0.9062
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1881 - acc: 0.9336 - val_loss: 0.2844 - val_acc: 0.9036
Epoch 297/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2150 - acc: 0.9219 - val_loss: 0.2950 - val_acc: 0.9010
Epoch 298/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2005 - acc: 0.9219 - val_loss: 0.2874 - val_acc: 0.9036
Epoch 299/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2013 - acc: 0.9310 - val_loss: 0.2956 - val_acc: 0.9010
Epoch 300/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 407/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2055 - acc: 0.9193 - val_loss: 0.2879 - val_acc: 0.9036
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2046 - acc: 0.9336 - val_loss: 0.2886 - val_acc: 0.9062
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2079 - acc: 0.9141 - val_loss: 0.2951 - val_acc: 0.9010
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2102 - acc: 0.9284 - val_loss: 0.2958 - val_acc: 0.9010
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2105 - acc: 0.9219 - val_loss: 0.2929 - val_acc: 0.9036
Epoch 412/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2092 - acc: 0.9349 - val_loss: 0.2827 - val_acc: 0.9062
Epoch 413/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2018 - acc: 0.9284 - val_loss: 0.2957 - val_acc: 0.9010
Epoch 414/1000
12/12 [==============================] - 0s 9ms

Epoch 467/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2027 - acc: 0.9284 - val_loss: 0.2955 - val_acc: 0.9010
Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2020 - acc: 0.9297 - val_loss: 0.2847 - val_acc: 0.9062
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2032 - acc: 0.9336 - val_loss: 0.2953 - val_acc: 0.9010
Epoch 470/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2077 - acc: 0.9219 - val_loss: 0.2917 - val_acc: 0.9036
Epoch 471/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2023 - acc: 0.9349 - val_loss: 0.2878 - val_acc: 0.9062
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2055 - acc: 0.9375 - val_loss: 0.2949 - val_acc: 0.9010
Epoch 473/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2082 - acc: 0.9232 - val_loss: 0.2962 - val_acc: 0.9010
Epoch 474/1000
12/12 [==============================] - 0s 9m

Epoch 526/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2089 - acc: 0.9206 - val_loss: 0.2963 - val_acc: 0.9010
Epoch 527/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2084 - acc: 0.9193 - val_loss: 0.2874 - val_acc: 0.9036
Epoch 528/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2036 - acc: 0.9232 - val_loss: 0.2907 - val_acc: 0.9036
Epoch 529/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1972 - acc: 0.9440 - val_loss: 0.2964 - val_acc: 0.9010
Epoch 530/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2197 - acc: 0.9180 - val_loss: 0.2961 - val_acc: 0.9010
Epoch 531/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1888 - acc: 0.9362 - val_loss: 0.2946 - val_acc: 0.9010
Epoch 532/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2094 - acc: 0.9297 - val_loss: 0.2958 - val_acc: 0.9010
Epoch 533/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 1ms/step
2-cairo:	acc: 90.28%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 91.23% (+/- 0.67%)
final: current database: cairo 	 90.63% (+/- 0.68%)
CPU times: user 5min 37s, sys: 35.1 s, total: 6min 12s
Wall time: 3min 33s

```

# <a id='constrain_2'>CS_2</a>

In [8]:
%%time
dict_config_cus['distance_int'] = '2'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_28 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_28 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_28 (Conv1D)           (None, 2000, 20)          1300      
_________________________________________________________________
activation_82 (Activation)   (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_28 (Glo (None, 20)                0         
_________________________________________________________________
dense_82 (Dense)             (None, 30)                630       
________________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.4602 - acc: 0.8307 - val_loss: 0.5301 - val_acc: 0.7839
Epoch 102/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4438 - acc: 0.8385 - val_loss: 0.5211 - val_acc: 0.7917
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4556 - acc: 0.8320 - val_loss: 0.5255 - val_acc: 0.7865
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4658 - acc: 0.8125 - val_loss: 0.5280 - val_acc: 0.7943
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4503 - acc: 0.8411 - val_loss: 0.5222 - val_acc: 0.7943
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4428 - acc: 0.8372 - val_loss: 0.5297 - val_acc: 0.7943
Epoch 107/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4585 - acc: 0.8255 - val_loss: 0.5182 - val_acc: 0.8021
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.4145 - acc: 0.8451 - val_loss: 0.5246 - val_acc: 0.7995
Epoch 215/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4083 - acc: 0.8333 - val_loss: 0.5094 - val_acc: 0.7969
Epoch 216/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4092 - acc: 0.8490 - val_loss: 0.5135 - val_acc: 0.8099
Epoch 217/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4186 - acc: 0.8411 - val_loss: 0.5088 - val_acc: 0.8099
Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4157 - acc: 0.8424 - val_loss: 0.5044 - val_acc: 0.8099
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4206 - acc: 0.8385 - val_loss: 0.5120 - val_acc: 0.8073
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4146 - acc: 0.8451 - val_loss: 0.5201 - val_acc: 0.7995
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 273/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3957 - acc: 0.8411 - val_loss: 0.5133 - val_acc: 0.8021

Epoch 00273: loss improved from 0.41078 to 0.39573, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_5/weights/Pbest-0-000273-0.395734-0.802083.hdf5
Epoch 274/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3900 - acc: 0.8503 - val_loss: 0.5194 - val_acc: 0.8021
Epoch 275/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4055 - acc: 0.8385 - val_loss: 0.5215 - val_acc: 0.8021
Epoch 276/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3894 - acc: 0.8503 - val_loss: 0.5148 - val_acc: 0.8047
Epoch 277/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4008 - acc: 0.8451 - val_loss: 0.5154 - val_acc: 0.8047
Epoch 278/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3945 - acc: 0.8529 - val_loss: 0.5163 - val_acc: 0.8021
Epoch 279/1000
12/12

Epoch 329/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4034 - acc: 0.8307 - val_loss: 0.5233 - val_acc: 0.7969
Epoch 330/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3954 - acc: 0.8398 - val_loss: 0.5254 - val_acc: 0.7969
Epoch 331/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3766 - acc: 0.8542 - val_loss: 0.5174 - val_acc: 0.7995
Epoch 332/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4129 - acc: 0.8516 - val_loss: 0.5196 - val_acc: 0.7995
Epoch 333/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4063 - acc: 0.8411 - val_loss: 0.5141 - val_acc: 0.8047
Epoch 334/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3927 - acc: 0.8555 - val_loss: 0.5065 - val_acc: 0.8021
Epoch 335/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4243 - acc: 0.8398 - val_loss: 0.5107 - val_acc: 0.8021
Epoch 336/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.3964 - acc: 0.8581 - val_loss: 0.5206 - val_acc: 0.8021
Epoch 448/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3864 - acc: 0.8529 - val_loss: 0.5174 - val_acc: 0.8021
Epoch 449/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4209 - acc: 0.8451 - val_loss: 0.5103 - val_acc: 0.8047
Epoch 450/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3964 - acc: 0.8503 - val_loss: 0.5222 - val_acc: 0.8021
Epoch 451/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3903 - acc: 0.8594 - val_loss: 0.5138 - val_acc: 0.8047
Epoch 452/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3987 - acc: 0.8490 - val_loss: 0.5178 - val_acc: 0.8047
Epoch 453/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4022 - acc: 0.8490 - val_loss: 0.5186 - val_acc: 0.8021
Epoch 454/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 1ms/step
0-cairo:	acc: 80.36%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 82ms/step - loss: 1.4182 - acc: 0.5872 - val_loss: 1.1181 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.1303 - acc: 0.6341 - val_loss: 1.0091 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0508 - acc: 0.6471 - val_loss: 0.9051 - val_acc: 0.6458
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9786 - acc: 0.6380 - val_loss: 0.8703 - val_acc: 0.6380
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9263 - acc: 0.6497 - val_loss: 0.8339 - val_acc: 0.6927
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9340 - acc: 0.6510 - val_loss: 0.8055 - val_acc: 0.7109
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8870 - acc: 0.6797 - val_loss: 0.7751 - val_acc: 0.7292
Epoch 8/1000
12/12 [==============================] - 

12/12 [==============================] - 0s 9ms/step - loss: 0.5060 - acc: 0.8086 - val_loss: 0.4332 - val_acc: 0.8307
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5016 - acc: 0.8086 - val_loss: 0.4479 - val_acc: 0.8151
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4547 - acc: 0.8294 - val_loss: 0.4465 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4679 - acc: 0.8203 - val_loss: 0.4466 - val_acc: 0.8229
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5040 - acc: 0.8164 - val_loss: 0.4437 - val_acc: 0.8281
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4853 - acc: 0.8099 - val_loss: 0.4343 - val_acc: 0.8255
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4853 - acc: 0.8125 - val_loss: 0.4443 - val_acc: 0.8255
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4248 - acc: 0.8398 - val_loss: 0.4374 - val_acc: 0.8307
Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4731 - acc: 0.8346 - val_loss: 0.4399 - val_acc: 0.8281
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4461 - acc: 0.8359 - val_loss: 0.4381 - val_acc: 0.8307
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4831 - acc: 0.8164 - val_loss: 0.4413 - val_acc: 0.8281
Epoch 179/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4702 - acc: 0.8294 - val_loss: 0.4418 - val_acc: 0.8255
Epoch 180/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4560 - acc: 0.8398 - val_loss: 0.4413 - val_acc: 0.8255
Epoch 181/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4456 - acc: 0.8372 - val_loss: 0.4373 - val_acc: 0.8307
Epoch 182/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4388 - acc: 0.8477 - val_loss: 0.4433 - val_acc: 0.8229
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4360 - acc: 0.8398 - val_loss: 0.4389 - val_acc: 0.8281
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4615 - acc: 0.8242 - val_loss: 0.4422 - val_acc: 0.8255
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4626 - acc: 0.8333 - val_loss: 0.4409 - val_acc: 0.8255
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4641 - acc: 0.8164 - val_loss: 0.4164 - val_acc: 0.8307
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4764 - acc: 0.8255 - val_loss: 0.4399 - val_acc: 0.8255
Epoch 241/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4377 - acc: 0.8411 - val_loss: 0.4273 - val_acc: 0.8281
Epoch 242/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.4597 - acc: 0.8320 - val_loss: 0.4430 - val_acc: 0.8229
Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4640 - acc: 0.8190 - val_loss: 0.4403 - val_acc: 0.8229
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4905 - acc: 0.8073 - val_loss: 0.4351 - val_acc: 0.8281
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4468 - acc: 0.8242 - val_loss: 0.4297 - val_acc: 0.8255
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4461 - acc: 0.8411 - val_loss: 0.4421 - val_acc: 0.8229
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4529 - acc: 0.8307 - val_loss: 0.4436 - val_acc: 0.8229
Epoch 355/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4724 - acc: 0.8216 - val_loss: 0.4381 - val_acc: 0.8255
Epoch 356/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
1-cairo:	acc: 82.61%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 88ms/step - loss: 1.4543 - acc: 0.5651 - val_loss: 1.0410 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0568 - acc: 0.6406 - val_loss: 0.8877 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9228 - acc: 0.6589 - val_loss: 0.8139 - val_acc: 0.6797
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8766 - acc: 0.6706 - val_loss: 0.7785 - val_acc: 0.7083
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8225 - acc: 0.7135 - val_loss: 0.7404 - val_acc: 0.7344
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8009 - acc: 0.6940 - val_loss: 0.7163 - val_acc: 0.7448
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7760 - acc: 0.7174 - val_loss: 0.6971 - val_acc: 0.7578
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 

Epoch 113/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4755 - acc: 0.8268 - val_loss: 0.5085 - val_acc: 0.8177
Epoch 114/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4836 - acc: 0.8138 - val_loss: 0.5031 - val_acc: 0.8255
Epoch 115/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4781 - acc: 0.8073 - val_loss: 0.5047 - val_acc: 0.8229
Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4971 - acc: 0.8073 - val_loss: 0.5067 - val_acc: 0.8203
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4833 - acc: 0.8281 - val_loss: 0.5114 - val_acc: 0.8151
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4764 - acc: 0.8164 - val_loss: 0.5062 - val_acc: 0.8229
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4905 - acc: 0.8255 - val_loss: 0.5092 - val_acc: 0.8151
Epoch 120/1000
12/12 [==============================] - 0s 9ms

Epoch 172/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4454 - acc: 0.8268 - val_loss: 0.5021 - val_acc: 0.8203
Epoch 173/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4646 - acc: 0.8164 - val_loss: 0.4917 - val_acc: 0.8177

Epoch 00173: loss improved from 0.48196 to 0.46457, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_5/weights/Pbest-2-000173-0.464573-0.817708.hdf5
Epoch 174/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4614 - acc: 0.8190 - val_loss: 0.5091 - val_acc: 0.8151
Epoch 175/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4625 - acc: 0.8125 - val_loss: 0.5104 - val_acc: 0.8125
Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4696 - acc: 0.8203 - val_loss: 0.5053 - val_acc: 0.8151
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4661 - acc: 0.8229 - val_loss: 0.5114 - val_acc: 0.8125
Epoch 178/1000
12/12

Epoch 231/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4562 - acc: 0.8138 - val_loss: 0.5097 - val_acc: 0.8125
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4616 - acc: 0.8268 - val_loss: 0.5025 - val_acc: 0.8177
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4716 - acc: 0.8190 - val_loss: 0.5068 - val_acc: 0.8151
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4658 - acc: 0.8203 - val_loss: 0.5037 - val_acc: 0.8177
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4787 - acc: 0.8190 - val_loss: 0.5093 - val_acc: 0.8151
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4899 - acc: 0.8190 - val_loss: 0.5022 - val_acc: 0.8203
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4727 - acc: 0.8099 - val_loss: 0.5008 - val_acc: 0.8177
Epoch 238/1000
12/12 [==============================] - 0s 9ms

Epoch 291/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4697 - acc: 0.8216 - val_loss: 0.5087 - val_acc: 0.8151
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4778 - acc: 0.8112 - val_loss: 0.5113 - val_acc: 0.8125
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4675 - acc: 0.8281 - val_loss: 0.5109 - val_acc: 0.8125
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4861 - acc: 0.8177 - val_loss: 0.5078 - val_acc: 0.8151
Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4869 - acc: 0.8086 - val_loss: 0.5079 - val_acc: 0.8151
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4465 - acc: 0.8268 - val_loss: 0.5036 - val_acc: 0.8177
Epoch 297/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4688 - acc: 0.8151 - val_loss: 0.5075 - val_acc: 0.8125
Epoch 298/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
2-cairo:	acc: 81.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 81.43% (+/- 1.03%)
final: current database: cairo 	 81.52% (+/- 0.92%)
CPU times: user 4min 14s, sys: 25.5 s, total: 4min 40s
Wall time: 2min 45s

```

# <a id='constrain_3'>CS_3</a>

In [9]:
%%time
dict_config_cus['distance_int'] = '3'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_37 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_37 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_37 (Conv1D)           (None, 2000, 20)          1300      
_________________________________________________________________
activation_109 (Activation)  (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_37 (Glo (None, 20)                0         
_________________________________________________________________
dense_109 (Dense)            (None, 30)                630       
________________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.4672 - acc: 0.8372 - val_loss: 0.4849 - val_acc: 0.8047
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4788 - acc: 0.8307 - val_loss: 0.4951 - val_acc: 0.7917
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4693 - acc: 0.8346 - val_loss: 0.4861 - val_acc: 0.8047
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4712 - acc: 0.8372 - val_loss: 0.4932 - val_acc: 0.7995
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4324 - acc: 0.8398 - val_loss: 0.5040 - val_acc: 0.7891
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4497 - acc: 0.8385 - val_loss: 0.5038 - val_acc: 0.7969
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4634 - acc: 0.8372 - val_loss: 0.4955 - val_acc: 0.8021
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 10ms/step - loss: 0.4023 - acc: 0.8581 - val_loss: 0.4816 - val_acc: 0.8021
Epoch 215/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4159 - acc: 0.8451 - val_loss: 0.4776 - val_acc: 0.8021
Epoch 216/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4063 - acc: 0.8529 - val_loss: 0.4959 - val_acc: 0.7969
Epoch 217/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4076 - acc: 0.8490 - val_loss: 0.4920 - val_acc: 0.7995
Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4240 - acc: 0.8438 - val_loss: 0.4805 - val_acc: 0.8021
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4577 - acc: 0.8359 - val_loss: 0.4972 - val_acc: 0.7943
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4067 - acc: 0.8424 - val_loss: 0.4985 - val_acc: 0.7943
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.4517 - acc: 0.8385 - val_loss: 0.4915 - val_acc: 0.7969
Epoch 329/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4426 - acc: 0.8359 - val_loss: 0.4883 - val_acc: 0.7995
Epoch 330/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4432 - acc: 0.8294 - val_loss: 0.4911 - val_acc: 0.7995
Epoch 331/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4319 - acc: 0.8359 - val_loss: 0.4967 - val_acc: 0.7969
Epoch 332/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4429 - acc: 0.8411 - val_loss: 0.4987 - val_acc: 0.7943
Epoch 333/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4218 - acc: 0.8529 - val_loss: 0.4890 - val_acc: 0.8021
Epoch 334/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4244 - acc: 0.8542 - val_loss: 0.4969 - val_acc: 0.7969
Epoch 335/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4260 - acc: 0.8464 - val_loss: 0.4832 - val_acc: 0.8021
Epoch 446/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4508 - acc: 0.8372 - val_loss: 0.4952 - val_acc: 0.7969
Epoch 447/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4097 - acc: 0.8464 - val_loss: 0.4986 - val_acc: 0.7943
Epoch 448/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4392 - acc: 0.8438 - val_loss: 0.4969 - val_acc: 0.7943
Epoch 449/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4414 - acc: 0.8294 - val_loss: 0.4969 - val_acc: 0.7943
Epoch 450/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4305 - acc: 0.8477 - val_loss: 0.4897 - val_acc: 0.7995
Epoch 451/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4092 - acc: 0.8529 - val_loss: 0.4959 - val_acc: 0.7969
Epoch 452/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 501/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4214 - acc: 0.8516 - val_loss: 0.4972 - val_acc: 0.7943
Epoch 502/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4160 - acc: 0.8568 - val_loss: 0.4897 - val_acc: 0.7969
Epoch 503/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4290 - acc: 0.8385 - val_loss: 0.4811 - val_acc: 0.8021
Epoch 504/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4413 - acc: 0.8346 - val_loss: 0.4914 - val_acc: 0.8021
Epoch 505/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4081 - acc: 0.8398 - val_loss: 0.4942 - val_acc: 0.8021
Epoch 506/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4197 - acc: 0.8581 - val_loss: 0.4917 - val_acc: 0.7995
Epoch 507/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4241 - acc: 0.8568 - val_loss: 0.4803 - val_acc: 0.8047
Epoch 508/1000
12/12 [==============================] - 0s 9m

12/12 [==============================] - 0s 9ms/step - loss: 0.4185 - acc: 0.8542 - val_loss: 0.4919 - val_acc: 0.7995
Epoch 563/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4154 - acc: 0.8424 - val_loss: 0.4851 - val_acc: 0.8021
Epoch 564/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4260 - acc: 0.8333 - val_loss: 0.4972 - val_acc: 0.7969
Epoch 565/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4178 - acc: 0.8424 - val_loss: 0.4909 - val_acc: 0.7969

Epoch 00565: loss improved from inf to 0.41783, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_5/weights/Pbest-0-000565-0.417826-0.796875.hdf5
Epoch 566/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4170 - acc: 0.8490 - val_loss: 0.4952 - val_acc: 0.7995
Epoch 567/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4259 - acc: 0.8359 - val_loss: 0.4967 - val_acc: 0.7969
Epoch 568/1000
12/12 [=================

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 2ms/step
0-cairo:	acc: 79.85%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 115ms/step - loss: 1.4405 - acc: 0.5859 - val_loss: 1.1243 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.1707 - acc: 0.6354 - val_loss: 1.0447 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0672 - acc: 0.6393 - val_loss: 0.9541 - val_acc: 0.6354
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0114 - acc: 0.6536 - val_loss: 0.8949 - val_acc: 0.6823
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9843 - acc: 0.6628 - val_loss: 0.8503 - val_acc: 0.6849
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9278 - acc: 0.6667 - val_loss: 0.8157 - val_acc: 0.6823
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9273 - acc: 0.6654 - val_loss: 0.7943 - val_acc: 0.6927
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - loss

12/12 [==============================] - 0s 9ms/step - loss: 0.5088 - acc: 0.8021 - val_loss: 0.4633 - val_acc: 0.8307
Epoch 114/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5178 - acc: 0.7943 - val_loss: 0.4731 - val_acc: 0.8281
Epoch 115/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5040 - acc: 0.8112 - val_loss: 0.4765 - val_acc: 0.8099
Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5057 - acc: 0.8138 - val_loss: 0.4719 - val_acc: 0.8177
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5332 - acc: 0.8151 - val_loss: 0.4739 - val_acc: 0.8151
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5084 - acc: 0.8164 - val_loss: 0.4758 - val_acc: 0.8177
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5235 - acc: 0.8086 - val_loss: 0.4722 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 173/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4888 - acc: 0.8034 - val_loss: 0.4588 - val_acc: 0.8281

Epoch 00173: loss improved from 0.49490 to 0.48881, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_5/weights/Pbest-1-000173-0.488808-0.828125.hdf5
Epoch 174/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4930 - acc: 0.8047 - val_loss: 0.4556 - val_acc: 0.8151
Epoch 175/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4982 - acc: 0.8047 - val_loss: 0.4603 - val_acc: 0.8281
Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5050 - acc: 0.8216 - val_loss: 0.4498 - val_acc: 0.8333

Epoch 00176: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4730 - acc: 0.8307 - val_loss: 0.4618 - val_acc: 0.8255

Epoch 00177: loss improved from 0.48881 to 0.47299, saving model to ../d

12/12 [==============================] - 0s 9ms/step - loss: 0.4774 - acc: 0.8229 - val_loss: 0.4558 - val_acc: 0.8281

Epoch 00285: loss improved from 0.48116 to 0.47741, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_5/weights/Pbest-1-000285-0.477407-0.828125.hdf5
Epoch 286/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4649 - acc: 0.8164 - val_loss: 0.4610 - val_acc: 0.8255
Epoch 287/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4972 - acc: 0.8190 - val_loss: 0.4565 - val_acc: 0.8281
Epoch 288/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4899 - acc: 0.8099 - val_loss: 0.4514 - val_acc: 0.8307
Epoch 289/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4920 - acc: 0.8138 - val_loss: 0.4481 - val_acc: 0.8333
Epoch 290/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4721 - acc: 0.8203 - val_loss: 0.4652 - val_acc: 0.8255
Epoch 291/1000
12/12 [=============

Epoch 344/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4798 - acc: 0.8086 - val_loss: 0.4646 - val_acc: 0.8229
Epoch 345/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4895 - acc: 0.8164 - val_loss: 0.4476 - val_acc: 0.8333
Epoch 346/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5030 - acc: 0.8138 - val_loss: 0.4285 - val_acc: 0.8333
Epoch 347/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4941 - acc: 0.8138 - val_loss: 0.4536 - val_acc: 0.8255
Epoch 348/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4756 - acc: 0.8190 - val_loss: 0.4675 - val_acc: 0.8229
Epoch 349/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4717 - acc: 0.8138 - val_loss: 0.4632 - val_acc: 0.8255
Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4816 - acc: 0.8177 - val_loss: 0.4586 - val_acc: 0.8281
Epoch 351/1000
12/12 [==============================] - 0s 9m

12/12 [==============================] - 0s 9ms/step - loss: 0.5021 - acc: 0.8177 - val_loss: 0.4655 - val_acc: 0.8229
Epoch 459/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4682 - acc: 0.8190 - val_loss: 0.4597 - val_acc: 0.8281
Epoch 460/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4783 - acc: 0.8151 - val_loss: 0.4523 - val_acc: 0.8307
Epoch 461/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4824 - acc: 0.8060 - val_loss: 0.4660 - val_acc: 0.8255
Epoch 462/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4754 - acc: 0.8125 - val_loss: 0.4648 - val_acc: 0.8229
Epoch 463/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4842 - acc: 0.8216 - val_loss: 0.4613 - val_acc: 0.8255
Epoch 464/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4889 - acc: 0.8151 - val_loss: 0.4618 - val_acc: 0.8255
Epoch 465/1000
12/12 [==============================] - 0s 9ms/step - loss: 

Epoch 517/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4939 - acc: 0.8060 - val_loss: 0.4519 - val_acc: 0.8307
Epoch 518/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4698 - acc: 0.8242 - val_loss: 0.4630 - val_acc: 0.8255
Epoch 519/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4884 - acc: 0.8281 - val_loss: 0.4513 - val_acc: 0.8281
Epoch 520/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4885 - acc: 0.8177 - val_loss: 0.4609 - val_acc: 0.8281
Epoch 521/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4698 - acc: 0.8060 - val_loss: 0.4619 - val_acc: 0.8255
Epoch 522/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4941 - acc: 0.8151 - val_loss: 0.4588 - val_acc: 0.8281
Epoch 523/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4849 - acc: 0.8099 - val_loss: 0.4615 - val_acc: 0.8255
Epoch 524/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.5051 - acc: 0.8008 - val_loss: 0.4662 - val_acc: 0.8177
Epoch 636/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5086 - acc: 0.8138 - val_loss: 0.4557 - val_acc: 0.8229
Epoch 637/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4930 - acc: 0.8060 - val_loss: 0.4624 - val_acc: 0.8203
Epoch 638/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4524 - acc: 0.8411 - val_loss: 0.4595 - val_acc: 0.8255
Epoch 639/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4756 - acc: 0.8177 - val_loss: 0.4608 - val_acc: 0.8203
Epoch 640/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4752 - acc: 0.8151 - val_loss: 0.4649 - val_acc: 0.8177
Epoch 641/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4759 - acc: 0.8242 - val_loss: 0.4601 - val_acc: 0.8229
Epoch 642/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
1-cairo:	acc: 82.10%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 120ms/step - loss: 1.4517 - acc: 0.5260 - val_loss: 1.1185 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.1488 - acc: 0.6380 - val_loss: 1.0422 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0661 - acc: 0.6393 - val_loss: 0.9981 - val_acc: 0.6328
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0368 - acc: 0.6419 - val_loss: 0.9629 - val_acc: 0.6276
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9975 - acc: 0.6380 - val_loss: 0.9218 - val_acc: 0.6354
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9599 - acc: 0.6432 - val_loss: 0.8929 - val_acc: 0.6328
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9258 - acc: 0.6497 - val_loss: 0.8660 - val_acc: 0.6406
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - l

12/12 [==============================] - 0s 9ms/step - loss: 0.5197 - acc: 0.8047 - val_loss: 0.5118 - val_acc: 0.8047
Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5054 - acc: 0.8125 - val_loss: 0.5169 - val_acc: 0.8021
Epoch 117/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5326 - acc: 0.7904 - val_loss: 0.5128 - val_acc: 0.8099
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5390 - acc: 0.7891 - val_loss: 0.5073 - val_acc: 0.8047
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5298 - acc: 0.7943 - val_loss: 0.5039 - val_acc: 0.8151
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5155 - acc: 0.8034 - val_loss: 0.5112 - val_acc: 0.8073
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4984 - acc: 0.8177 - val_loss: 0.5128 - val_acc: 0.8099
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss

Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4598 - acc: 0.8411 - val_loss: 0.5033 - val_acc: 0.8177
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4890 - acc: 0.8177 - val_loss: 0.4903 - val_acc: 0.8255
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4585 - acc: 0.8112 - val_loss: 0.5019 - val_acc: 0.8177
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4989 - acc: 0.7865 - val_loss: 0.4949 - val_acc: 0.8229
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4719 - acc: 0.8164 - val_loss: 0.4895 - val_acc: 0.8203
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4663 - acc: 0.8203 - val_loss: 0.4934 - val_acc: 0.8229
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4800 - acc: 0.8099 - val_loss: 0.5031 - val_acc: 0.8177
Epoch 239/1000
12/12 [==============================] - 0s 9ms

Epoch 349/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4802 - acc: 0.8073 - val_loss: 0.5003 - val_acc: 0.8229
Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4646 - acc: 0.8294 - val_loss: 0.4901 - val_acc: 0.8255
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4933 - acc: 0.8034 - val_loss: 0.4879 - val_acc: 0.8229
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4732 - acc: 0.8112 - val_loss: 0.4990 - val_acc: 0.8229
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4767 - acc: 0.8177 - val_loss: 0.5014 - val_acc: 0.8203
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4793 - acc: 0.8099 - val_loss: 0.5004 - val_acc: 0.8203
Epoch 355/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4856 - acc: 0.8021 - val_loss: 0.4995 - val_acc: 0.8229
Epoch 356/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
2-cairo:	acc: 82.35%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.52% (+/- 1.20%)
final: current database: cairo 	 81.43% (+/- 1.13%)
CPU times: user 5min 37s, sys: 32.3 s, total: 6min 9s
Wall time: 3min 37s

```

# <a id='constrain_4'>CS_4</a>

In [10]:
%%time
dict_config_cus['distance_int'] = '4'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_46 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_46 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_46 (Conv1D)           (None, 2000, 20)          1300      
_________________________________________________________________
activation_136 (Activation)  (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_46 (Glo (None, 20)                0         
_________________________________________________________________
dense_136 (Dense)            (None, 30)                630       
________________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.4968 - acc: 0.8125 - val_loss: 0.5057 - val_acc: 0.7891
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4758 - acc: 0.8333 - val_loss: 0.4963 - val_acc: 0.7891
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4764 - acc: 0.8281 - val_loss: 0.4999 - val_acc: 0.7917
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4918 - acc: 0.8294 - val_loss: 0.4971 - val_acc: 0.7865
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5048 - acc: 0.8151 - val_loss: 0.4999 - val_acc: 0.7891
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4905 - acc: 0.8112 - val_loss: 0.4987 - val_acc: 0.7943
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5156 - acc: 0.8177 - val_loss: 0.4901 - val_acc: 0.7917
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4881 - acc: 0.8190 - val_loss: 0.4956 - val_acc: 0.7943
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4913 - acc: 0.8268 - val_loss: 0.4834 - val_acc: 0.7943
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4657 - acc: 0.8346 - val_loss: 0.4966 - val_acc: 0.7865
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4783 - acc: 0.8281 - val_loss: 0.4740 - val_acc: 0.7891
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4634 - acc: 0.8255 - val_loss: 0.4813 - val_acc: 0.7943
Epoch 223/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4700 - acc: 0.8307 - val_loss: 0.4951 - val_acc: 0.7891

Epoch 00223: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 224/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4694 - acc: 0.8346 - val_loss: 0.5003 - val_acc: 0.

Epoch 333/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4713 - acc: 0.8411 - val_loss: 0.4962 - val_acc: 0.7917
Epoch 334/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4634 - acc: 0.8177 - val_loss: 0.4915 - val_acc: 0.7943
Epoch 335/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4609 - acc: 0.8307 - val_loss: 0.4895 - val_acc: 0.7943
Epoch 336/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4883 - acc: 0.8255 - val_loss: 0.4902 - val_acc: 0.7943
Epoch 337/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4683 - acc: 0.8268 - val_loss: 0.4889 - val_acc: 0.7969
Epoch 338/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4621 - acc: 0.8333 - val_loss: 0.4964 - val_acc: 0.7891
Epoch 339/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4449 - acc: 0.8346 - val_loss: 0.4912 - val_acc: 0.7917
Epoch 340/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 3ms/step
0-cairo:	acc: 79.34%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 140ms/step - loss: 1.4023 - acc: 0.5911 - val_loss: 1.1271 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.1599 - acc: 0.6341 - val_loss: 1.0266 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0933 - acc: 0.6315 - val_loss: 0.9335 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0145 - acc: 0.6497 - val_loss: 0.8873 - val_acc: 0.6693
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9813 - acc: 0.6523 - val_loss: 0.8466 - val_acc: 0.6849
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9255 - acc: 0.6719 - val_loss: 0.8122 - val_acc: 0.7188
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9315 - acc: 0.6888 - val_loss: 0.8081 - val_acc: 0.7422
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - 

12/12 [==============================] - 0s 10ms/step - loss: 0.5408 - acc: 0.8021 - val_loss: 0.4872 - val_acc: 0.8333
Epoch 115/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5264 - acc: 0.7969 - val_loss: 0.4924 - val_acc: 0.8177
Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5248 - acc: 0.8138 - val_loss: 0.4912 - val_acc: 0.8151
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5432 - acc: 0.8008 - val_loss: 0.4889 - val_acc: 0.8125
Epoch 118/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5501 - acc: 0.7839 - val_loss: 0.4833 - val_acc: 0.8177
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5274 - acc: 0.8021 - val_loss: 0.4860 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5259 - acc: 0.7995 - val_loss: 0.4798 - val_acc: 0.8255
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - lo

12/12 [==============================] - 0s 9ms/step - loss: 0.5035 - acc: 0.8086 - val_loss: 0.4698 - val_acc: 0.8151
Epoch 228/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4969 - acc: 0.8203 - val_loss: 0.4712 - val_acc: 0.8151
Epoch 229/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4821 - acc: 0.8203 - val_loss: 0.4738 - val_acc: 0.8177
Epoch 230/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4590 - acc: 0.8229 - val_loss: 0.4692 - val_acc: 0.8151
Epoch 231/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4831 - acc: 0.8034 - val_loss: 0.4766 - val_acc: 0.8125
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4653 - acc: 0.8281 - val_loss: 0.4666 - val_acc: 0.8151
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5117 - acc: 0.8021 - val_loss: 0.4668 - val_acc: 0.8151
Epoch 234/1000
12/12 [==============================] - 0s 10ms/step - loss

12/12 [==============================] - 0s 10ms/step - loss: 0.4726 - acc: 0.8216 - val_loss: 0.4730 - val_acc: 0.8151
Epoch 284/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4954 - acc: 0.8112 - val_loss: 0.4611 - val_acc: 0.8229
Epoch 285/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4834 - acc: 0.8216 - val_loss: 0.4612 - val_acc: 0.8177
Epoch 286/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4757 - acc: 0.8216 - val_loss: 0.4658 - val_acc: 0.8177
Epoch 287/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4743 - acc: 0.8099 - val_loss: 0.4678 - val_acc: 0.8177
Epoch 288/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4768 - acc: 0.8294 - val_loss: 0.4750 - val_acc: 0.8125
Epoch 289/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4633 - acc: 0.8268 - val_loss: 0.4738 - val_acc: 0.8125

Epoch 00289: loss improved from 0.46487 to 0.46330, saving model to ../d

Epoch 342/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4634 - acc: 0.8346 - val_loss: 0.4677 - val_acc: 0.8151
Epoch 343/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4838 - acc: 0.8255 - val_loss: 0.4705 - val_acc: 0.8151
Epoch 344/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4796 - acc: 0.8216 - val_loss: 0.4720 - val_acc: 0.8151
Epoch 345/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4682 - acc: 0.8281 - val_loss: 0.4625 - val_acc: 0.8151
Epoch 346/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4587 - acc: 0.8203 - val_loss: 0.4696 - val_acc: 0.8177
Epoch 347/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4588 - acc: 0.8307 - val_loss: 0.4621 - val_acc: 0.8177
Epoch 348/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4745 - acc: 0.8242 - val_loss: 0.4733 - val_acc: 0.8125
Epoch 349/1000
12/12 [==============================] - 0

Epoch 399/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4865 - acc: 0.8151 - val_loss: 0.4641 - val_acc: 0.8177
Epoch 400/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4598 - acc: 0.8281 - val_loss: 0.4644 - val_acc: 0.8177

Epoch 00400: saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_5/weights/1-000400-0.459849-0.817708.hdf5
Epoch 401/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4689 - acc: 0.8177 - val_loss: 0.4655 - val_acc: 0.8177
Epoch 402/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5035 - acc: 0.8086 - val_loss: 0.4709 - val_acc: 0.8151
Epoch 403/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4856 - acc: 0.8151 - val_loss: 0.4731 - val_acc: 0.8125
Epoch 404/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4920 - acc: 0.8164 - val_loss: 0.4561 - val_acc: 0.8229
Epoch 405/1000
12/12 [==============================] - 0s 10

Epoch 459/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4648 - acc: 0.8099 - val_loss: 0.4630 - val_acc: 0.8203
Epoch 460/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4626 - acc: 0.8138 - val_loss: 0.4735 - val_acc: 0.8125
Epoch 00460: early stopping
ModelCheckpoint 已经保存到 ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_5/weights/1-final.hdf5
save in: ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_5/log/20220201_2000_64_1_5.csv
time: 0:00:59 s
time: 59.0 s
average 0.059000 s
1 epoch finished
--------------------   best   --------------------
no_activities: 7

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
1-cairo:	acc: 81.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
1-cairo:	acc: 81.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 161ms/step - loss: 1.4924 - acc: 0.5169 - val_loss: 1.1402 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.1699 - acc: 0.6341 - val_loss: 1.0674 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0656 - acc: 0.6562 - val_loss: 0.9821 - val_acc: 0.6693
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0310 - acc: 0.6745 - val_loss: 0.9347 - val_acc: 0.6823
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9706 - acc: 0.6836 - val_loss: 0.8830 - val_acc: 0.6875
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9079 - acc: 0.6940 - val_loss: 0.8455 - val_acc: 0.7083
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8842 - acc: 0.7070 - val_loss: 0.8181 - val_acc: 0.7344
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - 

Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4800 - acc: 0.8359 - val_loss: 0.5083 - val_acc: 0.8307
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4811 - acc: 0.8255 - val_loss: 0.5207 - val_acc: 0.8307
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4957 - acc: 0.8255 - val_loss: 0.5210 - val_acc: 0.8307
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4858 - acc: 0.8294 - val_loss: 0.5322 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4758 - acc: 0.8359 - val_loss: 0.4987 - val_acc: 0.8307
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4578 - acc: 0.8398 - val_loss: 0.5301 - val_acc: 0.8255
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4683 - acc: 0.8490 - val_loss: 0.5252 - val_acc: 0.8281
Epoch 123/1000
12/12 [==============================] - 0s 10

Epoch 174/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4489 - acc: 0.8451 - val_loss: 0.5100 - val_acc: 0.8255
Epoch 175/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4635 - acc: 0.8411 - val_loss: 0.5152 - val_acc: 0.8255
Epoch 176/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4643 - acc: 0.8346 - val_loss: 0.5268 - val_acc: 0.8229
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4582 - acc: 0.8320 - val_loss: 0.5241 - val_acc: 0.8255
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4591 - acc: 0.8307 - val_loss: 0.5263 - val_acc: 0.8203
Epoch 179/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4579 - acc: 0.8398 - val_loss: 0.5243 - val_acc: 0.8229
Epoch 180/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4436 - acc: 0.8451 - val_loss: 0.5230 - val_acc: 0.8203
Epoch 181/1000
12/12 [==============================] - 0s

Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4248 - acc: 0.8477 - val_loss: 0.5083 - val_acc: 0.8281

Epoch 00233: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 234/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4358 - acc: 0.8385 - val_loss: 0.5052 - val_acc: 0.8307
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4522 - acc: 0.8516 - val_loss: 0.5114 - val_acc: 0.8281
Epoch 236/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4352 - acc: 0.8477 - val_loss: 0.5195 - val_acc: 0.8255
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4448 - acc: 0.8503 - val_loss: 0.5171 - val_acc: 0.8281
Epoch 238/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4294 - acc: 0.8490 - val_loss: 0.5144 - val_acc: 0.8281
Epoch 239/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4213 - acc: 0.8555 - val_loss: 0.5197 - val_acc:

Epoch 349/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4370 - acc: 0.8464 - val_loss: 0.5176 - val_acc: 0.8255
Epoch 350/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4587 - acc: 0.8398 - val_loss: 0.5206 - val_acc: 0.8229
Epoch 351/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4329 - acc: 0.8359 - val_loss: 0.5195 - val_acc: 0.8255
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4438 - acc: 0.8451 - val_loss: 0.5233 - val_acc: 0.8229
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4280 - acc: 0.8594 - val_loss: 0.5020 - val_acc: 0.8281
Epoch 354/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4390 - acc: 0.8398 - val_loss: 0.5182 - val_acc: 0.8281
Epoch 355/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4315 - acc: 0.8516 - val_loss: 0.5221 - val_acc: 0.8229
Epoch 356/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4358 - acc: 0.8477 - val_loss: 0.5169 - val_acc: 0.8255
Epoch 467/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4473 - acc: 0.8516 - val_loss: 0.5213 - val_acc: 0.8229
Epoch 468/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4286 - acc: 0.8477 - val_loss: 0.5137 - val_acc: 0.8281
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4370 - acc: 0.8464 - val_loss: 0.5230 - val_acc: 0.8229
Epoch 470/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4318 - acc: 0.8542 - val_loss: 0.5089 - val_acc: 0.8307
Epoch 471/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4434 - acc: 0.8411 - val_loss: 0.5200 - val_acc: 0.8229
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4452 - acc: 0.8464 - val_loss: 0.5156 - val_acc: 0.8281
Epoch 473/1000
12/12 [==============================] - 0s 10ms/step - lo

Epoch 526/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4426 - acc: 0.8398 - val_loss: 0.5207 - val_acc: 0.8255
Epoch 527/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4299 - acc: 0.8555 - val_loss: 0.5067 - val_acc: 0.8281
Epoch 528/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4631 - acc: 0.8424 - val_loss: 0.5170 - val_acc: 0.8255
Epoch 529/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4369 - acc: 0.8464 - val_loss: 0.5158 - val_acc: 0.8281
Epoch 530/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4614 - acc: 0.8372 - val_loss: 0.5186 - val_acc: 0.8255
Epoch 531/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4203 - acc: 0.8529 - val_loss: 0.5154 - val_acc: 0.8281
Epoch 532/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4516 - acc: 0.8438 - val_loss: 0.5182 - val_acc: 0.8255
Epoch 533/1000
12/12 [==============================] - 0s

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 4ms/step
2-cairo:	acc: 82.61%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 81.01% (+/- 1.60%)
final: current database: cairo 	 81.18% (+/- 1.37%)
CPU times: user 5min 15s, sys: 28.6 s, total: 5min 43s
Wall time: 3min 28s

```

# <a id='constrain_5'>CS_5</a>

In [11]:
%%time
dict_config_cus['distance_int'] = '5'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_5
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_55 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_55 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_55 (Conv1D)           (None, 2000, 20)          1300      
_________________________________________________________________
activation_163 (Activation)  (None, 2000, 20)          0         
_________________________________________________________________
global_max_pooling1d_55 (Glo (None, 20)                0         
_________________________________________________________________
dense_163 (Dense)            (None, 30)                630       
________________________________________

Epoch 105/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5126 - acc: 0.8086 - val_loss: 0.6505 - val_acc: 0.7630
Epoch 106/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4871 - acc: 0.8164 - val_loss: 0.6247 - val_acc: 0.7682
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5235 - acc: 0.8021 - val_loss: 0.6356 - val_acc: 0.7682
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5083 - acc: 0.8086 - val_loss: 0.6439 - val_acc: 0.7760
Epoch 109/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5249 - acc: 0.7969 - val_loss: 0.6474 - val_acc: 0.7760
Epoch 110/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4902 - acc: 0.8047 - val_loss: 0.6417 - val_acc: 0.7839
Epoch 111/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5119 - acc: 0.8190 - val_loss: 0.6492 - val_acc: 0.7708
Epoch 112/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 10ms/step - loss: 0.4602 - acc: 0.8268 - val_loss: 0.6474 - val_acc: 0.7760
Epoch 218/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4788 - acc: 0.8151 - val_loss: 0.6436 - val_acc: 0.7812
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4949 - acc: 0.8151 - val_loss: 0.6368 - val_acc: 0.7812
Epoch 220/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5052 - acc: 0.8086 - val_loss: 0.6426 - val_acc: 0.7786
Epoch 221/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4688 - acc: 0.8229 - val_loss: 0.6346 - val_acc: 0.7839
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4976 - acc: 0.8229 - val_loss: 0.6306 - val_acc: 0.7839
Epoch 223/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4699 - acc: 0.8294 - val_loss: 0.6416 - val_acc: 0.7786
Epoch 224/1000
12/12 [==============================] - 0s 10ms/step - lo

12/12 [==============================] - 0s 10ms/step - loss: 0.4694 - acc: 0.8242 - val_loss: 0.6354 - val_acc: 0.7786
Epoch 333/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4796 - acc: 0.8099 - val_loss: 0.6407 - val_acc: 0.7812
Epoch 334/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4850 - acc: 0.8203 - val_loss: 0.6333 - val_acc: 0.7812
Epoch 335/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4999 - acc: 0.8151 - val_loss: 0.6365 - val_acc: 0.7812
Epoch 336/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5011 - acc: 0.8164 - val_loss: 0.6407 - val_acc: 0.7786
Epoch 337/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4932 - acc: 0.8151 - val_loss: 0.6434 - val_acc: 0.7786
Epoch 338/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5076 - acc: 0.8047 - val_loss: 0.6352 - val_acc: 0.7839
Epoch 339/1000
12/12 [==============================] - 0s 10ms/step -

Epoch 390/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4825 - acc: 0.8190 - val_loss: 0.6386 - val_acc: 0.7812
Epoch 391/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4721 - acc: 0.8164 - val_loss: 0.6353 - val_acc: 0.7812
Epoch 392/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4847 - acc: 0.8112 - val_loss: 0.6325 - val_acc: 0.7865
Epoch 393/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5028 - acc: 0.8216 - val_loss: 0.6075 - val_acc: 0.7839
Epoch 394/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4717 - acc: 0.8255 - val_loss: 0.6202 - val_acc: 0.7865
Epoch 395/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4824 - acc: 0.8112 - val_loss: 0.6251 - val_acc: 0.7839
Epoch 396/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4798 - acc: 0.8203 - val_loss: 0.6417 - val_acc: 0.7786
Epoch 397/1000
12/12 [==============================] - 0s

Epoch 450/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4678 - acc: 0.8307 - val_loss: 0.6470 - val_acc: 0.7760
Epoch 451/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4913 - acc: 0.8125 - val_loss: 0.6298 - val_acc: 0.7839
Epoch 452/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4717 - acc: 0.8255 - val_loss: 0.6441 - val_acc: 0.7786
Epoch 453/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4763 - acc: 0.8346 - val_loss: 0.6316 - val_acc: 0.7812
Epoch 454/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4779 - acc: 0.8216 - val_loss: 0.6402 - val_acc: 0.7812
Epoch 455/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4758 - acc: 0.8112 - val_loss: 0.6412 - val_acc: 0.7786
Epoch 456/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4916 - acc: 0.8268 - val_loss: 0.6389 - val_acc: 0.7812
Epoch 457/1000
12/12 [==============================] -

Epoch 568/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4741 - acc: 0.8216 - val_loss: 0.6416 - val_acc: 0.7786
Epoch 569/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4841 - acc: 0.8268 - val_loss: 0.6323 - val_acc: 0.7839
Epoch 570/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4906 - acc: 0.8112 - val_loss: 0.6347 - val_acc: 0.7812
Epoch 571/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4914 - acc: 0.8151 - val_loss: 0.6231 - val_acc: 0.7865
Epoch 572/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4784 - acc: 0.8177 - val_loss: 0.6263 - val_acc: 0.7812
Epoch 573/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4863 - acc: 0.8164 - val_loss: 0.6433 - val_acc: 0.7786
Epoch 574/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5007 - acc: 0.8086 - val_loss: 0.6408 - val_acc: 0.7812
Epoch 575/1000
12/12 [==============================] - 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 2s 4ms/step
0-cairo:	acc: 78.06%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 182ms/step - loss: 1.5111 - acc: 0.5495 - val_loss: 1.2435 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.2373 - acc: 0.6354 - val_loss: 1.1135 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.1292 - acc: 0.6471 - val_loss: 1.0205 - val_acc: 0.6380
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0597 - acc: 0.6589 - val_loss: 0.9648 - val_acc: 0.6719
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9974 - acc: 0.6693 - val_loss: 0.8938 - val_acc: 0.6771
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9551 - acc: 0.6693 - val_loss: 0.8503 - val_acc: 0.7031
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8991 - acc: 0.6914 - val_loss: 0.8225 - val_acc: 0.6979
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - 

12/12 [==============================] - 0s 10ms/step - loss: 0.4866 - acc: 0.8138 - val_loss: 0.4914 - val_acc: 0.8073
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5099 - acc: 0.8164 - val_loss: 0.4967 - val_acc: 0.8151
Epoch 120/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4985 - acc: 0.8229 - val_loss: 0.4931 - val_acc: 0.8125
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5047 - acc: 0.8112 - val_loss: 0.4926 - val_acc: 0.8099
Epoch 122/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4956 - acc: 0.8086 - val_loss: 0.4817 - val_acc: 0.8151
Epoch 123/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5127 - acc: 0.8060 - val_loss: 0.4952 - val_acc: 0.8151
Epoch 124/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5104 - acc: 0.7995 - val_loss: 0.4966 - val_acc: 0.8073
Epoch 125/1000
12/12 [==============================] - 0s 10ms/step -

12/12 [==============================] - 0s 10ms/step - loss: 0.4698 - acc: 0.8112 - val_loss: 0.4901 - val_acc: 0.8047
Epoch 231/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4692 - acc: 0.8268 - val_loss: 0.4886 - val_acc: 0.8073
Epoch 232/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4706 - acc: 0.7995 - val_loss: 0.4860 - val_acc: 0.8099
Epoch 233/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4667 - acc: 0.8216 - val_loss: 0.4899 - val_acc: 0.8073
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4543 - acc: 0.8164 - val_loss: 0.4877 - val_acc: 0.8073
Epoch 235/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4876 - acc: 0.8034 - val_loss: 0.4909 - val_acc: 0.8073
Epoch 236/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4842 - acc: 0.8034 - val_loss: 0.4883 - val_acc: 0.8073
Epoch 237/1000
12/12 [==============================] - 0s 10ms/step - 

12/12 [==============================] - 0s 10ms/step - loss: 0.4543 - acc: 0.8164 - val_loss: 0.4695 - val_acc: 0.8125
Epoch 288/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4791 - acc: 0.8229 - val_loss: 0.4882 - val_acc: 0.8047
Epoch 289/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4621 - acc: 0.8268 - val_loss: 0.4793 - val_acc: 0.8125

Epoch 00289: loss improved from 0.47013 to 0.46212, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_5/weights/Pbest-1-000289-0.462124-0.812500.hdf5
Epoch 290/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4744 - acc: 0.8164 - val_loss: 0.4847 - val_acc: 0.8099
Epoch 291/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4726 - acc: 0.8216 - val_loss: 0.4930 - val_acc: 0.8047
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4779 - acc: 0.8190 - val_loss: 0.4876 - val_acc: 0.8073
Epoch 293/1000
12/12 [=========

Epoch 401/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4574 - acc: 0.8255 - val_loss: 0.4870 - val_acc: 0.8125
Epoch 402/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4667 - acc: 0.8268 - val_loss: 0.4853 - val_acc: 0.8125
Epoch 403/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4834 - acc: 0.8320 - val_loss: 0.4869 - val_acc: 0.8125
Epoch 404/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4498 - acc: 0.8229 - val_loss: 0.4805 - val_acc: 0.8125
Epoch 405/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4734 - acc: 0.8073 - val_loss: 0.4849 - val_acc: 0.8125
Epoch 406/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4738 - acc: 0.8229 - val_loss: 0.4853 - val_acc: 0.8125
Epoch 407/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4824 - acc: 0.8047 - val_loss: 0.4846 - val_acc: 0.8125
Epoch 408/1000
12/12 [==============================] - 0

Epoch 462/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4515 - acc: 0.8281 - val_loss: 0.4847 - val_acc: 0.8125
Epoch 463/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4707 - acc: 0.8177 - val_loss: 0.4873 - val_acc: 0.8099
Epoch 464/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4765 - acc: 0.8177 - val_loss: 0.4871 - val_acc: 0.8099
Epoch 465/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4735 - acc: 0.8255 - val_loss: 0.4798 - val_acc: 0.8125

Epoch 00465: loss improved from inf to 0.47348, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_5/weights/Pbest-1-000465-0.473480-0.812500.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4773 - acc: 0.8112 - val_loss: 0.4816 - val_acc: 0.8099
Epoch 467/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4602 - acc: 0.8294 - val_loss: 0.4823 - val_acc: 0.8151
Epoch 468/1000
12/12

12/12 [==============================] - 0s 10ms/step - loss: 0.4691 - acc: 0.8216 - val_loss: 0.4878 - val_acc: 0.8099
Epoch 578/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4630 - acc: 0.8203 - val_loss: 0.4857 - val_acc: 0.8099
Epoch 579/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4629 - acc: 0.8190 - val_loss: 0.4890 - val_acc: 0.8073
Epoch 580/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4700 - acc: 0.8151 - val_loss: 0.4880 - val_acc: 0.8099
Epoch 581/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4837 - acc: 0.8190 - val_loss: 0.4780 - val_acc: 0.8151
Epoch 582/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4733 - acc: 0.8177 - val_loss: 0.4904 - val_acc: 0.8073
Epoch 583/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4562 - acc: 0.8216 - val_loss: 0.4887 - val_acc: 0.8073
Epoch 584/1000
12/12 [==============================] - 0s 10ms/step - 

12/12 [==============================] - 0s 10ms/step - loss: 0.4674 - acc: 0.8190 - val_loss: 0.4874 - val_acc: 0.8099
Epoch 695/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4599 - acc: 0.8164 - val_loss: 0.4893 - val_acc: 0.8099
Epoch 696/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4837 - acc: 0.8229 - val_loss: 0.4885 - val_acc: 0.8099
Epoch 697/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4617 - acc: 0.8164 - val_loss: 0.4870 - val_acc: 0.8099
Epoch 698/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4351 - acc: 0.8294 - val_loss: 0.4831 - val_acc: 0.8125
Epoch 699/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4903 - acc: 0.8060 - val_loss: 0.4919 - val_acc: 0.8073
Epoch 700/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4821 - acc: 0.8190 - val_loss: 0.4906 - val_acc: 0.8099

Epoch 00700: saving model to ../datasets/casas/results/WCNNR/cairo/5/2

Epoch 754/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4553 - acc: 0.8203 - val_loss: 0.4907 - val_acc: 0.8099
Epoch 755/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4797 - acc: 0.8216 - val_loss: 0.4898 - val_acc: 0.8099
Epoch 756/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4621 - acc: 0.8177 - val_loss: 0.4842 - val_acc: 0.8099
Epoch 757/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4681 - acc: 0.8164 - val_loss: 0.4915 - val_acc: 0.8073
Epoch 758/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4781 - acc: 0.8190 - val_loss: 0.4811 - val_acc: 0.8125
Epoch 759/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4913 - acc: 0.8164 - val_loss: 0.4929 - val_acc: 0.8073
Epoch 760/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4514 - acc: 0.8307 - val_loss: 0.4760 - val_acc: 0.8125
Epoch 761/1000
12/12 [==============================] - 0

Epoch 810/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4669 - acc: 0.8281 - val_loss: 0.4846 - val_acc: 0.8099
Epoch 811/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4481 - acc: 0.8242 - val_loss: 0.4929 - val_acc: 0.8073
Epoch 812/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4702 - acc: 0.8164 - val_loss: 0.4770 - val_acc: 0.8177
Epoch 813/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4720 - acc: 0.8073 - val_loss: 0.4831 - val_acc: 0.8125
Epoch 814/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4815 - acc: 0.8125 - val_loss: 0.4867 - val_acc: 0.8099
Epoch 815/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4861 - acc: 0.8073 - val_loss: 0.4901 - val_acc: 0.8099
Epoch 816/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4916 - acc: 0.8216 - val_loss: 0.4848 - val_acc: 0.8125
Epoch 817/1000
12/12 [==============================] - 

12/12 [==============================] - 0s 10ms/step - loss: 0.4629 - acc: 0.8086 - val_loss: 0.4921 - val_acc: 0.8073
Epoch 928/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4836 - acc: 0.8073 - val_loss: 0.4867 - val_acc: 0.8125
Epoch 929/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4597 - acc: 0.8190 - val_loss: 0.4895 - val_acc: 0.8099
Epoch 930/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4789 - acc: 0.8229 - val_loss: 0.4845 - val_acc: 0.8099
Epoch 931/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4829 - acc: 0.8164 - val_loss: 0.4871 - val_acc: 0.8125
Epoch 932/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4741 - acc: 0.8190 - val_loss: 0.4843 - val_acc: 0.8099
Epoch 933/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4950 - acc: 0.8177 - val_loss: 0.4803 - val_acc: 0.8125
Epoch 934/1000
12/12 [==============================] - 0s 9ms/step - 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 5ms/step
1-cairo:	acc: 81.07%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 193ms/step - loss: 1.3222 - acc: 0.6276 - val_loss: 1.0892 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0815 - acc: 0.6432 - val_loss: 0.9760 - val_acc: 0.6458
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0131 - acc: 0.6549 - val_loss: 0.9128 - val_acc: 0.6667
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9742 - acc: 0.6706 - val_loss: 0.8815 - val_acc: 0.6849
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9179 - acc: 0.6719 - val_loss: 0.8503 - val_acc: 0.7240
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8992 - acc: 0.6810 - val_loss: 0.8210 - val_acc: 0.7344
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8824 - acc: 0.6862 - val_loss: 0.8021 - val_acc: 0.7370
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - 

12/12 [==============================] - 0s 10ms/step - loss: 0.5444 - acc: 0.7969 - val_loss: 0.5774 - val_acc: 0.7995
Epoch 116/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5299 - acc: 0.7995 - val_loss: 0.5755 - val_acc: 0.7995
Epoch 117/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5246 - acc: 0.8073 - val_loss: 0.5701 - val_acc: 0.7943
Epoch 118/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5447 - acc: 0.8047 - val_loss: 0.5722 - val_acc: 0.7943
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5434 - acc: 0.7995 - val_loss: 0.5768 - val_acc: 0.7943
Epoch 120/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5509 - acc: 0.7969 - val_loss: 0.5722 - val_acc: 0.7995
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5406 - acc: 0.7969 - val_loss: 0.5800 - val_acc: 0.7943
Epoch 122/1000
12/12 [==============================] - 0s 10ms/step -

Epoch 229/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5335 - acc: 0.8034 - val_loss: 0.5725 - val_acc: 0.8021
Epoch 230/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5308 - acc: 0.8034 - val_loss: 0.5708 - val_acc: 0.8047
Epoch 231/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5281 - acc: 0.7930 - val_loss: 0.5727 - val_acc: 0.8021
Epoch 232/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5378 - acc: 0.7852 - val_loss: 0.5744 - val_acc: 0.8021
Epoch 233/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5668 - acc: 0.7891 - val_loss: 0.5665 - val_acc: 0.8021
Epoch 234/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5334 - acc: 0.7995 - val_loss: 0.5666 - val_acc: 0.8073
Epoch 235/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5440 - acc: 0.7943 - val_loss: 0.5652 - val_acc: 0.8073
Epoch 236/1000
12/12 [==============================] -

Epoch 347/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5601 - acc: 0.8138 - val_loss: 0.5580 - val_acc: 0.8073
Epoch 348/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5360 - acc: 0.8021 - val_loss: 0.5727 - val_acc: 0.7995
Epoch 349/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5333 - acc: 0.8112 - val_loss: 0.5584 - val_acc: 0.8073
Epoch 350/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5453 - acc: 0.8008 - val_loss: 0.5555 - val_acc: 0.8047
Epoch 351/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5284 - acc: 0.7982 - val_loss: 0.5573 - val_acc: 0.8021
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5245 - acc: 0.7917 - val_loss: 0.5744 - val_acc: 0.7995
Epoch 353/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5426 - acc: 0.8021 - val_loss: 0.5419 - val_acc: 0.8073
Epoch 354/1000
12/12 [==============================] -

Epoch 403/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5578 - acc: 0.7904 - val_loss: 0.5657 - val_acc: 0.8047
Epoch 404/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5388 - acc: 0.8086 - val_loss: 0.5562 - val_acc: 0.8073
Epoch 405/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5188 - acc: 0.8034 - val_loss: 0.5665 - val_acc: 0.8021
Epoch 406/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5351 - acc: 0.7982 - val_loss: 0.5732 - val_acc: 0.7995
Epoch 407/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5336 - acc: 0.8008 - val_loss: 0.5666 - val_acc: 0.8047
Epoch 408/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5288 - acc: 0.8047 - val_loss: 0.5604 - val_acc: 0.8047
Epoch 409/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5583 - acc: 0.7773 - val_loss: 0.5730 - val_acc: 0.8021
Epoch 410/1000
12/12 [==============================] -

Epoch 464/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5509 - acc: 0.7891 - val_loss: 0.5662 - val_acc: 0.8047
Epoch 465/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5341 - acc: 0.7943 - val_loss: 0.5728 - val_acc: 0.7995

Epoch 00465: loss improved from inf to 0.53412, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_5/weights/Pbest-2-000465-0.534115-0.799479.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5485 - acc: 0.7930 - val_loss: 0.5679 - val_acc: 0.8021
Epoch 467/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5468 - acc: 0.7943 - val_loss: 0.5661 - val_acc: 0.8047
Epoch 468/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5411 - acc: 0.8060 - val_loss: 0.5654 - val_acc: 0.8047
Epoch 469/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5226 - acc: 0.7956 - val_loss: 0.5558 - val_acc: 0.8099

Epoch 00469: loss 

Epoch 520/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5508 - acc: 0.7891 - val_loss: 0.5677 - val_acc: 0.8021
Epoch 521/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5566 - acc: 0.7839 - val_loss: 0.5580 - val_acc: 0.8073
Epoch 522/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5588 - acc: 0.7786 - val_loss: 0.5697 - val_acc: 0.8021
Epoch 523/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5316 - acc: 0.7995 - val_loss: 0.5712 - val_acc: 0.7995
Epoch 524/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5411 - acc: 0.7969 - val_loss: 0.5704 - val_acc: 0.7995
Epoch 525/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5429 - acc: 0.8073 - val_loss: 0.5692 - val_acc: 0.8021
Epoch 526/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.5177 - acc: 0.8099 - val_loss: 0.5728 - val_acc: 0.7995
Epoch 527/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 5ms/step
2-cairo:	acc: 80.31%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 79.81% (+/- 1.28%)
final: current database: cairo 	 79.81% (+/- 1.28%)
CPU times: user 8min 18s, sys: 46.2 s, total: 9min 5s
Wall time: 5min 24s

```