# file name meaning

eg. 100_cairo_WCNN_2000_64_1000_1_8_1_1.ipynb

`[tag]_[dataset_name]_[method_name]_[data_length]_[batch_size]_[epochs]_[kernel_wide_base]_[kernel_number_base]_[net_deep_base]_[calculate_unit]`

In [1]:
from tools import general
import os
from tools.configure.constants import DATASETS_CONSTANT, METHOD_PARAMETER_TEMPLATE, JUPYTER_TOKEN
from tools.integration import train_val


nb_name_file = general.ipy_nb_name(JUPYTER_TOKEN["token_lists"])

Using TensorFlow backend.
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/musk/anaconda3/en

In [2]:
theNotebook = nb_name_file.split('_')
assert len(theNotebook) == 9 or len(theNotebook) == 10, 'The number of parameters should be 9 / 10'

global title_param
title_param = {
    'num': theNotebook[0],
    'dataset_name': theNotebook[1],
    'method_name': theNotebook[2],
    'data_lenght': int(theNotebook[3]),
    'batch_size': int(theNotebook[4]),
    'nb_epochs': int(theNotebook[5]),
    'kernel_wide_base': int(theNotebook[6]),
    'kernel_number_base': int(theNotebook[7]),
    'net_deep_base': int(theNotebook[8]),
    'calculation_unit': theNotebook[9] if len(theNotebook)==10 else '0',  # If not specified, the CPU is used to train the model
}

# assert title_param['dataset'] in ['cairo', 'milan', 'kyoto7', 'kyoto8', 'kyoto11'], 'Please correct the dataset name！'
# assert title_param['model_name'] in ['WCNN','LSTM'], 'The method is wrong. Please correct it！'
# assert title_param['optimizer'] in ['rms', 'adagrad'], 'The optimizer is wrong. Please correct it！'
# assert title_param['calculation_unit'] in ['0', '1', '2'], 'Error in calculation unit selection, please correct！'

display(title_param)

{'num': '657',
 'dataset_name': 'cairo',
 'method_name': 'WCNNR',
 'data_lenght': 2000,
 'batch_size': 64,
 'nb_epochs': 1000,
 'kernel_wide_base': 1,
 'kernel_number_base': 7,
 'net_deep_base': 1,
 'calculation_unit': '1'}

In [3]:
dict_config_cus = {

        "datasets_dir": DATASETS_CONSTANT["base_dir"],  # 这是公共数据集常量
        "archive_name": DATASETS_CONSTANT["archive_name"],
        "ksplit": DATASETS_CONSTANT["ksplit"],

        'distance_int': None,
    }

dict_config_cus = general.Merge(title_param, dict_config_cus)

from tools.configure.constants import WCNNR_CONSTANT as MODEL_DEFAULT_CONF

dict_config_cus = general.Merge(MODEL_DEFAULT_CONF, dict_config_cus)

In [4]:
import tensorflow as tf

calculation_unit = general.getAvailableId()
os.environ["CUDA_VISIBLE_DEVICES"] = calculation_unit

if calculation_unit != "-1":
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.Session(config=config)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

[origin](#origin)

[C](#constrain)

[CS_1](#constrain_1)

[CS_2](#constrain_2)

[CS_3](#constrain_3)

[CS_4](#constrain_4)

[CS_5](#constrain_5)


# <a id='origin'>origin</a>


In [26]:
%%time
dict_config_cus['distance_int'] = '9999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_190 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_190 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_190 (Conv1D)          (None, 2000, 28)          1820      
_________________________________________________________________
activation_568 (Activation)  (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_190 (Gl (None, 28)                0         
_________________________________________________________________
dense_568 (Dense)            (None, 42)                1218      
_____________________________________

Epoch 99/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4321 - acc: 0.8438 - val_loss: 0.5115 - val_acc: 0.7917
Epoch 100/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4233 - acc: 0.8477 - val_loss: 0.5111 - val_acc: 0.7995

Epoch 00100: saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/0-000100-0.423261-0.799479.hdf5
Epoch 101/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.4186 - acc: 0.8359 - val_loss: 0.5197 - val_acc: 0.7995
Epoch 102/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.4199 - acc: 0.8346 - val_loss: 0.5153 - val_acc: 0.7943
Epoch 103/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4108 - acc: 0.8411 - val_loss: 0.5238 - val_acc: 0.7995
Epoch 104/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4070 - acc: 0.8529 - val_loss: 0.5025 - val_acc: 0.7943
Epoch 105/1000
12/12 [==============================] - 0

Epoch 159/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3779 - acc: 0.8529 - val_loss: 0.5181 - val_acc: 0.7995
Epoch 160/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3744 - acc: 0.8607 - val_loss: 0.5148 - val_acc: 0.8047
Epoch 161/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3591 - acc: 0.8633 - val_loss: 0.5238 - val_acc: 0.7969
Epoch 162/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3700 - acc: 0.8594 - val_loss: 0.5102 - val_acc: 0.8021
Epoch 163/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3836 - acc: 0.8581 - val_loss: 0.5197 - val_acc: 0.7995
Epoch 164/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3849 - acc: 0.8398 - val_loss: 0.5042 - val_acc: 0.7995
Epoch 165/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3884 - acc: 0.8581 - val_loss: 0.5135 - val_acc: 0.8021

Epoch 00165: loss improved from inf to 0.38840, saving

Epoch 209/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3517 - acc: 0.8594 - val_loss: 0.5164 - val_acc: 0.7969
Epoch 210/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3596 - acc: 0.8451 - val_loss: 0.5223 - val_acc: 0.7995
Epoch 211/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3610 - acc: 0.8594 - val_loss: 0.5246 - val_acc: 0.7969
Epoch 212/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3454 - acc: 0.8542 - val_loss: 0.5209 - val_acc: 0.7995
Epoch 213/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3425 - acc: 0.8568 - val_loss: 0.5088 - val_acc: 0.8047
Epoch 214/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3621 - acc: 0.8529 - val_loss: 0.5224 - val_acc: 0.8021
Epoch 215/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3379 - acc: 0.8659 - val_loss: 0.5198 - val_acc: 0.8021
Epoch 216/1000
12/12 [==============================] -

Epoch 268/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3590 - acc: 0.8555 - val_loss: 0.5229 - val_acc: 0.7995
Epoch 269/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3480 - acc: 0.8685 - val_loss: 0.5210 - val_acc: 0.7995

Epoch 00269: loss improved from 0.35969 to 0.34798, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/Pbest-0-000269-0.347984-0.799479.hdf5
Epoch 270/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3480 - acc: 0.8646 - val_loss: 0.5242 - val_acc: 0.7969
Epoch 271/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3463 - acc: 0.8685 - val_loss: 0.5202 - val_acc: 0.8021
Epoch 272/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3526 - acc: 0.8724 - val_loss: 0.5312 - val_acc: 0.7943
Epoch 273/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3528 - acc: 0.8646 - val_loss: 0.5301 - val_acc: 0.7943
Epoch 274/1

12/12 [==============================] - 0s 18ms/step - loss: 0.3428 - acc: 0.8620 - val_loss: 0.4963 - val_acc: 0.8125
Epoch 383/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3531 - acc: 0.8529 - val_loss: 0.5247 - val_acc: 0.8021
Epoch 384/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3615 - acc: 0.8542 - val_loss: 0.5272 - val_acc: 0.8021
Epoch 385/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3477 - acc: 0.8646 - val_loss: 0.5276 - val_acc: 0.7995
Epoch 386/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3553 - acc: 0.8516 - val_loss: 0.5065 - val_acc: 0.8047
Epoch 387/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3310 - acc: 0.8672 - val_loss: 0.5124 - val_acc: 0.8047
Epoch 388/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3462 - acc: 0.8646 - val_loss: 0.5280 - val_acc: 0.8021
Epoch 389/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 442/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3442 - acc: 0.8659 - val_loss: 0.5171 - val_acc: 0.8021
Epoch 443/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3440 - acc: 0.8581 - val_loss: 0.5160 - val_acc: 0.8047
Epoch 444/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3590 - acc: 0.8568 - val_loss: 0.5276 - val_acc: 0.7995
Epoch 445/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3431 - acc: 0.8698 - val_loss: 0.5298 - val_acc: 0.7995
Epoch 446/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3471 - acc: 0.8607 - val_loss: 0.5168 - val_acc: 0.8021
Epoch 447/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3439 - acc: 0.8763 - val_loss: 0.5264 - val_acc: 0.8021
Epoch 448/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3448 - acc: 0.8659 - val_loss: 0.5236 - val_acc: 0.8047
Epoch 449/1000
12/12 [==============================] -

Epoch 499/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3647 - acc: 0.8490 - val_loss: 0.5040 - val_acc: 0.8073
Epoch 500/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3697 - acc: 0.8503 - val_loss: 0.5249 - val_acc: 0.8047

Epoch 00500: saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/0-000500-0.369727-0.804688.hdf5
Epoch 501/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3553 - acc: 0.8581 - val_loss: 0.5155 - val_acc: 0.8047
Epoch 502/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3500 - acc: 0.8594 - val_loss: 0.5104 - val_acc: 0.8073
Epoch 503/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3608 - acc: 0.8685 - val_loss: 0.5074 - val_acc: 0.8047
Epoch 504/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3398 - acc: 0.8698 - val_loss: 0.5175 - val_acc: 0.8021
Epoch 505/1000
12/12 [==============================] - 

Epoch 559/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3497 - acc: 0.8594 - val_loss: 0.5148 - val_acc: 0.8021
Epoch 560/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3362 - acc: 0.8594 - val_loss: 0.5215 - val_acc: 0.8021
Epoch 561/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3468 - acc: 0.8646 - val_loss: 0.5022 - val_acc: 0.8099
Epoch 562/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3458 - acc: 0.8594 - val_loss: 0.5255 - val_acc: 0.8021
Epoch 563/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3510 - acc: 0.8594 - val_loss: 0.5226 - val_acc: 0.8021
Epoch 564/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3279 - acc: 0.8646 - val_loss: 0.5122 - val_acc: 0.8047
Epoch 565/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3532 - acc: 0.8737 - val_loss: 0.5165 - val_acc: 0.8021

Epoch 00565: loss improved from inf to 0.35320, saving

Epoch 615/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3433 - acc: 0.8633 - val_loss: 0.5158 - val_acc: 0.8021
Epoch 616/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3501 - acc: 0.8529 - val_loss: 0.5105 - val_acc: 0.8047
Epoch 617/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3403 - acc: 0.8607 - val_loss: 0.5114 - val_acc: 0.8047
Epoch 618/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3558 - acc: 0.8542 - val_loss: 0.5297 - val_acc: 0.7995
Epoch 619/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3271 - acc: 0.8646 - val_loss: 0.5305 - val_acc: 0.7995
Epoch 620/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3536 - acc: 0.8633 - val_loss: 0.5261 - val_acc: 0.8021
Epoch 621/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3341 - acc: 0.8659 - val_loss: 0.5256 - val_acc: 0.8021
Epoch 622/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 9s 23ms/step
0-cairo:	acc: 80.36%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 11s 880ms/step - loss: 1.3707 - acc: 0.6107 - val_loss: 1.0470 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.0780 - acc: 0.6406 - val_loss: 0.9414 - val_acc: 0.6458
Epoch 3/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.9758 - acc: 0.6784 - val_loss: 0.8502 - val_acc: 0.7214
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.9379 - acc: 0.6836 - val_loss: 0.8009 - val_acc: 0.7318
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.8791 - acc: 0.6901 - val_loss: 0.7568 - val_acc: 0.7370
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.8393 - acc: 0.7057 - val_loss: 0.7223 - val_acc: 0.7396
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.8072 - acc: 0.7135 - val_loss: 0.7028 - val_acc: 0.7474
Epoch 8/1000
12/12 [==============================] - 0s 17ms/step 

12/12 [==============================] - 0s 18ms/step - loss: 0.4099 - acc: 0.8424 - val_loss: 0.4773 - val_acc: 0.8047
Epoch 116/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4132 - acc: 0.8451 - val_loss: 0.4735 - val_acc: 0.8099
Epoch 117/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4119 - acc: 0.8464 - val_loss: 0.4734 - val_acc: 0.8047
Epoch 118/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4282 - acc: 0.8216 - val_loss: 0.4794 - val_acc: 0.8073
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4220 - acc: 0.8451 - val_loss: 0.4746 - val_acc: 0.7943
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4318 - acc: 0.8346 - val_loss: 0.4633 - val_acc: 0.7995
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4138 - acc: 0.8438 - val_loss: 0.4728 - val_acc: 0.7995
Epoch 122/1000
12/12 [==============================] - 0s 18ms/step -


Epoch 00173: loss improved from 0.38509 to 0.37835, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/Pbest-1-000173-0.378349-0.796875.hdf5
Epoch 174/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3842 - acc: 0.8555 - val_loss: 0.4793 - val_acc: 0.7995
Epoch 175/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4147 - acc: 0.8451 - val_loss: 0.4830 - val_acc: 0.7995
Epoch 176/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3987 - acc: 0.8372 - val_loss: 0.4845 - val_acc: 0.7995
Epoch 177/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3833 - acc: 0.8568 - val_loss: 0.4847 - val_acc: 0.8021
Epoch 178/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3690 - acc: 0.8516 - val_loss: 0.4870 - val_acc: 0.8021
Epoch 179/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4033 - acc: 0.8542 - val_loss: 0.4742 - val_acc: 0.8073
Epoch 180/1

12/12 [==============================] - 0s 18ms/step - loss: 0.3678 - acc: 0.8477 - val_loss: 0.4838 - val_acc: 0.7943

Epoch 00289: loss improved from 0.38007 to 0.36782, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/Pbest-1-000289-0.367822-0.794271.hdf5
Epoch 290/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3813 - acc: 0.8607 - val_loss: 0.4778 - val_acc: 0.7969
Epoch 291/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3965 - acc: 0.8451 - val_loss: 0.4780 - val_acc: 0.7969
Epoch 292/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4051 - acc: 0.8477 - val_loss: 0.4765 - val_acc: 0.8021
Epoch 293/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3670 - acc: 0.8633 - val_loss: 0.4834 - val_acc: 0.7969

Epoch 00293: loss improved from 0.36782 to 0.36695, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/Pbest-1-000293-0.366

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 9s 24ms/step
1-cairo:	acc: 79.80%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 11s 898ms/step - loss: 1.4743 - acc: 0.5612 - val_loss: 1.1271 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.0758 - acc: 0.6432 - val_loss: 0.9493 - val_acc: 0.6745
Epoch 3/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.9767 - acc: 0.6589 - val_loss: 0.8893 - val_acc: 0.6953
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.9367 - acc: 0.6810 - val_loss: 0.8275 - val_acc: 0.7318
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.8877 - acc: 0.7018 - val_loss: 0.7934 - val_acc: 0.7344
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8525 - acc: 0.7122 - val_loss: 0.7717 - val_acc: 0.7422
Epoch 7/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.7999 - acc: 0.7461 - val_loss: 0.7569 - val_acc: 0.7422
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step 

12/12 [==============================] - 0s 18ms/step - loss: 0.4298 - acc: 0.8385 - val_loss: 0.5356 - val_acc: 0.8229
Epoch 115/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4115 - acc: 0.8477 - val_loss: 0.5131 - val_acc: 0.8307
Epoch 116/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4169 - acc: 0.8411 - val_loss: 0.5220 - val_acc: 0.8281
Epoch 117/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4107 - acc: 0.8320 - val_loss: 0.5342 - val_acc: 0.8333
Epoch 118/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4086 - acc: 0.8451 - val_loss: 0.5302 - val_acc: 0.8333
Epoch 119/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4211 - acc: 0.8242 - val_loss: 0.5335 - val_acc: 0.8255
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4098 - acc: 0.8555 - val_loss: 0.5298 - val_acc: 0.8255
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 173/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3921 - acc: 0.8438 - val_loss: 0.5362 - val_acc: 0.8177
Epoch 174/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3753 - acc: 0.8659 - val_loss: 0.5403 - val_acc: 0.8151
Epoch 175/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3748 - acc: 0.8581 - val_loss: 0.5254 - val_acc: 0.8229
Epoch 176/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4024 - acc: 0.8438 - val_loss: 0.5247 - val_acc: 0.8177
Epoch 177/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3702 - acc: 0.8490 - val_loss: 0.5143 - val_acc: 0.8229

Epoch 00177: loss improved from 0.38083 to 0.37024, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_7/weights/Pbest-2-000177-0.370236-0.822917.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3523 - acc: 0.8594 - val_loss: 0.5392 - val_acc: 0.8203
Epoch 179/1

Epoch 287/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3701 - acc: 0.8594 - val_loss: 0.5415 - val_acc: 0.8151
Epoch 288/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3959 - acc: 0.8451 - val_loss: 0.5323 - val_acc: 0.8203
Epoch 289/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3802 - acc: 0.8464 - val_loss: 0.5274 - val_acc: 0.8229
Epoch 290/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3887 - acc: 0.8490 - val_loss: 0.5370 - val_acc: 0.8177
Epoch 291/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3763 - acc: 0.8503 - val_loss: 0.5350 - val_acc: 0.8177
Epoch 292/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3794 - acc: 0.8438 - val_loss: 0.5391 - val_acc: 0.8151
Epoch 293/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3818 - acc: 0.8477 - val_loss: 0.5194 - val_acc: 0.8229
Epoch 294/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 10s 25ms/step
2-cairo:	acc: 81.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 80.75% (+/- 2.28%)
final: current database: cairo 	 80.92% (+/- 2.17%)
CPU times: user 4min 39s, sys: 30.6 s, total: 5min 10s
Wall time: 3min 1s

best: current database: cairo 	 81.09% (+/- 0.40%)
final: current database: cairo 	 81.18% (+/- 0.51%)
CPU times: user 7min 20s, sys: 33.9 s, total: 7min 54s
Wall time: 5min 17s

best: current database: cairo 	 82.37% (+/- 1.62%)
final: current database: cairo 	 82.28% (+/- 1.68%)
CPU times: user 9min 14s, sys: 28 s, total: 9min 42s
Wall time: 8min 24s

best: current database: cairo 	 81.09% (+/- 0.61%)
final: current database: cairo 	 80.66% (+/- 0.86%)
CPU times: user 9min 27s, sys: 28.1 s, total: 9min 55s
Wall time: 8min 38s
```

# <a id='constrain'>C</a>

In [6]:
%%time
dict_config_cus['distance_int'] = '999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_10 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_10 (Conv1D)           (None, 2000, 28)          1820      
_________________________________________________________________
activation_28 (Activation)   (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_10 (Glo (None, 28)                0         
_________________________________________________________________
dense_28 (Dense)             (None, 42)                1218      
______________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.4062 - acc: 0.8398 - val_loss: 0.5726 - val_acc: 0.8021
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3990 - acc: 0.8516 - val_loss: 0.5646 - val_acc: 0.8021
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3965 - acc: 0.8503 - val_loss: 0.5577 - val_acc: 0.8047
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4077 - acc: 0.8411 - val_loss: 0.5481 - val_acc: 0.8047
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4066 - acc: 0.8503 - val_loss: 0.5749 - val_acc: 0.8073
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3946 - acc: 0.8451 - val_loss: 0.5741 - val_acc: 0.8047
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3982 - acc: 0.8424 - val_loss: 0.5540 - val_acc: 0.8151
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3551 - acc: 0.8672 - val_loss: 0.5867 - val_acc: 0.8073
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3347 - acc: 0.8698 - val_loss: 0.5659 - val_acc: 0.8125
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3287 - acc: 0.8659 - val_loss: 0.5837 - val_acc: 0.8073
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3575 - acc: 0.8555 - val_loss: 0.5925 - val_acc: 0.8073
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3576 - acc: 0.8711 - val_loss: 0.5859 - val_acc: 0.8073
Epoch 223/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3525 - acc: 0.8724 - val_loss: 0.5912 - val_acc: 0.8099
Epoch 224/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3288 - acc: 0.8698 - val_loss: 0.5496 - val_acc: 0.8125
Epoch 225/1000
12/12 [==============================] - 0s 10m

Epoch 276/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3079 - acc: 0.8711 - val_loss: 0.5638 - val_acc: 0.8047
Epoch 277/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3199 - acc: 0.8789 - val_loss: 0.5879 - val_acc: 0.8047

Epoch 00277: loss improved from 0.32784 to 0.31988, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_7/weights/Pbest-0-000277-0.319884-0.804688.hdf5
Epoch 278/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.3142 - acc: 0.8802 - val_loss: 0.5818 - val_acc: 0.8047
Epoch 279/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3423 - acc: 0.8776 - val_loss: 0.5857 - val_acc: 0.8047
Epoch 280/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3402 - acc: 0.8737 - val_loss: 0.5810 - val_acc: 0.8047
Epoch 281/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3391 - acc: 0.8698 - val_loss: 0.5751 - val_acc: 0.8073
Epoch 282/1000
12/

Epoch 333/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3165 - acc: 0.8828 - val_loss: 0.5649 - val_acc: 0.7995
Epoch 334/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3419 - acc: 0.8711 - val_loss: 0.5902 - val_acc: 0.7995

Epoch 00334: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 335/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3282 - acc: 0.8685 - val_loss: 0.5886 - val_acc: 0.7995
Epoch 336/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3180 - acc: 0.8815 - val_loss: 0.5831 - val_acc: 0.7995
Epoch 337/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3354 - acc: 0.8620 - val_loss: 0.5734 - val_acc: 0.8021
Epoch 338/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3351 - acc: 0.8776 - val_loss: 0.5771 - val_acc: 0.7995
Epoch 339/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3241 - acc: 0.8789 - val_loss: 0.5733 - val_acc: 0.7

12/12 [==============================] - 0s 9ms/step - loss: 0.3262 - acc: 0.8750 - val_loss: 0.5962 - val_acc: 0.7943
Epoch 449/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3248 - acc: 0.8750 - val_loss: 0.5878 - val_acc: 0.8021
Epoch 450/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3233 - acc: 0.8828 - val_loss: 0.5800 - val_acc: 0.8021
Epoch 451/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3468 - acc: 0.8698 - val_loss: 0.5889 - val_acc: 0.7969
Epoch 452/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3246 - acc: 0.8763 - val_loss: 0.5771 - val_acc: 0.8047
Epoch 453/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3291 - acc: 0.8750 - val_loss: 0.5940 - val_acc: 0.7969
Epoch 454/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3305 - acc: 0.8854 - val_loss: 0.5865 - val_acc: 0.7969
Epoch 455/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - ETA:  - 0s 509us/step
0-cairo:	acc: 79.85%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Begin training ...
Epoch 1/1000
12/12 [==============================] - 0s 40ms/step - loss: 1.3443 - acc: 0.5911 - val_loss: 1.0461 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.0581 - acc: 0.6380 - val_loss: 0.9072 - val_acc: 0.6667
Epoch 3/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9271 - acc: 0.6706 - val_loss: 0.8247 - val_acc: 0.7005
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8753 - acc: 0.6966 - val_loss: 0.7714 - val_acc: 0.7188
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8383 - acc: 0.7057 - val_loss: 0.7126 - val_acc: 0.7370
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7853 - acc: 0.7266 - val_loss: 0.6957 - val_acc: 0.7656
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7587 - acc: 0.7305 - val_loss: 0.6636 - val_acc: 0.7812
Epoch 8/1000
12/12 [==============================] - 0s

12/12 [==============================] - 0s 9ms/step - loss: 0.4387 - acc: 0.8242 - val_loss: 0.5104 - val_acc: 0.8151
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4338 - acc: 0.8307 - val_loss: 0.5064 - val_acc: 0.8099
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4502 - acc: 0.8281 - val_loss: 0.5154 - val_acc: 0.8151
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4398 - acc: 0.8229 - val_loss: 0.5191 - val_acc: 0.8125
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4468 - acc: 0.8320 - val_loss: 0.5148 - val_acc: 0.8099
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4102 - acc: 0.8451 - val_loss: 0.5130 - val_acc: 0.8151
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4409 - acc: 0.8346 - val_loss: 0.5183 - val_acc: 0.8151
Epoch 125/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 175/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4091 - acc: 0.8372 - val_loss: 0.5152 - val_acc: 0.8099
Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4255 - acc: 0.8333 - val_loss: 0.5088 - val_acc: 0.8125
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4266 - acc: 0.8398 - val_loss: 0.5105 - val_acc: 0.8125
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4138 - acc: 0.8281 - val_loss: 0.5144 - val_acc: 0.8099
Epoch 179/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4391 - acc: 0.8151 - val_loss: 0.5134 - val_acc: 0.8099
Epoch 180/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4149 - acc: 0.8477 - val_loss: 0.5144 - val_acc: 0.8099
Epoch 181/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4270 - acc: 0.8372 - val_loss: 0.5020 - val_acc: 0.8125
Epoch 182/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.4417 - acc: 0.8294 - val_loss: 0.5132 - val_acc: 0.8125
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4281 - acc: 0.8307 - val_loss: 0.5006 - val_acc: 0.8151
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4162 - acc: 0.8333 - val_loss: 0.5053 - val_acc: 0.8151
Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4034 - acc: 0.8451 - val_loss: 0.5053 - val_acc: 0.8151
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4422 - acc: 0.8294 - val_loss: 0.5113 - val_acc: 0.8125
Epoch 297/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4414 - acc: 0.8281 - val_loss: 0.5152 - val_acc: 0.8099
Epoch 298/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4404 - acc: 0.8177 - val_loss: 0.5139 - val_acc: 0.8125
Epoch 299/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4472 - acc: 0.8333 - val_loss: 0.5101 - val_acc: 0.8125
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4264 - acc: 0.8372 - val_loss: 0.5124 - val_acc: 0.8099
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4095 - acc: 0.8451 - val_loss: 0.5137 - val_acc: 0.8125
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4045 - acc: 0.8411 - val_loss: 0.5115 - val_acc: 0.8125
Epoch 412/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4304 - acc: 0.8411 - val_loss: 0.5069 - val_acc: 0.8177
Epoch 413/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4508 - acc: 0.8164 - val_loss: 0.5115 - val_acc: 0.8125
Epoch 414/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4360 - acc: 0.8333 - val_loss: 0.5168 - val_acc: 0.8099
Epoch 415/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4098 - acc: 0.8477 - val_loss: 0.5067 - val_acc: 0.8151
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4085 - acc: 0.8294 - val_loss: 0.5139 - val_acc: 0.8125

Epoch 00469: loss improved from 0.42768 to 0.40849, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_7/weights/Pbest-1-000469-0.408488-0.812500.hdf5
Epoch 470/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.4003 - acc: 0.8385 - val_loss: 0.5017 - val_acc: 0.8177
Epoch 471/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4439 - acc: 0.8203 - val_loss: 0.5108 - val_acc: 0.8125
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4006 - acc: 0.8529 - val_loss: 0.5010 - val_acc: 0.8151
Epoch 473/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4382 - acc: 0.8294 - val_loss: 0.5028 - val_acc: 0.8151
Epoch 474/1000
12/

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 601us/step
1-cairo:	acc: 81.33%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 45ms/step - loss: 1.3356 - acc: 0.6159 - val_loss: 1.0951 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.0832 - acc: 0.6367 - val_loss: 0.9752 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9611 - acc: 0.6549 - val_loss: 0.9048 - val_acc: 0.6875
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8978 - acc: 0.6732 - val_loss: 0.8580 - val_acc: 0.7005
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8556 - acc: 0.7096 - val_loss: 0.8223 - val_acc: 0.7396
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8430 - acc: 0.7031 - val_loss: 0.7798 - val_acc: 0.7500
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8005 - acc: 0.7396 - val_loss: 0.7959 - val_acc: 0.7422
Epoch 8/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 9ms/step - loss: 0.4014 - acc: 0.8555 - val_loss: 0.4873 - val_acc: 0.8359
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3887 - acc: 0.8594 - val_loss: 0.5021 - val_acc: 0.8229
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4046 - acc: 0.8398 - val_loss: 0.4946 - val_acc: 0.8229
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3983 - acc: 0.8529 - val_loss: 0.4730 - val_acc: 0.8255
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3976 - acc: 0.8307 - val_loss: 0.5083 - val_acc: 0.8255
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3960 - acc: 0.8451 - val_loss: 0.4922 - val_acc: 0.8281
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3856 - acc: 0.8542 - val_loss: 0.4977 - val_acc: 0.8281
Epoch 125/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3547 - acc: 0.8555 - val_loss: 0.4977 - val_acc: 0.8333
Epoch 235/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3594 - acc: 0.8529 - val_loss: 0.4975 - val_acc: 0.8333
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3452 - acc: 0.8659 - val_loss: 0.4927 - val_acc: 0.8359
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3414 - acc: 0.8672 - val_loss: 0.4842 - val_acc: 0.8411
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3371 - acc: 0.8698 - val_loss: 0.4786 - val_acc: 0.8359
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3538 - acc: 0.8568 - val_loss: 0.4904 - val_acc: 0.8359
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3383 - acc: 0.8490 - val_loss: 0.4942 - val_acc: 0.8359
Epoch 241/1000
12/12 [==============================] - 0s 9m

12/12 [==============================] - 0s 9ms/step - loss: 0.3309 - acc: 0.8659 - val_loss: 0.4712 - val_acc: 0.8411
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3697 - acc: 0.8529 - val_loss: 0.4933 - val_acc: 0.8359
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3650 - acc: 0.8542 - val_loss: 0.4967 - val_acc: 0.8333
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3423 - acc: 0.8659 - val_loss: 0.4945 - val_acc: 0.8333
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3400 - acc: 0.8724 - val_loss: 0.4961 - val_acc: 0.8333
Epoch 355/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3460 - acc: 0.8633 - val_loss: 0.4928 - val_acc: 0.8359
Epoch 356/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3599 - acc: 0.8594 - val_loss: 0.4970 - val_acc: 0.8333
Epoch 357/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 745us/step
2-cairo:	acc: 83.63%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.52% (+/- 1.03%)
final: current database: cairo 	 81.60% (+/- 1.56%)
CPU times: user 4min 37s, sys: 29.2 s, total: 5min 6s
Wall time: 2min 58s

```

# <a id='constrain_1'>CS_1</a>

In [7]:
%%time
dict_config_cus['distance_int'] = '1'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_19 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_19 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_19 (Conv1D)           (None, 2000, 28)          1820      
_________________________________________________________________
activation_55 (Activation)   (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_19 (Glo (None, 28)                0         
_________________________________________________________________
dense_55 (Dense)             (None, 42)                1218      
________________________________________

Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1889 - acc: 0.9271 - val_loss: 0.2969 - val_acc: 0.9193
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1847 - acc: 0.9310 - val_loss: 0.3049 - val_acc: 0.9167
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1969 - acc: 0.9258 - val_loss: 0.3012 - val_acc: 0.9167
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1926 - acc: 0.9258 - val_loss: 0.3061 - val_acc: 0.9141
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1881 - acc: 0.9323 - val_loss: 0.2975 - val_acc: 0.9141
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1865 - acc: 0.9232 - val_loss: 0.2967 - val_acc: 0.9219
Epoch 110/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1955 - acc: 0.9232 - val_loss: 0.2880 - val_acc: 0.9193
Epoch 111/1000
12/12 [==============================] - 0s 9ms


Epoch 00163: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 164/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1936 - acc: 0.9297 - val_loss: 0.3064 - val_acc: 0.9167
Epoch 165/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1710 - acc: 0.9271 - val_loss: 0.3061 - val_acc: 0.9167

Epoch 00165: loss improved from inf to 0.17103, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_7/weights/Pbest-0-000165-0.171033-0.916667.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.2022 - acc: 0.9232 - val_loss: 0.2386 - val_acc: 0.9245
Epoch 167/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1862 - acc: 0.9336 - val_loss: 0.3068 - val_acc: 0.9167
Epoch 168/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1951 - acc: 0.9219 - val_loss: 0.2810 - val_acc: 0.9245
Epoch 169/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1830 - acc: 0.

Epoch 282/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1841 - acc: 0.9349 - val_loss: 0.3050 - val_acc: 0.9193
Epoch 283/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1836 - acc: 0.9336 - val_loss: 0.3041 - val_acc: 0.9193
Epoch 284/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1814 - acc: 0.9297 - val_loss: 0.3009 - val_acc: 0.9193
Epoch 285/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1939 - acc: 0.9219 - val_loss: 0.3030 - val_acc: 0.9193
Epoch 286/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1836 - acc: 0.9297 - val_loss: 0.3084 - val_acc: 0.9167
Epoch 287/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1881 - acc: 0.9297 - val_loss: 0.3015 - val_acc: 0.9193
Epoch 288/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1886 - acc: 0.9232 - val_loss: 0.2993 - val_acc: 0.9193
Epoch 289/1000
12/12 [==============================] - 0s 9ms

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 0s 894us/step
0-cairo:	acc: 91.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 60ms/step - loss: 1.2802 - acc: 0.5833 - val_loss: 0.8911 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8457 - acc: 0.6615 - val_loss: 0.7482 - val_acc: 0.7812
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7270 - acc: 0.7539 - val_loss: 0.6070 - val_acc: 0.8021
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6234 - acc: 0.7812 - val_loss: 0.5126 - val_acc: 0.8724
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5486 - acc: 0.8164 - val_loss: 0.4514 - val_acc: 0.8802
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4821 - acc: 0.8451 - val_loss: 0.3893 - val_acc: 0.8828
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4231 - acc: 0.8568 - val_loss: 0.3538 - val_acc: 0.8828
Epoch 8/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 9ms/step - loss: 0.2096 - acc: 0.9154 - val_loss: 0.2631 - val_acc: 0.8932
Epoch 115/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1974 - acc: 0.9245 - val_loss: 0.2620 - val_acc: 0.8932
Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2027 - acc: 0.9193 - val_loss: 0.2639 - val_acc: 0.8932
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1937 - acc: 0.9167 - val_loss: 0.2568 - val_acc: 0.8984
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1903 - acc: 0.9245 - val_loss: 0.2624 - val_acc: 0.8958
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1910 - acc: 0.9245 - val_loss: 0.2657 - val_acc: 0.8906

Epoch 00119: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1997 - acc: 0.9141 - val_loss: 0.2664 - val_acc: 0.8

Epoch 173/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1857 - acc: 0.9219 - val_loss: 0.2554 - val_acc: 0.8984

Epoch 00173: loss improved from 0.18888 to 0.18574, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_7/weights/Pbest-1-000173-0.185742-0.898438.hdf5
Epoch 174/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.1939 - acc: 0.9167 - val_loss: 0.2569 - val_acc: 0.8958
Epoch 175/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1796 - acc: 0.9284 - val_loss: 0.2523 - val_acc: 0.8958
Epoch 176/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1948 - acc: 0.9193 - val_loss: 0.2648 - val_acc: 0.8906
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1907 - acc: 0.9349 - val_loss: 0.2589 - val_acc: 0.8958
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1887 - acc: 0.9284 - val_loss: 0.2595 - val_acc: 0.8958
Epoch 179/1000
12/12

12/12 [==============================] - 0s 9ms/step - loss: 0.1968 - acc: 0.9245 - val_loss: 0.2663 - val_acc: 0.8906
Epoch 288/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1908 - acc: 0.9167 - val_loss: 0.2645 - val_acc: 0.8906
Epoch 289/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1949 - acc: 0.9258 - val_loss: 0.2660 - val_acc: 0.8906
Epoch 290/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1942 - acc: 0.9258 - val_loss: 0.2609 - val_acc: 0.8932
Epoch 291/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1872 - acc: 0.9180 - val_loss: 0.2589 - val_acc: 0.8932
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1921 - acc: 0.9206 - val_loss: 0.2648 - val_acc: 0.8906
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1948 - acc: 0.9245 - val_loss: 0.2657 - val_acc: 0.8906
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.1898 - acc: 0.9284 - val_loss: 0.2615 - val_acc: 0.8932
Epoch 404/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1853 - acc: 0.9232 - val_loss: 0.2619 - val_acc: 0.8906
Epoch 405/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2020 - acc: 0.9154 - val_loss: 0.2608 - val_acc: 0.8932
Epoch 406/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2054 - acc: 0.9219 - val_loss: 0.2658 - val_acc: 0.8906
Epoch 407/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1922 - acc: 0.9167 - val_loss: 0.2432 - val_acc: 0.8932
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2019 - acc: 0.9206 - val_loss: 0.2646 - val_acc: 0.8906
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2029 - acc: 0.9245 - val_loss: 0.2644 - val_acc: 0.8932
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 1ms/step
1-cairo:	acc: 89.26%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 1s 63ms/step - loss: 1.2528 - acc: 0.5742 - val_loss: 0.8604 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8362 - acc: 0.6458 - val_loss: 0.7614 - val_acc: 0.7318
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7276 - acc: 0.7448 - val_loss: 0.6520 - val_acc: 0.8099
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6179 - acc: 0.8177 - val_loss: 0.5539 - val_acc: 0.8151
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.5538 - acc: 0.8320 - val_loss: 0.5070 - val_acc: 0.8464
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4967 - acc: 0.8424 - val_loss: 0.4830 - val_acc: 0.8438
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4652 - acc: 0.8581 - val_loss: 0.4397 - val_acc: 0.8542
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.1731 - acc: 0.9388 - val_loss: 0.3602 - val_acc: 0.9010
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1763 - acc: 0.9414 - val_loss: 0.3737 - val_acc: 0.8984
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1757 - acc: 0.9440 - val_loss: 0.3252 - val_acc: 0.9062
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1733 - acc: 0.9414 - val_loss: 0.3707 - val_acc: 0.9036
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1759 - acc: 0.9362 - val_loss: 0.3779 - val_acc: 0.9010
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1651 - acc: 0.9401 - val_loss: 0.3738 - val_acc: 0.9036
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1687 - acc: 0.9401 - val_loss: 0.3796 - val_acc: 0.9036
Epoch 125/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.1674 - acc: 0.9401 - val_loss: 0.3882 - val_acc: 0.8984
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1723 - acc: 0.9388 - val_loss: 0.3777 - val_acc: 0.9010
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1684 - acc: 0.9440 - val_loss: 0.3898 - val_acc: 0.8984
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1737 - acc: 0.9375 - val_loss: 0.3873 - val_acc: 0.9010
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1630 - acc: 0.9362 - val_loss: 0.3881 - val_acc: 0.9010
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1710 - acc: 0.9375 - val_loss: 0.3892 - val_acc: 0.8984
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1702 - acc: 0.9388 - val_loss: 0.3900 - val_acc: 0.8984
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 288/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1617 - acc: 0.9453 - val_loss: 0.3880 - val_acc: 0.9010
Epoch 289/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1725 - acc: 0.9336 - val_loss: 0.3898 - val_acc: 0.8984
Epoch 290/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1718 - acc: 0.9401 - val_loss: 0.3876 - val_acc: 0.8984
Epoch 291/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1644 - acc: 0.9362 - val_loss: 0.3899 - val_acc: 0.8984
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1547 - acc: 0.9414 - val_loss: 0.3885 - val_acc: 0.8984
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1613 - acc: 0.9414 - val_loss: 0.3879 - val_acc: 0.9010
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1708 - acc: 0.9349 - val_loss: 0.3808 - val_acc: 0.9010
Epoch 295/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.1620 - acc: 0.9427 - val_loss: 0.3862 - val_acc: 0.9010
Epoch 405/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1596 - acc: 0.9401 - val_loss: 0.3879 - val_acc: 0.9010
Epoch 406/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1715 - acc: 0.9375 - val_loss: 0.3864 - val_acc: 0.9010
Epoch 407/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1729 - acc: 0.9310 - val_loss: 0.3896 - val_acc: 0.8984
Epoch 408/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1626 - acc: 0.9440 - val_loss: 0.3810 - val_acc: 0.9062
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1738 - acc: 0.9310 - val_loss: 0.3834 - val_acc: 0.9010
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1594 - acc: 0.9323 - val_loss: 0.3759 - val_acc: 0.9010
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.1483 - acc: 0.9466 - val_loss: 0.3889 - val_acc: 0.8984
Epoch 522/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1741 - acc: 0.9336 - val_loss: 0.3892 - val_acc: 0.8984
Epoch 523/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1611 - acc: 0.9362 - val_loss: 0.3859 - val_acc: 0.9010
Epoch 524/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1671 - acc: 0.9414 - val_loss: 0.3819 - val_acc: 0.9010
Epoch 525/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1578 - acc: 0.9427 - val_loss: 0.3892 - val_acc: 0.8984
Epoch 526/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1710 - acc: 0.9401 - val_loss: 0.3867 - val_acc: 0.9010
Epoch 527/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1653 - acc: 0.9349 - val_loss: 0.3900 - val_acc: 0.8984
Epoch 528/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 638/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1552 - acc: 0.9505 - val_loss: 0.3852 - val_acc: 0.9010
Epoch 639/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1599 - acc: 0.9414 - val_loss: 0.3875 - val_acc: 0.8984
Epoch 640/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1643 - acc: 0.9414 - val_loss: 0.3822 - val_acc: 0.9010
Epoch 641/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1565 - acc: 0.9362 - val_loss: 0.3903 - val_acc: 0.8984
Epoch 642/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1670 - acc: 0.9414 - val_loss: 0.3838 - val_acc: 0.9010
Epoch 643/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1608 - acc: 0.9388 - val_loss: 0.3894 - val_acc: 0.8984
Epoch 00643: early stopping
ModelCheckpoint 已经保存到 ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_7/weights/2-final.hdf5
save in: ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_6

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 1ms/step
2-cairo:	acc: 90.03%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 90.37% (+/- 1.08%)
final: current database: cairo 	 90.37% (+/- 1.08%)
CPU times: user 4min 48s, sys: 29.7 s, total: 5min 17s
Wall time: 3min 4s

```

# <a id='constrain_2'>CS_2</a>

In [8]:
%%time
dict_config_cus['distance_int'] = '2'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_28 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_28 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_28 (Conv1D)           (None, 2000, 28)          1820      
_________________________________________________________________
activation_82 (Activation)   (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_28 (Glo (None, 28)                0         
_________________________________________________________________
dense_82 (Dense)             (None, 42)                1218      
________________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.3653 - acc: 0.8685 - val_loss: 0.5399 - val_acc: 0.7943
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3601 - acc: 0.8555 - val_loss: 0.5414 - val_acc: 0.7969
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3810 - acc: 0.8516 - val_loss: 0.5368 - val_acc: 0.7943
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3688 - acc: 0.8633 - val_loss: 0.5356 - val_acc: 0.7995

Epoch 00107: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3763 - acc: 0.8516 - val_loss: 0.5344 - val_acc: 0.7995
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3764 - acc: 0.8451 - val_loss: 0.5257 - val_acc: 0.7995
Epoch 110/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3672 - acc: 0.8698 - val_loss: 0.5403 - val_acc: 0.7

Epoch 223/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3610 - acc: 0.8672 - val_loss: 0.5359 - val_acc: 0.7943
Epoch 224/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3623 - acc: 0.8555 - val_loss: 0.5124 - val_acc: 0.7995
Epoch 225/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3767 - acc: 0.8529 - val_loss: 0.5386 - val_acc: 0.7917
Epoch 226/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3627 - acc: 0.8646 - val_loss: 0.5274 - val_acc: 0.7969
Epoch 227/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3575 - acc: 0.8568 - val_loss: 0.5314 - val_acc: 0.7969
Epoch 228/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3793 - acc: 0.8542 - val_loss: 0.5433 - val_acc: 0.7891
Epoch 229/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3623 - acc: 0.8711 - val_loss: 0.5398 - val_acc: 0.7917
Epoch 230/1000
12/12 [==============================] - 0s 9m

save in: ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/log/20220201_2000_64_1_7.csv
time: 0:00:47 s
time: 47.0 s
average 0.047000 s
0 epoch finished
--------------------   best   --------------------
no_activities: 7

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 1ms/step
0-cairo:	acc: 79.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 1ms/step
0-cairo:	acc: 79.34%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 82ms/step - loss: 1.3531 - acc: 0.5859 - val_loss: 0.9957 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9979 - acc: 0.6393 - val_loss: 0.8212 - val_acc: 0.7240
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8762 - acc: 0.6953 - val_loss: 0.7371 - val_acc: 0.7344
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8264 - acc: 0.7031 - val_loss: 0.6871 - val_acc: 0.7552
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7734 - acc: 0.7240 - val_loss: 0.6772 - val_acc: 0.7578
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7299 - acc: 0.7396 - val_loss: 0.6384 - val_acc: 0.7760
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7316 - acc: 0.7344 - val_loss: 0.6111 - val_acc: 0.7786
Epoch 8/1000
12/12 [==============================] - 0

Epoch 116/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3994 - acc: 0.8438 - val_loss: 0.4535 - val_acc: 0.8385
Epoch 117/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3794 - acc: 0.8607 - val_loss: 0.4505 - val_acc: 0.8359
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3755 - acc: 0.8490 - val_loss: 0.4494 - val_acc: 0.8307
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3654 - acc: 0.8477 - val_loss: 0.4480 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3667 - acc: 0.8529 - val_loss: 0.4442 - val_acc: 0.8359
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3712 - acc: 0.8607 - val_loss: 0.4410 - val_acc: 0.8333
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3520 - acc: 0.8594 - val_loss: 0.4504 - val_acc: 0.8203
Epoch 123/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.3455 - acc: 0.8607 - val_loss: 0.4402 - val_acc: 0.8255
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3471 - acc: 0.8607 - val_loss: 0.4568 - val_acc: 0.8203
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3425 - acc: 0.8672 - val_loss: 0.4492 - val_acc: 0.8281
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3466 - acc: 0.8555 - val_loss: 0.4506 - val_acc: 0.8229
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3517 - acc: 0.8555 - val_loss: 0.4568 - val_acc: 0.8203
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3453 - acc: 0.8659 - val_loss: 0.4409 - val_acc: 0.8255
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3368 - acc: 0.8646 - val_loss: 0.4554 - val_acc: 0.8229
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 291/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3533 - acc: 0.8568 - val_loss: 0.4412 - val_acc: 0.8229
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3471 - acc: 0.8503 - val_loss: 0.4552 - val_acc: 0.8229
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3513 - acc: 0.8568 - val_loss: 0.4426 - val_acc: 0.8229
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3397 - acc: 0.8646 - val_loss: 0.4556 - val_acc: 0.8229
Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3469 - acc: 0.8477 - val_loss: 0.4551 - val_acc: 0.8229
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3492 - acc: 0.8464 - val_loss: 0.4584 - val_acc: 0.8203
Epoch 297/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3690 - acc: 0.8568 - val_loss: 0.4508 - val_acc: 0.8255
Epoch 298/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.3373 - acc: 0.8750 - val_loss: 0.4492 - val_acc: 0.8229
Epoch 409/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3366 - acc: 0.8646 - val_loss: 0.4424 - val_acc: 0.8307
Epoch 410/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3394 - acc: 0.8750 - val_loss: 0.4556 - val_acc: 0.8203
Epoch 411/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3470 - acc: 0.8789 - val_loss: 0.4502 - val_acc: 0.8229
Epoch 412/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3473 - acc: 0.8633 - val_loss: 0.4521 - val_acc: 0.8255
Epoch 413/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3666 - acc: 0.8464 - val_loss: 0.4460 - val_acc: 0.8255
Epoch 414/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3634 - acc: 0.8464 - val_loss: 0.4519 - val_acc: 0.8229
Epoch 415/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3465 - acc: 0.8581 - val_loss: 0.4553 - val_acc: 0.8203
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3671 - acc: 0.8477 - val_loss: 0.4577 - val_acc: 0.8203
Epoch 470/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3588 - acc: 0.8542 - val_loss: 0.4533 - val_acc: 0.8229
Epoch 471/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3549 - acc: 0.8659 - val_loss: 0.4580 - val_acc: 0.8203
Epoch 472/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3543 - acc: 0.8802 - val_loss: 0.4495 - val_acc: 0.8229
Epoch 473/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3478 - acc: 0.8646 - val_loss: 0.4471 - val_acc: 0.8255

Epoch 00473: loss improved from 0.35772 to 0.34778, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/weights/Pbest-1-000473-0.347780-0.825521.hdf5
Epoch 474/1000
12/12

12/12 [==============================] - 0s 9ms/step - loss: 0.3461 - acc: 0.8568 - val_loss: 0.4513 - val_acc: 0.8229
Epoch 583/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3460 - acc: 0.8516 - val_loss: 0.4573 - val_acc: 0.8203
Epoch 584/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3414 - acc: 0.8646 - val_loss: 0.4346 - val_acc: 0.8281
Epoch 585/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3547 - acc: 0.8568 - val_loss: 0.4435 - val_acc: 0.8229
Epoch 586/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3210 - acc: 0.8646 - val_loss: 0.4242 - val_acc: 0.8281
Epoch 587/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3622 - acc: 0.8451 - val_loss: 0.4560 - val_acc: 0.8203
Epoch 588/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3471 - acc: 0.8568 - val_loss: 0.4550 - val_acc: 0.8203
Epoch 589/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.3524 - acc: 0.8581 - val_loss: 0.4538 - val_acc: 0.8229
Epoch 700/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3530 - acc: 0.8646 - val_loss: 0.4471 - val_acc: 0.8255

Epoch 00700: saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/weights/1-000700-0.352981-0.825521.hdf5
Epoch 701/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3322 - acc: 0.8763 - val_loss: 0.4567 - val_acc: 0.8203
Epoch 702/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3396 - acc: 0.8620 - val_loss: 0.4428 - val_acc: 0.8255
Epoch 703/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3561 - acc: 0.8685 - val_loss: 0.4519 - val_acc: 0.8229
Epoch 704/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3413 - acc: 0.8490 - val_loss: 0.4452 - val_acc: 0.8229
Epoch 705/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.34

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
1-cairo:	acc: 82.35%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 89ms/step - loss: 1.3459 - acc: 0.5964 - val_loss: 1.0503 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0061 - acc: 0.6562 - val_loss: 0.8677 - val_acc: 0.6745
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8761 - acc: 0.6940 - val_loss: 0.7861 - val_acc: 0.7344
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8066 - acc: 0.6979 - val_loss: 0.7180 - val_acc: 0.7500
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7608 - acc: 0.7266 - val_loss: 0.6756 - val_acc: 0.7656
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7146 - acc: 0.7409 - val_loss: 0.6521 - val_acc: 0.7734
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.6916 - acc: 0.7435 - val_loss: 0.6389 - val_acc: 0.7734
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.3647 - acc: 0.8581 - val_loss: 0.4757 - val_acc: 0.8385
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3813 - acc: 0.8477 - val_loss: 0.4726 - val_acc: 0.8411
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3798 - acc: 0.8477 - val_loss: 0.4671 - val_acc: 0.8411
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3654 - acc: 0.8555 - val_loss: 0.4770 - val_acc: 0.8464
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3583 - acc: 0.8411 - val_loss: 0.4850 - val_acc: 0.8411
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3719 - acc: 0.8581 - val_loss: 0.4739 - val_acc: 0.8385
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3686 - acc: 0.8607 - val_loss: 0.4791 - val_acc: 0.8411
Epoch 125/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

12/12 [==============================] - 0s 9ms/step - loss: 0.3381 - acc: 0.8620 - val_loss: 0.4777 - val_acc: 0.8516
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3431 - acc: 0.8594 - val_loss: 0.4672 - val_acc: 0.8568

Epoch 00177: loss improved from 0.35397 to 0.34314, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/weights/Pbest-2-000177-0.343137-0.856771.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3446 - acc: 0.8529 - val_loss: 0.4798 - val_acc: 0.8516
Epoch 179/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3557 - acc: 0.8594 - val_loss: 0.4574 - val_acc: 0.8594
Epoch 180/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3536 - acc: 0.8633 - val_loss: 0.4767 - val_acc: 0.8490
Epoch 181/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3669 - acc: 0.8633 - val_loss: 0.4610 - val_acc: 0.8516
Epoch 182/1000
12/12 [=============

12/12 [==============================] - 0s 9ms/step - loss: 0.3622 - acc: 0.8516 - val_loss: 0.4753 - val_acc: 0.8464
Epoch 290/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3531 - acc: 0.8490 - val_loss: 0.4775 - val_acc: 0.8490
Epoch 291/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3642 - acc: 0.8581 - val_loss: 0.4790 - val_acc: 0.8464
Epoch 292/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3692 - acc: 0.8424 - val_loss: 0.4802 - val_acc: 0.8464
Epoch 293/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3443 - acc: 0.8659 - val_loss: 0.4800 - val_acc: 0.8464

Epoch 00293: loss improved from 0.34719 to 0.34431, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/weights/Pbest-2-000293-0.344311-0.846354.hdf5
Epoch 294/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3555 - acc: 0.8568 - val_loss: 0.4762 - val_acc: 0.8490
Epoch 295/1000
12/12 [=============

Epoch 348/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3384 - acc: 0.8633 - val_loss: 0.4557 - val_acc: 0.8516
Epoch 349/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3731 - acc: 0.8398 - val_loss: 0.4710 - val_acc: 0.8516
Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3518 - acc: 0.8607 - val_loss: 0.4775 - val_acc: 0.8490
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3407 - acc: 0.8633 - val_loss: 0.4488 - val_acc: 0.8516
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3413 - acc: 0.8633 - val_loss: 0.4735 - val_acc: 0.8516
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3390 - acc: 0.8646 - val_loss: 0.4762 - val_acc: 0.8490
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3552 - acc: 0.8568 - val_loss: 0.4751 - val_acc: 0.8490
Epoch 355/1000
12/12 [==============================] - 0s 9ms

12/12 [==============================] - 0s 9ms/step - loss: 0.3613 - acc: 0.8607 - val_loss: 0.4736 - val_acc: 0.8516

Epoch 00465: loss improved from inf to 0.36129, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/weights/Pbest-2-000465-0.361291-0.851562.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3472 - acc: 0.8711 - val_loss: 0.4587 - val_acc: 0.8516
Epoch 467/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3601 - acc: 0.8685 - val_loss: 0.4794 - val_acc: 0.8464
Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3424 - acc: 0.8685 - val_loss: 0.4802 - val_acc: 0.8464
Epoch 469/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3440 - acc: 0.8646 - val_loss: 0.4724 - val_acc: 0.8516

Epoch 00469: loss improved from 0.36129 to 0.34404, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_7/weights/Pbest-2-000469-0.344043-0.851562.hd

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
2-cairo:	acc: 83.89%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
2-cairo:	acc: 84.91%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.94% (+/- 1.78%)
final: current database: cairo 	 82.20% (+/- 2.28%)
CPU times: user 5min 27s, sys: 33.6 s, total: 6min 1s
Wall time: 3min 30s

```

# <a id='constrain_3'>CS_3</a>

In [9]:
%%time
dict_config_cus['distance_int'] = '3'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_37 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_37 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_37 (Conv1D)           (None, 2000, 28)          1820      
_________________________________________________________________
activation_109 (Activation)  (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_37 (Glo (None, 28)                0         
_________________________________________________________________
dense_109 (Dense)            (None, 42)                1218      
________________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.3821 - acc: 0.8542 - val_loss: 0.4954 - val_acc: 0.8203
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3928 - acc: 0.8659 - val_loss: 0.5122 - val_acc: 0.8125
Epoch 104/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4097 - acc: 0.8503 - val_loss: 0.4882 - val_acc: 0.8307
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4086 - acc: 0.8568 - val_loss: 0.5110 - val_acc: 0.8177
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4060 - acc: 0.8607 - val_loss: 0.5125 - val_acc: 0.8203
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3779 - acc: 0.8672 - val_loss: 0.5113 - val_acc: 0.8203
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4014 - acc: 0.8503 - val_loss: 0.5209 - val_acc: 0.8177
Epoch 109/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.3327 - acc: 0.8724 - val_loss: 0.5016 - val_acc: 0.8203
Epoch 219/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3680 - acc: 0.8633 - val_loss: 0.5085 - val_acc: 0.8177
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3741 - acc: 0.8646 - val_loss: 0.4961 - val_acc: 0.8229
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3249 - acc: 0.8724 - val_loss: 0.5103 - val_acc: 0.8177
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3460 - acc: 0.8724 - val_loss: 0.5058 - val_acc: 0.8203
Epoch 223/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3325 - acc: 0.8763 - val_loss: 0.5116 - val_acc: 0.8177
Epoch 224/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3405 - acc: 0.8724 - val_loss: 0.4963 - val_acc: 0.8255
Epoch 225/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 335/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3291 - acc: 0.8828 - val_loss: 0.4962 - val_acc: 0.8229
Epoch 336/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3377 - acc: 0.8724 - val_loss: 0.5076 - val_acc: 0.8203
Epoch 337/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3457 - acc: 0.8776 - val_loss: 0.5080 - val_acc: 0.8177
Epoch 338/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3411 - acc: 0.8737 - val_loss: 0.5056 - val_acc: 0.8203
Epoch 339/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3294 - acc: 0.8776 - val_loss: 0.5013 - val_acc: 0.8229
Epoch 340/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3412 - acc: 0.8763 - val_loss: 0.5110 - val_acc: 0.8177
Epoch 341/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3356 - acc: 0.8867 - val_loss: 0.5076 - val_acc: 0.8203
Epoch 342/1000
12/12 [==============================] - 0s 9ms

Epoch 395/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3308 - acc: 0.8971 - val_loss: 0.4997 - val_acc: 0.8229
Epoch 396/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3443 - acc: 0.8737 - val_loss: 0.5007 - val_acc: 0.8229
Epoch 397/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3354 - acc: 0.8737 - val_loss: 0.4984 - val_acc: 0.8229
Epoch 398/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3302 - acc: 0.8867 - val_loss: 0.5057 - val_acc: 0.8203
Epoch 399/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3338 - acc: 0.8750 - val_loss: 0.5027 - val_acc: 0.8203
Epoch 400/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3394 - acc: 0.8789 - val_loss: 0.4805 - val_acc: 0.8307

Epoch 00400: saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_7/weights/0-000400-0.339360-0.830729.hdf5
Epoch 401/1000
12/12 [==============================] - 0s 9ms/st

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 2ms/step
0-cairo:	acc: 82.14%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 114ms/step - loss: 1.3926 - acc: 0.5820 - val_loss: 1.0277 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0412 - acc: 0.6562 - val_loss: 0.8843 - val_acc: 0.6901
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9315 - acc: 0.6680 - val_loss: 0.8065 - val_acc: 0.6927
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8828 - acc: 0.6719 - val_loss: 0.7545 - val_acc: 0.7370
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8134 - acc: 0.6966 - val_loss: 0.7141 - val_acc: 0.7656
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8107 - acc: 0.7096 - val_loss: 0.7541 - val_acc: 0.7526
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7586 - acc: 0.7318 - val_loss: 0.6603 - val_acc: 0.7630
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss

12/12 [==============================] - 0s 9ms/step - loss: 0.4085 - acc: 0.8451 - val_loss: 0.4486 - val_acc: 0.8177
Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3920 - acc: 0.8411 - val_loss: 0.4361 - val_acc: 0.8151
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4140 - acc: 0.8424 - val_loss: 0.4393 - val_acc: 0.8255
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4239 - acc: 0.8346 - val_loss: 0.4462 - val_acc: 0.8125
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4015 - acc: 0.8255 - val_loss: 0.4496 - val_acc: 0.8229
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4157 - acc: 0.8451 - val_loss: 0.4404 - val_acc: 0.8255
Epoch 123/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4295 - acc: 0.8307 - val_loss: 0.4469 - val_acc: 0.8203
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0

Epoch 175/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3979 - acc: 0.8372 - val_loss: 0.4297 - val_acc: 0.8229
Epoch 176/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3702 - acc: 0.8516 - val_loss: 0.4368 - val_acc: 0.8151
Epoch 177/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3713 - acc: 0.8607 - val_loss: 0.4395 - val_acc: 0.8229

Epoch 00177: loss improved from 0.37583 to 0.37134, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_7/weights/Pbest-1-000177-0.371339-0.822917.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3719 - acc: 0.8555 - val_loss: 0.4360 - val_acc: 0.8229
Epoch 179/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3970 - acc: 0.8529 - val_loss: 0.4329 - val_acc: 0.8229
Epoch 180/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3983 - acc: 0.8320 - val_loss: 0.4477 - val_acc: 0.8177
Epoch 181/1000
12/

Epoch 233/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3564 - acc: 0.8607 - val_loss: 0.4438 - val_acc: 0.8229
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3879 - acc: 0.8542 - val_loss: 0.4395 - val_acc: 0.8255
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3769 - acc: 0.8620 - val_loss: 0.4432 - val_acc: 0.8203
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3852 - acc: 0.8516 - val_loss: 0.4391 - val_acc: 0.8203
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3629 - acc: 0.8555 - val_loss: 0.4443 - val_acc: 0.8203
Epoch 238/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3760 - acc: 0.8490 - val_loss: 0.4445 - val_acc: 0.8203
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3768 - acc: 0.8542 - val_loss: 0.4498 - val_acc: 0.8177
Epoch 240/1000
12/12 [==============================] - 0s 9m

Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3911 - acc: 0.8490 - val_loss: 0.4479 - val_acc: 0.8151
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4067 - acc: 0.8477 - val_loss: 0.4449 - val_acc: 0.8203
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3965 - acc: 0.8372 - val_loss: 0.4424 - val_acc: 0.8203
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3461 - acc: 0.8633 - val_loss: 0.4381 - val_acc: 0.8203
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3837 - acc: 0.8385 - val_loss: 0.4496 - val_acc: 0.8151
Epoch 355/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3914 - acc: 0.8464 - val_loss: 0.4506 - val_acc: 0.8151
Epoch 356/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3852 - acc: 0.8438 - val_loss: 0.4446 - val_acc: 0.8203
Epoch 357/1000
12/12 [==============================] - 0s 

12/12 [==============================] - 0s 9ms/step - loss: 0.3719 - acc: 0.8529 - val_loss: 0.4459 - val_acc: 0.8177
Epoch 465/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3513 - acc: 0.8581 - val_loss: 0.4487 - val_acc: 0.8151

Epoch 00465: loss improved from inf to 0.35131, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_7/weights/Pbest-1-000465-0.351312-0.815104.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3784 - acc: 0.8620 - val_loss: 0.4421 - val_acc: 0.8177
Epoch 467/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3972 - acc: 0.8477 - val_loss: 0.4388 - val_acc: 0.8177
Epoch 468/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3770 - acc: 0.8529 - val_loss: 0.4449 - val_acc: 0.8177
Epoch 469/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3915 - acc: 0.8516 - val_loss: 0.4410 - val_acc: 0.8177
Epoch 470/1000
12/12 [================

Epoch 523/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3717 - acc: 0.8659 - val_loss: 0.4493 - val_acc: 0.8151
Epoch 524/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3631 - acc: 0.8633 - val_loss: 0.4413 - val_acc: 0.8229
Epoch 525/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3807 - acc: 0.8359 - val_loss: 0.4408 - val_acc: 0.8177
Epoch 526/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3776 - acc: 0.8411 - val_loss: 0.4424 - val_acc: 0.8203
Epoch 527/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3891 - acc: 0.8346 - val_loss: 0.4383 - val_acc: 0.8203
Epoch 528/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3803 - acc: 0.8385 - val_loss: 0.4442 - val_acc: 0.8203
Epoch 529/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3872 - acc: 0.8490 - val_loss: 0.4454 - val_acc: 0.8177
Epoch 530/1000
12/12 [==============================] - 0s 10m

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
1-cairo:	acc: 81.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 121ms/step - loss: 1.3032 - acc: 0.6068 - val_loss: 1.0856 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0926 - acc: 0.6341 - val_loss: 0.9821 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0093 - acc: 0.6419 - val_loss: 0.8810 - val_acc: 0.6823
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.9100 - acc: 0.6719 - val_loss: 0.8033 - val_acc: 0.7083
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8553 - acc: 0.6979 - val_loss: 0.7383 - val_acc: 0.7708
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7828 - acc: 0.7214 - val_loss: 0.7030 - val_acc: 0.7812
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7206 - acc: 0.7422 - val_loss: 0.6581 - val_acc: 0.7943
Epoch 8/1000
12/12 [==============================] - 0s 9ms/step - loss:

Epoch 118/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4033 - acc: 0.8477 - val_loss: 0.4900 - val_acc: 0.8203
Epoch 119/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4185 - acc: 0.8307 - val_loss: 0.4873 - val_acc: 0.8229
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3835 - acc: 0.8490 - val_loss: 0.4865 - val_acc: 0.8203
Epoch 121/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3942 - acc: 0.8529 - val_loss: 0.4871 - val_acc: 0.8229
Epoch 122/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3900 - acc: 0.8581 - val_loss: 0.4845 - val_acc: 0.8229
Epoch 123/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4158 - acc: 0.8438 - val_loss: 0.4874 - val_acc: 0.8203
Epoch 124/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4098 - acc: 0.8451 - val_loss: 0.4638 - val_acc: 0.8229
Epoch 125/1000
12/12 [==============================] - 0s 9m

12/12 [==============================] - 0s 10ms/step - loss: 0.3881 - acc: 0.8529 - val_loss: 0.4860 - val_acc: 0.8281
Epoch 236/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3918 - acc: 0.8503 - val_loss: 0.4829 - val_acc: 0.8229
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3921 - acc: 0.8464 - val_loss: 0.4818 - val_acc: 0.8255
Epoch 238/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4062 - acc: 0.8333 - val_loss: 0.4883 - val_acc: 0.8255
Epoch 239/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4112 - acc: 0.8385 - val_loss: 0.4844 - val_acc: 0.8281
Epoch 240/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4083 - acc: 0.8503 - val_loss: 0.4687 - val_acc: 0.8281
Epoch 241/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3858 - acc: 0.8555 - val_loss: 0.4856 - val_acc: 0.8255
Epoch 242/1000
12/12 [==============================] - 0s 10ms/step - lo

Epoch 295/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4009 - acc: 0.8359 - val_loss: 0.4828 - val_acc: 0.8281
Epoch 296/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3863 - acc: 0.8581 - val_loss: 0.4687 - val_acc: 0.8307
Epoch 297/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3887 - acc: 0.8451 - val_loss: 0.4870 - val_acc: 0.8255
Epoch 298/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3987 - acc: 0.8490 - val_loss: 0.4884 - val_acc: 0.8229
Epoch 299/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4026 - acc: 0.8359 - val_loss: 0.4894 - val_acc: 0.8229
Epoch 300/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4243 - acc: 0.8359 - val_loss: 0.4874 - val_acc: 0.8255

Epoch 00300: saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_7/weights/2-000300-0.424270-0.825521.hdf5
Epoch 301/1000
12/12 [==============================] - 0s 9ms/s

12/12 [==============================] - 0s 9ms/step - loss: 0.3944 - acc: 0.8411 - val_loss: 0.4854 - val_acc: 0.8229
Epoch 356/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3916 - acc: 0.8424 - val_loss: 0.4870 - val_acc: 0.8255
Epoch 357/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4127 - acc: 0.8464 - val_loss: 0.4867 - val_acc: 0.8255
Epoch 358/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3917 - acc: 0.8555 - val_loss: 0.4806 - val_acc: 0.8281
Epoch 359/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3953 - acc: 0.8555 - val_loss: 0.4796 - val_acc: 0.8307
Epoch 360/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4251 - acc: 0.8333 - val_loss: 0.4890 - val_acc: 0.8229
Epoch 361/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3881 - acc: 0.8516 - val_loss: 0.4864 - val_acc: 0.8255
Epoch 362/1000
12/12 [==============================] - 0s 9ms/step - loss:

no_activities: 7

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
2-cairo:	acc: 82.61%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
2-cairo:	acc: 82.61%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 82.37% (+/- 0.21%)
final: current database: cairo 	 82.11% (+/- 0.42%)
CPU times: user 4min 53s, sys: 28.4 s, total: 5min 21s
Wall time: 3min 12s

```

# <a id='constrain_4'>CS_4</a>

In [22]:
%%time
dict_config_cus['distance_int'] = '4'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_154 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_154 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_154 (Conv1D)          (None, 2000, 28)          1820      
_________________________________________________________________
activation_460 (Activation)  (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_154 (Gl (None, 28)                0         
_________________________________________________________________
dense_460 (Dense)            (None, 42)                1218      
________________________________________

Epoch 101/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.4203 - acc: 0.8372 - val_loss: 0.4818 - val_acc: 0.7995
Epoch 102/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4218 - acc: 0.8398 - val_loss: 0.4931 - val_acc: 0.7969
Epoch 103/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4144 - acc: 0.8451 - val_loss: 0.4953 - val_acc: 0.8021
Epoch 104/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4287 - acc: 0.8411 - val_loss: 0.4934 - val_acc: 0.8021
Epoch 105/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4204 - acc: 0.8411 - val_loss: 0.4971 - val_acc: 0.7995
Epoch 106/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4275 - acc: 0.8411 - val_loss: 0.4852 - val_acc: 0.8073
Epoch 107/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4220 - acc: 0.8424 - val_loss: 0.4916 - val_acc: 0.8047
Epoch 108/1000
12/12 [==============================] -

Epoch 216/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4177 - acc: 0.8542 - val_loss: 0.4800 - val_acc: 0.8125
Epoch 217/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4166 - acc: 0.8503 - val_loss: 0.4851 - val_acc: 0.8099
Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4201 - acc: 0.8451 - val_loss: 0.4960 - val_acc: 0.8047
Epoch 219/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4279 - acc: 0.8320 - val_loss: 0.4808 - val_acc: 0.8125
Epoch 220/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4090 - acc: 0.8529 - val_loss: 0.4896 - val_acc: 0.8099
Epoch 221/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4151 - acc: 0.8516 - val_loss: 0.5000 - val_acc: 0.8021
Epoch 222/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4288 - acc: 0.8372 - val_loss: 0.4905 - val_acc: 0.8047
Epoch 223/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.4422 - acc: 0.8490 - val_loss: 0.5003 - val_acc: 0.8021
Epoch 275/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4196 - acc: 0.8451 - val_loss: 0.4990 - val_acc: 0.8021
Epoch 276/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4039 - acc: 0.8503 - val_loss: 0.4824 - val_acc: 0.8073
Epoch 277/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4043 - acc: 0.8451 - val_loss: 0.4918 - val_acc: 0.8047

Epoch 00277: loss improved from 0.41844 to 0.40428, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_7/weights/Pbest-0-000277-0.404276-0.804688.hdf5
Epoch 278/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.4302 - acc: 0.8464 - val_loss: 0.4972 - val_acc: 0.8047
Epoch 279/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4062 - acc: 0.8516 - val_loss: 0.4939 - val_acc: 0.8047
Epoch 280/1000
12/12 [=======

Epoch 390/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.4223 - acc: 0.8398 - val_loss: 0.4946 - val_acc: 0.8021
Epoch 391/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.4253 - acc: 0.8438 - val_loss: 0.4984 - val_acc: 0.7995
Epoch 392/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4303 - acc: 0.8320 - val_loss: 0.4819 - val_acc: 0.8073
Epoch 393/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4501 - acc: 0.8359 - val_loss: 0.4866 - val_acc: 0.8099
Epoch 394/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4219 - acc: 0.8464 - val_loss: 0.4933 - val_acc: 0.8021
Epoch 395/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4136 - acc: 0.8477 - val_loss: 0.4911 - val_acc: 0.8021
Epoch 396/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.4209 - acc: 0.8359 - val_loss: 0.5017 - val_acc: 0.7995
Epoch 397/1000
12/12 [==============================] -

Epoch 450/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4231 - acc: 0.8385 - val_loss: 0.4917 - val_acc: 0.8047
Epoch 451/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4157 - acc: 0.8542 - val_loss: 0.4848 - val_acc: 0.8073
Epoch 452/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4377 - acc: 0.8451 - val_loss: 0.4831 - val_acc: 0.8073
Epoch 453/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4216 - acc: 0.8411 - val_loss: 0.4820 - val_acc: 0.8073
Epoch 454/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4138 - acc: 0.8464 - val_loss: 0.5011 - val_acc: 0.7995
Epoch 455/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4013 - acc: 0.8503 - val_loss: 0.4920 - val_acc: 0.8073
Epoch 456/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4082 - acc: 0.8503 - val_loss: 0.4940 - val_acc: 0.8021
Epoch 457/1000
12/12 [==============================] -

12/12 [==============================] - 0s 17ms/step - loss: 0.4052 - acc: 0.8490 - val_loss: 0.4747 - val_acc: 0.8047
Epoch 568/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4210 - acc: 0.8516 - val_loss: 0.4982 - val_acc: 0.7995
Epoch 569/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4278 - acc: 0.8424 - val_loss: 0.4904 - val_acc: 0.8021
Epoch 570/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4211 - acc: 0.8451 - val_loss: 0.4888 - val_acc: 0.8047
Epoch 571/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4335 - acc: 0.8451 - val_loss: 0.4952 - val_acc: 0.8021
Epoch 572/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4199 - acc: 0.8451 - val_loss: 0.4934 - val_acc: 0.7995
Epoch 573/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4341 - acc: 0.8438 - val_loss: 0.4846 - val_acc: 0.8047
Epoch 574/1000
12/12 [==============================] - 0s 18ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 8s 20ms/step
0-cairo:	acc: 80.10%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 9s 766ms/step - loss: 1.3194 - acc: 0.5898 - val_loss: 1.0377 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 15ms/step - loss: 1.0493 - acc: 0.6380 - val_loss: 0.9289 - val_acc: 0.6380
Epoch 3/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.9438 - acc: 0.6667 - val_loss: 0.8237 - val_acc: 0.7083
Epoch 4/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.8783 - acc: 0.7005 - val_loss: 0.7728 - val_acc: 0.7344
Epoch 5/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8422 - acc: 0.7031 - val_loss: 0.7298 - val_acc: 0.7344
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7751 - acc: 0.7357 - val_loss: 0.6920 - val_acc: 0.7422
Epoch 7/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.7490 - acc: 0.7292 - val_loss: 0.6762 - val_acc: 0.7656
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3952 - acc: 0.8464 - val_loss: 0.4974 - val_acc: 0.8125
Epoch 118/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3993 - acc: 0.8490 - val_loss: 0.4954 - val_acc: 0.8125
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3826 - acc: 0.8477 - val_loss: 0.4943 - val_acc: 0.8151
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4008 - acc: 0.8411 - val_loss: 0.4965 - val_acc: 0.8099
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3837 - acc: 0.8607 - val_loss: 0.4788 - val_acc: 0.8177
Epoch 122/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4055 - acc: 0.8411 - val_loss: 0.4929 - val_acc: 0.8125

Epoch 00122: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 123/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3835 - acc: 0.8503 - val_loss: 0.4910 - val_a

Epoch 234/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3684 - acc: 0.8555 - val_loss: 0.4892 - val_acc: 0.8203
Epoch 235/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3841 - acc: 0.8542 - val_loss: 0.4891 - val_acc: 0.8177
Epoch 236/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3792 - acc: 0.8529 - val_loss: 0.4868 - val_acc: 0.8203
Epoch 237/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3615 - acc: 0.8516 - val_loss: 0.4838 - val_acc: 0.8177
Epoch 238/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3915 - acc: 0.8568 - val_loss: 0.4875 - val_acc: 0.8151
Epoch 239/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3904 - acc: 0.8464 - val_loss: 0.4838 - val_acc: 0.8151
Epoch 240/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3821 - acc: 0.8594 - val_loss: 0.4964 - val_acc: 0.8151
Epoch 241/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.3961 - acc: 0.8477 - val_loss: 0.4871 - val_acc: 0.8177
Epoch 293/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3747 - acc: 0.8490 - val_loss: 0.4937 - val_acc: 0.8151

Epoch 00293: loss improved from 0.37822 to 0.37471, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_7/weights/Pbest-1-000293-0.374707-0.815104.hdf5
Epoch 294/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3728 - acc: 0.8633 - val_loss: 0.4925 - val_acc: 0.8125
Epoch 295/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3993 - acc: 0.8451 - val_loss: 0.4922 - val_acc: 0.8177
Epoch 296/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3835 - acc: 0.8542 - val_loss: 0.4931 - val_acc: 0.8177
Epoch 297/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3679 - acc: 0.8516 - val_loss: 0.4863 - val_acc: 0.8203

Epoch 00297: loss improved f

12/12 [==============================] - 0s 16ms/step - loss: 0.3927 - acc: 0.8490 - val_loss: 0.4930 - val_acc: 0.8151
Epoch 407/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3826 - acc: 0.8555 - val_loss: 0.4921 - val_acc: 0.8177
Epoch 408/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3903 - acc: 0.8503 - val_loss: 0.4707 - val_acc: 0.8177
Epoch 409/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3819 - acc: 0.8555 - val_loss: 0.4931 - val_acc: 0.8151
Epoch 410/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3761 - acc: 0.8529 - val_loss: 0.4993 - val_acc: 0.8125
Epoch 411/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3846 - acc: 0.8542 - val_loss: 0.4973 - val_acc: 0.8125
Epoch 412/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4005 - acc: 0.8516 - val_loss: 0.4912 - val_acc: 0.8151
Epoch 413/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 466/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3753 - acc: 0.8685 - val_loss: 0.4836 - val_acc: 0.8203
Epoch 467/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3850 - acc: 0.8464 - val_loss: 0.4957 - val_acc: 0.8125
Epoch 468/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3740 - acc: 0.8555 - val_loss: 0.4819 - val_acc: 0.8203
Epoch 469/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4102 - acc: 0.8451 - val_loss: 0.4874 - val_acc: 0.8151
Epoch 470/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3861 - acc: 0.8529 - val_loss: 0.4912 - val_acc: 0.8151
Epoch 471/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3783 - acc: 0.8516 - val_loss: 0.4750 - val_acc: 0.8203
Epoch 472/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3935 - acc: 0.8542 - val_loss: 0.4884 - val_acc: 0.8151
Epoch 473/1000
12/12 [==============================] -

Epoch 526/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3910 - acc: 0.8464 - val_loss: 0.4985 - val_acc: 0.8125
Epoch 527/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3828 - acc: 0.8581 - val_loss: 0.4897 - val_acc: 0.8151
Epoch 528/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3862 - acc: 0.8516 - val_loss: 0.4975 - val_acc: 0.8125
Epoch 529/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3838 - acc: 0.8477 - val_loss: 0.4991 - val_acc: 0.8125
Epoch 530/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3832 - acc: 0.8607 - val_loss: 0.4779 - val_acc: 0.8229
Epoch 531/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3837 - acc: 0.8555 - val_loss: 0.4921 - val_acc: 0.8177
Epoch 532/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3875 - acc: 0.8451 - val_loss: 0.4863 - val_acc: 0.8177
Epoch 533/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 8s 20ms/step
1-cairo:	acc: 81.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 9s 775ms/step - loss: 1.3029 - acc: 0.6094 - val_loss: 1.0799 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 15ms/step - loss: 1.0700 - acc: 0.6380 - val_loss: 0.9704 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.9728 - acc: 0.6576 - val_loss: 0.8883 - val_acc: 0.6823
Epoch 4/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.8963 - acc: 0.6966 - val_loss: 0.8187 - val_acc: 0.7578
Epoch 5/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8442 - acc: 0.7174 - val_loss: 0.7853 - val_acc: 0.7422
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.8188 - acc: 0.7161 - val_loss: 0.7411 - val_acc: 0.7500
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7625 - acc: 0.7214 - val_loss: 0.7131 - val_acc: 0.7708
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3963 - acc: 0.8594 - val_loss: 0.5118 - val_acc: 0.8177
Epoch 117/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4004 - acc: 0.8451 - val_loss: 0.5103 - val_acc: 0.8177
Epoch 118/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4046 - acc: 0.8411 - val_loss: 0.5136 - val_acc: 0.8151
Epoch 119/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3905 - acc: 0.8542 - val_loss: 0.5159 - val_acc: 0.8177
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3966 - acc: 0.8490 - val_loss: 0.5151 - val_acc: 0.8177
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3995 - acc: 0.8464 - val_loss: 0.5141 - val_acc: 0.8177
Epoch 122/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4201 - acc: 0.8333 - val_loss: 0.5094 - val_acc: 0.8177
Epoch 123/1000
12/12 [==============================] - 0s 17ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3964 - acc: 0.8477 - val_loss: 0.5086 - val_acc: 0.8203
Epoch 232/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3890 - acc: 0.8581 - val_loss: 0.5119 - val_acc: 0.8203
Epoch 233/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3840 - acc: 0.8346 - val_loss: 0.4950 - val_acc: 0.8203
Epoch 234/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3997 - acc: 0.8451 - val_loss: 0.5139 - val_acc: 0.8177
Epoch 235/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3775 - acc: 0.8411 - val_loss: 0.4913 - val_acc: 0.8203
Epoch 236/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3928 - acc: 0.8372 - val_loss: 0.5133 - val_acc: 0.8203
Epoch 237/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4071 - acc: 0.8346 - val_loss: 0.5149 - val_acc: 0.8177
Epoch 238/1000
12/12 [==============================] - 0s 19ms/step -

Epoch 350/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3941 - acc: 0.8398 - val_loss: 0.5130 - val_acc: 0.8177
Epoch 351/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3939 - acc: 0.8424 - val_loss: 0.5147 - val_acc: 0.8151
Epoch 352/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3874 - acc: 0.8542 - val_loss: 0.5149 - val_acc: 0.8151
Epoch 353/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.4041 - acc: 0.8451 - val_loss: 0.5074 - val_acc: 0.8229
Epoch 354/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3963 - acc: 0.8359 - val_loss: 0.5161 - val_acc: 0.8151
Epoch 355/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3966 - acc: 0.8503 - val_loss: 0.5117 - val_acc: 0.8177
Epoch 356/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3866 - acc: 0.8411 - val_loss: 0.5155 - val_acc: 0.8151
Epoch 357/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 8s 21ms/step
2-cairo:	acc: 81.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

```bash
best: current database: cairo 	 80.67% (+/- 1.48%)
final: current database: cairo 	 80.67% (+/- 1.48%)
CPU times: user 5min 44s, sys: 31.9 s, total: 6min 16s
Wall time: 3min 47s

best: current database: cairo 	 80.92% (+/- 0.41%)
final: current database: cairo 	 80.84% (+/- 0.34%)
CPU times: user 9min 22s, sys: 36.7 s, total: 9min 59s
Wall time: 8min 30s

best: current database: cairo 	 81.18% (+/- 0.77%)
final: current database: cairo 	 81.18% (+/- 0.77%)
CPU times: user 10min 12s, sys: 35 s, total: 10min 47s
Wall time: 9min 6s
```

# <a id='constrain_5'>CS_5</a>

In [11]:
%%time
dict_config_cus['distance_int'] = '5'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_55 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_55 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_55 (Conv1D)           (None, 2000, 28)          1820      
_________________________________________________________________
activation_163 (Activation)  (None, 2000, 28)          0         
_________________________________________________________________
global_max_pooling1d_55 (Glo (None, 28)                0         
_________________________________________________________________
dense_163 (Dense)            (None, 42)                1218      
________________________________________

Epoch 101/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3907 - acc: 0.8424 - val_loss: 0.5438 - val_acc: 0.8021
Epoch 102/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3970 - acc: 0.8555 - val_loss: 0.5338 - val_acc: 0.7943
Epoch 103/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3997 - acc: 0.8529 - val_loss: 0.5343 - val_acc: 0.8021
Epoch 104/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4011 - acc: 0.8307 - val_loss: 0.5402 - val_acc: 0.8021
Epoch 105/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4198 - acc: 0.8398 - val_loss: 0.5117 - val_acc: 0.8125
Epoch 106/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4099 - acc: 0.8438 - val_loss: 0.5428 - val_acc: 0.7969
Epoch 107/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4047 - acc: 0.8503 - val_loss: 0.5344 - val_acc: 0.8021
Epoch 108/1000
12/12 [==============================] -

Epoch 162/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3824 - acc: 0.8646 - val_loss: 0.5452 - val_acc: 0.8073
Epoch 163/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3787 - acc: 0.8503 - val_loss: 0.5698 - val_acc: 0.7891
Epoch 164/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3573 - acc: 0.8542 - val_loss: 0.5627 - val_acc: 0.7891
Epoch 165/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3671 - acc: 0.8438 - val_loss: 0.5583 - val_acc: 0.7943

Epoch 00165: loss improved from inf to 0.36707, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7/weights/Pbest-0-000165-0.367068-0.794271.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3756 - acc: 0.8451 - val_loss: 0.5338 - val_acc: 0.7995
Epoch 167/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3716 - acc: 0.8359 - val_loss: 0.5643 - val_acc: 0.7891
Epoch 168/1000
12/1

12/12 [==============================] - 0s 10ms/step - loss: 0.3501 - acc: 0.8568 - val_loss: 0.5724 - val_acc: 0.7917
Epoch 217/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3410 - acc: 0.8633 - val_loss: 0.5764 - val_acc: 0.7891
Epoch 218/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3412 - acc: 0.8568 - val_loss: 0.5771 - val_acc: 0.7891
Epoch 219/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3408 - acc: 0.8581 - val_loss: 0.5675 - val_acc: 0.7943
Epoch 220/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3363 - acc: 0.8685 - val_loss: 0.5777 - val_acc: 0.7891
Epoch 221/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3547 - acc: 0.8659 - val_loss: 0.5790 - val_acc: 0.7865
Epoch 222/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3287 - acc: 0.8724 - val_loss: 0.5722 - val_acc: 0.7917
Epoch 223/1000
12/12 [==============================] - 0s 10ms/step - loss

12/12 [==============================] - 0s 10ms/step - loss: 0.3440 - acc: 0.8581 - val_loss: 0.5727 - val_acc: 0.7917
Epoch 331/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3453 - acc: 0.8490 - val_loss: 0.5703 - val_acc: 0.7917
Epoch 332/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3424 - acc: 0.8555 - val_loss: 0.5526 - val_acc: 0.7969
Epoch 333/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3645 - acc: 0.8568 - val_loss: 0.5699 - val_acc: 0.7917
Epoch 334/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3426 - acc: 0.8568 - val_loss: 0.5781 - val_acc: 0.7891
Epoch 335/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3242 - acc: 0.8581 - val_loss: 0.5779 - val_acc: 0.7891
Epoch 336/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3549 - acc: 0.8607 - val_loss: 0.5807 - val_acc: 0.7891
Epoch 337/1000
12/12 [==============================] - 0s 10ms/step - loss

Epoch 447/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3367 - acc: 0.8659 - val_loss: 0.5682 - val_acc: 0.7969
Epoch 448/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3498 - acc: 0.8646 - val_loss: 0.5704 - val_acc: 0.7917
Epoch 449/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3438 - acc: 0.8555 - val_loss: 0.5588 - val_acc: 0.7969
Epoch 450/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3402 - acc: 0.8594 - val_loss: 0.5756 - val_acc: 0.7917
Epoch 451/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3478 - acc: 0.8542 - val_loss: 0.5806 - val_acc: 0.7865
Epoch 452/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3398 - acc: 0.8633 - val_loss: 0.5493 - val_acc: 0.7943
Epoch 453/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3422 - acc: 0.8685 - val_loss: 0.5799 - val_acc: 0.7891
Epoch 454/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 10ms/step - loss: 0.3740 - acc: 0.8477 - val_loss: 0.5718 - val_acc: 0.7943
Epoch 504/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3276 - acc: 0.8711 - val_loss: 0.5827 - val_acc: 0.7865
Epoch 505/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3429 - acc: 0.8568 - val_loss: 0.5752 - val_acc: 0.7891
Epoch 506/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3479 - acc: 0.8490 - val_loss: 0.5803 - val_acc: 0.7865
Epoch 507/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3522 - acc: 0.8646 - val_loss: 0.5618 - val_acc: 0.7943
Epoch 508/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3357 - acc: 0.8620 - val_loss: 0.5829 - val_acc: 0.7865
Epoch 509/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3353 - acc: 0.8633 - val_loss: 0.5502 - val_acc: 0.7943
Epoch 510/1000
12/12 [==============================] - 0s 10ms/step - l

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 2s 4ms/step
0-cairo:	acc: 79.08%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 183ms/step - loss: 1.3165 - acc: 0.5977 - val_loss: 1.0577 - val_acc: 0.6406
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0722 - acc: 0.6328 - val_loss: 0.9600 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9709 - acc: 0.6602 - val_loss: 0.9140 - val_acc: 0.6849
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9228 - acc: 0.6667 - val_loss: 0.8264 - val_acc: 0.6953
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8669 - acc: 0.6888 - val_loss: 0.7943 - val_acc: 0.7135
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8206 - acc: 0.7096 - val_loss: 0.7434 - val_acc: 0.7604
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7822 - acc: 0.7188 - val_loss: 0.7284 - val_acc: 0.7604
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - 

Epoch 117/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3968 - acc: 0.8451 - val_loss: 0.5130 - val_acc: 0.8177
Epoch 118/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3676 - acc: 0.8516 - val_loss: 0.5193 - val_acc: 0.8125
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3913 - acc: 0.8372 - val_loss: 0.5190 - val_acc: 0.8047
Epoch 120/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3708 - acc: 0.8568 - val_loss: 0.5203 - val_acc: 0.8099
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3545 - acc: 0.8581 - val_loss: 0.5256 - val_acc: 0.8073
Epoch 122/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3624 - acc: 0.8659 - val_loss: 0.5134 - val_acc: 0.8151
Epoch 123/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3682 - acc: 0.8581 - val_loss: 0.5358 - val_acc: 0.8099
Epoch 124/1000
12/12 [==============================] - 

Epoch 230/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3425 - acc: 0.8607 - val_loss: 0.5271 - val_acc: 0.8229
Epoch 231/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3429 - acc: 0.8607 - val_loss: 0.5364 - val_acc: 0.8177
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3352 - acc: 0.8763 - val_loss: 0.5365 - val_acc: 0.8177
Epoch 233/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3435 - acc: 0.8698 - val_loss: 0.5424 - val_acc: 0.8125
Epoch 234/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3319 - acc: 0.8711 - val_loss: 0.5309 - val_acc: 0.8177

Epoch 00234: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 235/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3257 - acc: 0.8633 - val_loss: 0.5432 - val_acc: 0.8099
Epoch 236/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3432 - acc: 0.8724 - val_loss: 

12/12 [==============================] - 0s 10ms/step - loss: 0.3449 - acc: 0.8568 - val_loss: 0.5455 - val_acc: 0.8125
Epoch 346/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3311 - acc: 0.8711 - val_loss: 0.5448 - val_acc: 0.8125
Epoch 347/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3496 - acc: 0.8607 - val_loss: 0.5420 - val_acc: 0.8151
Epoch 348/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3328 - acc: 0.8763 - val_loss: 0.5390 - val_acc: 0.8177
Epoch 349/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3407 - acc: 0.8568 - val_loss: 0.5249 - val_acc: 0.8177
Epoch 350/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3452 - acc: 0.8568 - val_loss: 0.5309 - val_acc: 0.8203
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3403 - acc: 0.8659 - val_loss: 0.5381 - val_acc: 0.8177
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - l

Epoch 460/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3415 - acc: 0.8529 - val_loss: 0.5400 - val_acc: 0.8151
Epoch 461/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3250 - acc: 0.8789 - val_loss: 0.5315 - val_acc: 0.8151
Epoch 462/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3259 - acc: 0.8750 - val_loss: 0.5448 - val_acc: 0.8125
Epoch 463/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3341 - acc: 0.8750 - val_loss: 0.5322 - val_acc: 0.8203
Epoch 464/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3101 - acc: 0.8763 - val_loss: 0.5365 - val_acc: 0.8151
Epoch 465/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3478 - acc: 0.8607 - val_loss: 0.5307 - val_acc: 0.8151

Epoch 00465: loss improved from inf to 0.34781, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7/weights/Pbest-1-000465-0.347811-0.815104.hdf5
Epoch 466/1000
12/

Epoch 516/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3456 - acc: 0.8529 - val_loss: 0.5467 - val_acc: 0.8099
Epoch 517/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3599 - acc: 0.8646 - val_loss: 0.5293 - val_acc: 0.8151
Epoch 518/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3163 - acc: 0.8789 - val_loss: 0.5436 - val_acc: 0.8125
Epoch 519/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3401 - acc: 0.8841 - val_loss: 0.5285 - val_acc: 0.8125
Epoch 520/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3439 - acc: 0.8750 - val_loss: 0.5300 - val_acc: 0.8177
Epoch 521/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3336 - acc: 0.8854 - val_loss: 0.5447 - val_acc: 0.8125
Epoch 522/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3208 - acc: 0.8802 - val_loss: 0.5413 - val_acc: 0.8125
Epoch 523/1000
12/12 [==============================] - 

Epoch 635/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3403 - acc: 0.8659 - val_loss: 0.5353 - val_acc: 0.8203
Epoch 636/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3415 - acc: 0.8594 - val_loss: 0.5365 - val_acc: 0.8177
Epoch 637/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3321 - acc: 0.8724 - val_loss: 0.5302 - val_acc: 0.8177
Epoch 638/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3178 - acc: 0.8724 - val_loss: 0.5401 - val_acc: 0.8177
Epoch 639/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3087 - acc: 0.8854 - val_loss: 0.5391 - val_acc: 0.8151
Epoch 640/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3305 - acc: 0.8633 - val_loss: 0.5348 - val_acc: 0.8151
Epoch 641/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3289 - acc: 0.8685 - val_loss: 0.5460 - val_acc: 0.8125
Epoch 642/1000
12/12 [==============================] -

Epoch 753/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3442 - acc: 0.8633 - val_loss: 0.5278 - val_acc: 0.8151
Epoch 754/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3435 - acc: 0.8750 - val_loss: 0.5458 - val_acc: 0.8125
Epoch 755/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3246 - acc: 0.8646 - val_loss: 0.5406 - val_acc: 0.8151
Epoch 756/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3278 - acc: 0.8633 - val_loss: 0.5224 - val_acc: 0.8151
Epoch 757/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3220 - acc: 0.8789 - val_loss: 0.5448 - val_acc: 0.8151
Epoch 758/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3249 - acc: 0.8802 - val_loss: 0.5390 - val_acc: 0.8151
Epoch 759/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3161 - acc: 0.8711 - val_loss: 0.5286 - val_acc: 0.8151
Epoch 760/1000
12/12 [==============================] - 

12/12 [==============================] - 0s 10ms/step - loss: 0.3296 - acc: 0.8737 - val_loss: 0.5413 - val_acc: 0.8177

Epoch 00869: loss improved from 0.34316 to 0.32956, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7/weights/Pbest-1-000869-0.329564-0.817708.hdf5
Epoch 870/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3603 - acc: 0.8685 - val_loss: 0.5347 - val_acc: 0.8151
Epoch 871/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3286 - acc: 0.8802 - val_loss: 0.5428 - val_acc: 0.8151
Epoch 872/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3300 - acc: 0.8815 - val_loss: 0.5309 - val_acc: 0.8177
Epoch 873/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3248 - acc: 0.8685 - val_loss: 0.5399 - val_acc: 0.8177

Epoch 00873: loss improved from 0.32956 to 0.32477, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7/weights/Pbest-1-000873-0.324765-0.81

Epoch 924/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3482 - acc: 0.8529 - val_loss: 0.5445 - val_acc: 0.8151
Epoch 925/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3093 - acc: 0.8815 - val_loss: 0.5333 - val_acc: 0.8203
Epoch 926/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3395 - acc: 0.8568 - val_loss: 0.5469 - val_acc: 0.8125
Epoch 927/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3330 - acc: 0.8594 - val_loss: 0.5445 - val_acc: 0.8125
Epoch 928/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3399 - acc: 0.8607 - val_loss: 0.5459 - val_acc: 0.8125
Epoch 929/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3361 - acc: 0.8724 - val_loss: 0.5437 - val_acc: 0.8125
Epoch 930/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3409 - acc: 0.8620 - val_loss: 0.5417 - val_acc: 0.8151
Epoch 931/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 5ms/step
1-cairo:	acc: 81.59%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 192ms/step - loss: 1.3488 - acc: 0.6172 - val_loss: 1.0915 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0703 - acc: 0.6380 - val_loss: 0.9382 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9713 - acc: 0.6432 - val_loss: 0.8509 - val_acc: 0.6797
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8898 - acc: 0.6693 - val_loss: 0.7793 - val_acc: 0.7292
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8425 - acc: 0.6953 - val_loss: 0.7395 - val_acc: 0.7578
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7953 - acc: 0.7214 - val_loss: 0.7042 - val_acc: 0.7708
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7571 - acc: 0.7370 - val_loss: 0.6928 - val_acc: 0.7812
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - 

Epoch 117/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4020 - acc: 0.8424 - val_loss: 0.4864 - val_acc: 0.8229
Epoch 118/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4360 - acc: 0.8346 - val_loss: 0.5022 - val_acc: 0.8229
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4260 - acc: 0.8333 - val_loss: 0.5087 - val_acc: 0.8151
Epoch 120/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4139 - acc: 0.8411 - val_loss: 0.5076 - val_acc: 0.8203
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4108 - acc: 0.8411 - val_loss: 0.5065 - val_acc: 0.8177
Epoch 122/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4132 - acc: 0.8424 - val_loss: 0.5010 - val_acc: 0.8203
Epoch 123/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3926 - acc: 0.8490 - val_loss: 0.5057 - val_acc: 0.8125
Epoch 124/1000
12/12 [==============================] -

Epoch 174/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3904 - acc: 0.8581 - val_loss: 0.4999 - val_acc: 0.8229
Epoch 175/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4065 - acc: 0.8424 - val_loss: 0.4975 - val_acc: 0.8229
Epoch 176/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4033 - acc: 0.8477 - val_loss: 0.4986 - val_acc: 0.8229
Epoch 177/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3775 - acc: 0.8542 - val_loss: 0.5064 - val_acc: 0.8203
Epoch 178/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4012 - acc: 0.8359 - val_loss: 0.4888 - val_acc: 0.8255
Epoch 179/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3724 - acc: 0.8698 - val_loss: 0.5001 - val_acc: 0.8229
Epoch 180/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3948 - acc: 0.8568 - val_loss: 0.4998 - val_acc: 0.8255
Epoch 181/1000
12/12 [==============================] - 

12/12 [==============================] - 0s 10ms/step - loss: 0.3923 - acc: 0.8672 - val_loss: 0.4982 - val_acc: 0.8229
Epoch 287/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3720 - acc: 0.8529 - val_loss: 0.5033 - val_acc: 0.8203
Epoch 288/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3848 - acc: 0.8594 - val_loss: 0.4914 - val_acc: 0.8281
Epoch 289/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3764 - acc: 0.8503 - val_loss: 0.5034 - val_acc: 0.8203
Epoch 290/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3610 - acc: 0.8594 - val_loss: 0.5027 - val_acc: 0.8203
Epoch 291/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3925 - acc: 0.8529 - val_loss: 0.4905 - val_acc: 0.8229
Epoch 292/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3976 - acc: 0.8438 - val_loss: 0.4974 - val_acc: 0.8255
Epoch 293/1000
12/12 [==============================] - 0s 10ms/step -


Epoch 00400: saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7/weights/2-000400-0.367172-0.820312.hdf5
Epoch 401/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3875 - acc: 0.8581 - val_loss: 0.5023 - val_acc: 0.8203
Epoch 402/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3773 - acc: 0.8646 - val_loss: 0.4867 - val_acc: 0.8307
Epoch 403/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4009 - acc: 0.8451 - val_loss: 0.5042 - val_acc: 0.8203
Epoch 404/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3841 - acc: 0.8672 - val_loss: 0.4903 - val_acc: 0.8281
Epoch 405/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3670 - acc: 0.8568 - val_loss: 0.4824 - val_acc: 0.8281
Epoch 406/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3544 - acc: 0.8503 - val_loss: 0.4903 - val_acc: 0.8255
Epoch 407/1000
12/12 [==============================] - 0s 

Epoch 461/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3770 - acc: 0.8451 - val_loss: 0.4963 - val_acc: 0.8229
Epoch 462/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3914 - acc: 0.8424 - val_loss: 0.4918 - val_acc: 0.8281
Epoch 463/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3635 - acc: 0.8568 - val_loss: 0.5031 - val_acc: 0.8203
Epoch 464/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3703 - acc: 0.8581 - val_loss: 0.4964 - val_acc: 0.8255
Epoch 465/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3824 - acc: 0.8477 - val_loss: 0.4902 - val_acc: 0.8281

Epoch 00465: loss improved from inf to 0.38242, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_7/weights/Pbest-2-000465-0.382418-0.828125.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3849 - acc: 0.8490 - val_loss: 0.4979 - val_acc: 0.8255
Epoch 467/1000
12/1

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 5ms/step
2-cairo:	acc: 82.35%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.01% (+/- 1.40%)
final: current database: cairo 	 81.01% (+/- 1.40%)
CPU times: user 7min 34s, sys: 40.5 s, total: 8min 15s
Wall time: 4min 57s

```