# file name meaning

eg. 100_cairo_WCNN_2000_64_1000_1_8_1_1.ipynb

`[tag]_[dataset_name]_[method_name]_[data_length]_[batch_size]_[epochs]_[kernel_wide_base]_[kernel_number_base]_[net_deep_base]_[calculate_unit]`

In [1]:
from tools import general
import os
from tools.configure.constants import DATASETS_CONSTANT, METHOD_PARAMETER_TEMPLATE, JUPYTER_TOKEN
from tools.integration import train_val


nb_name_file = general.ipy_nb_name(JUPYTER_TOKEN["token_lists"])

Using TensorFlow backend.
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/musk/anaconda3/en

In [2]:
theNotebook = nb_name_file.split('_')
assert len(theNotebook) == 9 or len(theNotebook) == 10, 'The number of parameters should be 9 / 10'

global title_param
title_param = {
    'num': theNotebook[0],
    'dataset_name': theNotebook[1],
    'method_name': theNotebook[2],
    'data_lenght': int(theNotebook[3]),
    'batch_size': int(theNotebook[4]),
    'nb_epochs': int(theNotebook[5]),
    'kernel_wide_base': int(theNotebook[6]),
    'kernel_number_base': int(theNotebook[7]),
    'net_deep_base': int(theNotebook[8]),
    'calculation_unit': theNotebook[9] if len(theNotebook)==10 else '0',  # If not specified, the CPU is used to train the model
}

# assert title_param['dataset'] in ['cairo', 'milan', 'kyoto7', 'kyoto8', 'kyoto11'], 'Please correct the dataset name！'
# assert title_param['model_name'] in ['WCNN','LSTM'], 'The method is wrong. Please correct it！'
# assert title_param['optimizer'] in ['rms', 'adagrad'], 'The optimizer is wrong. Please correct it！'
# assert title_param['calculation_unit'] in ['0', '1', '2'], 'Error in calculation unit selection, please correct！'

display(title_param)

{'num': '658',
 'dataset_name': 'cairo',
 'method_name': 'WCNNR',
 'data_lenght': 2000,
 'batch_size': 64,
 'nb_epochs': 1000,
 'kernel_wide_base': 1,
 'kernel_number_base': 8,
 'net_deep_base': 1,
 'calculation_unit': '1'}

In [3]:
dict_config_cus = {

        "datasets_dir": DATASETS_CONSTANT["base_dir"],  # 这是公共数据集常量
        "archive_name": DATASETS_CONSTANT["archive_name"],
        "ksplit": DATASETS_CONSTANT["ksplit"],

        'distance_int': None,
    }

dict_config_cus = general.Merge(title_param, dict_config_cus)

from tools.configure.constants import WCNNR_CONSTANT as MODEL_DEFAULT_CONF

dict_config_cus = general.Merge(MODEL_DEFAULT_CONF, dict_config_cus)

In [4]:
import tensorflow as tf


if dict_config_cus['calculation_unit'] is '0':
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
else:
    if dict_config_cus['calculation_unit'] is '1':
        # 使用第0块GPU
        os.environ["CUDA_VISIBLE_DEVICES"] = "0"

    else:
        os.environ["CUDA_VISIBLE_DEVICES"] = "1"

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.Session(config=config)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

[origin](#origin)

[C](#constrain)

[CS_1](#constrain_1)

[CS_2](#constrain_2)

[CS_3](#constrain_3)

[CS_4](#constrain_4)

[CS_5](#constrain_5)


# <a id='origin'>origin</a>


In [13]:
%%time
dict_config_cus['distance_int'] = '9999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_73 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_73 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_73 (Conv1D)           (None, 2000, 32)          2080      
_________________________________________________________________
activation_217 (Activation)  (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_73 (Glo (None, 32)                0         
_________________________________________________________________
dense_217 (Dense)            (None, 48)                1584      
_____________________________________

Epoch 102/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3592 - acc: 0.8685 - val_loss: 0.5264 - val_acc: 0.7812
Epoch 103/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3947 - acc: 0.8451 - val_loss: 0.5313 - val_acc: 0.7682
Epoch 104/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3660 - acc: 0.8542 - val_loss: 0.5343 - val_acc: 0.7812
Epoch 105/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3746 - acc: 0.8620 - val_loss: 0.5238 - val_acc: 0.7708
Epoch 106/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3830 - acc: 0.8607 - val_loss: 0.5320 - val_acc: 0.7708
Epoch 107/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3696 - acc: 0.8542 - val_loss: 0.5296 - val_acc: 0.7604
Epoch 108/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3782 - acc: 0.8594 - val_loss: 0.5145 - val_acc: 0.7760
Epoch 109/1000
12/12 [==============================] -

Epoch 163/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3452 - acc: 0.8555 - val_loss: 0.5326 - val_acc: 0.7812
Epoch 164/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3226 - acc: 0.8555 - val_loss: 0.5082 - val_acc: 0.7865
Epoch 165/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3258 - acc: 0.8802 - val_loss: 0.5302 - val_acc: 0.7760

Epoch 00165: loss improved from inf to 0.32578, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_8/weights/Pbest-0-000165-0.325776-0.776042.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3390 - acc: 0.8620 - val_loss: 0.5285 - val_acc: 0.7812
Epoch 167/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3263 - acc: 0.8659 - val_loss: 0.5280 - val_acc: 0.7839
Epoch 168/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3440 - acc: 0.8594 - val_loss: 0.5243 - val_acc: 0.7891
Epoch 169/1000


Epoch 217/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3220 - acc: 0.8659 - val_loss: 0.5259 - val_acc: 0.7760
Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3318 - acc: 0.8698 - val_loss: 0.5324 - val_acc: 0.7734
Epoch 219/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3239 - acc: 0.8659 - val_loss: 0.5331 - val_acc: 0.7734
Epoch 220/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3223 - acc: 0.8672 - val_loss: 0.5358 - val_acc: 0.7760
Epoch 221/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2944 - acc: 0.8919 - val_loss: 0.5306 - val_acc: 0.7786
Epoch 222/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3303 - acc: 0.8659 - val_loss: 0.5135 - val_acc: 0.7786
Epoch 223/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3140 - acc: 0.8724 - val_loss: 0.5376 - val_acc: 0.7682
Epoch 224/1000
12/12 [==============================] -

Epoch 274/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3205 - acc: 0.8763 - val_loss: 0.5353 - val_acc: 0.7734
Epoch 275/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3079 - acc: 0.8815 - val_loss: 0.5242 - val_acc: 0.7812
Epoch 276/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3180 - acc: 0.8763 - val_loss: 0.5191 - val_acc: 0.7839
Epoch 277/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3007 - acc: 0.8789 - val_loss: 0.5278 - val_acc: 0.7760

Epoch 00277: loss improved from 0.30305 to 0.30072, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_8/weights/Pbest-0-000277-0.300715-0.776042.hdf5
Epoch 278/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3165 - acc: 0.8542 - val_loss: 0.5205 - val_acc: 0.7839
Epoch 279/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3033 - acc: 0.8802 - val_loss: 0.5331 - val_acc: 0.7734
Epoch 280/1

Epoch 389/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3054 - acc: 0.8854 - val_loss: 0.5234 - val_acc: 0.7812
Epoch 390/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3312 - acc: 0.8672 - val_loss: 0.5240 - val_acc: 0.7812
Epoch 391/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3090 - acc: 0.8672 - val_loss: 0.5290 - val_acc: 0.7812
Epoch 392/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3026 - acc: 0.8828 - val_loss: 0.5281 - val_acc: 0.7786
Epoch 393/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3119 - acc: 0.8737 - val_loss: 0.5310 - val_acc: 0.7760
Epoch 394/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3138 - acc: 0.8763 - val_loss: 0.5370 - val_acc: 0.7734
Epoch 395/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3006 - acc: 0.8711 - val_loss: 0.5242 - val_acc: 0.7786
Epoch 396/1000
12/12 [==============================] -

Epoch 449/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2888 - acc: 0.8828 - val_loss: 0.5311 - val_acc: 0.7786
Epoch 450/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3136 - acc: 0.8724 - val_loss: 0.5322 - val_acc: 0.7786
Epoch 451/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3084 - acc: 0.8711 - val_loss: 0.5319 - val_acc: 0.7760
Epoch 452/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3076 - acc: 0.8802 - val_loss: 0.5292 - val_acc: 0.7812
Epoch 453/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3035 - acc: 0.8815 - val_loss: 0.5353 - val_acc: 0.7760
Epoch 454/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3104 - acc: 0.8750 - val_loss: 0.5340 - val_acc: 0.7760
Epoch 455/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3163 - acc: 0.8919 - val_loss: 0.5174 - val_acc: 0.7812
Epoch 456/1000
12/12 [==============================] - 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 3s 7ms/step
0-cairo:	acc: 77.81%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 4s 296ms/step - loss: 1.3662 - acc: 0.5872 - val_loss: 0.9986 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0187 - acc: 0.6445 - val_loss: 0.8528 - val_acc: 0.6536
Epoch 3/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.9132 - acc: 0.6849 - val_loss: 0.7850 - val_acc: 0.7292
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8675 - acc: 0.7018 - val_loss: 0.7296 - val_acc: 0.7474
Epoch 5/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8225 - acc: 0.7135 - val_loss: 0.6956 - val_acc: 0.7370
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7819 - acc: 0.7253 - val_loss: 0.6681 - val_acc: 0.7448
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.7450 - acc: 0.7396 - val_loss: 0.6496 - val_acc: 0.7656
Epoch 8/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.3640 - acc: 0.8633 - val_loss: 0.4893 - val_acc: 0.8203
Epoch 112/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3926 - acc: 0.8438 - val_loss: 0.4848 - val_acc: 0.8177
Epoch 113/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3753 - acc: 0.8542 - val_loss: 0.4843 - val_acc: 0.8229
Epoch 114/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3692 - acc: 0.8503 - val_loss: 0.4875 - val_acc: 0.8229
Epoch 115/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3908 - acc: 0.8438 - val_loss: 0.4736 - val_acc: 0.8255
Epoch 116/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3964 - acc: 0.8424 - val_loss: 0.4897 - val_acc: 0.8151
Epoch 117/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3737 - acc: 0.8555 - val_loss: 0.4835 - val_acc: 0.8229
Epoch 118/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 228/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3326 - acc: 0.8620 - val_loss: 0.4918 - val_acc: 0.8125
Epoch 229/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3239 - acc: 0.8750 - val_loss: 0.4988 - val_acc: 0.8073
Epoch 230/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3500 - acc: 0.8581 - val_loss: 0.5003 - val_acc: 0.8073
Epoch 231/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3304 - acc: 0.8568 - val_loss: 0.4995 - val_acc: 0.8099
Epoch 232/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3231 - acc: 0.8698 - val_loss: 0.4885 - val_acc: 0.8177
Epoch 233/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3330 - acc: 0.8724 - val_loss: 0.4940 - val_acc: 0.8125
Epoch 234/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3146 - acc: 0.8815 - val_loss: 0.4769 - val_acc: 0.8151
Epoch 235/1000
12/12 [==============================] -

12/12 [==============================] - 0s 12ms/step - loss: 0.3223 - acc: 0.8685 - val_loss: 0.4976 - val_acc: 0.8099
Epoch 341/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3203 - acc: 0.8776 - val_loss: 0.4977 - val_acc: 0.8099
Epoch 342/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3260 - acc: 0.8776 - val_loss: 0.4985 - val_acc: 0.8099
Epoch 343/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3167 - acc: 0.8841 - val_loss: 0.4962 - val_acc: 0.8125
Epoch 344/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3191 - acc: 0.8685 - val_loss: 0.4866 - val_acc: 0.8125
Epoch 345/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3330 - acc: 0.8802 - val_loss: 0.4875 - val_acc: 0.8151
Epoch 346/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3422 - acc: 0.8698 - val_loss: 0.5015 - val_acc: 0.8073
Epoch 347/1000
12/12 [==============================] - 0s 13ms/step -

Epoch 455/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3018 - acc: 0.8789 - val_loss: 0.4953 - val_acc: 0.8125
Epoch 456/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3522 - acc: 0.8594 - val_loss: 0.4975 - val_acc: 0.8099
Epoch 457/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3120 - acc: 0.8893 - val_loss: 0.4865 - val_acc: 0.8151
Epoch 458/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3230 - acc: 0.8750 - val_loss: 0.4977 - val_acc: 0.8099
Epoch 459/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3233 - acc: 0.8568 - val_loss: 0.5025 - val_acc: 0.8073
Epoch 460/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2971 - acc: 0.8763 - val_loss: 0.4984 - val_acc: 0.8099
Epoch 461/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3306 - acc: 0.8763 - val_loss: 0.4998 - val_acc: 0.8099
Epoch 462/1000
12/12 [==============================] -

12/12 [==============================] - 0s 9ms/step - loss: 0.3095 - acc: 0.8828 - val_loss: 0.4917 - val_acc: 0.8125
Epoch 571/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3050 - acc: 0.8789 - val_loss: 0.4940 - val_acc: 0.8125
Epoch 572/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3129 - acc: 0.8802 - val_loss: 0.4855 - val_acc: 0.8151
Epoch 573/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3171 - acc: 0.8750 - val_loss: 0.4952 - val_acc: 0.8125

Epoch 00573: loss improved from 0.32761 to 0.31715, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_8/weights/Pbest-1-000573-0.317146-0.812500.hdf5
Epoch 574/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3385 - acc: 0.8594 - val_loss: 0.4961 - val_acc: 0.8099
Epoch 575/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3197 - acc: 0.8763 - val_loss: 0.4968 - val_acc: 0.8099
Epoch 576/1000
12/12 [=======

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 3s 8ms/step
1-cairo:	acc: 81.07%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 4s 322ms/step - loss: 1.2838 - acc: 0.6315 - val_loss: 1.0710 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.0610 - acc: 0.6393 - val_loss: 0.9412 - val_acc: 0.6745
Epoch 3/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.9579 - acc: 0.6536 - val_loss: 0.8623 - val_acc: 0.7031
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.9016 - acc: 0.6758 - val_loss: 0.7975 - val_acc: 0.7266
Epoch 5/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8340 - acc: 0.6888 - val_loss: 0.7508 - val_acc: 0.7760
Epoch 6/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.8050 - acc: 0.7266 - val_loss: 0.7183 - val_acc: 0.7865
Epoch 7/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7655 - acc: 0.7344 - val_loss: 0.6829 - val_acc: 0.7917
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3972 - acc: 0.8438 - val_loss: 0.4913 - val_acc: 0.8255
Epoch 118/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.4001 - acc: 0.8359 - val_loss: 0.4806 - val_acc: 0.8307
Epoch 119/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3998 - acc: 0.8398 - val_loss: 0.4892 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3957 - acc: 0.8516 - val_loss: 0.4882 - val_acc: 0.8359
Epoch 121/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3897 - acc: 0.8464 - val_loss: 0.4664 - val_acc: 0.8411
Epoch 122/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.4062 - acc: 0.8385 - val_loss: 0.4918 - val_acc: 0.8281
Epoch 123/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.4216 - acc: 0.8151 - val_loss: 0.4959 - val_acc: 0.8255
Epoch 124/1000
12/12 [==============================] -

Epoch 176/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3885 - acc: 0.8607 - val_loss: 0.4597 - val_acc: 0.8359
Epoch 177/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3827 - acc: 0.8581 - val_loss: 0.4902 - val_acc: 0.8307

Epoch 00177: loss improved from 0.38291 to 0.38265, saving model to ../datasets/casas/results/WCNNR/cairo/9999/20220201_2000_64_1_8/weights/Pbest-2-000177-0.382652-0.830729.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3723 - acc: 0.8594 - val_loss: 0.4836 - val_acc: 0.8359
Epoch 179/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3704 - acc: 0.8555 - val_loss: 0.4878 - val_acc: 0.8307
Epoch 180/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3803 - acc: 0.8568 - val_loss: 0.4926 - val_acc: 0.8281

Epoch 00180: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 181/1000
12/12 [==============================] - 0s 18ms/s

Epoch 232/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3887 - acc: 0.8477 - val_loss: 0.4890 - val_acc: 0.8307
Epoch 233/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.4035 - acc: 0.8424 - val_loss: 0.4863 - val_acc: 0.8307
Epoch 234/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3975 - acc: 0.8529 - val_loss: 0.4936 - val_acc: 0.8281
Epoch 235/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3656 - acc: 0.8620 - val_loss: 0.4894 - val_acc: 0.8307
Epoch 236/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3774 - acc: 0.8607 - val_loss: 0.4904 - val_acc: 0.8307
Epoch 237/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3711 - acc: 0.8451 - val_loss: 0.4882 - val_acc: 0.8307
Epoch 238/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3865 - acc: 0.8438 - val_loss: 0.4952 - val_acc: 0.8281
Epoch 239/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.3963 - acc: 0.8464 - val_loss: 0.4608 - val_acc: 0.8333
Epoch 291/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3811 - acc: 0.8542 - val_loss: 0.4880 - val_acc: 0.8307
Epoch 292/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3821 - acc: 0.8411 - val_loss: 0.4926 - val_acc: 0.8281
Epoch 293/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3905 - acc: 0.8398 - val_loss: 0.4849 - val_acc: 0.8333
Epoch 294/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3797 - acc: 0.8490 - val_loss: 0.4881 - val_acc: 0.8307
Epoch 295/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3707 - acc: 0.8711 - val_loss: 0.4861 - val_acc: 0.8333
Epoch 296/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3945 - acc: 0.8464 - val_loss: 0.4906 - val_acc: 0.8307
Epoch 297/1000
12/12 [==============================] - 0s 13ms/step -

Epoch 350/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3812 - acc: 0.8385 - val_loss: 0.4854 - val_acc: 0.8333
Epoch 351/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3923 - acc: 0.8529 - val_loss: 0.4893 - val_acc: 0.8307
Epoch 352/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3723 - acc: 0.8542 - val_loss: 0.4896 - val_acc: 0.8307
Epoch 353/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3898 - acc: 0.8477 - val_loss: 0.4759 - val_acc: 0.8333
Epoch 354/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3830 - acc: 0.8424 - val_loss: 0.4873 - val_acc: 0.8307
Epoch 355/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3877 - acc: 0.8516 - val_loss: 0.4852 - val_acc: 0.8307
Epoch 356/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3781 - acc: 0.8424 - val_loss: 0.4686 - val_acc: 0.8333
Epoch 357/1000
12/12 [==============================] -

12/12 [==============================] - 0s 17ms/step - loss: 0.3922 - acc: 0.8438 - val_loss: 0.4886 - val_acc: 0.8307
Epoch 404/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3879 - acc: 0.8581 - val_loss: 0.4888 - val_acc: 0.8333
Epoch 405/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3800 - acc: 0.8477 - val_loss: 0.4722 - val_acc: 0.8307
Epoch 406/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3913 - acc: 0.8464 - val_loss: 0.4730 - val_acc: 0.8359
Epoch 407/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3873 - acc: 0.8438 - val_loss: 0.4918 - val_acc: 0.8281
Epoch 408/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3759 - acc: 0.8594 - val_loss: 0.4925 - val_acc: 0.8281
Epoch 409/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3849 - acc: 0.8372 - val_loss: 0.4916 - val_acc: 0.8307
Epoch 410/1000
12/12 [==============================] - 0s 12ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 3s 8ms/step
2-cairo:	acc: 83.12%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.86% (+/- 0.34%)
final: current database: cairo 	 81.94% (+/- 0.41%)
CPU times: user 5min 10s, sys: 31.7 s, total: 5min 42s
Wall time: 4min 8s

best: current database: cairo 	 80.67% (+/- 2.19%)
final: current database: cairo 	 80.67% (+/- 2.19%)
CPU times: user 6min 40s, sys: 31.5 s, total: 7min 12s
Wall time: 5min 14s
```

# <a id='constrain'>C</a>

In [6]:
%%time
dict_config_cus['distance_int'] = '999'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_10 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_10 (Conv1D)           (None, 2000, 32)          2080      
_________________________________________________________________
activation_28 (Activation)   (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_10 (Glo (None, 32)                0         
_________________________________________________________________
dense_28 (Dense)             (None, 48)                1584      
______________________________________

Epoch 102/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3569 - acc: 0.8685 - val_loss: 0.4599 - val_acc: 0.8203
Epoch 103/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3773 - acc: 0.8529 - val_loss: 0.4571 - val_acc: 0.8177
Epoch 104/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3632 - acc: 0.8542 - val_loss: 0.4517 - val_acc: 0.8255
Epoch 105/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3345 - acc: 0.8763 - val_loss: 0.4575 - val_acc: 0.8229
Epoch 106/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3579 - acc: 0.8490 - val_loss: 0.4564 - val_acc: 0.8281
Epoch 107/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3686 - acc: 0.8594 - val_loss: 0.4589 - val_acc: 0.8177
Epoch 108/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3711 - acc: 0.8516 - val_loss: 0.4603 - val_acc: 0.8229
Epoch 109/1000
12/12 [==============================] -

12/12 [==============================] - 0s 17ms/step - loss: 0.3439 - acc: 0.8555 - val_loss: 0.4492 - val_acc: 0.8255
Epoch 217/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3656 - acc: 0.8581 - val_loss: 0.4555 - val_acc: 0.8203
Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3504 - acc: 0.8516 - val_loss: 0.4528 - val_acc: 0.8255
Epoch 219/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3411 - acc: 0.8646 - val_loss: 0.4547 - val_acc: 0.8203
Epoch 220/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3646 - acc: 0.8581 - val_loss: 0.4530 - val_acc: 0.8255
Epoch 221/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3505 - acc: 0.8659 - val_loss: 0.4485 - val_acc: 0.8255
Epoch 222/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3423 - acc: 0.8685 - val_loss: 0.4499 - val_acc: 0.8229
Epoch 223/1000
12/12 [==============================] - 0s 17ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3457 - acc: 0.8685 - val_loss: 0.4569 - val_acc: 0.8177
Epoch 333/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3504 - acc: 0.8646 - val_loss: 0.4372 - val_acc: 0.8255
Epoch 334/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3537 - acc: 0.8620 - val_loss: 0.4523 - val_acc: 0.8229
Epoch 335/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3398 - acc: 0.8620 - val_loss: 0.4434 - val_acc: 0.8229
Epoch 336/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3422 - acc: 0.8659 - val_loss: 0.4475 - val_acc: 0.8229
Epoch 337/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3631 - acc: 0.8607 - val_loss: 0.4536 - val_acc: 0.8177
Epoch 338/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3603 - acc: 0.8620 - val_loss: 0.4487 - val_acc: 0.8203
Epoch 339/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 389/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3426 - acc: 0.8854 - val_loss: 0.4468 - val_acc: 0.8229
Epoch 390/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3495 - acc: 0.8828 - val_loss: 0.4528 - val_acc: 0.8229
Epoch 391/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3511 - acc: 0.8594 - val_loss: 0.4584 - val_acc: 0.8177
Epoch 392/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3359 - acc: 0.8698 - val_loss: 0.4486 - val_acc: 0.8229
Epoch 393/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3518 - acc: 0.8594 - val_loss: 0.4451 - val_acc: 0.8229
Epoch 394/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3524 - acc: 0.8568 - val_loss: 0.4502 - val_acc: 0.8229
Epoch 395/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3497 - acc: 0.8685 - val_loss: 0.4536 - val_acc: 0.8229
Epoch 396/1000
12/12 [==============================] -

Epoch 449/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3379 - acc: 0.8763 - val_loss: 0.4539 - val_acc: 0.8229
Epoch 450/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3479 - acc: 0.8724 - val_loss: 0.4566 - val_acc: 0.8203
Epoch 451/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3614 - acc: 0.8555 - val_loss: 0.4490 - val_acc: 0.8229
Epoch 452/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3564 - acc: 0.8607 - val_loss: 0.4558 - val_acc: 0.8203
Epoch 453/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3494 - acc: 0.8542 - val_loss: 0.4544 - val_acc: 0.8203
Epoch 454/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3468 - acc: 0.8685 - val_loss: 0.4578 - val_acc: 0.8177
Epoch 455/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3512 - acc: 0.8594 - val_loss: 0.4501 - val_acc: 0.8229
Epoch 456/1000
12/12 [==============================] - 0s

Epoch 505/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3706 - acc: 0.8451 - val_loss: 0.4473 - val_acc: 0.8229
Epoch 506/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3496 - acc: 0.8750 - val_loss: 0.4484 - val_acc: 0.8229
Epoch 507/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3389 - acc: 0.8724 - val_loss: 0.4438 - val_acc: 0.8255
Epoch 508/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3533 - acc: 0.8659 - val_loss: 0.4545 - val_acc: 0.8203
Epoch 509/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3479 - acc: 0.8620 - val_loss: 0.4551 - val_acc: 0.8203
Epoch 510/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3372 - acc: 0.8659 - val_loss: 0.4575 - val_acc: 0.8203
Epoch 511/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3493 - acc: 0.8698 - val_loss: 0.4568 - val_acc: 0.8203
Epoch 512/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 0s 664us/step
0-cairo:	acc: 82.14%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 55ms/step - loss: 1.4594 - acc: 0.5638 - val_loss: 1.0767 - val_acc: 0.6458
Epoch 2/1000
12/12 [==============================] - 0s 13ms/step - loss: 1.1139 - acc: 0.6484 - val_loss: 0.9652 - val_acc: 0.6823
Epoch 3/1000
12/12 [==============================] - 0s 17ms/step - loss: 1.0015 - acc: 0.6849 - val_loss: 0.8893 - val_acc: 0.7214
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.9185 - acc: 0.6992 - val_loss: 0.8117 - val_acc: 0.7370
Epoch 5/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8689 - acc: 0.7161 - val_loss: 0.7633 - val_acc: 0.7578
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.8166 - acc: 0.7070 - val_loss: 0.7072 - val_acc: 0.7344
Epoch 7/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7696 - acc: 0.7266 - val_loss: 0.6827 - val_acc: 0.7448
Epoch 8/1000
12/12 [==============================

12/12 [==============================] - 0s 17ms/step - loss: 0.3843 - acc: 0.8555 - val_loss: 0.4715 - val_acc: 0.8151
Epoch 63/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3903 - acc: 0.8529 - val_loss: 0.4588 - val_acc: 0.8255
Epoch 64/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3852 - acc: 0.8620 - val_loss: 0.4675 - val_acc: 0.8203
Epoch 65/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4012 - acc: 0.8385 - val_loss: 0.4502 - val_acc: 0.8281

Epoch 00065: loss improved from inf to 0.40123, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_8/weights/Pbest-1-000065-0.401234-0.828125.hdf5
Epoch 66/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3995 - acc: 0.8294 - val_loss: 0.4666 - val_acc: 0.8125
Epoch 67/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3779 - acc: 0.8464 - val_loss: 0.4669 - val_acc: 0.8151
Epoch 68/1000
12/12 [===============

Epoch 117/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3458 - acc: 0.8659 - val_loss: 0.4619 - val_acc: 0.8099
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3229 - acc: 0.8724 - val_loss: 0.4657 - val_acc: 0.8125
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3275 - acc: 0.8698 - val_loss: 0.4723 - val_acc: 0.8177
Epoch 120/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3467 - acc: 0.8633 - val_loss: 0.4671 - val_acc: 0.8177
Epoch 121/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3365 - acc: 0.8737 - val_loss: 0.4540 - val_acc: 0.8125

Epoch 00121: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 122/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3413 - acc: 0.8659 - val_loss: 0.4617 - val_acc: 0.8125
Epoch 123/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3371 - acc: 0.8750 - val_loss:

12/12 [==============================] - 0s 11ms/step - loss: 0.3329 - acc: 0.8685 - val_loss: 0.4698 - val_acc: 0.8151
Epoch 175/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3399 - acc: 0.8698 - val_loss: 0.4641 - val_acc: 0.8177
Epoch 176/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3235 - acc: 0.8750 - val_loss: 0.4701 - val_acc: 0.8151
Epoch 177/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3314 - acc: 0.8789 - val_loss: 0.4597 - val_acc: 0.8203
Epoch 178/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3198 - acc: 0.8789 - val_loss: 0.4701 - val_acc: 0.8151
Epoch 179/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3525 - acc: 0.8542 - val_loss: 0.4703 - val_acc: 0.8151
Epoch 180/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3255 - acc: 0.8841 - val_loss: 0.4682 - val_acc: 0.8151
Epoch 181/1000
12/12 [==============================] - 0s 10ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.3402 - acc: 0.8555 - val_loss: 0.4579 - val_acc: 0.8203
Epoch 291/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3177 - acc: 0.8854 - val_loss: 0.4634 - val_acc: 0.8177
Epoch 292/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3299 - acc: 0.8737 - val_loss: 0.4673 - val_acc: 0.8151
Epoch 293/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3331 - acc: 0.8607 - val_loss: 0.4654 - val_acc: 0.8203
Epoch 294/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3317 - acc: 0.8724 - val_loss: 0.4597 - val_acc: 0.8177
Epoch 295/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3316 - acc: 0.8607 - val_loss: 0.4541 - val_acc: 0.8229
Epoch 296/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3268 - acc: 0.8776 - val_loss: 0.4686 - val_acc: 0.8151
Epoch 297/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 350/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3577 - acc: 0.8607 - val_loss: 0.4651 - val_acc: 0.8203
Epoch 351/1000
12/12 [==============================] - 0s 15ms/step - loss: 0.3236 - acc: 0.8815 - val_loss: 0.4679 - val_acc: 0.8177
Epoch 352/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.3266 - acc: 0.8763 - val_loss: 0.4679 - val_acc: 0.8177
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3402 - acc: 0.8633 - val_loss: 0.4671 - val_acc: 0.8177
Epoch 354/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3317 - acc: 0.8698 - val_loss: 0.4664 - val_acc: 0.8177
Epoch 355/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3247 - acc: 0.8776 - val_loss: 0.4679 - val_acc: 0.8151
Epoch 356/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3346 - acc: 0.8672 - val_loss: 0.4595 - val_acc: 0.8203
Epoch 357/1000
12/12 [==============================] - 0

12/12 [==============================] - 0s 17ms/step - loss: 0.3403 - acc: 0.8659 - val_loss: 0.4686 - val_acc: 0.8177
Epoch 408/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3326 - acc: 0.8698 - val_loss: 0.4708 - val_acc: 0.8151
Epoch 409/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3271 - acc: 0.8685 - val_loss: 0.4585 - val_acc: 0.8177
Epoch 410/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3350 - acc: 0.8698 - val_loss: 0.4703 - val_acc: 0.8151
Epoch 411/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3324 - acc: 0.8763 - val_loss: 0.4612 - val_acc: 0.8229
Epoch 412/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3201 - acc: 0.8828 - val_loss: 0.4558 - val_acc: 0.8255
Epoch 413/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.2923 - acc: 0.8854 - val_loss: 0.4655 - val_acc: 0.8177
Epoch 414/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3334 - acc: 0.8711 - val_loss: 0.4675 - val_acc: 0.8177
Epoch 524/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3348 - acc: 0.8620 - val_loss: 0.4502 - val_acc: 0.8255
Epoch 525/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3539 - acc: 0.8542 - val_loss: 0.4693 - val_acc: 0.8151
Epoch 526/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3283 - acc: 0.8841 - val_loss: 0.4689 - val_acc: 0.8151
Epoch 527/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3463 - acc: 0.8698 - val_loss: 0.4648 - val_acc: 0.8203
Epoch 528/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3335 - acc: 0.8711 - val_loss: 0.4697 - val_acc: 0.8177
Epoch 529/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3284 - acc: 0.8607 - val_loss: 0.4522 - val_acc: 0.8177
Epoch 530/1000
12/12 [==============================] - 0s 17ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 840us/step
1-cairo:	acc: 81.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Begin training ...
Epoch 1/1000
12/12 [==============================] - 1s 63ms/step - loss: 1.3693 - acc: 0.5716 - val_loss: 1.0981 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.0304 - acc: 0.6432 - val_loss: 0.9404 - val_acc: 0.6641
Epoch 3/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.9299 - acc: 0.6758 - val_loss: 0.8552 - val_acc: 0.6979
Epoch 4/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8649 - acc: 0.6979 - val_loss: 0.8088 - val_acc: 0.7214
Epoch 5/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8361 - acc: 0.7161 - val_loss: 0.7607 - val_acc: 0.7500
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7806 - acc: 0.7357 - val_loss: 0.7195 - val_acc: 0.7526
Epoch 7/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.7318 - acc: 0.7539 - val_loss: 0.6820 - val_acc: 0.7552
Epoch 8/1000
12/12 [==============================

12/12 [==============================] - 0s 19ms/step - loss: 0.4408 - acc: 0.8216 - val_loss: 0.4940 - val_acc: 0.8411
Epoch 63/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4432 - acc: 0.8281 - val_loss: 0.5041 - val_acc: 0.8333
Epoch 64/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4560 - acc: 0.8294 - val_loss: 0.4970 - val_acc: 0.8385
Epoch 65/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4461 - acc: 0.8320 - val_loss: 0.4960 - val_acc: 0.8411

Epoch 00065: loss improved from inf to 0.44609, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_8/weights/Pbest-2-000065-0.446087-0.841146.hdf5
Epoch 66/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.4376 - acc: 0.8242 - val_loss: 0.4977 - val_acc: 0.8411
Epoch 67/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.4340 - acc: 0.8203 - val_loss: 0.4851 - val_acc: 0.8516
Epoch 68/1000
12/12 [===============

12/12 [==============================] - 0s 16ms/step - loss: 0.4053 - acc: 0.8346 - val_loss: 0.4871 - val_acc: 0.8516
Epoch 174/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3981 - acc: 0.8516 - val_loss: 0.4778 - val_acc: 0.8516
Epoch 175/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3949 - acc: 0.8424 - val_loss: 0.4820 - val_acc: 0.8516
Epoch 176/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3919 - acc: 0.8438 - val_loss: 0.4794 - val_acc: 0.8516
Epoch 177/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.4170 - acc: 0.8333 - val_loss: 0.4932 - val_acc: 0.8490
Epoch 178/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.4037 - acc: 0.8346 - val_loss: 0.4811 - val_acc: 0.8516
Epoch 179/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3824 - acc: 0.8646 - val_loss: 0.4876 - val_acc: 0.8542
Epoch 180/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 233/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3973 - acc: 0.8490 - val_loss: 0.4949 - val_acc: 0.8464
Epoch 234/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3808 - acc: 0.8659 - val_loss: 0.4849 - val_acc: 0.8516
Epoch 235/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3816 - acc: 0.8555 - val_loss: 0.4884 - val_acc: 0.8490
Epoch 236/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3924 - acc: 0.8398 - val_loss: 0.4912 - val_acc: 0.8490
Epoch 237/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4140 - acc: 0.8451 - val_loss: 0.4945 - val_acc: 0.8464
Epoch 238/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4041 - acc: 0.8411 - val_loss: 0.4833 - val_acc: 0.8516
Epoch 239/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3953 - acc: 0.8503 - val_loss: 0.4934 - val_acc: 0.8464
Epoch 240/1000
12/12 [==============================] -

Epoch 348/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4009 - acc: 0.8438 - val_loss: 0.4768 - val_acc: 0.8516
Epoch 349/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3952 - acc: 0.8555 - val_loss: 0.4838 - val_acc: 0.8490
Epoch 350/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.4129 - acc: 0.8320 - val_loss: 0.4948 - val_acc: 0.8464
Epoch 351/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4055 - acc: 0.8451 - val_loss: 0.4822 - val_acc: 0.8542
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3982 - acc: 0.8529 - val_loss: 0.4921 - val_acc: 0.8464
Epoch 353/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3863 - acc: 0.8594 - val_loss: 0.4880 - val_acc: 0.8490
Epoch 354/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.4078 - acc: 0.8464 - val_loss: 0.4641 - val_acc: 0.8542
Epoch 355/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.4002 - acc: 0.8503 - val_loss: 0.4864 - val_acc: 0.8516
Epoch 406/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.4041 - acc: 0.8359 - val_loss: 0.4867 - val_acc: 0.8516
Epoch 407/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.4022 - acc: 0.8359 - val_loss: 0.4933 - val_acc: 0.8464
Epoch 408/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3880 - acc: 0.8503 - val_loss: 0.4922 - val_acc: 0.8464
Epoch 409/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3717 - acc: 0.8555 - val_loss: 0.4900 - val_acc: 0.8490
Epoch 410/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3833 - acc: 0.8464 - val_loss: 0.4754 - val_acc: 0.8516
Epoch 411/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3987 - acc: 0.8464 - val_loss: 0.4895 - val_acc: 0.8490
Epoch 412/1000
12/12 [==============================] - 0s 10ms/step -


Epoch 00465: loss improved from inf to 0.38827, saving model to ../datasets/casas/results/WCNNR/cairo/999/20220201_2000_64_1_8/weights/Pbest-2-000465-0.388271-0.848958.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3911 - acc: 0.8438 - val_loss: 0.4946 - val_acc: 0.8464
Epoch 467/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3944 - acc: 0.8581 - val_loss: 0.4941 - val_acc: 0.8464
Epoch 468/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3936 - acc: 0.8568 - val_loss: 0.4903 - val_acc: 0.8490
Epoch 469/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3892 - acc: 0.8542 - val_loss: 0.4929 - val_acc: 0.8464
Epoch 470/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3888 - acc: 0.8464 - val_loss: 0.4894 - val_acc: 0.8490
Epoch 471/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3949 - acc: 0.8490 - val_loss: 0.4922 - val_acc: 0.8490
Epoch 472/1000
1

12/12 [==============================] - 0s 11ms/step - loss: 0.3994 - acc: 0.8398 - val_loss: 0.4941 - val_acc: 0.8464
Epoch 524/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3858 - acc: 0.8529 - val_loss: 0.4898 - val_acc: 0.8464
Epoch 525/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3899 - acc: 0.8398 - val_loss: 0.4822 - val_acc: 0.8490
Epoch 526/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4083 - acc: 0.8411 - val_loss: 0.4843 - val_acc: 0.8516
Epoch 527/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4079 - acc: 0.8490 - val_loss: 0.4851 - val_acc: 0.8490
Epoch 528/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3847 - acc: 0.8529 - val_loss: 0.4943 - val_acc: 0.8464
Epoch 529/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3965 - acc: 0.8424 - val_loss: 0.4903 - val_acc: 0.8464
Epoch 530/1000
12/12 [==============================] - 0s 11ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 0s 998us/step
2-cairo:	acc: 84.91%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 82.96% (+/- 1.38%)
final: current database: cairo 	 82.96% (+/- 1.38%)
CPU times: user 5min 46s, sys: 33.8 s, total: 6min 20s
Wall time: 5min 10s

```

# <a id='constrain_1'>CS_1</a>

In [7]:
%%time
dict_config_cus['distance_int'] = '1'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_19 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_19 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_19 (Conv1D)           (None, 2000, 32)          2080      
_________________________________________________________________
activation_55 (Activation)   (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_19 (Glo (None, 32)                0         
_________________________________________________________________
dense_55 (Dense)             (None, 48)                1584      
________________________________________

12/12 [==============================] - 0s 18ms/step - loss: 0.1917 - acc: 0.9297 - val_loss: 0.3697 - val_acc: 0.9141
Epoch 103/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1954 - acc: 0.9232 - val_loss: 0.3251 - val_acc: 0.9193
Epoch 104/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.1965 - acc: 0.9258 - val_loss: 0.3650 - val_acc: 0.9141
Epoch 105/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1957 - acc: 0.9219 - val_loss: 0.3513 - val_acc: 0.9141
Epoch 106/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.1951 - acc: 0.9258 - val_loss: 0.3613 - val_acc: 0.9141
Epoch 107/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1881 - acc: 0.9258 - val_loss: 0.3611 - val_acc: 0.9141
Epoch 108/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.1772 - acc: 0.9336 - val_loss: 0.3586 - val_acc: 0.9167
Epoch 109/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.1826 - acc: 0.9258 - val_loss: 0.3849 - val_acc: 0.9167
Epoch 217/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1758 - acc: 0.9349 - val_loss: 0.3668 - val_acc: 0.9219
Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1794 - acc: 0.9336 - val_loss: 0.3831 - val_acc: 0.9167
Epoch 219/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1818 - acc: 0.9297 - val_loss: 0.3766 - val_acc: 0.9219
Epoch 220/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1941 - acc: 0.9206 - val_loss: 0.3755 - val_acc: 0.9219
Epoch 221/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1813 - acc: 0.9271 - val_loss: 0.3831 - val_acc: 0.9167
Epoch 222/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1887 - acc: 0.9219 - val_loss: 0.3828 - val_acc: 0.9167
Epoch 223/1000
12/12 [==============================] - 0s 19ms/step -

12/12 [==============================] - 0s 17ms/step - loss: 0.1748 - acc: 0.9310 - val_loss: 0.3765 - val_acc: 0.9193
Epoch 276/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1883 - acc: 0.9284 - val_loss: 0.3783 - val_acc: 0.9193
Epoch 277/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.1737 - acc: 0.9297 - val_loss: 0.3827 - val_acc: 0.9167

Epoch 00277: loss improved from 0.17763 to 0.17368, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_8/weights/Pbest-0-000277-0.173677-0.916667.hdf5
Epoch 278/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.1931 - acc: 0.9271 - val_loss: 0.3836 - val_acc: 0.9167
Epoch 279/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.1732 - acc: 0.9310 - val_loss: 0.3802 - val_acc: 0.9193
Epoch 280/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.1893 - acc: 0.9310 - val_loss: 0.3840 - val_acc: 0.9167
Epoch 281/1000
12/12 [=======

12/12 [==============================] - 0s 17ms/step - loss: 0.1697 - acc: 0.9388 - val_loss: 0.3845 - val_acc: 0.9167
Epoch 392/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1729 - acc: 0.9258 - val_loss: 0.3720 - val_acc: 0.9219
Epoch 393/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1784 - acc: 0.9310 - val_loss: 0.3810 - val_acc: 0.9193
Epoch 394/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1835 - acc: 0.9310 - val_loss: 0.3847 - val_acc: 0.9167
Epoch 395/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1846 - acc: 0.9271 - val_loss: 0.3416 - val_acc: 0.9219
Epoch 396/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.1817 - acc: 0.9349 - val_loss: 0.3601 - val_acc: 0.9219
Epoch 397/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1772 - acc: 0.9258 - val_loss: 0.3843 - val_acc: 0.9167
Epoch 398/1000
12/12 [==============================] - 0s 17ms/step -

Epoch 451/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.1724 - acc: 0.9349 - val_loss: 0.3850 - val_acc: 0.9167
Epoch 452/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.1765 - acc: 0.9336 - val_loss: 0.3850 - val_acc: 0.9167
Epoch 453/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1747 - acc: 0.9310 - val_loss: 0.3819 - val_acc: 0.9193
Epoch 454/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1754 - acc: 0.9362 - val_loss: 0.3754 - val_acc: 0.9193
Epoch 455/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1682 - acc: 0.9362 - val_loss: 0.3732 - val_acc: 0.9219
Epoch 456/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1735 - acc: 0.9271 - val_loss: 0.3822 - val_acc: 0.9167
Epoch 457/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1758 - acc: 0.9297 - val_loss: 0.3764 - val_acc: 0.9193
Epoch 458/1000
12/12 [==============================] -

Epoch 507/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1906 - acc: 0.9323 - val_loss: 0.3832 - val_acc: 0.9167
Epoch 508/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1727 - acc: 0.9310 - val_loss: 0.3625 - val_acc: 0.9193
Epoch 509/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.1749 - acc: 0.9245 - val_loss: 0.3790 - val_acc: 0.9193
Epoch 510/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1897 - acc: 0.9284 - val_loss: 0.3853 - val_acc: 0.9167
Epoch 511/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.1764 - acc: 0.9336 - val_loss: 0.3840 - val_acc: 0.9167
Epoch 512/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1904 - acc: 0.9284 - val_loss: 0.3837 - val_acc: 0.9167
Epoch 513/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1860 - acc: 0.9323 - val_loss: 0.3833 - val_acc: 0.9167
Epoch 514/1000
12/12 [==============================] -

392/392 [==============================] - 0s 1ms/step
0-cairo:	acc: 91.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 0s 1ms/step
0-cairo:	acc: 91.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 72ms/step - loss: 1.2914 - acc: 0.5703 - val_loss: 0.8852 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.8257 - acc: 0.6784 - val_loss: 0.6687 - val_acc: 0.8333
Epoch 3/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.6497 - acc: 0.8060 - val_loss: 0.5086 - val_acc: 0.8724
Epoch 4/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.5051 - acc: 0.8607 - val_loss: 0.3942 - val_acc: 0.9062
Epoch 5/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.4347 - acc: 0.8750 - val_loss: 0.3497 - val_acc: 0.9010
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3911 - acc: 0.8906 - val_loss: 0.3217 - val_acc: 0.9010
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3694 - acc: 0.8802 - val_loss: 0.3067 - val_acc: 0.8984
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step - 

Epoch 117/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1855 - acc: 0.9323 - val_loss: 0.2669 - val_acc: 0.9167
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1822 - acc: 0.9258 - val_loss: 0.2728 - val_acc: 0.9115
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1858 - acc: 0.9271 - val_loss: 0.2703 - val_acc: 0.9089
Epoch 120/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1845 - acc: 0.9284 - val_loss: 0.2720 - val_acc: 0.9115
Epoch 121/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1633 - acc: 0.9388 - val_loss: 0.2727 - val_acc: 0.9115
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1819 - acc: 0.9297 - val_loss: 0.2782 - val_acc: 0.9115
Epoch 123/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1829 - acc: 0.9336 - val_loss: 0.2723 - val_acc: 0.9141
Epoch 124/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.1709 - acc: 0.9336 - val_loss: 0.2793 - val_acc: 0.9115
Epoch 176/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1728 - acc: 0.9323 - val_loss: 0.2774 - val_acc: 0.9141
Epoch 177/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1701 - acc: 0.9284 - val_loss: 0.2786 - val_acc: 0.9167
Epoch 178/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.1649 - acc: 0.9375 - val_loss: 0.2614 - val_acc: 0.9062
Epoch 179/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1684 - acc: 0.9323 - val_loss: 0.2694 - val_acc: 0.9167

Epoch 00179: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
Epoch 180/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1662 - acc: 0.9284 - val_loss: 0.2785 - val_acc: 0.9036
Epoch 181/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1751 - acc: 0.9245 - val_loss: 0.2698 - val_a

12/12 [==============================] - 0s 11ms/step - loss: 0.1641 - acc: 0.9375 - val_loss: 0.2830 - val_acc: 0.9089
Epoch 289/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1628 - acc: 0.9297 - val_loss: 0.2579 - val_acc: 0.9115
Epoch 290/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1602 - acc: 0.9284 - val_loss: 0.2871 - val_acc: 0.9062
Epoch 291/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1610 - acc: 0.9375 - val_loss: 0.2819 - val_acc: 0.9089
Epoch 292/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1634 - acc: 0.9323 - val_loss: 0.2821 - val_acc: 0.9089
Epoch 293/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1615 - acc: 0.9336 - val_loss: 0.2821 - val_acc: 0.9089

Epoch 00293: loss improved from 0.16163 to 0.16153, saving model to ../datasets/casas/results/WCNNR/cairo/1/20220201_2000_64_1_8/weights/Pbest-1-000293-0.161528-0.908854.hdf5
Epoch 294/1000
12/12 [=======

12/12 [==============================] - 0s 8ms/step - loss: 0.1514 - acc: 0.9414 - val_loss: 0.2830 - val_acc: 0.9089
Epoch 405/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1615 - acc: 0.9271 - val_loss: 0.2838 - val_acc: 0.9089
Epoch 406/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1767 - acc: 0.9336 - val_loss: 0.2838 - val_acc: 0.9089
Epoch 407/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1616 - acc: 0.9362 - val_loss: 0.2855 - val_acc: 0.9062
Epoch 408/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1650 - acc: 0.9336 - val_loss: 0.2829 - val_acc: 0.9062
Epoch 409/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1644 - acc: 0.9336 - val_loss: 0.2845 - val_acc: 0.9089
Epoch 410/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1535 - acc: 0.9414 - val_loss: 0.2829 - val_acc: 0.9089
Epoch 411/1000
12/12 [==============================] - 0s 11ms/step - 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 1ms/step
1-cairo:	acc: 90.79%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Epoch 1/1000
12/12 [==============================] - 1s 85ms/step - loss: 1.1499 - acc: 0.6146 - val_loss: 0.8441 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.7815 - acc: 0.7240 - val_loss: 0.7016 - val_acc: 0.7630
Epoch 3/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.6389 - acc: 0.7956 - val_loss: 0.5899 - val_acc: 0.7969
Epoch 4/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.5490 - acc: 0.8281 - val_loss: 0.4908 - val_acc: 0.8542
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.4643 - acc: 0.8737 - val_loss: 0.4437 - val_acc: 0.8568
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.4022 - acc: 0.8789 - val_loss: 0.4372 - val_acc: 0.8594
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3634 - acc: 0.8828 - val_loss: 0.3951 - val_acc: 0.8672
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step - 

12/12 [==============================] - 0s 18ms/step - loss: 0.1667 - acc: 0.9401 - val_loss: 0.4054 - val_acc: 0.9010
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1531 - acc: 0.9453 - val_loss: 0.3930 - val_acc: 0.9089
Epoch 120/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.1627 - acc: 0.9336 - val_loss: 0.4032 - val_acc: 0.9089
Epoch 121/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1532 - acc: 0.9453 - val_loss: 0.4091 - val_acc: 0.9062
Epoch 122/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.1612 - acc: 0.9414 - val_loss: 0.4092 - val_acc: 0.9062
Epoch 123/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1648 - acc: 0.9401 - val_loss: 0.4090 - val_acc: 0.9062
Epoch 124/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1556 - acc: 0.9440 - val_loss: 0.3791 - val_acc: 0.9141
Epoch 125/1000
12/12 [==============================] - 0s 17ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.1500 - acc: 0.9427 - val_loss: 0.4061 - val_acc: 0.9036
Epoch 232/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1460 - acc: 0.9440 - val_loss: 0.4027 - val_acc: 0.9062
Epoch 233/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1532 - acc: 0.9453 - val_loss: 0.4190 - val_acc: 0.9036
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1603 - acc: 0.9427 - val_loss: 0.4114 - val_acc: 0.9062
Epoch 235/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.1514 - acc: 0.9466 - val_loss: 0.4233 - val_acc: 0.9010
Epoch 236/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.1619 - acc: 0.9349 - val_loss: 0.3940 - val_acc: 0.9062
Epoch 237/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.1550 - acc: 0.9414 - val_loss: 0.4228 - val_acc: 0.9010
Epoch 238/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.1633 - acc: 0.9375 - val_loss: 0.4167 - val_acc: 0.9062
Epoch 348/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1554 - acc: 0.9427 - val_loss: 0.4223 - val_acc: 0.9010
Epoch 349/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1626 - acc: 0.9466 - val_loss: 0.4185 - val_acc: 0.9036
Epoch 350/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.1540 - acc: 0.9427 - val_loss: 0.4236 - val_acc: 0.9010
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1559 - acc: 0.9427 - val_loss: 0.4166 - val_acc: 0.9036
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.1456 - acc: 0.9427 - val_loss: 0.4201 - val_acc: 0.9036
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.1508 - acc: 0.9453 - val_loss: 0.4236 - val_acc: 0.9010
Epoch 354/1000
12/12 [==============================] - 0s 10ms/step - lo

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
2-cairo:	acc: 90.28%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 90.97% (+/- 0.65%)
final: current database: cairo 	 90.97% (+/- 0.65%)
CPU times: user 5min 16s, sys: 30 s, total: 5min 46s
Wall time: 4min 51s

```

# <a id='constrain_2'>CS_2</a>

In [8]:
%%time
dict_config_cus['distance_int'] = '2'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_28 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_28 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_28 (Conv1D)           (None, 2000, 32)          2080      
_________________________________________________________________
activation_82 (Activation)   (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_28 (Glo (None, 32)                0         
_________________________________________________________________
dense_82 (Dense)             (None, 48)                1584      
________________________________________

12/12 [==============================] - 0s 11ms/step - loss: 0.3355 - acc: 0.8646 - val_loss: 0.4810 - val_acc: 0.8125
Epoch 104/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3516 - acc: 0.8698 - val_loss: 0.4954 - val_acc: 0.7969
Epoch 105/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3253 - acc: 0.8633 - val_loss: 0.4863 - val_acc: 0.7917
Epoch 106/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3265 - acc: 0.8789 - val_loss: 0.4962 - val_acc: 0.7943
Epoch 107/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3417 - acc: 0.8711 - val_loss: 0.4698 - val_acc: 0.7969
Epoch 108/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3325 - acc: 0.8711 - val_loss: 0.4664 - val_acc: 0.8099
Epoch 109/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3619 - acc: 0.8594 - val_loss: 0.4797 - val_acc: 0.7995
Epoch 110/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3256 - acc: 0.8685 - val_loss: 0.4762 - val_acc: 0.8047
Epoch 218/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3413 - acc: 0.8698 - val_loss: 0.4941 - val_acc: 0.7995
Epoch 219/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3244 - acc: 0.8724 - val_loss: 0.4843 - val_acc: 0.8021
Epoch 220/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3171 - acc: 0.8711 - val_loss: 0.4797 - val_acc: 0.8021
Epoch 221/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3139 - acc: 0.8737 - val_loss: 0.4862 - val_acc: 0.8021
Epoch 222/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3220 - acc: 0.8776 - val_loss: 0.4606 - val_acc: 0.8125
Epoch 223/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3378 - acc: 0.8659 - val_loss: 0.4903 - val_acc: 0.8021
Epoch 224/1000
12/12 [==============================] - 0s 17ms/step -

12/12 [==============================] - 0s 17ms/step - loss: 0.3085 - acc: 0.8802 - val_loss: 0.4842 - val_acc: 0.8047
Epoch 335/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3286 - acc: 0.8737 - val_loss: 0.4926 - val_acc: 0.8021
Epoch 336/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3139 - acc: 0.8750 - val_loss: 0.4716 - val_acc: 0.8047
Epoch 337/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3130 - acc: 0.8802 - val_loss: 0.4791 - val_acc: 0.8073
Epoch 338/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3278 - acc: 0.8789 - val_loss: 0.4904 - val_acc: 0.8021
Epoch 339/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3180 - acc: 0.8802 - val_loss: 0.4773 - val_acc: 0.8047
Epoch 340/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3175 - acc: 0.8802 - val_loss: 0.4887 - val_acc: 0.8021
Epoch 341/1000
12/12 [==============================] - 0s 17ms/step -

Epoch 391/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3210 - acc: 0.8698 - val_loss: 0.4931 - val_acc: 0.8021
Epoch 392/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3181 - acc: 0.8672 - val_loss: 0.4887 - val_acc: 0.8047
Epoch 393/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3244 - acc: 0.8633 - val_loss: 0.4880 - val_acc: 0.8047
Epoch 394/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3115 - acc: 0.8711 - val_loss: 0.4737 - val_acc: 0.8073
Epoch 395/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3205 - acc: 0.8841 - val_loss: 0.4871 - val_acc: 0.8047
Epoch 396/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3223 - acc: 0.8802 - val_loss: 0.4914 - val_acc: 0.8021
Epoch 397/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3168 - acc: 0.8698 - val_loss: 0.4821 - val_acc: 0.8021

Epoch 00397: loss improved from 0.31784 to 0.31681, sa

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 2ms/step
0-cairo:	acc: 80.36%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 105ms/step - loss: 1.4024 - acc: 0.5768 - val_loss: 1.1098 - val_acc: 0.6380
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.1078 - acc: 0.6380 - val_loss: 0.9883 - val_acc: 0.6354
Epoch 3/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.9934 - acc: 0.6445 - val_loss: 0.8508 - val_acc: 0.6979
Epoch 4/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8720 - acc: 0.7057 - val_loss: 0.7543 - val_acc: 0.7396
Epoch 5/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.8067 - acc: 0.7318 - val_loss: 0.6772 - val_acc: 0.7526
Epoch 6/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7445 - acc: 0.7461 - val_loss: 0.6178 - val_acc: 0.7708
Epoch 7/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7022 - acc: 0.7500 - val_loss: 0.5819 - val_acc: 0.8021
Epoch 8/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3120 - acc: 0.8659 - val_loss: 0.4179 - val_acc: 0.8359
Epoch 118/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3381 - acc: 0.8646 - val_loss: 0.4184 - val_acc: 0.8411
Epoch 119/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3302 - acc: 0.8698 - val_loss: 0.3871 - val_acc: 0.8516
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3406 - acc: 0.8711 - val_loss: 0.4242 - val_acc: 0.8333
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3456 - acc: 0.8737 - val_loss: 0.4215 - val_acc: 0.8359
Epoch 122/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3412 - acc: 0.8685 - val_loss: 0.4164 - val_acc: 0.8438
Epoch 123/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3427 - acc: 0.8672 - val_loss: 0.4101 - val_acc: 0.8464
Epoch 124/1000
12/12 [==============================] -

Epoch 176/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3000 - acc: 0.8854 - val_loss: 0.4188 - val_acc: 0.8438
Epoch 177/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3025 - acc: 0.8776 - val_loss: 0.4254 - val_acc: 0.8411

Epoch 00177: loss improved from 0.30866 to 0.30254, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/weights/Pbest-1-000177-0.302544-0.841146.hdf5
Epoch 178/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3097 - acc: 0.8711 - val_loss: 0.4227 - val_acc: 0.8385
Epoch 179/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3170 - acc: 0.8633 - val_loss: 0.4257 - val_acc: 0.8385
Epoch 180/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3003 - acc: 0.8737 - val_loss: 0.4215 - val_acc: 0.8411
Epoch 181/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3197 - acc: 0.8724 - val_loss: 0.4255 - val_acc: 0.8385
Epoch 182/1000

12/12 [==============================] - 0s 17ms/step - loss: 0.3125 - acc: 0.8763 - val_loss: 0.4269 - val_acc: 0.8333
Epoch 289/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3009 - acc: 0.8737 - val_loss: 0.3994 - val_acc: 0.8385
Epoch 290/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3173 - acc: 0.8685 - val_loss: 0.4256 - val_acc: 0.8333
Epoch 291/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.2995 - acc: 0.8815 - val_loss: 0.4077 - val_acc: 0.8411
Epoch 292/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2889 - acc: 0.8880 - val_loss: 0.4250 - val_acc: 0.8359
Epoch 293/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3112 - acc: 0.8698 - val_loss: 0.4265 - val_acc: 0.8333
Epoch 294/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3129 - acc: 0.8815 - val_loss: 0.4050 - val_acc: 0.8438
Epoch 295/1000
12/12 [==============================] - 0s 17ms/step -

Epoch 348/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3059 - acc: 0.8763 - val_loss: 0.4232 - val_acc: 0.8359
Epoch 349/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3032 - acc: 0.8711 - val_loss: 0.4250 - val_acc: 0.8359
Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3119 - acc: 0.8763 - val_loss: 0.4235 - val_acc: 0.8359
Epoch 351/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3050 - acc: 0.8776 - val_loss: 0.4290 - val_acc: 0.8333
Epoch 352/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2980 - acc: 0.8854 - val_loss: 0.4243 - val_acc: 0.8359
Epoch 353/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3153 - acc: 0.8711 - val_loss: 0.4222 - val_acc: 0.8359
Epoch 354/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2941 - acc: 0.8802 - val_loss: 0.4245 - val_acc: 0.8359
Epoch 355/1000
12/12 [==============================] - 0

Epoch 404/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3080 - acc: 0.8815 - val_loss: 0.4278 - val_acc: 0.8333
Epoch 405/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3126 - acc: 0.8763 - val_loss: 0.4220 - val_acc: 0.8385
Epoch 406/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3085 - acc: 0.8737 - val_loss: 0.4213 - val_acc: 0.8385
Epoch 407/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3052 - acc: 0.8815 - val_loss: 0.4243 - val_acc: 0.8359
Epoch 408/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.2946 - acc: 0.8880 - val_loss: 0.4293 - val_acc: 0.8333
Epoch 409/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3181 - acc: 0.8711 - val_loss: 0.4232 - val_acc: 0.8385
Epoch 410/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3199 - acc: 0.8789 - val_loss: 0.4223 - val_acc: 0.8385
Epoch 411/1000
12/12 [==============================] -

Epoch 465/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3212 - acc: 0.8711 - val_loss: 0.4106 - val_acc: 0.8385

Epoch 00465: loss improved from inf to 0.32123, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/weights/Pbest-1-000465-0.321233-0.838542.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2998 - acc: 0.8750 - val_loss: 0.4284 - val_acc: 0.8333
Epoch 467/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3256 - acc: 0.8724 - val_loss: 0.4295 - val_acc: 0.8333
Epoch 468/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3256 - acc: 0.8737 - val_loss: 0.4267 - val_acc: 0.8333
Epoch 469/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2961 - acc: 0.8841 - val_loss: 0.4276 - val_acc: 0.8333

Epoch 00469: loss improved from 0.32123 to 0.29612, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/weights/Pbest-1-000469-

Epoch 521/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3196 - acc: 0.8659 - val_loss: 0.4251 - val_acc: 0.8359
Epoch 522/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3019 - acc: 0.8737 - val_loss: 0.4268 - val_acc: 0.8333
Epoch 523/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3147 - acc: 0.8789 - val_loss: 0.4250 - val_acc: 0.8359
Epoch 524/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3017 - acc: 0.8893 - val_loss: 0.4228 - val_acc: 0.8359
Epoch 525/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3194 - acc: 0.8672 - val_loss: 0.4275 - val_acc: 0.8333
Epoch 526/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3035 - acc: 0.8789 - val_loss: 0.4291 - val_acc: 0.8333
Epoch 527/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3072 - acc: 0.8737 - val_loss: 0.4221 - val_acc: 0.8385
Epoch 528/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.3068 - acc: 0.8789 - val_loss: 0.4279 - val_acc: 0.8333
Epoch 580/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2905 - acc: 0.8880 - val_loss: 0.4011 - val_acc: 0.8385
Epoch 581/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3035 - acc: 0.8711 - val_loss: 0.4224 - val_acc: 0.8385
Epoch 582/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3018 - acc: 0.8789 - val_loss: 0.4237 - val_acc: 0.8359
Epoch 583/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3079 - acc: 0.8789 - val_loss: 0.4240 - val_acc: 0.8359
Epoch 584/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3070 - acc: 0.8724 - val_loss: 0.4258 - val_acc: 0.8333
Epoch 585/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3110 - acc: 0.8789 - val_loss: 0.4267 - val_acc: 0.8359
Epoch 586/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 639/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2996 - acc: 0.8841 - val_loss: 0.4283 - val_acc: 0.8333
Epoch 640/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2872 - acc: 0.8893 - val_loss: 0.4210 - val_acc: 0.8359
Epoch 641/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3174 - acc: 0.8711 - val_loss: 0.4268 - val_acc: 0.8333
Epoch 642/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3278 - acc: 0.8672 - val_loss: 0.4193 - val_acc: 0.8359
Epoch 643/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3056 - acc: 0.8685 - val_loss: 0.4156 - val_acc: 0.8438
Epoch 644/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3020 - acc: 0.8672 - val_loss: 0.4223 - val_acc: 0.8385
Epoch 645/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2919 - acc: 0.8815 - val_loss: 0.4253 - val_acc: 0.8359
Epoch 646/1000
12/12 [==============================] -

Epoch 696/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3083 - acc: 0.8789 - val_loss: 0.4213 - val_acc: 0.8359
Epoch 697/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3232 - acc: 0.8633 - val_loss: 0.4289 - val_acc: 0.8333
Epoch 698/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2977 - acc: 0.8776 - val_loss: 0.4219 - val_acc: 0.8385
Epoch 699/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3069 - acc: 0.8711 - val_loss: 0.4272 - val_acc: 0.8333
Epoch 700/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3032 - acc: 0.8867 - val_loss: 0.4192 - val_acc: 0.8359

Epoch 00700: saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/weights/1-000700-0.303150-0.835938.hdf5
Epoch 701/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3005 - acc: 0.8750 - val_loss: 0.4263 - val_acc: 0.8359
Epoch 702/1000
12/12 [==============================] - 0s 

Epoch 756/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3141 - acc: 0.8750 - val_loss: 0.4188 - val_acc: 0.8385
Epoch 757/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3056 - acc: 0.8802 - val_loss: 0.4235 - val_acc: 0.8359
Epoch 758/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.2800 - acc: 0.8880 - val_loss: 0.4251 - val_acc: 0.8385
Epoch 759/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3234 - acc: 0.8789 - val_loss: 0.4262 - val_acc: 0.8359
Epoch 760/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.2934 - acc: 0.8763 - val_loss: 0.4147 - val_acc: 0.8385
Epoch 761/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3026 - acc: 0.8750 - val_loss: 0.4155 - val_acc: 0.8411
Epoch 762/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3240 - acc: 0.8802 - val_loss: 0.4270 - val_acc: 0.8359
Epoch 763/1000
12/12 [==============================] -

12/12 [==============================] - 0s 9ms/step - loss: 0.3081 - acc: 0.8880 - val_loss: 0.4297 - val_acc: 0.8333
Epoch 813/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3101 - acc: 0.8828 - val_loss: 0.4267 - val_acc: 0.8359
Epoch 814/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3111 - acc: 0.8789 - val_loss: 0.4271 - val_acc: 0.8333
Epoch 815/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3023 - acc: 0.8802 - val_loss: 0.4234 - val_acc: 0.8385
Epoch 816/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2985 - acc: 0.8854 - val_loss: 0.4217 - val_acc: 0.8411
Epoch 817/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3126 - acc: 0.8802 - val_loss: 0.3993 - val_acc: 0.8385
Epoch 818/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2992 - acc: 0.8698 - val_loss: 0.4288 - val_acc: 0.8333
Epoch 819/1000
12/12 [==============================] - 0s 9ms/step - loss: 

Epoch 931/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3038 - acc: 0.8724 - val_loss: 0.4272 - val_acc: 0.8333
Epoch 932/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.2973 - acc: 0.8854 - val_loss: 0.4210 - val_acc: 0.8385
Epoch 933/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3042 - acc: 0.8802 - val_loss: 0.4269 - val_acc: 0.8359
Epoch 934/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.2922 - acc: 0.8841 - val_loss: 0.4300 - val_acc: 0.8333
Epoch 935/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3049 - acc: 0.8880 - val_loss: 0.4299 - val_acc: 0.8333
Epoch 936/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3019 - acc: 0.8828 - val_loss: 0.4227 - val_acc: 0.8385
Epoch 937/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3091 - acc: 0.8789 - val_loss: 0.4167 - val_acc: 0.8359
Epoch 938/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
1-cairo:	acc: 83.63%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 1s 117ms/step - loss: 1.3347 - acc: 0.5990 - val_loss: 1.0408 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.0012 - acc: 0.6419 - val_loss: 0.8642 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.8824 - acc: 0.6745 - val_loss: 0.7573 - val_acc: 0.7161
Epoch 4/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.8128 - acc: 0.6927 - val_loss: 0.7010 - val_acc: 0.7552
Epoch 5/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.7660 - acc: 0.7318 - val_loss: 0.6630 - val_acc: 0.7969
Epoch 6/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.7193 - acc: 0.7370 - val_loss: 0.6301 - val_acc: 0.8099
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6926 - acc: 0.7422 - val_loss: 0.6058 - val_acc: 0.7995
Epoch 8/1000
12/12 [==============================] - 0s 13ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3726 - acc: 0.8464 - val_loss: 0.4425 - val_acc: 0.8177
Epoch 118/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3677 - acc: 0.8542 - val_loss: 0.4464 - val_acc: 0.8229
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3729 - acc: 0.8477 - val_loss: 0.4458 - val_acc: 0.8255
Epoch 120/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3599 - acc: 0.8594 - val_loss: 0.4370 - val_acc: 0.8333
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3707 - acc: 0.8555 - val_loss: 0.4383 - val_acc: 0.8229
Epoch 122/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3555 - acc: 0.8659 - val_loss: 0.4424 - val_acc: 0.8333
Epoch 123/1000
12/12 [==============================] - 0s 21ms/step - loss: 0.3739 - acc: 0.8490 - val_loss: 0.4460 - val_acc: 0.8255
Epoch 124/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.3480 - acc: 0.8607 - val_loss: 0.4521 - val_acc: 0.8411
Epoch 176/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3720 - acc: 0.8620 - val_loss: 0.4516 - val_acc: 0.8307
Epoch 177/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3684 - acc: 0.8646 - val_loss: 0.4410 - val_acc: 0.8385
Epoch 178/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3445 - acc: 0.8724 - val_loss: 0.4554 - val_acc: 0.8307
Epoch 179/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3426 - acc: 0.8607 - val_loss: 0.4622 - val_acc: 0.8307
Epoch 180/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3453 - acc: 0.8581 - val_loss: 0.4602 - val_acc: 0.8359
Epoch 181/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3463 - acc: 0.8633 - val_loss: 0.4506 - val_acc: 0.8333
Epoch 182/1000
12/12 [==============================] - 0s 19ms/step -

Epoch 233/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3263 - acc: 0.8724 - val_loss: 0.4547 - val_acc: 0.8438
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3389 - acc: 0.8607 - val_loss: 0.4556 - val_acc: 0.8411
Epoch 235/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3145 - acc: 0.8711 - val_loss: 0.4573 - val_acc: 0.8385
Epoch 236/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3275 - acc: 0.8672 - val_loss: 0.4401 - val_acc: 0.8490
Epoch 237/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3357 - acc: 0.8620 - val_loss: 0.4352 - val_acc: 0.8568
Epoch 238/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3261 - acc: 0.8789 - val_loss: 0.4516 - val_acc: 0.8490
Epoch 239/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3416 - acc: 0.8737 - val_loss: 0.4580 - val_acc: 0.8464
Epoch 240/1000
12/12 [==============================] -

Epoch 351/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3221 - acc: 0.8607 - val_loss: 0.4583 - val_acc: 0.8438
Epoch 352/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3491 - acc: 0.8607 - val_loss: 0.4571 - val_acc: 0.8464
Epoch 353/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3191 - acc: 0.8815 - val_loss: 0.4405 - val_acc: 0.8516
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3475 - acc: 0.8620 - val_loss: 0.4549 - val_acc: 0.8464
Epoch 355/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3362 - acc: 0.8659 - val_loss: 0.4591 - val_acc: 0.8438
Epoch 356/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3371 - acc: 0.8750 - val_loss: 0.4549 - val_acc: 0.8464
Epoch 357/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3470 - acc: 0.8646 - val_loss: 0.4471 - val_acc: 0.8464
Epoch 358/1000
12/12 [==============================] - 

12/12 [==============================] - 0s 11ms/step - loss: 0.3294 - acc: 0.8750 - val_loss: 0.4572 - val_acc: 0.8438
Epoch 468/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3324 - acc: 0.8659 - val_loss: 0.4571 - val_acc: 0.8464
Epoch 469/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3224 - acc: 0.8750 - val_loss: 0.4564 - val_acc: 0.8438
Epoch 470/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3249 - acc: 0.8737 - val_loss: 0.4369 - val_acc: 0.8490
Epoch 471/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3227 - acc: 0.8750 - val_loss: 0.4597 - val_acc: 0.8438
Epoch 472/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3458 - acc: 0.8503 - val_loss: 0.4599 - val_acc: 0.8438
Epoch 473/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3169 - acc: 0.8763 - val_loss: 0.4591 - val_acc: 0.8438

Epoch 00473: loss improved from 0.32105 to 0.31691, saving model to .

12/12 [==============================] - 0s 11ms/step - loss: 0.3265 - acc: 0.8646 - val_loss: 0.4578 - val_acc: 0.8464
Epoch 584/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3492 - acc: 0.8555 - val_loss: 0.4602 - val_acc: 0.8438
Epoch 585/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3226 - acc: 0.8815 - val_loss: 0.4583 - val_acc: 0.8438

Epoch 00585: loss improved from 0.32323 to 0.32257, saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/weights/Pbest-2-000585-0.322573-0.843750.hdf5
Epoch 586/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3292 - acc: 0.8685 - val_loss: 0.4571 - val_acc: 0.8464
Epoch 587/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3300 - acc: 0.8698 - val_loss: 0.4594 - val_acc: 0.8438
Epoch 588/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3235 - acc: 0.8672 - val_loss: 0.4597 - val_acc: 0.8438
Epoch 589/1000
12/12 [=======

12/12 [==============================] - 0s 16ms/step - loss: 0.3215 - acc: 0.8711 - val_loss: 0.4551 - val_acc: 0.8464
Epoch 696/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3313 - acc: 0.8620 - val_loss: 0.4586 - val_acc: 0.8464
Epoch 697/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3415 - acc: 0.8698 - val_loss: 0.4602 - val_acc: 0.8438
Epoch 698/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3252 - acc: 0.8776 - val_loss: 0.4367 - val_acc: 0.8490
Epoch 699/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3334 - acc: 0.8685 - val_loss: 0.4234 - val_acc: 0.8568
Epoch 700/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3208 - acc: 0.8698 - val_loss: 0.4570 - val_acc: 0.8464

Epoch 00700: saving model to ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/weights/2-000700-0.320786-0.846354.hdf5
Epoch 701/1000
12/12 [==============================] - 0s 12ms/step - los

Epoch 755/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3344 - acc: 0.8828 - val_loss: 0.4551 - val_acc: 0.8464
Epoch 756/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3316 - acc: 0.8685 - val_loss: 0.4606 - val_acc: 0.8438
Epoch 757/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3230 - acc: 0.8698 - val_loss: 0.4572 - val_acc: 0.8464
Epoch 758/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3232 - acc: 0.8672 - val_loss: 0.4594 - val_acc: 0.8438
Epoch 759/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3419 - acc: 0.8763 - val_loss: 0.4589 - val_acc: 0.8438
Epoch 760/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3234 - acc: 0.8789 - val_loss: 0.4601 - val_acc: 0.8438
Epoch 761/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3371 - acc: 0.8672 - val_loss: 0.4595 - val_acc: 0.8438
Epoch 762/1000
12/12 [==============================] -

save in: ../datasets/casas/results/WCNNR/cairo/2/20220201_2000_64_1_8/log/20220201_2000_64_1_8.csv
time: 0:02:20 s
time: 140.0 s
average 0.140000 s
2 epoch finished
--------------------   best   --------------------
no_activities: 7

Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 2ms/step
2-cairo:	acc: 84.65%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 1s 3ms/step
2-cairo:	acc: 84.65%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 82.80% (+/- 1.95%)
final: current database: cairo 	 82.88% (+/- 1.83%)
CPU times: user 7min 58s, sys: 44.1 s, total: 8min 42s
Wall time: 6min 56s

```

# <a id='constrain_3'>CS_3</a>

In [16]:
%%time
dict_config_cus['distance_int'] = '3'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_100 (InputLayer)       (None, 2000)              0         
_________________________________________________________________
embedding_100 (Embedding)    (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_100 (Conv1D)          (None, 2000, 32)          2080      
_________________________________________________________________
activation_298 (Activation)  (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_100 (Gl (None, 32)                0         
_________________________________________________________________
dense_298 (Dense)            (None, 48)                1584      
________________________________________

12/12 [==============================] - 0s 11ms/step - loss: 0.3663 - acc: 0.8581 - val_loss: 0.4943 - val_acc: 0.8047
Epoch 99/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3643 - acc: 0.8542 - val_loss: 0.4813 - val_acc: 0.7995
Epoch 100/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3501 - acc: 0.8659 - val_loss: 0.4823 - val_acc: 0.8021

Epoch 00100: saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8/weights/0-000100-0.350055-0.802083.hdf5
Epoch 101/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3879 - acc: 0.8516 - val_loss: 0.4989 - val_acc: 0.7969
Epoch 102/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3837 - acc: 0.8503 - val_loss: 0.5029 - val_acc: 0.7943
Epoch 103/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3626 - acc: 0.8633 - val_loss: 0.4880 - val_acc: 0.8047
Epoch 104/1000
12/12 [==============================] - 0s 12ms/step - loss

Epoch 210/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3590 - acc: 0.8451 - val_loss: 0.5004 - val_acc: 0.7943
Epoch 211/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3653 - acc: 0.8776 - val_loss: 0.4948 - val_acc: 0.7995
Epoch 212/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3665 - acc: 0.8594 - val_loss: 0.4959 - val_acc: 0.7995
Epoch 213/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3474 - acc: 0.8698 - val_loss: 0.4880 - val_acc: 0.7969
Epoch 214/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3463 - acc: 0.8724 - val_loss: 0.4928 - val_acc: 0.7995
Epoch 215/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3708 - acc: 0.8646 - val_loss: 0.5028 - val_acc: 0.7943
Epoch 216/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3706 - acc: 0.8516 - val_loss: 0.4924 - val_acc: 0.7969
Epoch 217/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.3577 - acc: 0.8581 - val_loss: 0.4925 - val_acc: 0.8021
Epoch 327/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3738 - acc: 0.8516 - val_loss: 0.4990 - val_acc: 0.7969
Epoch 328/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3529 - acc: 0.8620 - val_loss: 0.4928 - val_acc: 0.7995
Epoch 329/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3659 - acc: 0.8620 - val_loss: 0.4829 - val_acc: 0.8047
Epoch 330/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3439 - acc: 0.8659 - val_loss: 0.4925 - val_acc: 0.7995
Epoch 331/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3606 - acc: 0.8607 - val_loss: 0.4939 - val_acc: 0.7969
Epoch 332/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3641 - acc: 0.8724 - val_loss: 0.5020 - val_acc: 0.7943
Epoch 333/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 441/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3677 - acc: 0.8633 - val_loss: 0.4845 - val_acc: 0.7995
Epoch 442/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3596 - acc: 0.8646 - val_loss: 0.5014 - val_acc: 0.7943
Epoch 443/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3665 - acc: 0.8607 - val_loss: 0.4846 - val_acc: 0.8021
Epoch 444/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3707 - acc: 0.8542 - val_loss: 0.4846 - val_acc: 0.8047
Epoch 445/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3397 - acc: 0.8737 - val_loss: 0.4949 - val_acc: 0.7995
Epoch 446/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3636 - acc: 0.8698 - val_loss: 0.4880 - val_acc: 0.7995
Epoch 447/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3592 - acc: 0.8633 - val_loss: 0.5025 - val_acc: 0.7943
Epoch 448/1000
12/12 [==============================] -

12/12 [==============================] - 0s 18ms/step - loss: 0.3583 - acc: 0.8594 - val_loss: 0.4851 - val_acc: 0.8047
Epoch 00499: early stopping
ModelCheckpoint 已经保存到 ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8/weights/0-final.hdf5
Create subdir directory: ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8/log...
save in: ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8/log/20220201_2000_64_1_8.csv
time: 0:01:56 s
time: 116.0 s
average 0.116000 s
0 epoch finished
--------------------   best   --------------------
no_activities: 7

Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 5s 12ms/step
0-cairo:	acc: 79.85%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 5s 12ms/step
0-cairo:	acc: 79.85%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 6s 466ms/step - loss: 1.3290 - acc: 0.5885 - val_loss: 1.0840 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0605 - acc: 0.6471 - val_loss: 0.9367 - val_acc: 0.6745
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9513 - acc: 0.6732 - val_loss: 0.8409 - val_acc: 0.7188
Epoch 4/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.8723 - acc: 0.6940 - val_loss: 0.7639 - val_acc: 0.7292
Epoch 5/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.8196 - acc: 0.7083 - val_loss: 0.7116 - val_acc: 0.7500
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7644 - acc: 0.7279 - val_loss: 0.6688 - val_acc: 0.7526
Epoch 7/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.7475 - acc: 0.7214 - val_loss: 0.6488 - val_acc: 0.7500
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step -

Epoch 117/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3581 - acc: 0.8581 - val_loss: 0.4582 - val_acc: 0.8255
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3604 - acc: 0.8490 - val_loss: 0.4389 - val_acc: 0.8333
Epoch 119/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3556 - acc: 0.8477 - val_loss: 0.4562 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3613 - acc: 0.8555 - val_loss: 0.4439 - val_acc: 0.8307
Epoch 121/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3534 - acc: 0.8516 - val_loss: 0.4473 - val_acc: 0.8333
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3471 - acc: 0.8672 - val_loss: 0.4467 - val_acc: 0.8333
Epoch 123/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3688 - acc: 0.8620 - val_loss: 0.4415 - val_acc: 0.8359
Epoch 124/1000
12/12 [==============================] -

12/12 [==============================] - 0s 12ms/step - loss: 0.3235 - acc: 0.8646 - val_loss: 0.4551 - val_acc: 0.8255
Epoch 175/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3312 - acc: 0.8646 - val_loss: 0.4530 - val_acc: 0.8281
Epoch 176/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3180 - acc: 0.8711 - val_loss: 0.4591 - val_acc: 0.8281
Epoch 177/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3349 - acc: 0.8594 - val_loss: 0.4492 - val_acc: 0.8333
Epoch 178/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3533 - acc: 0.8490 - val_loss: 0.4522 - val_acc: 0.8307
Epoch 179/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3440 - acc: 0.8607 - val_loss: 0.4580 - val_acc: 0.8229
Epoch 180/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3289 - acc: 0.8646 - val_loss: 0.4355 - val_acc: 0.8333
Epoch 181/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 233/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3010 - acc: 0.8763 - val_loss: 0.4581 - val_acc: 0.8229
Epoch 234/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3110 - acc: 0.8685 - val_loss: 0.4553 - val_acc: 0.8229
Epoch 235/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3224 - acc: 0.8776 - val_loss: 0.4396 - val_acc: 0.8229
Epoch 236/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3235 - acc: 0.8659 - val_loss: 0.4333 - val_acc: 0.8281
Epoch 237/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3388 - acc: 0.8594 - val_loss: 0.4587 - val_acc: 0.8203
Epoch 238/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3119 - acc: 0.8789 - val_loss: 0.4506 - val_acc: 0.8229
Epoch 239/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3102 - acc: 0.8711 - val_loss: 0.4610 - val_acc: 0.8203
Epoch 240/1000
12/12 [==============================] -

Epoch 347/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3205 - acc: 0.8646 - val_loss: 0.4512 - val_acc: 0.8255
Epoch 348/1000
12/12 [==============================] - 0s 20ms/step - loss: 0.3259 - acc: 0.8594 - val_loss: 0.4593 - val_acc: 0.8203
Epoch 349/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3169 - acc: 0.8646 - val_loss: 0.4413 - val_acc: 0.8255
Epoch 350/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3307 - acc: 0.8581 - val_loss: 0.4552 - val_acc: 0.8229
Epoch 351/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3281 - acc: 0.8633 - val_loss: 0.4544 - val_acc: 0.8229
Epoch 352/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3317 - acc: 0.8594 - val_loss: 0.4570 - val_acc: 0.8229
Epoch 353/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3144 - acc: 0.8646 - val_loss: 0.4483 - val_acc: 0.8255
Epoch 354/1000
12/12 [==============================] -

Epoch 465/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3483 - acc: 0.8594 - val_loss: 0.4595 - val_acc: 0.8203

Epoch 00465: loss improved from inf to 0.34826, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8/weights/Pbest-1-000465-0.348265-0.820312.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3361 - acc: 0.8581 - val_loss: 0.4548 - val_acc: 0.8255
Epoch 467/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3232 - acc: 0.8685 - val_loss: 0.4578 - val_acc: 0.8229
Epoch 468/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3316 - acc: 0.8659 - val_loss: 0.4575 - val_acc: 0.8229
Epoch 469/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3460 - acc: 0.8555 - val_loss: 0.4527 - val_acc: 0.8281

Epoch 00469: loss improved from 0.34826 to 0.34598, saving model to ../datasets/casas/results/WCNNR/cairo/3/20220201_2000_64_1_8/weights/Pbest-1-000469-

12/12 [==============================] - 0s 18ms/step - loss: 0.3353 - acc: 0.8581 - val_loss: 0.4597 - val_acc: 0.8203
Epoch 578/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3158 - acc: 0.8698 - val_loss: 0.4444 - val_acc: 0.8281
Epoch 579/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3069 - acc: 0.8711 - val_loss: 0.4532 - val_acc: 0.8255
Epoch 580/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3181 - acc: 0.8672 - val_loss: 0.4609 - val_acc: 0.8203
Epoch 581/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3152 - acc: 0.8568 - val_loss: 0.4360 - val_acc: 0.8229
Epoch 582/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3147 - acc: 0.8490 - val_loss: 0.4593 - val_acc: 0.8203
Epoch 583/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3165 - acc: 0.8711 - val_loss: 0.4597 - val_acc: 0.8229
Epoch 584/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 692/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3243 - acc: 0.8750 - val_loss: 0.4590 - val_acc: 0.8229
Epoch 693/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3147 - acc: 0.8659 - val_loss: 0.4614 - val_acc: 0.8203
Epoch 694/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3428 - acc: 0.8529 - val_loss: 0.4556 - val_acc: 0.8229
Epoch 695/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.2995 - acc: 0.8815 - val_loss: 0.4528 - val_acc: 0.8281
Epoch 696/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3221 - acc: 0.8581 - val_loss: 0.4551 - val_acc: 0.8255
Epoch 697/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3167 - acc: 0.8607 - val_loss: 0.4619 - val_acc: 0.8203
Epoch 698/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3265 - acc: 0.8646 - val_loss: 0.4618 - val_acc: 0.8203
Epoch 699/1000
12/12 [==============================] -

Epoch 752/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3180 - acc: 0.8659 - val_loss: 0.4582 - val_acc: 0.8229
Epoch 753/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3184 - acc: 0.8698 - val_loss: 0.4440 - val_acc: 0.8255
Epoch 754/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3330 - acc: 0.8424 - val_loss: 0.4617 - val_acc: 0.8203
Epoch 755/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3282 - acc: 0.8698 - val_loss: 0.4507 - val_acc: 0.8255
Epoch 756/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3350 - acc: 0.8568 - val_loss: 0.4542 - val_acc: 0.8229
Epoch 757/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3147 - acc: 0.8763 - val_loss: 0.4578 - val_acc: 0.8203
Epoch 758/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3170 - acc: 0.8789 - val_loss: 0.4500 - val_acc: 0.8281
Epoch 759/1000
12/12 [==============================] -

Epoch 808/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3268 - acc: 0.8594 - val_loss: 0.4601 - val_acc: 0.8203
Epoch 809/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3174 - acc: 0.8724 - val_loss: 0.4498 - val_acc: 0.8255
Epoch 810/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3247 - acc: 0.8633 - val_loss: 0.4464 - val_acc: 0.8255
Epoch 811/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3195 - acc: 0.8672 - val_loss: 0.4549 - val_acc: 0.8229
Epoch 812/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3311 - acc: 0.8620 - val_loss: 0.4622 - val_acc: 0.8203
Epoch 813/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3303 - acc: 0.8659 - val_loss: 0.4560 - val_acc: 0.8255
Epoch 814/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3286 - acc: 0.8529 - val_loss: 0.4449 - val_acc: 0.8255
Epoch 815/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 5s 12ms/step
1-cairo:	acc: 82.35%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 6s 477ms/step - loss: 1.2897 - acc: 0.5990 - val_loss: 0.9979 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.9322 - acc: 0.6719 - val_loss: 0.8373 - val_acc: 0.7031
Epoch 3/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8499 - acc: 0.6862 - val_loss: 0.7860 - val_acc: 0.7031
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.7883 - acc: 0.7018 - val_loss: 0.7295 - val_acc: 0.7552
Epoch 5/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.7165 - acc: 0.7357 - val_loss: 0.6888 - val_acc: 0.7656
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7260 - acc: 0.7188 - val_loss: 0.6384 - val_acc: 0.7839
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.6685 - acc: 0.7669 - val_loss: 0.6279 - val_acc: 0.8073
Epoch 8/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 15ms/step - loss: 0.3812 - acc: 0.8529 - val_loss: 0.4572 - val_acc: 0.8438
Epoch 119/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3561 - acc: 0.8581 - val_loss: 0.4555 - val_acc: 0.8411
Epoch 120/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3589 - acc: 0.8555 - val_loss: 0.4605 - val_acc: 0.8281
Epoch 121/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3684 - acc: 0.8516 - val_loss: 0.4605 - val_acc: 0.8359
Epoch 122/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3925 - acc: 0.8424 - val_loss: 0.4639 - val_acc: 0.8229
Epoch 123/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3690 - acc: 0.8581 - val_loss: 0.4541 - val_acc: 0.8281
Epoch 124/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3740 - acc: 0.8503 - val_loss: 0.4548 - val_acc: 0.8385
Epoch 125/1000
12/12 [==============================] - 0s 18ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3452 - acc: 0.8581 - val_loss: 0.4594 - val_acc: 0.8307
Epoch 234/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3284 - acc: 0.8594 - val_loss: 0.4541 - val_acc: 0.8385
Epoch 235/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3252 - acc: 0.8724 - val_loss: 0.4555 - val_acc: 0.8307

Epoch 00235: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 236/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3355 - acc: 0.8711 - val_loss: 0.4672 - val_acc: 0.8281
Epoch 237/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3329 - acc: 0.8633 - val_loss: 0.4676 - val_acc: 0.8281
Epoch 238/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3417 - acc: 0.8490 - val_loss: 0.4579 - val_acc: 0.8307
Epoch 239/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3427 - acc: 0.8542 - val_loss: 0.4643 - val_acc: 0.8307
Epoc

Epoch 291/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3345 - acc: 0.8750 - val_loss: 0.4600 - val_acc: 0.8307
Epoch 292/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3362 - acc: 0.8659 - val_loss: 0.4565 - val_acc: 0.8307
Epoch 293/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3338 - acc: 0.8763 - val_loss: 0.4589 - val_acc: 0.8333
Epoch 294/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3463 - acc: 0.8529 - val_loss: 0.4618 - val_acc: 0.8307
Epoch 295/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3512 - acc: 0.8659 - val_loss: 0.4627 - val_acc: 0.8333
Epoch 296/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3540 - acc: 0.8646 - val_loss: 0.4666 - val_acc: 0.8281
Epoch 297/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3473 - acc: 0.8516 - val_loss: 0.4629 - val_acc: 0.8307
Epoch 298/1000
12/12 [==============================] -

Epoch 351/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3431 - acc: 0.8542 - val_loss: 0.4680 - val_acc: 0.8281
Epoch 352/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3369 - acc: 0.8568 - val_loss: 0.4576 - val_acc: 0.8333
Epoch 353/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3464 - acc: 0.8581 - val_loss: 0.4647 - val_acc: 0.8307
Epoch 354/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3265 - acc: 0.8620 - val_loss: 0.4678 - val_acc: 0.8281
Epoch 355/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3490 - acc: 0.8607 - val_loss: 0.4678 - val_acc: 0.8281
Epoch 356/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3663 - acc: 0.8568 - val_loss: 0.4554 - val_acc: 0.8333
Epoch 357/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3366 - acc: 0.8555 - val_loss: 0.4679 - val_acc: 0.8281
Epoch 358/1000
12/12 [==============================] -

Epoch 407/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3455 - acc: 0.8568 - val_loss: 0.4497 - val_acc: 0.8333
Epoch 408/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3369 - acc: 0.8633 - val_loss: 0.4664 - val_acc: 0.8281
Epoch 409/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3322 - acc: 0.8568 - val_loss: 0.4547 - val_acc: 0.8333
Epoch 410/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3468 - acc: 0.8529 - val_loss: 0.4466 - val_acc: 0.8333
Epoch 411/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3313 - acc: 0.8607 - val_loss: 0.4656 - val_acc: 0.8281
Epoch 412/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3439 - acc: 0.8568 - val_loss: 0.4590 - val_acc: 0.8333
Epoch 413/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3286 - acc: 0.8711 - val_loss: 0.4273 - val_acc: 0.8359
Epoch 414/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 5s 12ms/step
2-cairo:	acc: 83.12%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.52% (+/- 1.60%)
final: current database: cairo 	 81.52% (+/- 1.60%)
CPU times: user 4min 38s, sys: 22.8 s, total: 5min 1s
Wall time: 4min 4s

best: current database: cairo 	 81.77% (+/- 1.75%)
final: current database: cairo 	 81.69% (+/- 1.68%)
CPU times: user 7min 6s, sys: 29.8 s, total: 7min 36s
Wall time: 6min 10s

best: current database: cairo 	 81.77% (+/- 1.40%)
final: current database: cairo 	 81.77% (+/- 1.40%)
CPU times: user 8min 35s, sys: 34.9 s, total: 9min 10s
Wall time: 7min 29s
```

# <a id='constrain_4'>CS_4</a>

In [10]:
%%time
dict_config_cus['distance_int'] = '4'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_46 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_46 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_46 (Conv1D)           (None, 2000, 32)          2080      
_________________________________________________________________
activation_136 (Activation)  (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_46 (Glo (None, 32)                0         
_________________________________________________________________
dense_136 (Dense)            (None, 48)                1584      
________________________________________

12/12 [==============================] - 0s 11ms/step - loss: 0.3654 - acc: 0.8607 - val_loss: 0.4665 - val_acc: 0.8177
Epoch 104/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3718 - acc: 0.8594 - val_loss: 0.4542 - val_acc: 0.8359
Epoch 105/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3850 - acc: 0.8307 - val_loss: 0.4639 - val_acc: 0.8281
Epoch 106/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3806 - acc: 0.8633 - val_loss: 0.4611 - val_acc: 0.8229
Epoch 107/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3897 - acc: 0.8398 - val_loss: 0.4482 - val_acc: 0.8385
Epoch 108/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3720 - acc: 0.8411 - val_loss: 0.4568 - val_acc: 0.8203
Epoch 109/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3695 - acc: 0.8581 - val_loss: 0.4663 - val_acc: 0.8203
Epoch 110/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 164/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3592 - acc: 0.8581 - val_loss: 0.4729 - val_acc: 0.8255
Epoch 165/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3387 - acc: 0.8711 - val_loss: 0.4735 - val_acc: 0.8281

Epoch 00165: loss improved from inf to 0.33872, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_8/weights/Pbest-0-000165-0.338723-0.828125.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3556 - acc: 0.8568 - val_loss: 0.4663 - val_acc: 0.8255
Epoch 167/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3382 - acc: 0.8568 - val_loss: 0.4691 - val_acc: 0.8307
Epoch 168/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3345 - acc: 0.8646 - val_loss: 0.4678 - val_acc: 0.8385
Epoch 169/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3289 - acc: 0.8698 - val_loss: 0.4533 - val_acc: 0.8333

Epoch 00169: loss

Epoch 220/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3175 - acc: 0.8659 - val_loss: 0.4868 - val_acc: 0.8099
Epoch 221/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3064 - acc: 0.8750 - val_loss: 0.4751 - val_acc: 0.8281
Epoch 222/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3177 - acc: 0.8685 - val_loss: 0.4808 - val_acc: 0.8073
Epoch 223/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3167 - acc: 0.8802 - val_loss: 0.4865 - val_acc: 0.8255
Epoch 224/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3088 - acc: 0.8776 - val_loss: 0.4783 - val_acc: 0.8229
Epoch 225/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3113 - acc: 0.8724 - val_loss: 0.4851 - val_acc: 0.8151
Epoch 226/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3087 - acc: 0.8724 - val_loss: 0.4856 - val_acc: 0.8151
Epoch 227/1000
12/12 [==============================] -

Epoch 279/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2980 - acc: 0.8750 - val_loss: 0.4849 - val_acc: 0.8125
Epoch 280/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2911 - acc: 0.8815 - val_loss: 0.4853 - val_acc: 0.8151
Epoch 281/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3063 - acc: 0.8802 - val_loss: 0.4986 - val_acc: 0.8073
Epoch 282/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3000 - acc: 0.8802 - val_loss: 0.4802 - val_acc: 0.8125
Epoch 283/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3001 - acc: 0.8802 - val_loss: 0.4898 - val_acc: 0.8099

Epoch 00283: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
Epoch 284/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2997 - acc: 0.8906 - val_loss: 0.4955 - val_acc: 0.8125
Epoch 285/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2902 - acc: 0.8815 - val_loss:

12/12 [==============================] - 0s 12ms/step - loss: 0.2948 - acc: 0.8698 - val_loss: 0.4968 - val_acc: 0.8125
Epoch 336/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2993 - acc: 0.8789 - val_loss: 0.4931 - val_acc: 0.8125
Epoch 337/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3180 - acc: 0.8685 - val_loss: 0.4961 - val_acc: 0.8125
Epoch 338/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2884 - acc: 0.8828 - val_loss: 0.4773 - val_acc: 0.8177
Epoch 339/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3092 - acc: 0.8763 - val_loss: 0.4797 - val_acc: 0.8151
Epoch 340/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3030 - acc: 0.8646 - val_loss: 0.4951 - val_acc: 0.8125
Epoch 341/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2997 - acc: 0.8763 - val_loss: 0.4977 - val_acc: 0.8125
Epoch 342/1000
12/12 [==============================] - 0s 11ms/step -

Epoch 392/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2865 - acc: 0.8919 - val_loss: 0.4917 - val_acc: 0.8151
Epoch 393/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2902 - acc: 0.8815 - val_loss: 0.4990 - val_acc: 0.8099
Epoch 394/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.2933 - acc: 0.8763 - val_loss: 0.4886 - val_acc: 0.8125
Epoch 395/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2973 - acc: 0.8815 - val_loss: 0.4973 - val_acc: 0.8125
Epoch 396/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2888 - acc: 0.8841 - val_loss: 0.4847 - val_acc: 0.8177
Epoch 397/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2879 - acc: 0.8880 - val_loss: 0.4707 - val_acc: 0.8151
Epoch 398/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.2999 - acc: 0.8737 - val_loss: 0.4916 - val_acc: 0.8151
Epoch 399/1000
12/12 [==============================] -

Epoch 452/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2969 - acc: 0.8763 - val_loss: 0.4890 - val_acc: 0.8177
Epoch 453/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2949 - acc: 0.8750 - val_loss: 0.4831 - val_acc: 0.8125
Epoch 454/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.2873 - acc: 0.8815 - val_loss: 0.5013 - val_acc: 0.8099
Epoch 455/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3143 - acc: 0.8737 - val_loss: 0.4905 - val_acc: 0.8177
Epoch 456/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3121 - acc: 0.8880 - val_loss: 0.5018 - val_acc: 0.8073
Epoch 457/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3045 - acc: 0.8685 - val_loss: 0.5008 - val_acc: 0.8073
Epoch 458/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2922 - acc: 0.8906 - val_loss: 0.4906 - val_acc: 0.8099
Epoch 459/1000
12/12 [==============================] -

Epoch 570/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3038 - acc: 0.8724 - val_loss: 0.4963 - val_acc: 0.8125
Epoch 571/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2918 - acc: 0.8828 - val_loss: 0.4982 - val_acc: 0.8099
Epoch 572/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2875 - acc: 0.8841 - val_loss: 0.4940 - val_acc: 0.8099
Epoch 573/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2802 - acc: 0.8906 - val_loss: 0.4791 - val_acc: 0.8177

Epoch 00573: loss improved from 0.28140 to 0.28015, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_8/weights/Pbest-0-000573-0.280155-0.817708.hdf5
Epoch 574/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.3251 - acc: 0.8646 - val_loss: 0.4848 - val_acc: 0.8125
Epoch 575/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2898 - acc: 0.8906 - val_loss: 0.4938 - val_acc: 0.8125
Epoch 576/1000
12/12

Epoch 629/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2938 - acc: 0.8776 - val_loss: 0.4801 - val_acc: 0.8151
Epoch 630/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2905 - acc: 0.8854 - val_loss: 0.5018 - val_acc: 0.8073
Epoch 631/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3067 - acc: 0.8763 - val_loss: 0.4968 - val_acc: 0.8099
Epoch 632/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2728 - acc: 0.8906 - val_loss: 0.4906 - val_acc: 0.8177
Epoch 633/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2821 - acc: 0.8880 - val_loss: 0.4874 - val_acc: 0.8125
Epoch 634/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2914 - acc: 0.8802 - val_loss: 0.4942 - val_acc: 0.8099
Epoch 635/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.2845 - acc: 0.8880 - val_loss: 0.4840 - val_acc: 0.8125
Epoch 636/1000
12/12 [==============================] - 0s 9ms


Epoch 00685: loss improved from 0.28975 to 0.28556, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_8/weights/Pbest-0-000685-0.285560-0.812500.hdf5
Epoch 686/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3073 - acc: 0.8633 - val_loss: 0.4935 - val_acc: 0.8099
Epoch 687/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2779 - acc: 0.8685 - val_loss: 0.5025 - val_acc: 0.8073
Epoch 688/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2943 - acc: 0.8867 - val_loss: 0.4986 - val_acc: 0.8099
Epoch 689/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.2861 - acc: 0.8880 - val_loss: 0.4969 - val_acc: 0.8099
Epoch 690/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2929 - acc: 0.8932 - val_loss: 0.4977 - val_acc: 0.8125
Epoch 691/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.2961 - acc: 0.8711 - val_loss: 0.4991 - val_acc: 0.8099
Epoch 692/1000

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 1s 4ms/step
0-cairo:	acc: 81.12%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 163ms/step - loss: 1.4004 - acc: 0.5612 - val_loss: 1.0680 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0424 - acc: 0.6523 - val_loss: 0.8880 - val_acc: 0.7005
Epoch 3/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.9174 - acc: 0.6927 - val_loss: 0.7921 - val_acc: 0.7396
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8676 - acc: 0.7201 - val_loss: 0.7411 - val_acc: 0.7656
Epoch 5/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8336 - acc: 0.7070 - val_loss: 0.6844 - val_acc: 0.7552
Epoch 6/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7589 - acc: 0.7422 - val_loss: 0.6683 - val_acc: 0.7995
Epoch 7/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.7287 - acc: 0.7565 - val_loss: 0.6232 - val_acc: 0.8021
Epoch 8/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.3645 - acc: 0.8594 - val_loss: 0.4755 - val_acc: 0.8151
Epoch 119/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3708 - acc: 0.8516 - val_loss: 0.4805 - val_acc: 0.8125
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3561 - acc: 0.8737 - val_loss: 0.4793 - val_acc: 0.8125
Epoch 121/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3588 - acc: 0.8815 - val_loss: 0.4824 - val_acc: 0.8151
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3777 - acc: 0.8646 - val_loss: 0.4768 - val_acc: 0.8151
Epoch 123/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3691 - acc: 0.8620 - val_loss: 0.4828 - val_acc: 0.8125
Epoch 124/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3868 - acc: 0.8542 - val_loss: 0.4693 - val_acc: 0.8203
Epoch 125/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 235/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3595 - acc: 0.8646 - val_loss: 0.4861 - val_acc: 0.8151
Epoch 236/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3778 - acc: 0.8737 - val_loss: 0.4769 - val_acc: 0.8229
Epoch 237/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3699 - acc: 0.8542 - val_loss: 0.4800 - val_acc: 0.8177
Epoch 238/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3721 - acc: 0.8607 - val_loss: 0.4761 - val_acc: 0.8177
Epoch 239/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3550 - acc: 0.8646 - val_loss: 0.4695 - val_acc: 0.8203
Epoch 240/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3550 - acc: 0.8685 - val_loss: 0.4857 - val_acc: 0.8151
Epoch 241/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3734 - acc: 0.8620 - val_loss: 0.4688 - val_acc: 0.8203
Epoch 242/1000
12/12 [==============================] -

Epoch 292/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3660 - acc: 0.8646 - val_loss: 0.4824 - val_acc: 0.8177
Epoch 293/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3686 - acc: 0.8568 - val_loss: 0.4856 - val_acc: 0.8151
Epoch 294/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3891 - acc: 0.8555 - val_loss: 0.4706 - val_acc: 0.8203
Epoch 295/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3618 - acc: 0.8685 - val_loss: 0.4747 - val_acc: 0.8203
Epoch 296/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3806 - acc: 0.8555 - val_loss: 0.4794 - val_acc: 0.8203
Epoch 297/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3681 - acc: 0.8620 - val_loss: 0.4732 - val_acc: 0.8229
Epoch 298/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3697 - acc: 0.8646 - val_loss: 0.4823 - val_acc: 0.8177
Epoch 299/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 4ms/step
1-cairo:	acc: 81.84%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 2s 178ms/step - loss: 1.3534 - acc: 0.5938 - val_loss: 1.1250 - val_acc: 0.6328
Epoch 2/1000
12/12 [==============================] - 0s 9ms/step - loss: 1.0982 - acc: 0.6354 - val_loss: 1.0084 - val_acc: 0.6302
Epoch 3/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.9709 - acc: 0.6549 - val_loss: 0.8946 - val_acc: 0.6641
Epoch 4/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8906 - acc: 0.6849 - val_loss: 0.7930 - val_acc: 0.7266
Epoch 5/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.8252 - acc: 0.7083 - val_loss: 0.7324 - val_acc: 0.7396
Epoch 6/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7622 - acc: 0.7331 - val_loss: 0.6903 - val_acc: 0.7578
Epoch 7/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.7135 - acc: 0.7487 - val_loss: 0.6500 - val_acc: 0.7734
Epoch 8/1000
12/12 [==============================] - 0s 10ms/step - loss

12/12 [==============================] - 0s 12ms/step - loss: 0.3446 - acc: 0.8672 - val_loss: 0.4876 - val_acc: 0.8203
Epoch 114/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3517 - acc: 0.8685 - val_loss: 0.4571 - val_acc: 0.8255
Epoch 115/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3345 - acc: 0.8620 - val_loss: 0.4753 - val_acc: 0.8229
Epoch 116/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3449 - acc: 0.8789 - val_loss: 0.4727 - val_acc: 0.8281
Epoch 117/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3672 - acc: 0.8568 - val_loss: 0.4770 - val_acc: 0.8255
Epoch 118/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3710 - acc: 0.8711 - val_loss: 0.4747 - val_acc: 0.8385
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3447 - acc: 0.8542 - val_loss: 0.4772 - val_acc: 0.8307
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 172/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3230 - acc: 0.8867 - val_loss: 0.4635 - val_acc: 0.8411
Epoch 173/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3271 - acc: 0.8646 - val_loss: 0.4765 - val_acc: 0.8385
Epoch 174/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3169 - acc: 0.8750 - val_loss: 0.4720 - val_acc: 0.8411
Epoch 175/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3297 - acc: 0.8841 - val_loss: 0.4787 - val_acc: 0.8385
Epoch 176/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3195 - acc: 0.8685 - val_loss: 0.4714 - val_acc: 0.8411
Epoch 177/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3019 - acc: 0.8724 - val_loss: 0.4789 - val_acc: 0.8385

Epoch 00177: loss improved from 0.31941 to 0.30186, saving model to ../datasets/casas/results/WCNNR/cairo/4/20220201_2000_64_1_8/weights/Pbest-2-000177-0.301861-0.838542.hdf5
Epoch 178/1000

Epoch 230/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3101 - acc: 0.8893 - val_loss: 0.4755 - val_acc: 0.8411
Epoch 231/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3215 - acc: 0.8737 - val_loss: 0.4777 - val_acc: 0.8385
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3037 - acc: 0.8815 - val_loss: 0.4839 - val_acc: 0.8359
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3181 - acc: 0.8828 - val_loss: 0.4797 - val_acc: 0.8385
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3165 - acc: 0.8802 - val_loss: 0.4790 - val_acc: 0.8359
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3126 - acc: 0.8750 - val_loss: 0.4641 - val_acc: 0.8464
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3181 - acc: 0.8711 - val_loss: 0.4840 - val_acc: 0.8333
Epoch 237/1000
12/12 [==============================] - 0s 9

Epoch 347/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3267 - acc: 0.8594 - val_loss: 0.4663 - val_acc: 0.8359
Epoch 348/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3290 - acc: 0.8659 - val_loss: 0.4796 - val_acc: 0.8359
Epoch 349/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3205 - acc: 0.8633 - val_loss: 0.4839 - val_acc: 0.8333
Epoch 350/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3122 - acc: 0.8802 - val_loss: 0.4827 - val_acc: 0.8359
Epoch 351/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3201 - acc: 0.8698 - val_loss: 0.4842 - val_acc: 0.8333
Epoch 352/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3090 - acc: 0.8802 - val_loss: 0.4717 - val_acc: 0.8385
Epoch 353/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3196 - acc: 0.8685 - val_loss: 0.4689 - val_acc: 0.8359
Epoch 354/1000
12/12 [==============================] -

12/12 [==============================] - 0s 11ms/step - loss: 0.3117 - acc: 0.8763 - val_loss: 0.4811 - val_acc: 0.8359
Epoch 402/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3208 - acc: 0.8776 - val_loss: 0.4769 - val_acc: 0.8385
Epoch 403/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3049 - acc: 0.8737 - val_loss: 0.4846 - val_acc: 0.8333
Epoch 404/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3248 - acc: 0.8763 - val_loss: 0.4833 - val_acc: 0.8359
Epoch 405/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3227 - acc: 0.8906 - val_loss: 0.4782 - val_acc: 0.8359
Epoch 406/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3156 - acc: 0.8763 - val_loss: 0.4843 - val_acc: 0.8333
Epoch 407/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3065 - acc: 0.8880 - val_loss: 0.4544 - val_acc: 0.8411
Epoch 408/1000
12/12 [==============================] - 0s 12ms/step -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 5ms/step
2-cairo:	acc: 83.63%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 81.77% (+/- 0.50%)
final: current database: cairo 	 82.20% (+/- 1.06%)
CPU times: user 5min 48s, sys: 31 s, total: 6min 19s
Wall time: 4min 18s

```

# <a id='constrain_5'>CS_5</a>

In [11]:
%%time
dict_config_cus['distance_int'] = '5'
train_val(dict_config_cus)

current dataset: cairo
../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_8
no_activities: 7

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_55 (InputLayer)        (None, 2000)              0         
_________________________________________________________________
embedding_55 (Embedding)     (None, 2000, 64)          50048     
_________________________________________________________________
conv1d_55 (Conv1D)           (None, 2000, 32)          2080      
_________________________________________________________________
activation_163 (Activation)  (None, 2000, 32)          0         
_________________________________________________________________
global_max_pooling1d_55 (Glo (None, 32)                0         
_________________________________________________________________
dense_163 (Dense)            (None, 48)                1584      
________________________________________

12/12 [==============================] - 0s 9ms/step - loss: 0.3797 - acc: 0.8568 - val_loss: 0.5654 - val_acc: 0.7917
Epoch 103/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3956 - acc: 0.8503 - val_loss: 0.5716 - val_acc: 0.7995
Epoch 104/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4028 - acc: 0.8542 - val_loss: 0.5685 - val_acc: 0.8099
Epoch 105/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3750 - acc: 0.8542 - val_loss: 0.5680 - val_acc: 0.7995
Epoch 106/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3871 - acc: 0.8503 - val_loss: 0.5610 - val_acc: 0.7995
Epoch 107/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.4050 - acc: 0.8503 - val_loss: 0.5684 - val_acc: 0.7865
Epoch 108/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3872 - acc: 0.8438 - val_loss: 0.5703 - val_acc: 0.7969
Epoch 109/1000
12/12 [==============================] - 0s 11ms/step - loss: 

Epoch 163/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3519 - acc: 0.8581 - val_loss: 0.5655 - val_acc: 0.7917
Epoch 164/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3598 - acc: 0.8620 - val_loss: 0.5353 - val_acc: 0.7995
Epoch 165/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3616 - acc: 0.8581 - val_loss: 0.5706 - val_acc: 0.7917

Epoch 00165: loss improved from inf to 0.36155, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_8/weights/Pbest-0-000165-0.361553-0.791667.hdf5
Epoch 166/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3605 - acc: 0.8659 - val_loss: 0.5635 - val_acc: 0.7969
Epoch 167/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3521 - acc: 0.8633 - val_loss: 0.5737 - val_acc: 0.7891
Epoch 168/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3543 - acc: 0.8672 - val_loss: 0.5658 - val_acc: 0.7917
Epoch 169/1000
12/

Epoch 218/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3512 - acc: 0.8698 - val_loss: 0.5631 - val_acc: 0.8021
Epoch 219/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3415 - acc: 0.8594 - val_loss: 0.5649 - val_acc: 0.7995
Epoch 220/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3524 - acc: 0.8581 - val_loss: 0.5639 - val_acc: 0.8021
Epoch 221/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3491 - acc: 0.8568 - val_loss: 0.5602 - val_acc: 0.7995
Epoch 222/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3658 - acc: 0.8542 - val_loss: 0.5668 - val_acc: 0.7969
Epoch 223/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3458 - acc: 0.8724 - val_loss: 0.5592 - val_acc: 0.7969
Epoch 224/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3482 - acc: 0.8594 - val_loss: 0.5674 - val_acc: 0.7969
Epoch 225/1000
12/12 [==============================] -

Epoch 335/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3596 - acc: 0.8659 - val_loss: 0.5625 - val_acc: 0.7995
Epoch 336/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3478 - acc: 0.8711 - val_loss: 0.5607 - val_acc: 0.7995
Epoch 337/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3744 - acc: 0.8659 - val_loss: 0.5644 - val_acc: 0.7995
Epoch 338/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3427 - acc: 0.8672 - val_loss: 0.5631 - val_acc: 0.8021
Epoch 339/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3630 - acc: 0.8542 - val_loss: 0.5663 - val_acc: 0.7995
Epoch 340/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3783 - acc: 0.8568 - val_loss: 0.5699 - val_acc: 0.7969
Epoch 341/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3519 - acc: 0.8776 - val_loss: 0.5629 - val_acc: 0.7995
Epoch 342/1000
12/12 [==============================] -

12/12 [==============================] - 0s 12ms/step - loss: 0.3433 - acc: 0.8672 - val_loss: 0.5696 - val_acc: 0.7943
Epoch 394/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3510 - acc: 0.8711 - val_loss: 0.5737 - val_acc: 0.7917
Epoch 395/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3642 - acc: 0.8542 - val_loss: 0.5557 - val_acc: 0.7969
Epoch 396/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3569 - acc: 0.8503 - val_loss: 0.5670 - val_acc: 0.7969
Epoch 397/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3631 - acc: 0.8542 - val_loss: 0.5639 - val_acc: 0.7969
Epoch 398/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3363 - acc: 0.8620 - val_loss: 0.5548 - val_acc: 0.7969
Epoch 399/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3366 - acc: 0.8594 - val_loss: 0.5721 - val_acc: 0.7943
Epoch 400/1000
12/12 [==============================] - 0s 12ms/step -

Epoch 453/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3564 - acc: 0.8685 - val_loss: 0.5751 - val_acc: 0.7917
Epoch 454/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3578 - acc: 0.8607 - val_loss: 0.5619 - val_acc: 0.7995
Epoch 455/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3473 - acc: 0.8646 - val_loss: 0.5626 - val_acc: 0.7969
Epoch 456/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3616 - acc: 0.8568 - val_loss: 0.5687 - val_acc: 0.7943
Epoch 457/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3580 - acc: 0.8633 - val_loss: 0.5676 - val_acc: 0.7943
Epoch 458/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3534 - acc: 0.8620 - val_loss: 0.5664 - val_acc: 0.7969
Epoch 459/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3610 - acc: 0.8490 - val_loss: 0.5462 - val_acc: 0.8021
Epoch 460/1000
12/12 [==============================] -


Epoch 00569: loss improved from 0.35559 to 0.33954, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_8/weights/Pbest-0-000569-0.339535-0.789062.hdf5
Epoch 570/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.3512 - acc: 0.8594 - val_loss: 0.5694 - val_acc: 0.7891
Epoch 571/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3482 - acc: 0.8607 - val_loss: 0.5689 - val_acc: 0.7917
Epoch 572/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3499 - acc: 0.8607 - val_loss: 0.5638 - val_acc: 0.7943
Epoch 573/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3589 - acc: 0.8633 - val_loss: 0.5600 - val_acc: 0.7943
Epoch 574/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3366 - acc: 0.8711 - val_loss: 0.5622 - val_acc: 0.7969
Epoch 575/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3527 - acc: 0.8659 - val_loss: 0.5694 - val_acc: 0.7943
Epoch 576/1000
12/1

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
392/392 [==============================] - 2s 5ms/step
0-cairo:	acc: 79.34%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 3s 211ms/step - loss: 1.3176 - acc: 0.6198 - val_loss: 1.0578 - val_acc: 0.6354
Epoch 2/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0541 - acc: 0.6341 - val_loss: 0.9143 - val_acc: 0.6745
Epoch 3/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.9749 - acc: 0.6589 - val_loss: 0.8305 - val_acc: 0.7135
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8921 - acc: 0.6849 - val_loss: 0.7721 - val_acc: 0.7083
Epoch 5/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.8354 - acc: 0.7096 - val_loss: 0.7304 - val_acc: 0.7500
Epoch 6/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.7816 - acc: 0.7396 - val_loss: 0.6933 - val_acc: 0.7578
Epoch 7/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.7667 - acc: 0.7266 - val_loss: 0.6563 - val_acc: 0.7865
Epoch 8/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.3750 - acc: 0.8581 - val_loss: 0.4704 - val_acc: 0.8281
Epoch 120/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3884 - acc: 0.8659 - val_loss: 0.4761 - val_acc: 0.8307
Epoch 121/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3742 - acc: 0.8581 - val_loss: 0.4678 - val_acc: 0.8307
Epoch 122/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3806 - acc: 0.8672 - val_loss: 0.4847 - val_acc: 0.8203
Epoch 123/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3843 - acc: 0.8633 - val_loss: 0.4735 - val_acc: 0.8281
Epoch 124/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3615 - acc: 0.8607 - val_loss: 0.4656 - val_acc: 0.8359
Epoch 125/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3886 - acc: 0.8659 - val_loss: 0.4514 - val_acc: 0.8333
Epoch 126/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.3207 - acc: 0.8763 - val_loss: 0.4774 - val_acc: 0.8307
Epoch 237/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3226 - acc: 0.8724 - val_loss: 0.4785 - val_acc: 0.8307
Epoch 238/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3434 - acc: 0.8633 - val_loss: 0.4724 - val_acc: 0.8333
Epoch 239/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3289 - acc: 0.8685 - val_loss: 0.4678 - val_acc: 0.8307
Epoch 240/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3040 - acc: 0.8906 - val_loss: 0.4812 - val_acc: 0.8255
Epoch 241/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3060 - acc: 0.8841 - val_loss: 0.4661 - val_acc: 0.8281
Epoch 242/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3362 - acc: 0.8646 - val_loss: 0.4806 - val_acc: 0.8281
Epoch 243/1000
12/12 [==============================] - 0s 11ms/step -

12/12 [==============================] - 0s 18ms/step - loss: 0.2947 - acc: 0.8958 - val_loss: 0.4700 - val_acc: 0.8333
Epoch 353/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3269 - acc: 0.8815 - val_loss: 0.4572 - val_acc: 0.8385
Epoch 354/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3087 - acc: 0.8854 - val_loss: 0.4735 - val_acc: 0.8307
Epoch 355/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3222 - acc: 0.8854 - val_loss: 0.4789 - val_acc: 0.8307
Epoch 356/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3264 - acc: 0.8776 - val_loss: 0.4754 - val_acc: 0.8307
Epoch 357/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3345 - acc: 0.8750 - val_loss: 0.4812 - val_acc: 0.8281
Epoch 358/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3336 - acc: 0.8685 - val_loss: 0.4787 - val_acc: 0.8281
Epoch 359/1000
12/12 [==============================] - 0s 18ms/step -

Epoch 408/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.2985 - acc: 0.8919 - val_loss: 0.4781 - val_acc: 0.8307
Epoch 409/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3079 - acc: 0.8854 - val_loss: 0.4706 - val_acc: 0.8333
Epoch 410/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3251 - acc: 0.8750 - val_loss: 0.4812 - val_acc: 0.8281
Epoch 411/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3231 - acc: 0.8893 - val_loss: 0.4662 - val_acc: 0.8333
Epoch 412/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3272 - acc: 0.8659 - val_loss: 0.4748 - val_acc: 0.8307
Epoch 413/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3292 - acc: 0.8750 - val_loss: 0.4824 - val_acc: 0.8281
Epoch 414/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3256 - acc: 0.8763 - val_loss: 0.4769 - val_acc: 0.8307
Epoch 415/1000
12/12 [==============================] -

Epoch 527/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3162 - acc: 0.8802 - val_loss: 0.4787 - val_acc: 0.8307
Epoch 528/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3186 - acc: 0.8789 - val_loss: 0.4812 - val_acc: 0.8281
Epoch 529/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3205 - acc: 0.8828 - val_loss: 0.4803 - val_acc: 0.8281
Epoch 530/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.2860 - acc: 0.8932 - val_loss: 0.4716 - val_acc: 0.8359
Epoch 531/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3147 - acc: 0.8828 - val_loss: 0.4769 - val_acc: 0.8307
Epoch 532/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3229 - acc: 0.8750 - val_loss: 0.4772 - val_acc: 0.8307
Epoch 533/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3194 - acc: 0.8867 - val_loss: 0.4790 - val_acc: 0.8307
Epoch 534/1000
12/12 [==============================] -

Epoch 584/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3257 - acc: 0.8750 - val_loss: 0.4788 - val_acc: 0.8307
Epoch 585/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3275 - acc: 0.8711 - val_loss: 0.4690 - val_acc: 0.8307
Epoch 586/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3339 - acc: 0.8828 - val_loss: 0.4736 - val_acc: 0.8307
Epoch 587/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3390 - acc: 0.8802 - val_loss: 0.4627 - val_acc: 0.8333
Epoch 588/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3251 - acc: 0.8802 - val_loss: 0.4535 - val_acc: 0.8359
Epoch 589/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3153 - acc: 0.8906 - val_loss: 0.4754 - val_acc: 0.8307
Epoch 590/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3336 - acc: 0.8802 - val_loss: 0.4774 - val_acc: 0.8307
Epoch 591/1000
12/12 [==============================] -

Epoch 644/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.3142 - acc: 0.8854 - val_loss: 0.4714 - val_acc: 0.8333
Epoch 645/1000
12/12 [==============================] - 0s 19ms/step - loss: 0.3231 - acc: 0.8776 - val_loss: 0.4823 - val_acc: 0.8281
Epoch 646/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3300 - acc: 0.8802 - val_loss: 0.4715 - val_acc: 0.8333
Epoch 647/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.3243 - acc: 0.8633 - val_loss: 0.4772 - val_acc: 0.8307
Epoch 648/1000
12/12 [==============================] - 0s 13ms/step - loss: 0.3346 - acc: 0.8724 - val_loss: 0.4800 - val_acc: 0.8281
Epoch 649/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3129 - acc: 0.8841 - val_loss: 0.4750 - val_acc: 0.8333
Epoch 650/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.3405 - acc: 0.8633 - val_loss: 0.4701 - val_acc: 0.8333
Epoch 651/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 6ms/step
1-cairo:	acc: 83.12%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Epoch 1/1000
12/12 [==============================] - 3s 237ms/step - loss: 1.3311 - acc: 0.5755 - val_loss: 1.0972 - val_acc: 0.6302
Epoch 2/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.0552 - acc: 0.6380 - val_loss: 0.9778 - val_acc: 0.6328
Epoch 3/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.9674 - acc: 0.6758 - val_loss: 0.8390 - val_acc: 0.7031
Epoch 4/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.8422 - acc: 0.7135 - val_loss: 0.8041 - val_acc: 0.7422
Epoch 5/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7911 - acc: 0.7318 - val_loss: 0.7438 - val_acc: 0.7682
Epoch 6/1000
12/12 [==============================] - 0s 18ms/step - loss: 0.7237 - acc: 0.7435 - val_loss: 0.7037 - val_acc: 0.8021
Epoch 7/1000
12/12 [==============================] - 0s 16ms/step - loss: 0.7129 - acc: 0.7630 - val_loss: 0.6756 - val_acc: 0.7943
Epoch 8/1000
12/12 [==============================] - 0s 13ms/step -

12/12 [==============================] - 0s 11ms/step - loss: 0.3838 - acc: 0.8555 - val_loss: 0.4872 - val_acc: 0.8359
Epoch 116/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3855 - acc: 0.8359 - val_loss: 0.4840 - val_acc: 0.8203
Epoch 117/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.4022 - acc: 0.8307 - val_loss: 0.4632 - val_acc: 0.8229
Epoch 118/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3704 - acc: 0.8424 - val_loss: 0.4698 - val_acc: 0.8281
Epoch 119/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3786 - acc: 0.8424 - val_loss: 0.4884 - val_acc: 0.8229
Epoch 120/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3675 - acc: 0.8516 - val_loss: 0.4841 - val_acc: 0.8307
Epoch 121/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3800 - acc: 0.8516 - val_loss: 0.4629 - val_acc: 0.8359
Epoch 122/1000
12/12 [==============================] - 0s 12ms/step -

12/12 [==============================] - 0s 10ms/step - loss: 0.3586 - acc: 0.8555 - val_loss: 0.4939 - val_acc: 0.8359
Epoch 231/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3319 - acc: 0.8763 - val_loss: 0.4965 - val_acc: 0.8359
Epoch 232/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3289 - acc: 0.8659 - val_loss: 0.4926 - val_acc: 0.8333
Epoch 233/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3258 - acc: 0.8737 - val_loss: 0.5033 - val_acc: 0.8307
Epoch 234/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3253 - acc: 0.8672 - val_loss: 0.4943 - val_acc: 0.8359
Epoch 235/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3312 - acc: 0.8724 - val_loss: 0.4984 - val_acc: 0.8359
Epoch 236/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3262 - acc: 0.8672 - val_loss: 0.5009 - val_acc: 0.8333
Epoch 237/1000
12/12 [==============================] - 0s 9ms/step - loss: 

12/12 [==============================] - 0s 9ms/step - loss: 0.3501 - acc: 0.8594 - val_loss: 0.4965 - val_acc: 0.8333
Epoch 348/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3392 - acc: 0.8646 - val_loss: 0.4957 - val_acc: 0.8333
Epoch 349/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3425 - acc: 0.8711 - val_loss: 0.5010 - val_acc: 0.8333
Epoch 350/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3417 - acc: 0.8672 - val_loss: 0.4868 - val_acc: 0.8385
Epoch 351/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3321 - acc: 0.8763 - val_loss: 0.5029 - val_acc: 0.8307
Epoch 352/1000
12/12 [==============================] - 0s 9ms/step - loss: 0.3446 - acc: 0.8698 - val_loss: 0.4993 - val_acc: 0.8359
Epoch 353/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3372 - acc: 0.8646 - val_loss: 0.4985 - val_acc: 0.8333
Epoch 354/1000
12/12 [==============================] - 0s 9ms/step - loss: 

Epoch 464/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3301 - acc: 0.8698 - val_loss: 0.4966 - val_acc: 0.8359
Epoch 465/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3311 - acc: 0.8633 - val_loss: 0.4990 - val_acc: 0.8359

Epoch 00465: loss improved from inf to 0.33110, saving model to ../datasets/casas/results/WCNNR/cairo/5/20220201_2000_64_1_8/weights/Pbest-2-000465-0.331101-0.835938.hdf5
Epoch 466/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3387 - acc: 0.8685 - val_loss: 0.4977 - val_acc: 0.8359
Epoch 467/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3298 - acc: 0.8685 - val_loss: 0.4851 - val_acc: 0.8359
Epoch 468/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3216 - acc: 0.8724 - val_loss: 0.5025 - val_acc: 0.8333
Epoch 469/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3312 - acc: 0.8672 - val_loss: 0.4985 - val_acc: 0.8333
Epoch 470/1000
12/

Epoch 578/1000
12/12 [==============================] - 0s 17ms/step - loss: 0.3387 - acc: 0.8659 - val_loss: 0.4801 - val_acc: 0.8385
Epoch 579/1000
12/12 [==============================] - 0s 10ms/step - loss: 0.3372 - acc: 0.8724 - val_loss: 0.5000 - val_acc: 0.8307
Epoch 580/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3307 - acc: 0.8802 - val_loss: 0.4836 - val_acc: 0.8385
Epoch 581/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3392 - acc: 0.8672 - val_loss: 0.4908 - val_acc: 0.8333
Epoch 582/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3361 - acc: 0.8724 - val_loss: 0.4817 - val_acc: 0.8359
Epoch 583/1000
12/12 [==============================] - 0s 11ms/step - loss: 0.3415 - acc: 0.8607 - val_loss: 0.4957 - val_acc: 0.8359
Epoch 584/1000
12/12 [==============================] - 0s 12ms/step - loss: 0.3430 - acc: 0.8737 - val_loss: 0.4985 - val_acc: 0.8333
Epoch 585/1000
12/12 [==============================] -

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


Created model and loaded weights from file
Begin testing ...
391/391 [==============================] - 2s 6ms/step
2-cairo:	acc: 83.38%
Report:
********************
list(Y[test]: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/home/musk/anaconda3/envs/HARedit/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass labels=[6, 5, 1, 4, 0, 3, 2] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


```bash
best: current database: cairo 	 82.11% (+/- 1.08%)
final: current database: cairo 	 81.94% (+/- 1.85%)
CPU times: user 7min 34s, sys: 38.7 s, total: 8min 12s
Wall time: 5min 59s

```